Repository pimcore/pimcore, pull requests merged in 2018-06, with the labels that each got.

#2893 Google api client updated to latest version 2
  composer.json
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
  pimcore/lib/Pimcore/Google/Api.php
Labels: Task

#2906 Scheduled blocks
  doc/Development_Documentation/03_Documents/01_Editables/42_Scheduled_Block.md
  doc/Development_Documentation/03_Documents/01_Editables/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/39_Preview_Scheduled_Content.md
  doc/Development_Documentation/img/scheduled_block_date.jpg
  doc/Development_Documentation/img/scheduled_block_item_menu.jpg
  doc/Development_Documentation/img/scheduled_block_item_menu_delete.jpg
  doc/Development_Documentation/img/scheduled_block_plus.jpg
  doc/Development_Documentation/img/scheduled_block_preview.jpg
  doc/Development_Documentation/img/scheduled_block_slider.jpg
  doc/Development_Documentation/img/scheduledblock_editmode.jpg
  doc/Development_Documentation/img/scheduledblock_preview.jpg
  pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/EnablePreviewTimeSliderListener.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/config/event_listeners.yml
  pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/EditmodeListener.php
  pimcore/lib/Pimcore/Bundle/CoreBundle/EventListener/Frontend/OutputTimestampListener.php
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/aliases.yml
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/event_listeners.yml
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/request_response.yml
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
  pimcore/lib/Pimcore/Document/Tag/NamingStrategy/AbstractNamingStrategy.php
  pimcore/lib/Pimcore/Http/Request/Resolver/OutputTimestampResolver.php
  pimcore/lib/Pimcore/Templating/PhpEngine.php
  pimcore/models/Document/Tag/Scheduledblock.php
  web/pimcore/static6/css/editmode.css
  web/pimcore/static6/js/pimcore/document/pages/preview.js
  web/pimcore/static6/js/pimcore/document/tags/scheduledblock.js
  web/pimcore/static6/js/pimcore/tool/milestoneslider.js
Labels: Improvement

#2912 add missing getter for Class
  pimcore/models/Document/Tag/Link.php
Labels: Improvement

#2879 Object Grid Improvements
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
  pimcore/lib/Pimcore/DataObject/GridColumnConfig/Value/DefaultValue.php
  pimcore/lib/Pimcore/DataObject/GridColumnConfig/Value/Href.php
  pimcore/lib/Pimcore/DataObject/GridColumnConfig/Value/Objects.php
  web/pimcore/static6/js/pimcore/object/helpers/grid.js
  web/pimcore/static6/js/pimcore/object/helpers/gridConfigDialog.js
Labels: Improvement

#2918 Two Factor Authentication
  composer.json
  doc/Development_Documentation/18_Tools_and_Features/40_Two_Factor_Authentication.md
  doc/Development_Documentation/img/two_factor_authentication_app_descriptions.png
  doc/Development_Documentation/img/two_factor_authentication_login.png
  doc/Development_Documentation/img/two_factor_authentication_required.png
  doc/Development_Documentation/img/two_factor_authentication_setup.png
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/IndexController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/LoginController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/UserController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/ImportConfigListener.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/TwoFactorListener.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Index/index.html.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Login/layout.html.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Login/login.html.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Login/lostpassword.html.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Security/Authentication/Token/TwoFactorRequiredToken.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Security/Guard/AdminAuthenticator.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Security/User/User.php
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/config.yml
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/security.yml
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/pimcore/two_factor_authentication.yml
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
  pimcore/lib/Pimcore/Install/Resources/install.sql
  pimcore/lib/Pimcore/Kernel.php
  pimcore/models/User.php
  pimcore/models/User/AbstractUser/Dao.php
  update-scripts/256/postupdate.php
  web/pimcore/static6/css/login.css
  web/pimcore/static6/js/pimcore/layout/toolbar.js
  web/pimcore/static6/js/pimcore/settings/profile/panel.js
  web/pimcore/static6/js/pimcore/settings/profile/twoFactorSettings.js
  web/pimcore/static6/js/pimcore/settings/user/user/settings.js
  web/pimcore/static6/js/pimcore/startup.js
Labels: New Feature

#2928 [Ecommerce] WirecardSeamless payment provider - updated setting payment state to PENDING
  pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php
Labels: Improvement

#2933 [WIP] [Assets] Focal point on images
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  doc/Development_Documentation/img/asset_focal_point.png
  doc/Development_Documentation/img/document_image_editable_focal_point.png
  doc/Development_Documentation/img/image_thumbnails_cover_focal_point.png
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
  pimcore/lib/Pimcore/Image/Adapter.php
  pimcore/models/Asset/Image.php
  pimcore/models/Asset/Image/Thumbnail/Processor.php
  pimcore/models/Document/Tag/Image.php
  web/pimcore/static6/css/admin.css
  web/pimcore/static6/css/icons.css
  web/pimcore/static6/img/flat-color-icons/focal_point.svg
  web/pimcore/static6/js/pimcore/asset/image.js
  web/pimcore/static6/js/pimcore/document/tags/image.js
  web/pimcore/static6/js/pimcore/settings/thumbnail/item.js
Labels: New Feature

#2961 Remove superfluous cast to boolean
  pimcore/lib/Pimcore/Controller/Traits/TemplateControllerTrait.php
Labels: Improvement

#2962 fix: added variant object type to BatchJobs
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
Labels: Bug

#2970 Fix position of closing parenthesis
  pimcore/lib/Pimcore/Http/Request/Resolver/TemplateVarsResolver.php
Labels: Bug

#2973 QuickSearch
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Searchadmin/SearchController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Index/index.html.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/asset.html.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/document.html.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/info-table.html.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/object.html.php
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
  pimcore/lib/Pimcore/Event/AdminEvents.php
  pimcore/lib/Pimcore/Tool/Text.php
  pimcore/models/User.php
  web/pimcore/static6/css/admin.css
  web/pimcore/static6/img/magnifier.svg
  web/pimcore/static6/js/pimcore/helpers.js
  web/pimcore/static6/js/pimcore/layout/toolbar.js
  web/pimcore/static6/js/pimcore/overrides.js
  web/pimcore/static6/js/pimcore/startup.js
Labels: New Feature

#2924 Translate quantity value units
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/QuantityValueController.php
Labels: Bug

#2977 Document types grouping
  pimcore/models/Document/DocType.php
  pimcore/models/Document/DocType/Dao.php
  web/pimcore/static6/js/pimcore/document/settings_abstract.js
  web/pimcore/static6/js/pimcore/document/tree.js
  web/pimcore/static6/js/pimcore/settings/docTypes.js
Labels: Improvement

#2981 issue-2915: Preview of older document version
  web/pimcore/static6/js/pimcore/document/versions.js
Labels: Bug

#3003 Classes: possibility to define table identifier
  .travis/run-tests.sh
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/ClassController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Rest/ClassController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/GridConfigListener.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/EventListener/ImportConfigListener.php
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
  pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Model/IIndexable.php
  pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Tools/Installer.php
  pimcore/lib/Pimcore/DataObject/Import/Service.php
  pimcore/lib/Pimcore/Install/Resources/install.sql
  pimcore/lib/Pimcore/Tool/RestClient/AbstractRestClient.php
  pimcore/models/DataObject/ClassDefinition.php
  pimcore/models/DataObject/ClassDefinition/CustomLayout.php
  pimcore/models/DataObject/ClassDefinition/Dao.php
  pimcore/models/DataObject/ClassDefinition/Service.php
  pimcore/models/DataObject/Concrete.php
  pimcore/models/DataObject/Listing/Concrete.php
  pimcore/models/DataObject/Objectbrick/Definition.php
  pimcore/models/Element/Service.php
  pimcore/models/GridConfigFavourite.php
  pimcore/tests/_support/Helper/ClassManager.php
  pimcore/tests/_support/Helper/Model.php
  update-scripts/269/postupdate.php
  web/pimcore/static6/js/pimcore/object/class.js
  web/pimcore/static6/js/pimcore/object/classes/class.js
  web/pimcore/static6/js/pimcore/object/folder/search.js
Labels: Improvement
