Repository pimcore/pimcore, pull requests merged in 2018-09, with the labels that each got.

#3293 [XLIFF export/import] Refactor to make it extendable and reusable
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/DependencyInjection/Compiler/TranslationServicesPass.php
  bundles/AdminBundle/PimcoreAdminBundle.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/services.yml
  lib/Translation/AttributeSet/Attribute.php
  lib/Translation/AttributeSet/AttributeSet.php
  lib/Translation/Escaper/Xliff12Escaper.php
  lib/Translation/ExportDataExtractorService/DataExtractor/AbstractElementDataExtractor.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DataExtractorInterface.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
  lib/Translation/ExportDataExtractorService/ExportDataExtractorService.php
  lib/Translation/ExportDataExtractorService/ExportDataExtractorServiceInterface.php
  lib/Translation/ExportService/ExportService.php
  lib/Translation/ExportService/ExportServiceInterface.php
  lib/Translation/ExportService/Exporter/ExporterInterface.php
  lib/Translation/ExportService/Exporter/Xliff12Exporter.php
  lib/Translation/ImportDataExtractor/ImportDataExtractorInterface.php
  lib/Translation/ImportDataExtractor/TranslationItemResolver/TranslationItemResolver.php
  lib/Translation/ImportDataExtractor/TranslationItemResolver/TranslationItemResolverInterface.php
  lib/Translation/ImportDataExtractor/Xliff12DataExtractor.php
  lib/Translation/ImporterService/Importer/AbstractElementImporter.php
  lib/Translation/ImporterService/Importer/DataObjectImporter.php
  lib/Translation/ImporterService/Importer/DocumentImporter.php
  lib/Translation/ImporterService/Importer/ImporterInterface.php
  lib/Translation/ImporterService/ImporterService.php
  lib/Translation/ImporterService/ImporterServiceInterface.php
  lib/Translation/TranslationItemCollection/TranslationItem.php
  lib/Translation/TranslationItemCollection/TranslationItemCollection.php
  lib/Translation/XliffEscaper.php
Labels: Improvement

#3300 [Bugfix] Class definition ids may now be alphanumeric
  bundles/CoreBundle/Command/ClassesRebuildCommand.php
Labels: Bug

#3308 [Assets] Custom callbacks for image transformations
  lib/Image/Adapter.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: Improvement

#3325 Fix CSV import with alphanumeric ID's
  lib/DataObject/Import/Service.php
Labels: Bug

#3345 Custom Reports: Fixed headers exporting CSV ","
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
Labels: Bug

#3347 Update symfony/swiftmailer-bundle
  bundles/CoreBundle/Resources/migrations/Version20180913132106.php
  composer.json
  lib/Mail.php
Labels: Task

#3350 [ecommerce][index service] Elasticsearch delete from index bugfix in combination with virtual product ids
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultElasticSearch.php
Labels: Bug

#3357 [DataObject] Add property geter for Grid
  bundles/AdminBundle/Resources/config/export.yml
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/PropertyGetter.js
  lib/DataObject/GridColumnConfig/Operator/PropertyGetter.php
Labels: Improvement

#3364 [CSV import] always pass the "target" to Field Definitions' `getFromCsvImport` method
  lib/DataObject/Import/ColumnConfig/Value/DefaultValue.php
Labels: Bug

#3373 Generate valid keys with length(key) <= length(key) of database tables
  models/Element/Service.php
Labels: Bug

#3372 QuantityValue webservice bugfix
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Bug
