Repository pimcore/pimcore, pull requests merged in 2018-12, with the labels that each got.

#3694 Order agent bugfix
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
Labels: Improvement

#3704 Cleanup unused order items
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
Labels: Improvement

#3697 Refactoring treenodelocator
  bundles/AdminBundle/Resources/public/js/pimcore/treenodelocator.js
Labels: Improvement, Prio-Backlog

#3706 Fix: OwnerAwareField shouldn't save Owner
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/InputQuantityValue.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/Localizedfield/Dao.php
Labels: Bug

#3532 Restore layout state after reloading object
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
  bundles/AdminBundle/Resources/public/js/pimcore/plugin/plugin.js
Labels: Improvement

#3730 Fix Symfony Deprecations
  bundles/CoreBundle/Resources/config/services.yml
Labels: Task

#3715 Interfaces for Data Types
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
  lib/Tool.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/CustomResourcePersistingInterface.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
  models/DataObject/ClassDefinition/Data/Geopolygon.php
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/Input.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Nonownerobjects.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/QueryResourcePersistenceAwareInterface.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/ResourcePersistenceAwareInterface.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/Slider.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/ClassDefinition/Data/Textarea.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Fieldcollection/Dao.php
  models/DataObject/Fieldcollection/Data/Dao.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
Labels: BC-BREAK, Improvement

#3735 Fix: PHP Docs of datatypes
  bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelection.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/Extension/Text.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
  models/DataObject/ClassDefinition/Data/Geopolygon.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/Input.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/ClassDefinition/Data/Persona.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/Slider.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/ClassDefinition/Data/TargetGroup.php
  models/DataObject/ClassDefinition/Data/Textarea.php
  models/DataObject/ClassDefinition/Data/User.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/Data/ObjectMetadata.php
  models/DataObject/Data/Video.php
Labels: Task

#3728 Rename Nonownerobjects to ReverseManyToManyObjectRelation
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Resources/translations/aliases.json
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/37_Non_Owner_Objects_Type.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/37_Reverse_Many_To_Many_Object_Relation_Type.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
  lib/Loader/Autoloader/AliasMapper.php
  models/DataObject/ClassDefinition/Data/ReverseManyToManyObjectRelation.php
  models/Version.php
  tests/_support/Util/TestHelper.php
Labels: Task

#3661 [Email] Consider multiple recipients and email name annotation 'NAME <name@email.com>'
  bundles/AdminBundle/Controller/Admin/EmailController.php
  lib/Helper/Mail.php
  lib/Mail.php
  models/Document/Email.php
  models/Document/Newsletter.php
Labels: Improvement

#3615 [Custom Layouts] Added definable identifier and changed storage to php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
  bundles/CoreBundle/Resources/migrations/Version20181115114003.php
  bundles/InstallBundle/Resources/install.sql
  lib/helper-functions.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
Labels: BC-BREAK, Improvement

#3749 add version preview for metadata fields of advanced multi relation types
  bundles/AdminBundle/Resources/public/css/object_versions.css
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
Labels: Improvement

#3752 [Elasticserach] Add setter for custom search aggregations
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
Labels: Improvement

#3758 Fixed usage of wrong variable in webservice import of videos
  models/DataObject/ClassDefinition/Data/Video.php
Labels: Bug

#3756 Fix: Can't save object with CalculatedValue
  models/DataObject/Concrete/Dao.php
  models/DataObject/Fieldcollection/Dao.php
  models/DataObject/Fieldcollection/Data/Dao.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
Labels: Bug

#3766 Add AppBundle placeholder path
  doc/Development_Documentation/19_Development_Tools_and_Details/23_Placeholders/README.md
  lib/Placeholder.php
Labels: Improvement

#3786 Fix: Can't execute tests locally
  tests/cache/Factory.php
Labels: Bug
