Repository pimcore/pimcore, pull requests merged in 2018-08, with the labels that each got.

#3160 Added option to set CSV settings on Import
  bundles/AdminBundle/Controller/Admin/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/csvSettingsTab.js
Labels: Improvement

#3188 Support comma as separation symbol for floating-point numbers
  bundles/EcommerceFrameworkBundle/Type/Decimal.php
  tests/ecommerce/Type/DecimalTest.php
Labels: Bug, Improvement

#3193 [Documents] Possibility to customize placement of block controls
  doc/Development_Documentation/03_Documents/01_Editables/06_Block.md
  models/Document/Tag/Block.php
Labels: Improvement

#3191 implement feature to set Kernel Class via constant/env/.env config
  lib/Bootstrap.php
Labels: Improvement

#3199 Navigation: Added `hasVisiblePages()` convenience method
  lib/Navigation/Container.php
Labels: Improvement

#3208 Fix Twig edit template duplcate issue
  lib/Twig/Extension/DocumentTagExtension.php
Labels: Bug

#3209 sort bundles, actiona, templates for frontend
  bundles/AdminBundle/Controller/Admin/MiscController.php
Labels: Improvement

#3183 Implement webservice import for videos in data objects.
  models/DataObject/ClassDefinition/Data/Video.php
Labels: Improvement

#3219 Fix: When creating folder by path multiple warnings are logged
  models/Element/Service.php
Labels: Improvement

#3222 Fix multiple subtypes & classnames for getElementsForTag
  models/Element/Tag/Dao.php
Labels: Bug

#3246 [Bugfix] Getting value of localized field of newly created field collection should return null
  models/DataObject/Localizedfield.php
Labels: Bug

#3270 Portlet Bugfix - move condition to list statement
  pimcore/modules/admin/controllers/PortalController.php
Labels: Bug

#3287 Minor payment refactorings
  bundles/CoreBundle/Resources/migrations/Version20180830113528.php
  bundles/CoreBundle/Resources/migrations/Version20180830122128.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/Model/AbstractOrder.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_PaymentInfo_export.json
Labels: Improvement
