Repository pimcore/pimcore, pull requests merged in 2018-10, with the labels that each got.

#3400 Option to add a nice name with HTML-icons in filter definition
  bundles/EcommerceFrameworkBundle/FilterService/FilterGroupHelper.php
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service.md
Labels: Improvement

#3404 Prevent warning array_keys() expects parameter 1 to be array, null given
  models/Workflow.php
Labels: Improvement

#3410 [Workflows] add getTransitionByName helper method to workflow manager
  lib/Workflow/Manager.php
Labels: Improvement

#3417 Update colinmollenhour credis latest version 1.10.0
  composer.json
  lib/Cache/Pool/Redis.php
  lib/Storage/Redis/Connection.php
  lib/Storage/Redis/ConnectionFactory.php
  tests/cache/Pool/Traits/RedisItemPoolTrait.php
Labels: Task

#3423 Fix dependency warning on delete for all elements
  models/Dependency.php
Labels: Bug

#3427 Update DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFactFinder.php
Labels: Improvement

#3442 [fix] Get class definition in ObjectsMetadata
  models/DataObject/ClassDefinition/Data/ObjectsMetadata.php
Labels: Bug

#3452 [Document|Object] Reference latest not published version in extra column #3262
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/DocumentController.php
  bundles/AdminBundle/Controller/Admin/EmailController.php
  bundles/AdminBundle/Controller/Admin/HardlinkController.php
  bundles/AdminBundle/Controller/Admin/LinkController.php
  bundles/AdminBundle/Controller/Admin/NewsletterController.php
  bundles/AdminBundle/Controller/Admin/PageController.php
  bundles/AdminBundle/Controller/Admin/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Admin/SnippetController.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js
  bundles/CoreBundle/Resources/migrations/Version20181009135158.php
  bundles/InstallBundle/Resources/install.sql
  models/Asset/Dao.php
  models/DataObject/Concrete/Dao.php
  models/Document/PageSnippet/Dao.php
  models/Element/AbstractElement.php
  models/Element/Service.php
  models/Version.php
Labels: Improvement

#3460 [assets] getChildren() performance improvement and php doc fixes for asset DAO
  models/Asset/Dao.php
Labels: Improvement

#3464 [Workflows] email notification roles fix
  lib/Workflow/NotificationEmail/NotificationEmailService.php
Labels: Bug

#3414 Disable Inline Upload for Document Tags Multihref / Image
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/multihref.js
  doc/Development_Documentation/03_Documents/01_Editables/14_Image.md
  doc/Development_Documentation/03_Documents/01_Editables/20_Multihref.md
Labels: Improvement

#3466 [ClassificationStore] allow to use only individual keys from a group …
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/js/pimcore/element/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/classificationstore.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
  bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/13_Classification_Store.md
  doc/Development_Documentation/img/Objects_ClassificationStore_classes.png
  doc/Development_Documentation/img/Objects_ClassificationStore_edit_object.png
  models/DataObject/ClassDefinition/Data/Classificationstore.php
Labels: Improvement

#3489 [Asset] WebP Support for Image Thumbnails
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
  lib/Image/Adapter.php
  lib/Image/Adapter/GD.php
  lib/Image/Adapter/Imagick.php
  lib/Tool/Frontend.php
  lib/Tool/Requirements.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: Improvement

#3496 [ecommmerce][elasticsearch] delete moved variants from old parents
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultElasticSearch.php
Labels: Bug

#3506 [GDPR Extractor] Consider entity permissions on actions
  bundles/AdminBundle/Controller/Admin/Document/EmailController.php
  bundles/AdminBundle/Controller/Admin/EmailController.php
  bundles/AdminBundle/Controller/GDPR/AssetController.php
  bundles/AdminBundle/Controller/GDPR/DataObjectController.php
  bundles/AdminBundle/Controller/GDPR/PimcoreUsersController.php
  bundles/AdminBundle/Controller/GDPR/SentMailController.php
  bundles/AdminBundle/GDPR/DataProvider/Assets.php
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/gdpr/dataproviders/assets.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/gdpr/dataproviders/dataObjects.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/gdpr/dataproviders/pimcoreUsers.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/gdpr/dataproviders/sentMail.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: Task

#3519 boolean select - batch assignment fix
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
Labels: Bug

#3540 Documents paste as language variant
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
  bundles/CoreBundle/Resources/translations/en.json
  models/Document/Service.php
Labels: Improvement, New Feature

#3548 workflow state grid operator: do not output html content in csv export
  lib/DataObject/GridColumnConfig/Operator/WorkflowState.php
  lib/Workflow/Place/StatusInfo.php
Labels: Improvement
