Repository pimcore/pimcore, pull requests merged in 2018-07, with the labels that each got.

#3020 refactor preview for objects
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
  web/pimcore/static6/js/pimcore/object/object.js
Labels: Proposal

#3018 Add name property to object textareas
  web/pimcore/static6/js/pimcore/object/tags/textarea.js
Labels: Improvement

#3014 [Ecommerce] Update Wirecard Init Payment URL
  pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/PaymentManager/Payment/QPay.php
Labels: Task

#3041 Renamed Locale service and introduced LocaleServiceInterface
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DocumentTag/RenderletController.php
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/aliases.yml
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/config/l10n.yml
  pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/Environment.php
  pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/SessionEnvironment.php
  pimcore/lib/Pimcore/DataObject/GridColumnConfig/Operator/Factory/LFExpanderFactory.php
  pimcore/lib/Pimcore/DataObject/GridColumnConfig/Operator/Factory/LocaleSwitcherFactory.php
  pimcore/lib/Pimcore/DataObject/GridColumnConfig/Operator/LFExpander.php
  pimcore/lib/Pimcore/DataObject/GridColumnConfig/Operator/LocaleSwitcher.php
  pimcore/lib/Pimcore/DataObject/Import/ColumnConfig/Operator/Factory/LocaleSwitcherFactory.php
  pimcore/lib/Pimcore/DataObject/Import/ColumnConfig/Operator/LocaleSwitcher.php
  pimcore/lib/Pimcore/DataObject/Import/Resolver/Code.php
  pimcore/lib/Pimcore/Loader/Autoloader/AliasMapper.php
  pimcore/lib/Pimcore/Localization/IntlFormatter.php
  pimcore/lib/Pimcore/Localization/LocaleService.php
  pimcore/lib/Pimcore/Localization/LocaleServiceInterface.php
  pimcore/tests/_support/Test/EcommerceTestCase.php
Labels: Improvement

#3034 Fix "Unknown key for a VALUE_NULL in [from]"
  pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/ProductList/DefaultElasticSearch.php
Labels: Bug

#3037 Fix/ecommerce switch index alias elasticsearch
  pimcore/lib/Pimcore/Bundle/EcommerceFrameworkBundle/IndexService/Worker/DefaultElasticSearch.php
Labels: Bug

#3050 New feature: Added thumbnail download option
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/AssetController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/SettingsController.php
  pimcore/lib/Pimcore/Bundle/CoreBundle/Resources/translations/en.json
  pimcore/models/Asset/Image/Thumbnail/Config.php
  pimcore/models/Asset/Image/Thumbnail/Config/Dao.php
  web/pimcore/static6/js/pimcore/asset/image.js
  web/pimcore/static6/js/pimcore/settings/thumbnail/item.js
Labels: New Feature

#3074 Fix: Workspace permissions multiple paths issue
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/UserController.php
  web/pimcore/static6/js/pimcore/settings/user/workspace/asset.js
  web/pimcore/static6/js/pimcore/settings/user/workspace/document.js
  web/pimcore/static6/js/pimcore/settings/user/workspace/object.js
Labels: Bug

#3022 Grid configuration for Object search view
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/DataObjectHelperController.php
  web/pimcore/static6/js/pimcore/element/selector/object.js
Labels: New Feature, Task

#3083 Replace Google Maps API by Leaflet & OSM
  doc/Development_Documentation/img/classes-datatypes-geo-1.png
  doc/Development_Documentation/img/classes-datatypes-geo-2.png
  doc/Development_Documentation/img/classes-datatypes-geo-3.png
  doc/Development_Documentation/img/classes-datatypes-geo-4.png
  pimcore/lib/Pimcore/Bundle/AdminBundle/Controller/Admin/IndexController.php
  pimcore/lib/Pimcore/Bundle/AdminBundle/Resources/views/Admin/Index/index.html.php
  pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/Configuration.php
  pimcore/models/DataObject/ClassDefinition/Data/Geo/AbstractGeo.php
  web/pimcore/static6/css/admin.css
  web/pimcore/static6/js/lib/leaflet.draw/images/layers-2x.png
  web/pimcore/static6/js/lib/leaflet.draw/images/layers.png
  web/pimcore/static6/js/lib/leaflet.draw/images/marker-icon-2x.png
  web/pimcore/static6/js/lib/leaflet.draw/images/marker-icon.png
  web/pimcore/static6/js/lib/leaflet.draw/images/marker-shadow.png
  web/pimcore/static6/js/lib/leaflet.draw/images/spritesheet-2x.png
  web/pimcore/static6/js/lib/leaflet.draw/images/spritesheet.png
  web/pimcore/static6/js/lib/leaflet.draw/images/spritesheet.svg
  web/pimcore/static6/js/lib/leaflet.draw/leaflet.draw-src.css
  web/pimcore/static6/js/lib/leaflet.draw/leaflet.draw-src.js
  web/pimcore/static6/js/lib/leaflet.draw/leaflet.draw-src.map
  web/pimcore/static6/js/lib/leaflet.draw/leaflet.draw.css
  web/pimcore/static6/js/lib/leaflet.draw/leaflet.draw.js
  web/pimcore/static6/js/lib/leaflet/images/layers-2x.png
  web/pimcore/static6/js/lib/leaflet/images/layers.png
  web/pimcore/static6/js/lib/leaflet/images/marker-icon-2x.png
  web/pimcore/static6/js/lib/leaflet/images/marker-icon.png
  web/pimcore/static6/js/lib/leaflet/images/marker-shadow.png
  web/pimcore/static6/js/lib/leaflet/leaflet-src.js
  web/pimcore/static6/js/lib/leaflet/leaflet-src.js.map
  web/pimcore/static6/js/lib/leaflet/leaflet.css
  web/pimcore/static6/js/lib/leaflet/leaflet.js
  web/pimcore/static6/js/lib/leaflet/leaflet.js.map
  web/pimcore/static6/js/pimcore/object/classes/data/geo/abstract.js
  web/pimcore/static6/js/pimcore/object/tags/geo/abstract.js
  web/pimcore/static6/js/pimcore/object/tags/geobounds.js
  web/pimcore/static6/js/pimcore/object/tags/geopoint.js
  web/pimcore/static6/js/pimcore/object/tags/geopolygon.js
Labels: Task

#3092 Fix dropdowns option editor empty apply
  web/pimcore/static6/js/pimcore/object/helpers/optionEditor.js
Labels: Bug

#3093 Fix generated PhpDoc of ObjectBricks
  pimcore/models/DataObject/ClassDefinition/Data.php
Labels: Improvement

#3123 Fix for date filter 'ON' not fetching correct results
  pimcore/models/Tool/CustomReport/Adapter/Sql.php
Labels: Bug

#3126 Bugfix sanitizedPath
  pimcore/models/Element/Service.php
Labels: Bug

#3106 Replace prototype-light.js
  bundles/AdminBundle/Resources/public/js/lib/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/wysiwyg.js
  bundles/AdminBundle/Resources/public/js/pimcore/event-dispatcher.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/analytics.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/customreports.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/feed.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/modificationStatistic.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/modifiedAssets.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/modifiedDocuments.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/modifiedObjects.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/piwik.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/booleanSelect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
  bundles/AdminBundle/Resources/public/js/pimcore/perspective.js
  bundles/AdminBundle/Resources/public/js/pimcore/plugin/broker.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/analytics/siteoverview.js
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
  bundles/AdminBundle/Resources/public/js/pimcore/user.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5.md
Labels: Task

#3136 Fixed syntax error in classificationstore
  pimcore/models/DataObject/Classificationstore/KeyConfig/Listing/Dao.php
Labels: Bug

#3141 Fix Converter file name is only to the first Whitespace
  pimcore/models/Asset/Video/Thumbnail/Processor.php
Labels: Bug

#3143 Feature / allow hide single items in context menu
  app/config/pimcore/customviews.example.php
  web/pimcore/static6/js/pimcore/document/tree.js
Labels: Improvement

#3157 Add parent class and traits for listing data object model
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_FilterDefinition_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolCustomProduct_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOfferItem_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOffer_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrderItem_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopTaxClass_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherSeries_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherToken_export.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/01_Inheritance.md
  doc/Development_Documentation/20_Extending_Pimcore/07_Parent_Class_for_Objects.md
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Service.php
  models/Webservice/Data/ClassDefinition.php
  tests/_support/Resources/objects/class-allfields.json
  tests/_support/Resources/objects/class-import.json
  tests/_support/Resources/objects/classificationstore.json
  tests/_support/Resources/objects/inheritance.json
Labels: Improvement

#3153 Add setter for maxWriteToCacheItems
  lib/Cache/Core/CoreHandler.php
Labels: Task
