Repository pimcore/pimcore, pull requests merged in 2019-11, with the labels that each got.

#5194 [ClassificationStore] - add given group to active groups
  models/DataObject/Classificationstore.php
Labels: Improvement

#5192 [Document] Fix: Tags getElement method returns only saved data
  models/Document/PageSnippet.php
  models/Document/PageSnippet/Dao.php
  models/Document/Tag.php
  models/Document/Tag/Area.php
  models/Document/Tag/Area/Info.php
  models/Document/Tag/Areablock.php
  models/Document/Tag/Block.php
  models/Document/Tag/Link.php
  models/Document/Tag/Scheduledblock.php
  models/Document/Tag/Wysiwyg.php
Labels: Task

#5213 Move ss option of ffmpeg to the beginning
  lib/Video/Adapter/Ffmpeg.php
Labels: Improvement

#5215 [Documents] WYSIWYG editable - fix Phone Number field styling for Link
  bundles/AdminBundle/Resources/public/css/editmode.css
Labels: Improvement

#5216 [Document|Data Object] Video dialog: switch video type when pasting a URL
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#5217 [Documents] Pretty URL warnings
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/pages/settings.js
Labels: Improvement

#5175 Objectbricks mandatory fields are not validated correctly
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/Concrete.php
Labels: Bug

#4977 Pimcore installation on MySQL with required SSL connection
  bundles/InstallBundle/Command/InstallCommand.php
  bundles/InstallBundle/Installer.php
Labels: Improvement

#4941 Add toolbar button for sharing currently opened element via notification
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
  bundles/AdminBundle/Resources/public/js/pimcore/notification/modal.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/18_Tools_and_Features/41_Notifications.md
  doc/Development_Documentation/img/share_via_notifications_example.png
Labels: New Feature

#5182 [ADMIN] Token login links shouldn't contain the username
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Security/Guard/AdminAuthenticator.php
  lib/Tool/Authentication.php
Labels: Improvement

#5208 [Asset] Metadata - disallow tilde(~) in names
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
  models/Metadata/Predefined.php
Labels: BC-BREAK, Task

#5157 [Asset] Grid Improvements - Batch edit Asset metadata
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Helper/GridHelperService.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/gridConfigDialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/date.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/select.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/textarea.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridCellEditor.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/wysiwyg.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  models/Asset/Service.php
Labels: New Feature

#5231 Fix: deleting element containing pimcore_areablock
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/areablock.js
Labels: Bug

#5237 Fix: Unable to restore deleted objects-folder recursively from recycle bin
  models/Element/Recyclebin/Item.php
Labels: Bug

#5236 [Documents] Deleting snippet always shows dependency warning
  models/Dependency.php
Labels: Bug

#5230 [Assets, Documents] Do not load listing data on Asset::getList() / Document::getList()
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
Labels: Bug, Task

#5233 [ClassificationStorre] Error validating mandatory fields
  models/DataObject/ClassDefinition/Data/Classificationstore.php
Labels: Bug

#5222 [Admin] Remove jQuery in Admin UI
  3rd-party-licenses.md
  bundles/AdminBundle/Resources/public/js/lib/jquery-3.4.1.min.js
  bundles/AdminBundle/Resources/public/js/lib/jquery-3.4.1.min.map
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/edit.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/printpages/pdf_preview.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geo/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geobounds.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopoint.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopolygon.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopolyline.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/targeting/conditions.js
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
  bundles/AdminBundle/Resources/views/Admin/Asset/imageEditor.html.php
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/AdminBundle/Resources/views/Admin/Login/layout.html.php
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
  bundles/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.php
  bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
  bundles/EcommerceFrameworkBundle/Resources/public/js/voucherservice/voucherSeriesTabScript.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap4/js/bootstrap-native-v4.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap4/js/bootstrap.bundle.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap4/js/bootstrap.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap4/js/bootstrap.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/flatpickr.min.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/flatpickr.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/jquery-1.11.1.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/jquery-2.1.3.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/jquery-3.4.1.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/pickadate.classic.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/pickadate.classic.date.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/pickadate.classic.time.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/picker.date.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/picker.date.v3.5.3.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/picker.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/picker.v3.5.3.js
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/detail.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/list.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/back-office.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/parts/modals/cleanup_reservations_modal.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/parts/modals/pattern/cleanup_modal.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/parts/usage_statistic_script.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/voucher_code_tab_pattern.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/voucher_code_tab_single.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/voucher_layout.html.twig
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  license-faq.md
Labels: BC-BREAK, Improvement

#5242 [UI][User] "Copy to clipboard" feature for "Login as this user" dialog
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js
Labels: Improvement

#5243 [Data objects] Truncate unique fields on copying
  models/DataObject/Service.php
  models/Element/Service.php
Labels: Improvement

#5245 Fix: Better check for project root and fall back to env
  .gitignore
  lib/Bootstrap.php
  tests/_bootstrap.php
Labels: Task

#5248 Move Symfony toolbar trigger to left navigation bar
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
Labels: Improvement

#5258 [Document] Performance optimization when working with sites/hardlinks
  bundles/CoreBundle/Resources/migrations/Version20191114132014.php
  bundles/InstallBundle/Resources/install.sql
  models/Document.php
  models/Document/Page.php
Labels: Improvement

#5263 [Assets] Fix metadata grid issues
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Helper/GridHelperService.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/gridConfigDialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/select.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/textarea.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#5256 [Documents] Properties - Add document language inheritance rollback option
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/properties.js
  bundles/CoreBundle/Resources/migrations/Version20191114123638.php
Labels: Improvement

#5273 Add icon select to classdefinition
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/img/object-icons/00_purple.svg
  bundles/AdminBundle/Resources/public/img/object-icons/01_magenta.svg
  bundles/AdminBundle/Resources/public/img/object-icons/02_red.svg
  bundles/AdminBundle/Resources/public/img/object-icons/03_vermilion.svg
  bundles/AdminBundle/Resources/public/img/object-icons/04_orange.svg
  bundles/AdminBundle/Resources/public/img/object-icons/05_amber.svg
  bundles/AdminBundle/Resources/public/img/object-icons/06_yellow.svg
  bundles/AdminBundle/Resources/public/img/object-icons/07_chartreuse.svg
  bundles/AdminBundle/Resources/public/img/object-icons/08_green.svg
  bundles/AdminBundle/Resources/public/img/object-icons/09_teal.svg
  bundles/AdminBundle/Resources/public/img/object-icons/10_blue.svg
  bundles/AdminBundle/Resources/public/img/object-icons/11_violet.svg
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  lib/Event/AdminEvents.php
Labels: Improvement

#5275 [DataObject] Start Map Search in Geo Data fields with Enter key
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geobounds.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopoint.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopolygon.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopolyline.js
Labels: Improvement

#5280 [ImageOptimizerQueue] write file path to 'data' column instead of 'id' column
  lib/Maintenance/Tasks/ImageOptimizeTask.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: Bug

#5254 Fix: exception 'undefined index google' on running tests
  lib/Config.php
Labels: Task

#5287 [Admin] DataObjects - Allow 'Search and Move' on Empty Folders
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
Labels: Improvement

#5296 [Maintenance] Refactor Db connection layer for maintenance tasks
  lib/Maintenance/Tasks/CheckErrorLogsDbTask.php
  lib/Maintenance/Tasks/DbCleanupBrokenViewsTask.php
  lib/Maintenance/Tasks/LogArchiveTask.php
  lib/Maintenance/Tasks/LogErrorCleanupTask.php
  lib/Maintenance/Tasks/LogMailMaintenanceTask.php
  lib/Maintenance/Tasks/TmpStoreCleanupTask.php
Labels: Improvement

#5312 Add grid helpers refactoring notice #5304
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#5286 Fixed layout bug which granted access to admin layout without permissions
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#5203 Ecommerce | Reindex Command Improvement
  bundles/EcommerceFrameworkBundle/Command/IndexService/ResetQueueCommand.php
Labels: Approved, Improvement

#5181 Ecommerce index service improvements and advanced error handling events in ecommerce index preparation
  bundles/CoreBundle/Resources/migrations/Version20191121150326.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractWorker.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultMysql.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/OptimizedMysql.php
  doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
  lib/Event/Ecommerce/IndexServiceEvents.php
  lib/Event/Model/Ecommerce/IndexService/PreprocessAttributeErrorEvent.php
  lib/Event/Model/Ecommerce/IndexService/PreprocessErrorEvent.php
Labels: Approved, Improvement

#5336 fixed #5259 - [IndexService][ElasticSearch] - Duplicate entries (same _id) in elastic search
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/OptimizedMysql.php
Labels: Bug

#5332 [Ecommerce] Updated data column of index store table to LONGTEXT
  bundles/CoreBundle/Resources/migrations/Version20191125135853.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
Labels: Improvement

#5339 Refactor PageController::checkPrettyUrlAction()
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
Labels: Bug, Task

#5344 Simplification of the ecommerce tracking for custom product data
  bundles/EcommerceFrameworkBundle/Tracking/AbstractData.php
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/EnhancedEcommerce.php
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/UniversalEcommerce.php
  bundles/EcommerceFrameworkBundle/Tracking/TrackingItemBuilder.php
Labels: Improvement

#5320 [Documents] Add default value option for Select Editable
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/select.js
  doc/Development_Documentation/03_Documents/01_Editables/30_Select.md
Labels: Improvement

#5330 [Email] Add option to forward sent emails #5193
  bundles/AdminBundle/Controller/Admin/EmailController.php
  bundles/AdminBundle/Resources/public/img/flat-color-icons/email-forward.svg
  bundles/AdminBundle/Resources/public/js/pimcore/settings/email/log.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: Improvement

#5349 While cloning a Select or Multiselect field, all attributes are not saved in cloned field.
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/multiselect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/select.js
Labels: Bug

#5294 [Assets] Metadata Grid - fix 'ON' date filter
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Bug

#5321 fixed Inconsistency in versioning system
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
Labels: Bug

#5310 Always use PIMCORE_PHP_ERROR_REPORTING and fix PHP notices
  .travis.yml
  bin/pimcore-install
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/Helper/GridHelperService.php
  bundles/EcommerceFrameworkBundle/CartManager/CartPriceModificator/Discount.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
  bundles/EcommerceFrameworkBundle/PricingManager/Rule.php
  lib/Bootstrap.php
  lib/Config.php
  lib/Helper/Dashboard.php
  lib/Kernel.php
  lib/Model/Listing/Dao/AbstractDao.php
  lib/Pimcore.php
  lib/Tool.php
  models/Asset.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/Classificationstore/Dao.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Concrete/Dao/InheritanceHelper.php
  models/DataObject/Data/Link.php
  models/DataObject/Localizedfield.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Data/AbstractData.php
  models/DataObject/Objectbrick/Data/Dao.php
  models/DataObject/Service.php
  models/DataObject/Traits/ObjectVarTrait.php
  models/Document/PageSnippet.php
  models/Document/Tag/Areablock.php
  models/Document/Tag/Image.php
  models/Element/Service.php
  models/Metadata/Predefined.php
  models/Notification/Service/NotificationService.php
  models/Translation/AbstractTranslation/Listing/Dao.php
  tests/_support/Util/TestHelper.php
  tests/rest/ObjectTest.php
Labels: Task

#5352 [Custom Reports] Use Labels as headers instead of field name in export file
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
Labels: Improvement
