Repository pimcore/pimcore, pull requests merged in 2019-05, with the labels that each got.

#4311 Fix documents template setting load
  bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
Labels: Bug

#4320 Fix down logic in Migration 20190403120728
  bundles/CoreBundle/Resources/migrations/Version20190403120728.php
Labels: Bug

#4342 [Symfony 4] Define commands as services #3799
  bundles/CoreBundle/Resources/config/commands.yml
  bundles/CoreBundle/Resources/config/services.yml
  bundles/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  bundles/EcommerceFrameworkBundle/Resources/config/commands.yml
Labels: Task

#4331 Use index for version maintenance query
  bundles/CoreBundle/Resources/migrations/Version20190508074339.php
  bundles/InstallBundle/Resources/install.sql
Labels: Improvement

#4350 Make EcommerceFrameworkBundle::hasCurrentUserId() more reliable
  bundles/EcommerceFrameworkBundle/Environment.php
  bundles/EcommerceFrameworkBundle/SessionEnvironment.php
Labels: Improvement

#4352 Fix dependencies rendering
  bundles/AdminBundle/Resources/public/js/pimcore/element/dependencies.js
Labels: Bug

#4356 [Fieldcollection] Allow class definition import with missing fieldcollections
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/Fieldcollection/Definition.php
Labels: Improvement

#4360 [DataObject] If newer (not published) object version is available, published state is not shown correctly in Pimcore Admin
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
Labels: Bug, Prio-Backlog

#4362 new Image cacheBuster Feature was not working
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Bug

#4364 [Symfony 4] Replace sensio/distribution-bundle #4340
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
  lib/Composer.php
  lib/Kernel.php
Labels: Task

#4348 Updates for SensioFrameworkExtraBundle latest version(^5.2)
  bundles/CoreBundle/DependencyInjection/Compiler/LegacyTemplatePass.php
  bundles/CoreBundle/DependencyInjection/Compiler/RoutingLoaderPass.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/EventListener/LegacyTemplateListener.php
  bundles/CoreBundle/EventListener/TemplateControllerListener.php
  bundles/CoreBundle/PimcoreCoreBundle.php
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Templating/LegacyTemplateGuesser.php
  composer.json
  lib/Controller/Config/ConfigNormalizer.php
  lib/Routing/Loader/AnnotatedRouteControllerLoader.php
  lib/Twig/Extension/AssetCompressExtension.php
  lib/Twig/Extension/DocumentTagExtension.php
  lib/Twig/Extension/DumpExtension.php
  lib/Twig/Extension/GlossaryExtension.php
  lib/Twig/Extension/HelpersExtension.php
  lib/Twig/Extension/NavigationExtension.php
  lib/Twig/Extension/PimcoreObjectExtension.php
  lib/Twig/Extension/SubrequestExtension.php
  lib/Twig/Extension/TemplatingHelperExtension.php
  lib/Twig/Extension/WebsiteConfigExtension.php
Labels: Task

#4373 Fix: Deprecations of Twig, Google Client and Pimcore
  composer.json
  lib/Config.php
  lib/Google/Api.php
  lib/Templating/Helper/Cache.php
  lib/Twig/Extension/DocumentTagExtension.php
  lib/Twig/Extension/HelpersExtension.php
  lib/Twig/Extension/NavigationExtension.php
  lib/Twig/Extension/PimcoreObjectExtension.php
  lib/Twig/Extension/SubrequestExtension.php
  lib/Twig/Extension/TemplatingHelperExtension.php
  lib/Twig/Extension/WebsiteConfigExtension.php
  lib/Twig/Node/AssetCompressNode.php
  lib/Twig/Node/GlossaryNode.php
  lib/Twig/TokenParser/AssetCompressParser.php
  lib/Twig/TokenParser/GlossaryTokenParser.php
  models/Asset/Image/Thumbnail.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: Task

#4367 Fix: Missing field name translation in grid cell editor
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridCellEditor.js
Labels: Bug

#4368 [Symfony 4] Replace SensioGeneratorBundle #3275
  bundles/GeneratorBundle/Command/BaseGenerateBundleCommand.php
  bundles/GeneratorBundle/Command/BaseGeneratorCommand.php
  bundles/GeneratorBundle/Command/GenerateBundleCommand.php
  bundles/GeneratorBundle/Command/Helper/QuestionHelper.php
  bundles/GeneratorBundle/Command/Validators.php
  bundles/GeneratorBundle/Generator/BaseBundleGenerator.php
  bundles/GeneratorBundle/Generator/BundleGenerator.php
  bundles/GeneratorBundle/Generator/DoctrineCrudGenerator.php
  bundles/GeneratorBundle/Generator/Generator.php
  bundles/GeneratorBundle/Manipulator/ConfigurationManipulator.php
  bundles/GeneratorBundle/Manipulator/KernelManipulator.php
  bundles/GeneratorBundle/Manipulator/Manipulator.php
  bundles/GeneratorBundle/Manipulator/RoutingManipulator.php
  bundles/GeneratorBundle/Model/BaseBundle.php
  bundles/GeneratorBundle/Model/Bundle.php
  bundles/GeneratorBundle/Resources/config/services.yml
  bundles/GeneratorBundle/Resources/skeleton/bundle/BaseBundle.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/Bundle.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/Configuration.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/DefaultControllerTest.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/Extension.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/index.html.twig.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/routing.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/routing.xml.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/routing.yml.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/services.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/services.xml.twig
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
  lib/Kernel.php
Labels: Task

#4385 [Symfony 4] Fix Guard Authenticator deprecations
  bundles/AdminBundle/Security/Guard/AdminAuthenticator.php
Labels: Task

#4376 Sort objects numerically when sorting by index
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Improvement

#4349 [Newsletter] Improved error handling while sending newsletter
  bundles/CoreBundle/Command/InternalNewsletterDocumentSendCommand.php
  lib/Mail.php
  lib/Tool/Newsletter.php
Labels: Improvement

#4402 [Symfony 4] Cache Compatibility
  lib/Cache/Pool/AbstractCacheItemPool.php
  lib/Cache/Pool/CacheItem.php
  tests/_support/Util/TestHelper.php
  tests/cache/Factory.php
  tests/cache/Pool/SymfonyProxy/ArrayAdapterProxyTest.php
  tests/cache/Pool/SymfonyProxy/FilesystemAdapterProxyTest.php
Labels: Task

#4405 Remove Legacy Mode and Support for v4 Compatibility Bridge
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
  bundles/AdminBundle/Controller/Rest/InfoController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/extensionmanager/admin.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
  bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
  bundles/CoreBundle/Resources/migrations/Version20190520151448.php
  bundles/CoreBundle/Resources/translations/en.json
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
  lib/Bootstrap.php
  lib/Document/Tag/TagHandlerInterface.php
  lib/ExtensionManager.php
  lib/Helper/LegacyClass.php
  lib/Helper/LongRunningHelper.php
  lib/Pimcore.php
  lib/Routing/Dynamic/DocumentRouteHandler.php
  lib/Routing/Staticroute/Router.php
  lib/Templating/Renderer/IncludeRenderer.php
  lib/Tool.php
  models/Document.php
  models/Document/DocType.php
  models/Document/DocType/Dao.php
  models/Document/PageSnippet.php
  models/Document/Service.php
  models/Document/Tag/Area.php
  models/Document/Tag/Area/Info.php
  models/Document/Tag/Areablock.php
  models/Staticroute.php
  models/Staticroute/Dao.php
  stubs/compatibility-v4.php
Labels: Task

#4417 [Document|Object] Sort contextmenu by translated names
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Improvement

#4338 Checkbox nullvalue
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
Labels: BC-BREAK, Improvement

#4245 Add CSS selector for classification store tag
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
Labels: Task

#4413 [Symfony4] Fix deprecations
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/DependencyInjection/Compiler/SerializerPass.php
  bundles/CoreBundle/Command/Bundle/AbstractBundleCommand.php
  bundles/CoreBundle/Command/Bundle/DisableCommand.php
  bundles/CoreBundle/Command/Bundle/EnableCommand.php
  bundles/CoreBundle/Command/Bundle/InstallCommand.php
  bundles/CoreBundle/Command/Bundle/ListCommand.php
  bundles/CoreBundle/Command/Bundle/UninstallCommand.php
  bundles/CoreBundle/Command/Bundle/UpdateCommand.php
  bundles/CoreBundle/Controller/PublicServicesController.php
  bundles/CoreBundle/Resources/config/commands.yml
  doc/Development_Documentation/01_Getting_Started/03_Configuration.md
  doc/Development_Documentation/19_Development_Tools_and_Details/35_Working_with_Sessions.md
  doc/Development_Documentation/19_Development_Tools_and_Details/40_Custom_Admin_Login_Entry_Point.md
  lib/Console/AbstractCommand.php
  lib/Controller/Controller.php
  lib/Routing/Dynamic/DocumentRouteHandler.php
  lib/Tool/Console.php
  lib/Translation/Translator.php
Labels: Task

#4420 [Data Object] make call of preGetValue() hook optional
  bundles/EcommerceFrameworkBundle/Model/AbstractFilterDefinition.php
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/01_Inheritance.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/Concrete.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
  models/DataObject/PreGetValueHookInterface.php
Labels: BC-BREAK

#4381 Performance enhancement when moving object to folder with lots of children
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Improvement

#4450 [Element] removed ChildsCompatibilityTrait from all Elements
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/SelectRelation.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectRelation.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectRelation.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
  models/Asset.php
  models/Asset/Dao.php
  models/Asset/Folder.php
  models/Asset/Service.php
  models/DataObject/AbstractObject.php
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/Service.php
  models/Document.php
  models/Document/Dao.php
  models/Document/Hardlink.php
  models/Document/Hardlink/Wrapper.php
  models/Document/Hardlink/Wrapper/Email.php
  models/Document/Hardlink/Wrapper/Folder.php
  models/Document/Hardlink/Wrapper/Hardlink.php
  models/Document/Hardlink/Wrapper/Link.php
  models/Document/Hardlink/Wrapper/Page.php
  models/Document/Hardlink/Wrapper/Printcontainer.php
  models/Document/Hardlink/Wrapper/Printpage.php
  models/Document/Hardlink/Wrapper/Snippet.php
  models/Document/Printcontainer.php
  models/Document/Service.php
  models/Element/AbstractElement.php
  models/Element/Export/Service.php
  models/Element/Recyclebin/Item.php
  models/Element/Service.php
  models/Webservice/Data/Asset.php
  models/Webservice/Data/DataObject.php
  models/Webservice/Data/Document.php
Labels: Task

#4453 [Data Object] Remove Object <> DataObject autoloader aliases
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
  lib/Bootstrap.php
  lib/Loader/Autoloader/DataObjectCompatibility.php
Labels: Task

#4447 Es Bugfix - Bool filter
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/MultiSelect.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/AbstractConfig.php
Labels: Bug

#4462 [Autoloader] Removed alias autoloader
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
  lib/Bootstrap.php
  lib/Loader/Autoloader/AbstractAutoloader.php
  lib/Loader/Autoloader/AliasMapper.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Href.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Multihref.php
  models/DataObject/ClassDefinition/Data/MultihrefMetadata.php
  models/DataObject/ClassDefinition/Data/Nonownerobjects.php
  models/DataObject/ClassDefinition/Data/Objects.php
  models/DataObject/ClassDefinition/Data/ObjectsMetadata.php
  models/DataObject/ClassDefinition/Data/ReverseManyToManyObjectRelation.php
  models/Document/Tag/Href.php
  models/Document/Tag/Multihref.php
  models/Document/Tag/Relation.php
  models/Document/Tag/Relations.php
Labels: BC-BREAK, Task

#4461 [DataObject] Remove data types BC layers - see #4378
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
  lib/Tool.php
  models/DataObject/ClassDefinition/Dao.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Fieldcollection/Dao.php
  models/DataObject/Fieldcollection/Data/Dao.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
  models/DataObject/Objectbrick/Definition/Dao.php
Labels: BC-BREAK, Task
