Repository pimcore/pimcore, pull requests merged in 2019-08, with the labels that each got.

#4781 Sort permissions for users & roles by categories
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/role/settings.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js
  bundles/CoreBundle/Resources/migrations/Version20190729085052.php
  models/User/Permission/Definition.php
Labels: Improvement

#4699 Start session for ecommerce indexer when run in cli - v2
  bundles/EcommerceFrameworkBundle/IndexService/Tool/IndexUpdater.php
Labels: Improvement

#4794 [Documents] Newsletter: add option to maintain a manual edited plain-text version
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/document/newsletter.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/newsletters/plaintextPanel.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/Resources/translations/de.json
  bundles/CoreBundle/Resources/translations/en.json
  lib/Tool/Newsletter.php
  models/Document/Newsletter.php
Labels: New Feature

#4723 Remove FeatureToggles
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Rest/AbstractRestController.php
  bundles/AdminBundle/Controller/Rest/Element/DocumentController.php
  bundles/AdminBundle/EventListener/AdminExceptionListener.php
  bundles/AdminBundle/EventListener/HttpCacheListener.php
  bundles/CoreBundle/DataCollector/PimcoreDataCollector.php
  bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
  bundles/CoreBundle/EventListener/Frontend/OutputTimestampListener.php
  bundles/CoreBundle/EventListener/ResponseExceptionListener.php
  bundles/CoreBundle/Resources/config/services.yml
  bundles/CoreBundle/Resources/views/Profiler/data_collector.html.twig
  bundles/EcommerceFrameworkBundle/Model/DefaultMockup.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php
  composer.json
  doc/Development_Documentation/19_Development_Tools_and_Details/03_Feature_Flags_And_Debug_Mode.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_V5_to_V6.md
  lib/Bootstrap.php
  lib/Cache.php
  lib/Config.php
  lib/Config/EnvironmentConfig.php
  lib/FeatureToggles/Feature.php
  lib/FeatureToggles/FeatureContext.php
  lib/FeatureToggles/FeatureContextInterface.php
  lib/FeatureToggles/FeatureManager.php
  lib/FeatureToggles/FeatureManagerInterface.php
  lib/FeatureToggles/FeatureState.php
  lib/FeatureToggles/FeatureStateInitializerInterface.php
  lib/FeatureToggles/FeatureStateInterface.php
  lib/FeatureToggles/Features/DebugMode.php
  lib/FeatureToggles/Features/DevMode.php
  lib/FeatureToggles/Initializers/ClosureInitializer.php
  lib/Mail.php
  lib/Mail/Plugins/RedirectingPlugin.php
  lib/Pimcore.php
  lib/Targeting/Code/TargetingCodeGenerator.php
  lib/Tool.php
  models/Document/Tag.php
  models/Document/Tag/Pdf.php
  models/Document/Tag/Renderlet.php
  models/Document/Tag/Snippet.php
  models/Document/Tag/Video.php
  tests/unit/FeatureToggles/FeatureContextTest.php
  tests/unit/FeatureToggles/FeatureManagerTest.php
  tests/unit/FeatureToggles/FeatureStateTest.php
  tests/unit/FeatureToggles/FeatureTest.php
  tests/unit/FeatureToggles/Fixtures/Features.php
  tests/unit/FeatureToggles/Initializers/ClosureInitializerTest.php
Labels: Task

#4676 Reduce size of version files
  models/Version.php
  models/Version/ElementDescriptor.php
  models/Version/MarshalMatcher.php
  models/Version/UnmarshalMatcher.php
  tests/_bootstrap.php
  tests/_support/ServiceTester.php
  tests/_support/Util/TestHelper.php
  tests/service.suite.dist.yml
  tests/service/Element/VersionTest.php
  tests/service/_bootstrap.php
Labels: Improvement

#4764 Add setter for default currency in ecommerce environment.
  bundles/EcommerceFrameworkBundle/Environment.php
  bundles/EcommerceFrameworkBundle/EnvironmentInterface.php
Labels: BC-BREAK, Improvement

#4645 [Ecommerce] Refactoring Voucher Service
  bundles/CoreBundle/Resources/translations/en.json
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/CartManager/CartInterface.php
  bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculator.php
  bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculatorInterface.php
  bundles/EcommerceFrameworkBundle/Exception/VoucherServiceException.php
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/Bracket.php
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/BracketInterface.php
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/VoucherToken.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManagerInterface.php
  bundles/EcommerceFrameworkBundle/PricingManager/Rule.php
  bundles/EcommerceFrameworkBundle/PricingManager/RuleInterface.php
  bundles/EcommerceFrameworkBundle/Resources/config/voucher_service.yml
  bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js
  bundles/EcommerceFrameworkBundle/VoucherService/DefaultService.php
  bundles/EcommerceFrameworkBundle/VoucherService/PricingManagerTokenInformation.php
  bundles/EcommerceFrameworkBundle/VoucherService/Reservation.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/AbstractTokenManager.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php
  bundles/EcommerceFrameworkBundle/VoucherService/VoucherServiceInterface.php
  doc/Development_Documentation/10_E-Commerce_Framework/09_Working_with_Prices/07_Vouchers.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: BC-BREAK, Improvement

#4809 Transmit values of system columns to grid operators
  lib/DataObject/GridColumnConfig/Value/DefaultValue.php
Labels: Bug

#4693 [Assets] Get checksum of remote assets before they got saved
  models/Asset.php
Labels: Improvement

#3696 Improvements Mpay24
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Mpay24Seamless.php
Labels: Improvement

#4403 Grid Tab batch edit error only show the IDs
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
Labels: Improvement

#4529 [XLIFF] Support for blocks in localized fields and field collections containing localized fields
  lib/Translation/AttributeSet/Attribute.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
  lib/Translation/ImporterService/Importer/DataObjectImporter.php
Labels: Improvement

#4819 [Documents] Navigation - Added option to provide class for sub menus
  doc/Development_Documentation/03_Documents/03_Navigation.md
  lib/Navigation/Renderer/Menu.php
Labels: Improvement

#4801 [Ecommerce] Back Office - migrate order templates to Twig
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Resources/migrations/Version20190807121356.php
  bundles/CoreBundle/Resources/translations/en.json
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/PimcoreEcommerceFrameworkBundle.php
  bundles/EcommerceFrameworkBundle/Resources/install/admin-translations/init.csv
  bundles/EcommerceFrameworkBundle/Resources/public/css/back-office.css
  bundles/EcommerceFrameworkBundle/Resources/public/js/bundle.js
  bundles/EcommerceFrameworkBundle/Resources/public/js/order/OrderTab.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap4/css/bootstrap.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap4/css/bootstrap.min.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap4/js/bootstrap.bundle.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap4/js/bootstrap.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap4/js/bootstrap.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome-all.min.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/jquery-3.4.1.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/pickadate.classic.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/pickadate.classic.date.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/pickadate.classic.time.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/picker.date.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/picker.js
  bundles/EcommerceFrameworkBundle/Resources/views/AdminOrder/detail.html.php
  bundles/EcommerceFrameworkBundle/Resources/views/AdminOrder/itemCancel.html.php
  bundles/EcommerceFrameworkBundle/Resources/views/AdminOrder/itemComplaint.html.php
  bundles/EcommerceFrameworkBundle/Resources/views/AdminOrder/itemEdit.html.php
  bundles/EcommerceFrameworkBundle/Resources/views/AdminOrder/list.html.php
  bundles/EcommerceFrameworkBundle/Resources/views/Includes/paging.html.php
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/detail.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/item_cancel.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/item_complaint.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/item_edit.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/list.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/back-office.html.php
  bundles/EcommerceFrameworkBundle/Resources/views/back-office.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/includes/paging.html.twig
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#4808 [Ecommerce][CartManager] Calculate GiftItems of Cart only if not already calculated
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculator.php
  bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculatorInterface.php
Labels: BC-BREAK, Improvement

#4827 [Ecommerce] Consider json_decode errors on updating index
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
Labels: Improvement

#4834 Allow _ in custom object layout names
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
Labels: Task

#4838 [ecommerceframework][v7 CheckoutManager] recreate order if trying to start a payment with an aborted, cancelled or commited order
  bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CheckoutManager.php
Labels: Improvement

#4849 [UI] Use monospace font for server file explorer
  bundles/AdminBundle/Resources/public/js/pimcore/settings/fileexplorer/file.js
Labels: Improvement

#4859 [Assets] Make metadata setters chainable
  models/Asset.php
Labels: Task

#4842 [Session] Use PHP's default session mechanism
  bundles/AdminBundle/Session/Handler/AbstractAdminSessionHandler.php
  bundles/AdminBundle/Session/Handler/AdminSessionHandler.php
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#4856 Version restore of objects with inexisting advanced many to many obje…
  models/DataObject/Data/ElementMetadata.php
  models/DataObject/Data/ObjectMetadata.php
Labels: Bug

#4863 [Version] Added marshal-filter for container and view-model
  models/Version.php
Labels: Bug

#4877 override default dump_directory from public to web
  bundles/CoreBundle/Resources/config/pimcore/default.yml
Labels: Bug

#4785 Process queue improvements
  bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessQueueCommand.php
  bundles/EcommerceFrameworkBundle/IndexService/Tool/IndexUpdater.php
Labels: Improvement

#4869 [ecommerceframework][payment] add heidelpay payment provider implementation
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Heidelpay.php
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderHeidelPay_export.json
  phpstan.neon
Labels: Improvement

#4892 Hotspotimage does not use crop data when medias are available
  models/DataObject/Data/Hotspotimage.php
Labels: Bug

#4895 Adds missing content type to robots.txt
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Task

#4890 [Assets] hasMetaData should be false if setMetaData(null) gets called
  models/Asset.php
Labels: Bug

#4894 [Twig] Helper stubs for IDE auto-complete
  lib/Twig/Extension/DocumentTagExtension.php
  lib/Twig/Extension/TemplatingHelperExtension.php
Labels: Task

#4896 [Data Objects] Show editlock dialog only if user has permissions to edit object
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/FolderController.php
  bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
  bundles/AdminBundle/Controller/Admin/Document/LinkController.php
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
Labels: Improvement

#4899 Don't load by tag parent by empty id
  models/Element/Tag.php
Labels: Task

#4902 [DataObject] Avoid fatal errors if class definition file is missing
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Listing/Dao.php
Labels: Task

#4900 add primary key to http_error_log
  bundles/CoreBundle/Resources/migrations/Version20190828142756.php
  bundles/InstallBundle/Resources/install.sql
Labels: Improvement

#4866 [Workflows] Layout not reloaded after transition
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitionPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitions.js
Labels: Bug

#4860 [Document] Support for Folders & Links as a Fallback Document
  bundles/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
  bundles/CoreBundle/EventListener/Frontend/ElementListener.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: BC-BREAK, Improvement

#4904 Workflow notifications
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Resources/config/services_workflow.yml
  doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md
  doc/Development_Documentation/07_Workflow_Management/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Workflow/EventSubscriber/NotificationSubscriber.php
  lib/Workflow/Notification/AbstractNotificationService.php
  lib/Workflow/Notification/NotificationEmailService.php
  lib/Workflow/Notification/NotificationInterface.php
  lib/Workflow/Notification/NotificationTrait.php
  lib/Workflow/Notification/PimcoreNotificationService.php
  lib/Workflow/Transition.php
Labels: Improvement

#4906 fixed #4905 - [Elements] Save button must not unpublish element
  bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: BC-BREAK, Improvement
