Repository pimcore/pimcore, pull requests merged in 2019-06, with the labels that each got.

#4463 Enable localized fields in object bricks
  models/DataObject/Objectbrick/Definition.php
Labels: Improvement

#4485 add reload option to relations editable
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/relations.js
  doc/Development_Documentation/03_Documents/01_Editables/13_Relations_(Many-To-Many).md
Labels: Improvement

#4489 Fix wrong QuantityValue::getUnitWidth
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Bug

#4479 Make the custom layout pop up properly after page refresh.
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#4492 [EcommerceFramework][Datatrans-Lightbox] - add upp-start-target attribute
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
Labels: Improvement

#4475 [Core] Migrate System Config to Symfony Core
  .travis/app/config/config.yml
  .travis/app/config/local/database.yml
  .travis/app/config/system.yml
  .travis/setup-tests.sh
  .travis/system.template.php
  .travis/web/app_test.php
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/DependencyInjection/Configuration.php
  bundles/AdminBundle/DependencyInjection/PimcoreAdminExtension.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Resources/migrations/Version20190527121800.php
  bundles/InstallBundle/Command/InstallCommand.php
  bundles/InstallBundle/Installer.php
  bundles/InstallBundle/SystemConfig/ConfigWriter.php
  doc/Development_Documentation/01_Getting_Started/03_Configuration.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/23_Localized_Fields.md
  doc/Development_Documentation/18_Tools_and_Features/05_Notes_and_Events.md
  doc/Development_Documentation/18_Tools_and_Features/25_System_Settings.md
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing.md
  doc/Development_Documentation/21_Deployment/03_Multi_Environment.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
  lib/Bootstrap.php
  lib/Config.php
  lib/FeatureToggles/Features/DevMode.php
  lib/HttpKernel/Config/SystemConfigParamResource.php
  lib/Kernel.php
  lib/Pimcore.php
  lib/Tool/Console.php
Labels: BC-BREAK, Task

#4509 [UI] New Styling for Login-Page
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/css/login.css
  bundles/AdminBundle/Resources/public/img/login/pimconaut-ecommerce.svg
  bundles/AdminBundle/Resources/public/img/login/pimconaut-engineer.svg
  bundles/AdminBundle/Resources/public/img/login/pimconaut-moon.svg
  bundles/AdminBundle/Resources/public/img/login/pimconaut-rocket.svg
  bundles/AdminBundle/Resources/public/img/login/pimconaut-world.svg
  bundles/AdminBundle/Resources/public/img/logo-claim-white.svg
  bundles/AdminBundle/Resources/views/Admin/Login/layout.html.php
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
  bundles/AdminBundle/Resources/views/Admin/Login/lostpassword.html.php
  bundles/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.php
Labels: Task

#4511 [Ecommerce] Remove deprecated methods of CheckoutManager
  bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
Labels: BC-BREAK, Task

#4513 [Core] Normalize boolean values for configuration tree
  bundles/CoreBundle/DependencyInjection/Configuration.php
Labels: Task

#4503 Update siblings
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  models/DataObject/AbstractObject.php
  models/DataObject/Concrete.php
  models/DataObject/Concrete/Dao.php
  models/Version.php
Labels: Improvement

#4516 Add z-index property for WYSIWYG editable dialog box
  bundles/AdminBundle/Resources/public/css/editmode.css
Labels: Bug

#4499 [User Permissions] Fix wrong inheritance of wider permissions
  models/Asset/Dao.php
  models/DataObject/AbstractObject/Dao.php
  models/Document/Dao.php
Labels: Bug

#4408 Send language param in grid tab
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
Labels: Bug

#4524 Extend Validation Exeption
  models/DataObject/ClassDefinition/Data/Numeric.php
Labels: Improvement

#4546 Mysql password optional
  bundles/InstallBundle/Command/InstallCommand.php
Labels: Improvement

#4558 ApplicationLoggerDb service exception fix
  bundles/CoreBundle/Resources/config/logging.yml
Labels: Bug

#4564 Output document thumbnail with correct content-type header
  bundles/AdminBundle/Controller/Admin/AssetController.php
  models/Asset/Document.php
  models/Asset/Video.php
Labels: Bug

#4554 [ecommerceframework][elasticsearch] allow product index fields without mapping
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search.md
Labels: Improvement, Prio-Backlog

#4540 getBundle returns object so array_pop does not work
  bundles/CoreBundle/Templating/LegacyTemplateGuesser.php
Labels: Bug

#4523 Update GridHelperService.php
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Improvement

#4548 Elastic search subtenants
  bundles/EcommerceFrameworkBundle/IndexService/Config/DefaultElasticSearchSubTenantConfig.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/ElasticSearch.php
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/03_Assortment_Tenant_Configuration.md
Labels: Improvement

#4571 Re-enables delete action for admin translations
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translations.js
Labels: Bug

#4568 [ElementServices] Extend functionality
  models/Asset/Service.php
  models/DataObject/Service.php
  models/Document/Service.php
Labels: Improvement

#4581 [Custom layouts] Prevent SQL error for non-numarical ID
  models/DataObject/Service.php
Labels: Bug

#4559 Unless grid is filtered or sorted - ignore localized fields when getting ids
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Improvement, Prio-Backlog

#4542 Fix #4495: user.classes column too short for custom identifieres
  bundles/CoreBundle/Resources/migrations/Version20190618154000.php
  bundles/InstallBundle/Resources/install.sql
Labels: Improvement, Prio-Backlog
