Repository pimcore/pimcore, pull requests merged in 2019-12, with the labels that each got.

#5360 WYSIWYG: Simplify Regex to check for dependencies with `pimcore_(id|type)` attributes
  lib/Tool/Text.php
Labels: Task

#5363 Add indexedValues to the variables passed to view
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/SelectCategory.php
Labels: Improvement

#5348 [Ecommerce][Tracking] add GTM tracker
  bundles/CoreBundle/Resources/config/analytics.yml
  bundles/CoreBundle/Resources/views/Analytics/Tracking/GoogleTagManager/dataLayer.html.twig
  bundles/EcommerceFrameworkBundle/Resources/config/pimcore/config.yml
  bundles/EcommerceFrameworkBundle/Resources/config/tracking_manager.yml
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/tagManager/call.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/tagManager/call.js.twig
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/GoogleTagManager.php
  bundles/EcommerceFrameworkBundle/Tracking/TrackingItemBuilderInterface.php
  lib/Analytics/GoogleTagManager/EventSubscriber/TrackingCodeSubscriber.php
Labels: Improvement

#5315 [Translations] XLIFF Export - Add option to include relations
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/xliff.js
  bundles/CoreBundle/Resources/translations/en.extended.json
Labels: Improvement, New Feature

#5366 [Data Objects] fix all CVE's fixed in Pimcore > 6.* in 5.8 branch
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Controller/Admin/EmailController.php
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translations.js
  bundles/AdminBundle/Resources/views/Admin/Login/lostpassword.html.php
  bundles/CoreBundle/Resources/translations/en.json
  models/Notification/Service/NotificationService.php
Labels: Bug, Task

#5371 [Translations] Bugfix: "undefined" translation for new language
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translations.js
Labels: Bug

#5375 [Ecommerce][PricingManager] Rules should not not be loaded multiple times if no active rules exist
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
Labels: Improvement

#5372 Fix: Missing PHPDoc return tags
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Controller/Admin/WorkflowController.php
  bundles/AdminBundle/Controller/GDPR/AssetController.php
  bundles/AdminBundle/Controller/GDPR/DataObjectController.php
  bundles/AdminBundle/Controller/GDPR/PimcoreUsersController.php
  bundles/AdminBundle/Controller/GDPR/SentMailController.php
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/CartManager/CartCheckoutData/Listing.php
  bundles/EcommerceFrameworkBundle/Controller/PricingController.php
  lib/DataObject/Import/Service.php
  lib/Web2Print/Processor.php
  lib/helper-functions.php
  models/Asset.php
  models/Asset/Image/Thumbnail/Config.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/Textarea.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/ClassDefinition/Layout/Iframe.php
  models/DataObject/ClassDefinition/Layout/Text.php
  models/DataObject/Classificationstore/GroupConfig.php
  models/DataObject/Concrete.php
  models/DataObject/Data/StructuredTable.php
  models/Dependency/Dao.php
  models/Document/PrintAbstract.php
  models/Property/Predefined.php
  models/Webservice/Service.php
Labels: Improvement

#5378 [Data Objects] fixed grid row heights for images in (advanced)many-to-many-object relation fields
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
Labels: Bug

#5376 [Document] getFullPath() performance optimization
  lib/Routing/Dynamic/DocumentRouteHandler.php
  models/Document.php
  models/Document/Hardlink/Wrapper/WrapperInterface.php
  models/Document/Service/Dao.php
Labels: Improvement

#5379 [Asset] Image Thumbnails: Performance Improvements
  lib/Pimcore.php
  models/Asset/Image/Thumbnail.php
  models/Asset/Image/Thumbnail/Config.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: Improvement

#5381 Fix: Cannot instantiate abstract class Pimcore\Model\User\AbstractUser
  models/User/AbstractUser.php
Labels: Improvement

#5382 Fix: Wrong PHPDocs in Pimcore\Model\Notification
  models/Notification.php
Labels: Improvement

#5386 Fix Notice: Undefined index: thumbnail
  models/Document/Tag/Video.php
Labels: Task

#5391 [Asset] Improvements for pimcore:thumbnails:image Command: high-res, webp and media queries support
  bundles/CoreBundle/Command/ThumbnailsImageCommand.php
Labels: Improvement

#5401 Fix for 2fa bypass
  composer.json
Labels: Bug

#5397 Fix: Undefined 'childs' key
  models/DataObject/ClassDefinition/Service.php
Labels: Task

#5400 Remove duplicate indexes
  bundles/CoreBundle/Resources/migrations/Version20191208175348.php
  bundles/InstallBundle/Resources/install.sql
  models/DataObject/ClassDefinition/Dao.php
  models/DataObject/Classificationstore/Dao.php
  models/DataObject/Data/ObjectMetadata/Dao.php
  models/DataObject/Fieldcollection/Definition/Dao.php
  models/DataObject/Localizedfield/Dao.php
Labels: Improvement

#5403 added missing third gender option in gender field
  models/DataObject/ClassDefinition/Data/Gender.php
Labels: Improvement

#5407 [Asset] getMimeTime() on an image thumbnail may return the wrong type
  models/Asset/Image/Thumbnail.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#5406 fix password hash must also be calculate if info algorithm returns null
  models/DataObject/ClassDefinition/Data/Password.php
Labels: Bug

#5410 [Asset] Image Thumbnails: auto format should use progressive JPEGs instead of normal JPG
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  lib/Image/Adapter/Imagick.php
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Improvement

#5411 [Asset] Image Thumbnails: deliver the requested image format when using auto format (ignore detection, webp, ...)
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Improvement

#5415 [Tags] Allow shorter tag names
  bundles/AdminBundle/Resources/public/js/pimcore/element/tag/tree.js
  models/Element/Tag/Dao.php
Labels: Bug

#5414 BREACH Attack fix for login and lost password forms
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/EventListener/CsrfProtectionListener.php
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
  bundles/AdminBundle/Resources/views/Admin/Login/lostpassword.html.php
  bundles/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.php
  bundles/CoreBundle/Resources/config/templating_php.yml
  lib/Templating/Helper/BreachAttackRandomContent.php
  lib/Templating/PhpEngine.php
  lib/Twig/Extension/TemplatingHelperExtension.php
Labels: Task

#5408 [Asset] HTTP headers of the public thumbnail generation service shouldn't be overridden by the SessionListener
  bundles/CoreBundle/Controller/PublicServicesController.php
  bundles/CoreBundle/Resources/config/aliases.yml
  models/Document/Tag/Link.php
  phpstan.neon
Labels: Bug

#5419 [Ecommerce][Payment][Heidelpay] Improve logging and fix fetchPayment()
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Heidelpay.php
Labels: Bug, Task

#5392 [Documents] Add "Paste Only Contents here" option for all types
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
Labels: Improvement

#5420 Enable grid editing for ManyToManyObjectRelations
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/Service.php
Labels: Improvement

#5422 Error when deleting an item in a Fieldcollection
  models/DataObject/Fieldcollection.php
Labels: Bug

#5423 [Recycle Bin] Fix restoring relations in Localized Fields, Object Bricks and Field Collections
  models/Element/Recyclebin/Item.php
Labels: Bug

#5433 [Grid operators] PHPCode: Catch Exception if no class has been set
  lib/DataObject/GridColumnConfig/Operator/PHPCode.php
Labels: Bug

#5434 [Migration] Fix compatibility with MySQL
  bundles/CoreBundle/Resources/migrations/Version20191126130004.php
Labels: Bug

#5355 [Core] Fix TODOs
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/CoreBundle/EventListener/Frontend/DocumentRendererListener.php
  bundles/CoreBundle/Resources/config/event_listeners.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/AbstractConfig.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManagerInterface.php
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/AbstractAnalyticsTracker.php
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/14_Path_Formatter.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Analytics/Google/Tracker.php
  lib/Document/Renderer/DocumentRenderer.php
  lib/Document/Tag/TagHandler.php
  lib/Image/Optimizer.php
  lib/Routing/RedirectHandler.php
  lib/Templating/Helper/Placeholder/ContainerService.php
  lib/Templating/Renderer/TagRenderer.php
Labels: Task

#5354 Support Iterator for all Listings
  bundles/EcommerceFrameworkBundle/CartManager/Cart/Listing.php
  bundles/EcommerceFrameworkBundle/CartManager/CartCheckoutData/Listing.php
  bundles/EcommerceFrameworkBundle/CartManager/CartItem/Listing.php
  bundles/EcommerceFrameworkBundle/PricingManager/Rule/Listing.php
  bundles/EcommerceFrameworkBundle/VoucherService/Token/Listing.php
  lib/Model/Listing/AbstractListing.php
  lib/Model/Listing/Dao/AbstractDao.php
  models/Asset/Listing.php
  models/DataObject/ClassDefinition/CustomLayout/Listing.php
  models/DataObject/ClassDefinition/Listing.php
  models/DataObject/Classificationstore/CollectionConfig/Listing.php
  models/DataObject/Classificationstore/CollectionGroupRelation/Listing.php
  models/DataObject/Classificationstore/GroupConfig/Listing.php
  models/DataObject/Classificationstore/KeyConfig/Listing.php
  models/DataObject/Classificationstore/KeyGroupRelation/Listing.php
  models/DataObject/Classificationstore/StoreConfig/Listing.php
  models/DataObject/Listing.php
  models/DataObject/Listing/Concrete.php
  models/DataObject/QuantityValue/Unit/Listing.php
  models/DataObject/Service.php
  models/Document/Listing.php
  models/Element/Note/Listing.php
  models/Element/Recyclebin/Item/Listing.php
  models/Element/Tag/Listing.php
  models/Element/WorkflowState/Listing.php
  models/Glossary/Listing.php
  models/GridConfig/Listing.php
  models/GridConfigFavourite/Listing.php
  models/GridConfigShare/Listing.php
  models/ImportConfig/Listing.php
  models/ImportConfigShare/Listing.php
  models/Notification/Listing.php
  models/Redirect/Listing.php
  models/Schedule/Task/Listing.php
  models/Search/Backend/Data/Listing.php
  models/Site/Listing.php
  models/Tool/Email/Blacklist/Listing.php
  models/Tool/Email/Log/Listing.php
  models/Tool/Targeting/Rule/Listing.php
  models/Tool/Targeting/TargetGroup/Listing.php
  models/Translation/AbstractTranslation/Listing.php
  models/User/Listing/AbstractListing.php
  models/User/Permission/Definition/Listing.php
  models/Version/Listing.php
Labels: Improvement, Task

#5431 Add batch remove feature for MultiSelect and MultiRelation types
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/abstractRelations.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/multiselect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/variantsTab.js
  bundles/CoreBundle/Resources/translations/en.json
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
Labels: Improvement

#5441 [Asset] Possibility to force <picture> HTML tag on thumbnail config
  bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
  bundles/CoreBundle/Resources/translations/en.json
  models/Asset/Image/Thumbnail.php
  models/Asset/Image/Thumbnail/Config.php
  models/Asset/Image/Thumbnail/Config/Dao.php
Labels: Improvement

#5443 [Asset] include webp type in <picture> tag if target format is auto
  models/Asset/Image/Thumbnail.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: Improvement

#5447 [Ecommerce][ElasticSerach] Fix unsupported mapping parameter "store"
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
Labels: Bug

#5452 [Travis] Switched to proper PHP 7.4 instead of 'snapshot'
  .travis.yml
Labels: Task

#5461 invalid VideoObject jsonLd with cdn
  models/Document/Tag/Video.php
Labels: Bug

#5458 [ecommerceframework] store table migration fixes
  bundles/CoreBundle/Resources/migrations/Version20191121150326.php
  bundles/CoreBundle/Resources/migrations/Version20191125200416.php
Labels: Bug

#5466 [Versions] Fix fopen mode
  models/Version.php
Labels: Bug

#5470 Fix: Wrong PHP Doc visibleFields
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
Labels: Task

#5472 [PHPSTAN] Ignore Doctrine\DBAL\Driver\Connection::query() errors
  phpstan.neon
Labels: Task

#5481 fix checking fallback languages with inheritance for AbstractRelations
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/23_Localized_Fields.md
  doc/Development_Documentation/img/Objects_LocalizedFields_levels.png
  models/DataObject/Localizedfield.php
Labels: Bug

#5457 [ecommerceframework][elasticsearch] price sorting does not work with elasticsearch 6
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
Labels: Bug

#5453 [Ecommerce][Productindex] Errorhandling
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
  lib/Event/Model/Ecommerce/IndexService/PreprocessAttributeErrorEvent.php
  lib/Event/Model/Ecommerce/IndexService/PreprocessErrorEvent.php
Labels: Improvement

#5486 undefined index
  bundles/AdminBundle/Controller/Admin/ElementController.php
Labels: Bug

#5390 Support localized calculated fields in object bricks
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/33_Calculated_Value_Type.md
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/Localizedfield.php
  models/DataObject/Service.php
Labels: Improvement

#4355 Add filter methods for data object fields in their corresponding listing classes
  bundles/CoreBundle/Resources/migrations/Version20191218073528.php
  doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Country.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/Input.php
  models/DataObject/ClassDefinition/Data/Language.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/Slider.php
  models/DataObject/ClassDefinition/Data/Textarea.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/Concrete.php
Labels: Improvement, Prio-Backlog

#5467 [CustomReport] Fix wrong sql text
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/definitions/sql.js
  models/Tool/CustomReport/Adapter/Sql.php
Labels: Bug

#5506 [Ecommerce] Cart-Item Performance Improvement: added index to DB table
  bundles/CoreBundle/Resources/migrations/Version20191230103524.php
  bundles/EcommerceFrameworkBundle/Tools/Installer.php
Labels: Improvement

#5508 [Ecommerce] OnlineShopOrder class: change column length of field cartId to 190 -> max. index length
  bundles/CoreBundle/Resources/migrations/Version20191230104529.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#5501 ManyToOnyRelation - Content of query table wrong #5500
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
Labels: Bug

#5498 Improved behavior of non-existent assets
  bundles/AdminBundle/Controller/Admin/AssetController.php
Labels: Improvement

#5511 [Cache] Cleanup in maintenance should only be executed once within a day
  lib/Maintenance/Tasks/CacheCleanupTask.php
Labels: Improvement

#5483 Caching layer
  .travis.yml
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/16_Cache_Raw_Relation_Data.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/README.md
  doc/Development_Documentation/img/cache_raw_relation_data.png
  models/DataObject/AbstractObject.php
  models/DataObject/CacheRawRelationDataInterface.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Concrete.php
  models/DataObject/Traits/CacheRawRelationDataTrait.php
  models/Webservice/Data/ClassDefinition.php
  tests/_support/Resources/objects/lazyloading/class_LazyLoading_export.json
  tests/model/LazyLoading/AbstractLazyLoadingTest.php
  tests/model/LazyLoading/AdvancedManyToManyObjectRelationTest.php
  tests/model/LazyLoading/AdvancedManyToManyRelationTest.php
  tests/model/LazyLoading/ManyToManyObjectRelationTest.php
  tests/model/LazyLoading/ManyToManyRelationTest.php
  tests/model/LazyLoading/ManyToOneRelationTest.php
Labels: Improvement
