Repository pimcore/pimcore, pull requests merged in 2019-07, with the labels that each got.

#4578 [Ecommerce Payment] handle Response is called multiple times
  bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
Labels: Improvement, Prio-Backlog

#4592 Minor config improvements in getWebsiteConfig()
  lib/Config.php
Labels: Task

#4593 [Translation] Allow trans to support plurals & Fix transChoice
  bundles/AdminBundle/Controller/Admin/PortalController.php
  bundles/AdminBundle/Controller/Reports/PiwikController.php
  bundles/AdminBundle/Security/Guard/AdminAuthenticator.php
  bundles/AdminBundle/Translation/AdminUserTranslator.php
  bundles/CoreBundle/Resources/config/aliases.yml
  bundles/CoreBundle/Resources/views/Workflow/NotificationEmail/notificationEmail.html.twig
  bundles/CoreBundle/Resources/views/Workflow/statusinfo/allPlacesStatusInfo.html.twig
  bundles/CoreBundle/Resources/views/Workflow/statusinfo/toolbarStatusInfo.html.twig
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/AbstractFilterType.php
  bundles/EcommerceFrameworkBundle/Reports/Piwik/PiwikReportsProvider.php
  composer.json
  lib/Analytics/Piwik/Api/SitesManager.php
  lib/Analytics/Piwik/ReportBroker.php
  lib/Analytics/SiteId/SiteId.php
  lib/DataObject/GridColumnConfig/Operator/Factory/TranslateValueFactory.php
  lib/DataObject/GridColumnConfig/Operator/TranslateValue.php
  lib/Document/Tag/TagHandler.php
  lib/Templating/Helper/Translate.php
  lib/Translation/Translator.php
  lib/Workflow/EventSubscriber/NotesSubscriber.php
  lib/Workflow/EventSubscriber/NotificationEmailSubscriber.php
  lib/Workflow/NotificationEmail/NotificationEmailService.php
  lib/Workflow/Place/OptionsProvider.php
  lib/Workflow/Place/StatusInfo.php
Labels: Bug

#4582 [DataObjects] Add configuration option for header names to table data type
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/table.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/table.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  models/DataObject/ClassDefinition/Data/Table.php
Labels: Improvement, Prio-Backlog

#4496 Relations allow (DataObject)-folder restriction
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
Labels: Improvement, Prio-Backlog

#4586 [Notifications] Role permission are not inherited
  models/Notification/Service/NotificationService.php
  models/Notification/Service/UserService.php
Labels: Bug

#4577 [Ecommerce Payment] Integrate PayPal Smart Checkout Button
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPal.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
  bundles/EcommerceFrameworkBundle/Resources/config/payment_manager.yml
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderPayPalSmartButton_export.json
  composer.json
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/04_PayPal.md
Labels: Improvement

#4610 [Quantity Value] Error when auto-converting unset unit
  bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
Labels: Bug

#4608 [Workflow] note checkbox exception
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
Labels: Bug

#4611 [Improvement] First day of week localized on calendars #4602
  bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
Labels: Improvement

#4628 [Templating] Fix twig auto rendering
  bundles/CoreBundle/Templating/LegacyTemplateGuesser.php
Labels: Bug

#4627 fixes a Bug where Custom Reports are loaded with a wrong reportClass
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/toolbarenricher.js
Labels: Bug

#4630 [Templating] simplify condition and remove unused variable
  bundles/CoreBundle/Templating/LegacyTemplateGuesser.php
Labels: Task

#4612 [Localization] Add command to clean unused locale data
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
  bundles/CoreBundle/Command/DeleteUnusedLocaleDataCommand.php
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/06_Multi_Language_i18n/README.md
Labels: Improvement

#4639 Show progress in Index Updater log.
  bundles/EcommerceFrameworkBundle/IndexService/Tool/IndexUpdater.php
Labels: Improvement

#4637 [Workflow] Fixed parent for Command class and removed deprecated ContainerAwareCommand
  bundles/CoreBundle/Command/WorkflowDumpCommand.php
Labels: Task

#4655 don't allow folders in ManyToManyObject Relations Search Dialog
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
Labels: Improvement

#4664 [Core] Fix typo in Bootstrap::bootstrap() method name
  .travis/web/app_test.php
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing.md
  lib/Bootstrap.php
  tests/_bootstrap.php
Labels: Task

#4657 Fix w3c validation warning in HeadStyle template helper
  lib/Templating/Helper/HeadStyle.php
Labels: Task

#4665 Environment Variable Improvements
  bin/pimcore-install
  doc/Development_Documentation/01_Getting_Started/03_Configuration.md
  lib/Bootstrap.php
  lib/Config.php
  lib/Tool/Console.php
Labels: Improvement

#4661 [Sanity Check] Elements with a newer unpublished version should be al…
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js
  lib/Maintenance/Tasks/SanitizeElementsTask.php
  models/DataObject/Concrete.php
  models/DataObject/Concrete/Dao.php
Labels: Bug

#4653 [Bundles] Clear cache after pimcore:bundle:install/uninstall/update command
  bundles/CoreBundle/Command/Bundle/InstallCommand.php
  bundles/CoreBundle/Command/Bundle/UninstallCommand.php
  bundles/CoreBundle/Command/Bundle/UpdateCommand.php
  bundles/CoreBundle/Resources/config/commands.yml
Labels: Improvement

#4658 [Assets] Fix Image focal points detection delete
  bundles/AdminBundle/Controller/Admin/AssetController.php
  models/Asset/Image.php
Labels: Bug

#4644 Fix bulk importing new custom layout
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
  models/DataObject/ClassDefinition/Dao.php
Labels: Bug

#4634 [Documents] Restrict document translation linking without language
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
  bundles/CoreBundle/Resources/migrations/Version20190708175236.php
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#4651 Iframe Layout Component: Correction of height and distances
  bundles/AdminBundle/Resources/public/js/pimcore/object/layout/iframe.js
Labels: Improvement

#4649 [Newsletter] Default URL prefix
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/CoreBundle/Command/InternalNewsletterDocumentSendCommand.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Resources/config/commands.yml
  doc/Development_Documentation/18_Tools_and_Features/19_Newsletter.md
  lib/Tool/Newsletter.php
  models/Tool/TmpStore.php
Labels: Improvement

#4643 [Data Objects] Partial classes bulk export #4609
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/bulk-base.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/bulk-export.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/bulk-import.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
Labels: New Feature

#4434 add php stan to tests
  .travis.yml
  .travis/run-stan.sh
  .travis/setup-tests.sh
  composer.json
  phpstan.local.neon
  phpstan.neon
  phpstan.s4.travis.neon
  phpstan.travis.neon
Labels: Task

#4674 [TESTS] moved phpstan configs for travis to ./.travis folder
  .travis/phpstan.s4.travis.neon
  .travis/phpstan.travis.neon
  .travis/run-stan.sh
Labels: Task

#4673 [Data Objects] Changed back WYSIWYG enter mode from using <br> to <p>
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/wysiwyg.js
  doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/01_Text_Types.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
Labels: Task

#4684 [Data Object] Class Definitions: Allow underscores in ID and Class Na…
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/class.js
Labels: Improvement

#4685 Removed Zend_Date leftovers
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_V5_to_V6.md
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/Document/Tag/Date.php
Labels: BC-BREAK, Task

#4688 Set mime-type in BinaryResponse for thumbnails. When loading assets from
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Improvement

#4687 When sorting data objects in the tree, the new index isn't reflected in event listener
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#4652 [DataObjects] Fixed language restriction on collections
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  models/DataObject/Service.php
Labels: Bug

#4550 [Cache] Avoid redirects cache stampede
  lib/Routing/RedirectHandler.php
Labels: Improvement

#4635 Start session for ecommerce indexer when run in cli
  bundles/EcommerceFrameworkBundle/IndexService/Tool/IndexUpdater.php
Labels: Improvement

#4695 [Perspective] Translation for name in toolbar
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
Labels: Improvement

#4690 No exception if opened object got deleted in the meantime
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Task

#4696 [Assets] Set remote stream
  models/Asset.php
Labels: Bug

#4710 #4709 Workaround for shutdown handling during cache warmup
  lib/Pimcore.php
Labels: Bug

#4716 Changed use of PropertyAccessor to PropertyAccessorInterface
  lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php
Labels: Bug, Task

#4718 [Classes] Changed protected to public for $fieldDefinitions
  models/DataObject/ClassDefinition/Service.php
Labels: Bug

#4730 [Asset] Update image dimensions in database on the fly
  models/Asset/Dao.php
  models/Asset/Image.php
Labels: Improvement

#4724 [DOCS] Restructuring Upgrade Section
  doc/Development_Documentation/01_Getting_Started/08_Pimcore_5_For_Pimcore_Devs.md
  doc/Development_Documentation/01_Getting_Started/README.md
  doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/01_Inheritance.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/05_Preview.md
  doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
  doc/Development_Documentation/10_E-Commerce_Framework/README.md
  doc/Development_Documentation/18_Tools_and_Features/29_Custom_Reports.md
  doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/README.md
  doc/Development_Documentation/20_Extending_Pimcore/07_Parent_Class_for_Objects.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_Upgrade_from_4_to_5/01_Basic_Migration.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_Upgrade_from_4_to_5/02_Migrate_for_Compatibility_Bridge.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_Upgrade_from_4_to_5/04_Migrate_to_Symfony_Stack.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_Upgrade_from_4_to_5/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_Upgrade_from_4_to_5/migration.sh
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/01_V5_to_V6.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/04_V4_to_V6.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/03_Within_V5/01_Update_from_5.x_to_5.4_or_above.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/03_Within_V5/05_Workflow_Management.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/03_Within_V5/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/05_V4_to_V5.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/12_Ecommerce_Framework/01_Ecommerce_Framework_Price_Objects.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/12_Ecommerce_Framework/02_Ecommerce_Framework_Config_Signature_Changes.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/12_Ecommerce_Framework/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/README.md
Labels: Task

#4733 Version restore of object metadata fails for versions created before …
  models/DataObject/Data/ObjectMetadata.php
Labels: Bug

#4702 [Static Routes] Delegate `encode` Param to the Generator
  lib/Routing/Staticroute/Router.php
  lib/Templating/Helper/PimcoreUrl.php
Labels: Bug

#4780 [WebsiteSettings] Fix language specific settings
  lib/Templating/Helper/WebsiteConfig.php
Labels: Bug
