Repository pimcore/pimcore, pull requests merged in 2020-06, with the labels that each got.

#6498 [Ecommerce][Indexservice] Fix timeout for transactional queries
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
Labels: Bug

#6443 [Console command] System requirements check
  bundles/AdminBundle/Controller/Admin/InstallController.php
  bundles/CoreBundle/Command/RequirementsCheckCommand.php
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
  lib/Tool/Requirements.php
Labels: Approved, New Feature

#6493 update branch alias
  composer.json
Labels: Approved

#6437 [Ecommerce][Elastic Search] Replace reindexing-mode with ES Native Reindexing
  bundles/EcommerceFrameworkBundle/Command/IndexService/EsSyncCommand.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
  composer.json
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
Labels: Approved, Improvement

#6320 Ecommerce | Load Elastic Search (ES) Data directly from Index
  bundles/EcommerceFrameworkBundle/IndexService/Config/ElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Approved, Improvement

#6485 ClassDefinition: don't check for permission when you don't intend to use it
  models/DataObject/ClassDefinition.php
Labels: Approved, Improvement

#6460 [Search Backend] consider Pdf content generation for search backend reindex
  bundles/CoreBundle/Command/SearchBackendReindexCommand.php
  lib/Document/Adapter/Ghostscript.php
  lib/Document/Adapter/LibreOffice.php
Labels: Approved, Improvement

#6403 [Admin] XSS Protection for grids
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/glossary.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/website.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translations.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/videothumbnail/item.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js
Labels: Approved, Bug

#6451 Sometimes Objects cannot be found when click "Show In Tree"
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/AdminBundle/Resources/public/js/pimcore/treenodelocator.js
  models/Element/Service.php
Labels: Approved, Bug

#6482 [Admin] Users - Fix user type for Analyze Permissions
  bundles/AdminBundle/Controller/Admin/ElementController.php
  models/Element/PermissionChecker.php
Labels: Bug

#6486 [Data Object] Incorrect/inconsistent behavior with unpublished relations
  bundles/CoreBundle/Migrations/Version20200529121630.php
  models/DataObject/ClassDefinition/Data.php
  tests/model/LazyLoading/ManyToManyRelationTest.php
Labels: Bug

#6503 Block fields have no spacing to next field
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/block.js
Labels: Bug

#6500 further usage of routing
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
  lib/Tool/Admin.php
Labels: Task

#6511 [Video Thumbnails] Fix video preview generation
  models/Asset/Video/Thumbnail/Processor.php
Labels: Bug

#6492 fix session save for objects with complex linked entities as well
  models/Element/Service.php
Labels: Bug

#6489 Add class to html output of video editable
  models/Document/Tag/Video.php
Labels: Bug

#6488 fix staticroute router
  lib/Routing/Staticroute/Router.php
Labels: Bug

#6483 [xliff import] fix XML special characters for input fields
  lib/Translation/Escaper/Xliff12Escaper.php
Labels: Bug

#6514 Fix Tracking when there is no price available
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/EnhancedEcommerce.php
Labels: Bug

#6510 [Data objects] Add "open" button for non-editable image fields
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
Labels: Approved, Improvement

#6506 Dispatch pimcore.system.cache.clear event when calling pimcore:cache:clear command
  bundles/CoreBundle/Command/CacheClearCommand.php
Labels: Approved, Improvement

#6413 [Data objects] Fulltext search for select fields
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
Labels: Approved, Improvement

#6384 Removes limitation on password length
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/password.js
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/95_Text_Types.md
  models/DataObject/ClassDefinition/Data/Password.php
Labels: Approved, Improvement

#6360 [Maintenance mode] Console commands to enable/disable the maintenance mode
  bundles/CoreBundle/Command/MaintenanceModeCommand.php
  doc/Development_Documentation/20_Extending_Pimcore/15_Maintenance_Mode.md
Labels: Approved, Improvement

#6347 [Documents] Snippet - Add Cache option
  doc/Development_Documentation/03_Documents/01_Editables/32_Snippet.md
  models/Document/Tag/Snippet.php
Labels: Approved, Improvement

#6336 [ElementRouter] Support query parameter and reference type
  lib/Routing/Element/Router.php
Labels: Approved, Improvement

#6204 Field Lookup for Objects
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldlookup/filterdialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldlookup/helper.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/slider.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/Resources/translations/en.json
  doc/User_Documentation/05_DataObjects/30_Field_Lookup.md
  doc/User_Documentation/05_DataObjects/README.md
  doc/User_Documentation/img/fieldlookup/class_settings.png
  doc/User_Documentation/img/fieldlookup/filterdialog.png
  models/DataObject/ClassDefinition.php
  models/Webservice/Data/ClassDefinition.php
Labels: Approved, New Feature

#6309 [CSV Import] No error if header and data rows have different number of columns
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: Improvement

#6519 [Travis] DB install with --allow-unauthenticated
  .travis/setup-db-server.sh
Labels: Task

#6439 Prevents synchrounous XHttpRequests for statistics
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Approved, Improvement

#6400 [DataObjects] Behavior of default values in combination with inherita…
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/README.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/25_Inheritance.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Traits/DefaultValueTrait.php
Labels: Approved, BC-BREAK, Bug

#6449 [Users/Roles] Add getChildren() method for user/role folders
  models/User/Folder.php
  models/User/UserRole/Folder.php
Labels: Improvement, Task

#6512 [Asset] Image editor should use internal URL to fetch image, …
  bundles/AdminBundle/Resources/views/Admin/Asset/imageEditor.html.php
Labels: Bug

#6465 [DataObject] Fix Localizedfield lazyloading for fallback
  models/DataObject/Localizedfield.php
Labels: Bug

#6477 [Data Objects] fields in bricks are not set on object creation
  bundles/CoreBundle/Migrations/Version20200604110336.php
  models/DataObject/Localizedfield.php
  models/DataObject/Objectbrick/Definition.php
  tests/_support/Helper/Model.php
  tests/_support/Resources/objects/brick-import.json
  tests/_support/Resources/objects/inheritance.json
  tests/model/Inheritance/ObjectbrickTest.php
Labels: Bug

#6538 fix brick route
  bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
Labels: Bug

#6534 [Admin] Editmode - Fix "pimcore_admin_asset_getimagethumbnail" does not exist
  bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
Labels: Bug

#6499 CustomReport | CSV Download with progress bar #6408
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
Labels: Improvement

#6543 [Recyclebin] Fix deleting multiple elements - #6495
  bundles/AdminBundle/Controller/Admin/RecyclebinController.php
Labels: Bug

#6536 [Data Objects] Class Definition JSON Export should be independent fro…
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  models/DataObject/ClassDefinition/Service.php
Labels: Task

#6549 Fix xliff import overriding source values
  lib/Translation/ImporterService/Importer/DataObjectImporter.php
Labels: Bug

#6563 [Bug] Download as ZIP causes redirect to JSON file
  bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
Labels: Bug

#6565 [Document|Asset] + sign shouldn't be allowed in keys
  models/Element/Service.php
Labels: Bug

#6552 Mandatory Fields Error is not User Friendly
  models/DataObject/Concrete.php
Labels: Improvement

#6554 Fix to keep icon sizes regular and centered
  bundles/AdminBundle/Resources/views/Admin/Misc/admin-css.html.php
Labels: Bug

#6564 Resolve semiotic alignment of external/internal vs export/import
  bundles/AdminBundle/Resources/public/css/icons.css
Labels: Bug

#6555 Fix to avoid inverting colour icons
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Bug

#6566 [Documents] Fix moving multiple documents for auto redirects
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
Labels: Bug

#6582 [Object search] Sort by class name
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
Labels: Improvement

#6585 Prevent `get_class(null)` calls
  models/Document/Tag/Areablock/Item.php
  models/Document/Tag/Block/AbstractBlockItem.php
  models/Document/Tag/Block/Item.php
Labels: Bug

#6579 [Travis] use NetCologne mirror for MariaDB as Rackspace seems to be not really reliable
  .travis/setup-db-server.sh
Labels: Task

#6580 Unable to add/edit classification store
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
Labels: Bug

#6590 Unable to upload asset through ManyToOne(Many)Relation
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#6593 [Assets] Fix route for upload zip archive
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
Labels: Bug

#6487 Ecommerce | Refactoring queue commands
  bundles/EcommerceFrameworkBundle/Command/IndexService/BootstrapCommand.php
  bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessPreparationQueueCommand.php
  bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessQueueCommand.php
  bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessUpdateIndexQueueCommand.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  bundles/EcommerceFrameworkBundle/IndexService/IndexUpdateService.php
  bundles/EcommerceFrameworkBundle/IndexService/Tool/IndexUpdater.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractMockupCacheWorker.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/BatchProcessingWorkerInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/OptimizedMysql.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ProductCentricBatchProcessingWorker.php
  bundles/EcommerceFrameworkBundle/Resources/config/commands.yml
  bundles/EcommerceFrameworkBundle/Resources/config/index_service.yml
  bundles/EcommerceFrameworkBundle/Resources/config/index_service_configs_workers.yml
  bundles/EcommerceFrameworkBundle/Resources/config/services.yml
  composer.json
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/05_Data_Architecture_and_Indexing_Process.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
  lib/Console/Traits/Parallelization.php
  lib/Console/Traits/Timeout.php
Labels: Improvement

#6594 Fix put mapping during reindex for elasticsearch5
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
Labels: Bug

#6602 [Assets] Fix uploading new videos error
  models/Asset/Video.php
Labels: Bug

#6599 "Paste as Child" not working since Backend Routing rework
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
Labels: Bug

#6517 [Ecommerce] Out-of-the-Box support for Elastic Search Synonyms
  bundles/EcommerceFrameworkBundle/Command/IndexService/EsSyncCommand.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/ElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/ElasticSearchConfigInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/SynonymProvider/AbstractSynonymProvider.php
  bundles/EcommerceFrameworkBundle/IndexService/SynonymProvider/FileSynonymProvider.php
  bundles/EcommerceFrameworkBundle/IndexService/SynonymProvider/SynonymProviderInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/Resources/config/index_service.yml
  bundles/EcommerceFrameworkBundle/Resources/config/index_service_synonym_providers.yml
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/01_Configuration_Details.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/02_Synonyms.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
Labels: Improvement

#6617 AdminStyle Improvements
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Improvement

#6622 [DataObjects] Grid - Fix sorting & filter for grid fields
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Bug

#6616 [CS-Fixer] Add trailing comma in multiline array rule
  .php_cs.dist
Labels: Task

#6615 Update Pimcore DB master/slave to primary/replica
  doc/Development_Documentation/26_Best_Practice/55_Primary-Replica_Database_Connection.md
Labels: Task

#6618 [Admin] Documents tree - Update visibility based on exclude_from_navigation
  models/Element/AdminStyle.php
Labels: Improvement

#6627 Fix issues with shutdown when running cache warming / building the container
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  lib/Pimcore.php
Labels: Bug

#6612 Dataloss in localized fields and maps
  models/DataObject/Localizedfield/Dao.php
  tests/_support/Helper/Model.php
  tests/_support/Resources/objects/brick-import.json
  tests/_support/Resources/objects/class-import.json
  tests/_support/Resources/objects/fieldcollection-import.json
  tests/_support/Resources/objects/inheritance.json
  tests/_support/Resources/objects/relations/class_RelationTest_export.json
  tests/model/Relations/FieldcollectionTest.php
Labels: Bug

#6624 Possibility to remove "> Blank" menu items in all document types
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
Labels: Improvement

#6607 Update presta/sitemap-bundle
  composer.json
Labels: Task

#6539 Check for customConfig passed to ckeditor
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/wysiwyg.js
  doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
Labels: Improvement

#6577 Pagination gets lost
  bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
Labels: Bug

#6330 [User] Possibility to clear profile picture
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/profile/panel.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js
  models/User.php
Labels: Improvement

#6637 [Documents] Blocks - Fix getElements() throws exception with defaults
  models/Document/Tag/Block.php
Labels: Bug

#6467 Areabrick rendering via twig template
  bundles/CoreBundle/Resources/views/Areabrick/wrapper.html.twig
  lib/Document/Tag/TagHandler.php
  lib/Extension/Document/Areabrick/AbstractAreabrick.php
Labels: Improvement

#6659 [Data Objects] grid cell editor for quantity value broken
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridCellEditor.js
Labels: Bug

#6656 [Asset] Listfolder grid celleditor window broken
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/tags/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridCellEditor.js
Labels: Bug

#6647 [QuantityValue] Fix notice: Undefined offset: 1
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Bug

#6646 [DataObjects][UrlSlug] isEmpty implementation is wrong
  models/DataObject/ClassDefinition/Data/UrlSlug.php
Labels: Bug

#6645 Slug inheritance
  models/DataObject/ClassDefinition/Data/UrlSlug.php
Labels: Bug

#6633 Document should first update data and then process page count
  models/Asset/Document.php
  tests/_support/Util/TestHelper.php
  tests/model/Asset/AssetTest.php
  tests/model/Asset/ListingTest.php
Labels: Bug

#6608 Prefix GA profiles with the name of their properties
  bundles/AdminBundle/Controller/Reports/AnalyticsController.php
Labels: Improvement

#6532 Corrects doctype for Table ClassDefinition inputs
  models/DataObject/ClassDefinition/Data/Table.php
Labels: Task

#6491 Possibility to override the admin locale in view templates
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/l10n.yml
  doc/Development_Documentation/06_Multi_Language_i18n/07_Admin_Translations.md
  lib/Translation/Translator.php
Labels: New Feature

#6600 Notification events for add/delete
  doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
  lib/Event/Model/NotificationEvent.php
  lib/Event/NotificationEvents.php
  models/Notification.php
Labels: Improvement

#6328 [DataObject]Make Localizedfield owner aware
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Data/BlockElement.php
  models/DataObject/Fieldcollection.php
  models/DataObject/Fieldcollection/Dao.php
  models/DataObject/Localizedfield.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
  models/DataObject/Traits/OwnerAwareFieldTrait.php
Labels: Improvement

#6667 [QuantityValue] CSV Export/Import with abbreviation instead of unit ID
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Improvement

#6675 [UI] Disabled toolbar buttons are hard to see
  bundles/AdminBundle/Resources/public/css/admin.css
Labels: Improvement

#6515 [Document] Areablocks: Add option to limit certain bricks
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/areablock.js
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
  lib/Document/Tag/TagHandler.php
  models/Document/Tag/Areablock.php
Labels: New Feature

#6674 [DataObject] Fix route generation for folders save
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder.js
Labels: Bug

#6677 [Documents] Link Editable - Add data & aria custom attributes support
  doc/Development_Documentation/03_Documents/01_Editables/18_Link.md
  models/Document/Tag/Link.php
Labels: Bug

#6672 [DataObject] Objectbricks - Fix saving inherited bricks with OmitMandatoryCheck
  models/DataObject/ClassDefinition/Data/Objectbricks.php
Labels: Bug

#6669 [Web2Print] Remove unnecessary displayfield settings in web2print.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/web2print.js
Labels: Task

#6664 [DataObject] Fix DataObject alias for AbstractObject
  models/DataObject.php
  models/DataObject/AbstractObject.php
Labels: Bug

#6685 Fix: FOSJsRouting for symfony 3.4
  bundles/CoreBundle/Resources/config/routing.yml
  bundles/CoreBundle/Resources/config/services_routing.yml
  lib/Routing/Loader/FOSJsRoutingLoader.php
Labels: Bug

#6662 [Admin] UI Improvement - Set allowed units to empty array when saving a quantityvalue attribute.
  bundles/AdminBundle/Resources/public/js/pimcore/helpers/quantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/inputQuantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
Labels: Improvement

#6613 [Ecommerce] Deprecate FactFinder integration
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/MultiSelect.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/NumberRange.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/Select.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/SelectCategory.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/FactFinderConfigInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFactFinder.php
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/03_Assortment_Tenant_Configuration.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/07_Product_List.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#6639 [Ecommerce] Make Elasticsearch Sort more flexible
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
Labels: Improvement

#6634 [Workflow] fix #6013 initial place empty on add with `single_state` store
  bundles/CoreBundle/EventListener/WorkflowManagementListener.php
  lib/Workflow/Manager.php
Labels: Bug

#6694 [Areablock] Fix Notice: Undefined index
  models/Document/Tag/Areablock.php
Labels: Bug
