Repository pimcore/pimcore, pull requests merged in 2020-07, with the labels that each got.

#6712 fix seo panel tree route
  bundles/AdminBundle/Resources/public/js/pimcore/document/seopanel.js
Labels: Bug

#6711 Fix JS error in areablock when no limits are set
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/areablock.js
Labels: Bug

#6723 [Assets] Grid Batch Update - Fix Notice: Undefined offset: 1
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
Labels: Bug

#6719 Objectbrick data is not loaded
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Bug

#6707 Implement saveToSession for assets
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
Labels: Task

#6731 Fix ecommerce filter to keep order
  bundles/EcommerceFrameworkBundle/FilterService/Helper.php
Labels: Improvement

#6708 [DataObjects/Documents] Fix modification date updated from last published version
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
Labels: Bug

#6705 [Console Commands] Fix classes:rebuild -d fails when trying to delete a class
  models/DataObject/ClassDefinition.php
  models/DataObject/Concrete/Dao.php
Labels: Bug

#6709 [Workflows - Data Objects / Documents ] Update modification date during workflow transition publish
  bundles/AdminBundle/Controller/Admin/WorkflowController.php
Labels: Bug

#6727 [DataObject] Block in Fieldcollection not working anymore #6726
  models/DataObject/Data/BlockElement.php
  models/DataObject/Fieldcollection/Dao.php
  models/DataObject/Fieldcollection/Data/Dao.php
Labels: Bug

#6741 [Admin] XSS Protection
  bundles/AdminBundle/Resources/public/js/pimcore/asset/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/email/blacklist.js
Labels: Bug

#6744 CSV Export: no carriage return every 20 lines
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#6753 Bug fix: "Use current player position as preview" Button not working
  bundles/AdminBundle/Resources/public/js/pimcore/asset/video.js
Labels: Bug

#6702 An Ext.form.Fieldcontainer does not have a title
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/fieldcontainer.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/layout.js
Labels: Improvement

#6756 Allow usage of `Pimcore\Navigation\Builder` without request
  lib/Navigation/Builder.php
Labels: Bug

#6670 Correct ACL for overlapping roles
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  models/Asset/Dao.php
  models/DataObject/AbstractObject/Dao.php
  models/Document/Dao.php
Labels: Bug

#6765 [Admin] Users - Fix permissions analyzer result
  models/Element/PermissionChecker.php
Labels: Bug

#6769 [Data Objects] Fix API-saving unpublished with empty mandatory field throws exception
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Concrete.php
Labels: Bug

#6777 Bugfix Webdav Link Generating
  bundles/AdminBundle/Controller/Admin/AssetController.php
Labels: Bug

#6781 [Tests] Model - Add test for Boolean Select field
  tests/_support/Helper/DataType/TestDataHelper.php
  tests/_support/Helper/Model.php
  tests/_support/Resources/objects/class-import.json
  tests/_support/Test/DataType/AbstractDataTypeTestCase.php
  tests/_support/Util/TestHelper.php
Labels: Improvement

#6778 Image in image-editable breaks if too many Hotspots
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/image.js
Labels: Bug

#6770 [Documents] Newsletter - Fix no preview button available in toolbar
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
Labels: Bug

#6776 Gridconfig dialog: renderer should not be mandatory
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridConfigDialog.js
Labels: Bug

#6484 [Objects] Optional PHP type declarations for Data Object Classes
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/README.md
  doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Geo/AbstractGeo.php
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/Input.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/Slider.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Textarea.php
  models/DataObject/ClassDefinition/Data/TypeDeclarationSupportInterface.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Traits/FieldcollectionObjectbrickDefinitionTrait.php
  models/Webservice/Data/ClassDefinition.php
  tests/_support/Helper/DataType/TestDataHelper.php
  tests/_support/Helper/Model.php
  tests/_support/Resources/objects/class-import.json
  tests/_support/Resources/objects/classificationstore.json
  tests/_support/Resources/objects/fieldcollection-import.json
  tests/_support/Resources/objects/lazyloading/class_LazyLoading_export.json
  tests/_support/Resources/objects/lazyloading/fieldcollection_LazyLoadingLocalizedTest_export.json
  tests/_support/Resources/objects/lazyloading/fieldcollection_LazyLoadingTest_export.json
  tests/_support/Resources/objects/lazyloading/objectbrick_LazyLoadingLocalizedTest_export.json
  tests/_support/Resources/objects/lazyloading/objectbrick_LazyLoadingTest_export.json
  tests/_support/Resources/objects/relations/class_MultipleAssignments_export.json
  tests/_support/Resources/objects/relations/class_RelationTest_export.json
Labels: New Feature

#6794 ViewModel: "document" parameter doesn't get set/updated when view model was initialized before document was resolved
  lib/Http/Request/Resolver/DocumentResolver.php
  models/Document/PageSnippet.php
  models/Document/Tag.php
Labels: Bug

#6374 [DataObject] Fully implement isEqual for all datatypes
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/Country.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/Email.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/EqualComparisonInterface.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/Firstname.php
  models/DataObject/ClassDefinition/Data/Gender.php
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
  models/DataObject/ClassDefinition/Data/Geopolygon.php
  models/DataObject/ClassDefinition/Data/Geopolyline.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/Input.php
  models/DataObject/ClassDefinition/Data/Language.php
  models/DataObject/ClassDefinition/Data/Lastname.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/NewsletterActive.php
  models/DataObject/ClassDefinition/Data/NewsletterConfirmed.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/Slider.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/ClassDefinition/Data/Textarea.php
  models/DataObject/ClassDefinition/Data/Time.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/Traits/ElementWithMetadataComparisonTrait.php
  models/DataObject/Traits/SimpleComparisonTrait.php
  tests/_support/Helper/DataType/TestDataHelper.php
Labels: Improvement, Pending

#6749 [DataObject] Performance enhancements when rebuilding classes
  models/DataObject/ClassDefinition/Service.php
Labels: Improvement

#6689 Performance enhancements when deleting elements
  bundles/AdminBundle/Controller/Admin/ElementControllerBase.php
  bundles/AdminBundle/Controller/Admin/RecyclebinController.php
  models/DataObject/AbstractObject.php
Labels: Improvement

#6806 [PHPStan] Fix Ignored error
  .travis/phpstan.s4.travis.neon
  .travis/phpstan.travis.neon
  composer.json
  phpstan.neon
Labels: Task

#6398 implement custom copy function for class-definition types
  models/DataObject/ClassDefinition/Data/CustomDataCopyInterface.php
  models/Element/Service.php
Labels: Improvement

#6811 Force context resolving for error page
  bundles/CoreBundle/EventListener/PimcoreContextListener.php
  bundles/CoreBundle/EventListener/ResponseExceptionListener.php
Labels: Bug

#6812 Hide all unpublished elements in document relation tags
  models/Document/Tag/Relation.php
  models/Document/Tag/Relations.php
  models/Element/Service.php
Labels: Bug

#6817 [Asset] Apply 8BIM embedded clipping path to thumbnails
  lib/Image/Adapter/Imagick.php
Labels: New Feature

#6822 [Test] Fix wrong if expression
  .travis/phpstan-bootstrap.php
  tests/_bootstrap.php
Labels: Bug

#6385 [Assets] Decouple asset metadata editor tab from actual implementation
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Resources/public/js/lib/ext-plugins/portlet/PortalDropZone.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/audio.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/gridConfigDialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/gridTabAbstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/metadataTree.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/dataProvider.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/editor.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/tags/select.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/text.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/unknown.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/video.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridConfigDialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/perspective.js
  bundles/AdminBundle/Resources/views/Admin/Asset/showVersionImage.html.php
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/Migrations/Version20200619071650.php
  bundles/CoreBundle/Resources/translations/en.json
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Plugin_Backend_UI.md
  lib/Event/AdminEvents.php
  lib/Event/AssetEvents.php
  lib/Model/Asset/Metadata/Loader/DataLoader.php
  lib/Model/Asset/Metadata/Loader/DataLoaderInterface.php
  models/Asset.php
  models/Asset/Dao.php
  models/Asset/MetaData/ClassDefinition/Data/Asset.php
  models/Asset/MetaData/ClassDefinition/Data/Data.php
  models/Asset/MetaData/ClassDefinition/Data/DataDefinitionInterface.php
  models/Asset/MetaData/ClassDefinition/Data/DataObject.php
  models/Asset/MetaData/ClassDefinition/Data/Date.php
  models/Asset/MetaData/ClassDefinition/Data/Document.php
  models/Asset/Service.php
  models/Metadata/Predefined.php
  models/Search/Backend/Data.php
Labels: Prio-Backlog

#6826 Sitemap - Empty Hardlinks causing error
  lib/Sitemap/Document/DocumentTreeGenerator.php
Labels: Bug

#6839 Depend on `StreamOutput` instead of `ConsoleOutput` in `Pimcore\Console\Dumper`
  lib/Console/Dumper.php
Labels: Task

#6845 Asset::addMetadata - Fix type phpdoc
  models/Asset.php
Labels: Bug

#6843 [Version preview] Add whitespace between class name and element fullpath for many-to-many relation fields
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
Labels: Improvement

#6836 adjusts portrait images in the search preview to prevent overflow
  bundles/AdminBundle/Resources/public/css/admin.css
Labels: Improvement

#6835 [Admin] Fix opening new assets
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/grid.js
Labels: Bug

#6849 Login page: CSRF token refresh on tab activate and before the PHP session expires
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
  bundles/CoreBundle/Resources/config/pimcore/security.yml
Labels: Bug, Improvement

#6851 [Data Object] Fixed Video CSV Import
  models/DataObject/ClassDefinition/Data/Video.php
Labels: Bug

#6837 [Asset] Thumbnail workaround for Imagick in case colorspaces are different
  lib/Image/Adapter/Imagick.php
Labels: Bug, Third Party Bug

#6853 [Data object version preview] Equal version preview of many-to-many relations and advanced many-to-many relations
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
Labels: Improvement

#6855 Follow-up for #5439: OrderManager\V7 - Save applied pricing Rule ID in the order / OrderPriceModification Fieldcollection
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
Labels: Improvement

#6867 Add getCategories for default Mockup
  bundles/EcommerceFrameworkBundle/Model/DefaultMockup.php
Labels: Bug

#6870 fix: csv dataobject import reload column configuration
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js
Labels: Bug

#6872 [DataObject] Fix: Checkbox/Link/Slider/Datetime label width is not respected
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/datetime.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/link.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/slider.js
Labels: Bug
