Repository pimcore/pimcore, pull requests merged in 2020-11, with the labels that each got.

#6880 [DataObject] Edit form: Label Align
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/localizedfields.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/fieldcontainer.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/fieldset.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/panel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/booleanSelect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/calculatedValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/date.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/datetime.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/link.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/multiselect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/slider.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/textarea.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Layout.php
  models/DataObject/ClassDefinition/Layout/Fieldcontainer.php
  models/DataObject/ClassDefinition/Layout/Fieldset.php
  models/DataObject/ClassDefinition/Layout/Panel.php
  models/DataObject/ClassDefinition/Layout/Traits/LabelTrait.php
Labels: Improvement

#7421 [Pimcore7] admin-helper: remove deprecation
  bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
  lib/Tool/Admin.php
Labels: Task

#7424 [Asset] Allow empty asset metadata
  models/Asset/Dao.php
Labels: Improvement

#7431 sylius/theme-bundle allows translations per theme, by that it adds the theme-name to the locale with @
  lib/Translation/Translator.php
Labels: Task

#7429 [Dashboard] Set flex=1 for columns without specified width for custom report portlet
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/customreports.js
Labels: Improvement

#7433 [DOCS] Removed all PHP template examples where there's already a Twig alternative
  doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
  doc/Development_Documentation/02_MVC/02_Template/01_Layouts.md
  doc/Development_Documentation/02_MVC/02_Template/04_Thumbnails.md
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
  doc/Development_Documentation/03_Documents/01_Editables/04_Area.md
  doc/Development_Documentation/03_Documents/01_Editables/06_Block.md
  doc/Development_Documentation/03_Documents/01_Editables/08_Checkbox.md
  doc/Development_Documentation/03_Documents/01_Editables/10_Date.md
  doc/Development_Documentation/03_Documents/01_Editables/12_Relation_(Many-To-One).md
  doc/Development_Documentation/03_Documents/01_Editables/13_Relations_(Many-To-Many).md
  doc/Development_Documentation/03_Documents/01_Editables/14_Image.md
  doc/Development_Documentation/03_Documents/01_Editables/16_Input.md
  doc/Development_Documentation/03_Documents/01_Editables/18_Link.md
  doc/Development_Documentation/03_Documents/01_Editables/22_Multiselect.md
  doc/Development_Documentation/03_Documents/01_Editables/24_Numeric.md
  doc/Development_Documentation/03_Documents/01_Editables/25_Embed.md
  doc/Development_Documentation/03_Documents/01_Editables/26_PDF.md
  doc/Development_Documentation/03_Documents/01_Editables/28_Renderlet.md
  doc/Development_Documentation/03_Documents/01_Editables/30_Select.md
  doc/Development_Documentation/03_Documents/01_Editables/32_Snippet.md
  doc/Development_Documentation/03_Documents/01_Editables/34_Table.md
  doc/Development_Documentation/03_Documents/01_Editables/36_Textarea.md
  doc/Development_Documentation/03_Documents/01_Editables/38_Video.md
  doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
  doc/Development_Documentation/03_Documents/01_Editables/42_Scheduled_Block.md
  doc/Development_Documentation/03_Documents/01_Editables/README.md
  doc/Development_Documentation/03_Documents/03_Navigation.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/45_Image_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/30_Link_Generator.md
  doc/Development_Documentation/06_Multi_Language_i18n/02_Localize_your_Documents.md
  doc/Development_Documentation/06_Multi_Language_i18n/04_Shared_Translations.md
  doc/Development_Documentation/06_Multi_Language_i18n/07_Admin_Translations.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/README.md
  doc/Development_Documentation/18_Tools_and_Features/07_Properties.md
  doc/Development_Documentation/18_Tools_and_Features/27_Website_Settings.md
Labels: Task

#7444 [Document] Removed Editables BC Layers
  lib/Extension/Document/Areabrick/AbstractAreabrick.php
  lib/Templating/Renderer/EditableRenderer.php
  models/Document/Editable.php
  models/Document/Editable/Area.php
  models/Document/Editable/Date.php
  models/Document/Editable/Renderlet.php
  models/Document/Editable/Snippet.php
  models/Document/Editable/Table.php
  models/Document/Editable/Video.php
Labels: BC-BREAK, Task

#7445 Remove deprecated DirtyIndicatorInterface and DirtyIndicatorTrait
  models/DataObject/DirtyIndicatorInterface.php
  models/DataObject/Service.php
  models/DataObject/Traits/DirtyIndicatorTrait.php
  models/Element/DirtyIndicatorInterface.php
  models/Element/Traits/DirtyIndicatorTrait.php
Labels: BC-BREAK, Task

#7441 [Document] Allow editables to throw an exception
  bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
  lib/Controller/FrontendController.php
  lib/Extension/Document/Areabrick/AbstractAreabrick.php
  lib/Templating/Renderer/EditableRenderer.php
Labels: BC-BREAK, Task

#7442 [Document] Improve usability of block editable for Twig templates
  doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
  doc/Development_Documentation/03_Documents/01_Editables/06_Block.md
  doc/Development_Documentation/03_Documents/01_Editables/18_Link.md
  doc/Development_Documentation/03_Documents/01_Editables/42_Scheduled_Block.md
  lib/Twig/Extension/DocumentEditableExtension.php
  models/Document/Editable/Areablock.php
  models/Document/Editable/Block.php
  models/Document/Editable/BlockInterface.php
Labels: BC-BREAK, Improvement

#7446 Remove CalculatorClassInterface BC Layer
  models/DataObject/ClassDefinition/Helper/CalculatorClassResolver.php
  models/DataObject/Service.php
Labels: BC-BREAK

#7447 [Document] Added render() to EditableInterface, removed frontend() and admin()
  models/Document/Editable.php
  models/Document/Editable/EditableInterface.php
Labels: BC-BREAK, Task

#7449 Remove deprecated Newsletter::sendMail() function
  lib/Tool/Newsletter.php
Labels: BC-BREAK

#7448 Remove deprecated static PathFormatter layer
  bundles/AdminBundle/Controller/Admin/ElementController.php
Labels: BC-BREAK, Task

#7186 Delete application_logs archive tables after configurable amount of time
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Resources/translations/en.extended.json
  lib/Config.php
  lib/Maintenance/Tasks/LogArchiveTask.php
Labels: Improvement

#7437 [Thumbnails] Fallback if clipping by embedded clipping path does not work
  lib/Image/Adapter/Imagick.php
Labels: Bug

#7440 [DataObject] Preview with Image Advanced and Thumbnails failing, wrongly ElementDescriptor returned
  models/DataObject/Data/Hotspotimage.php
Labels: Bug

#6939 Pass and consume correct error messages when declining a workflow transition
  bundles/AdminBundle/Controller/Admin/WorkflowController.php
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitionPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitions.js
Labels: Improvement

#7452 Removed PHP Templating engine leftovers
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  lib/Controller/Config/ConfigNormalizer.php
  lib/Extension/Document/Areabrick/AbstractTemplateAreabrick.php
  lib/Extension/Document/Areabrick/TemplateAreabrickInterface.php
  phpstan-baseline.neon
  phpstan.neon
Labels: BC-BREAK, Task

#7459 Correct file path to fosjsrouting router.js
  bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
Labels: Bug

#7460 Fixes/improvements to sort in MiscController
  bundles/AdminBundle/Controller/Admin/MiscController.php
Labels: Improvement

#7461 [Asset] Image thumbnails: allow loading=lazy attribute
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  models/Asset/Image/Thumbnail.php
Labels: Improvement

#7436 [DOCS] Twig Templates
  doc/Development_Documentation/01_Getting_Started/06_Create_a_First_Project.md
  doc/Development_Documentation/02_MVC/00_Controller.md
  doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
  doc/Development_Documentation/02_MVC/02_Template/01_Layouts.md
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/README.md
  doc/Development_Documentation/02_MVC/02_Template/README.md
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/00_Documents_and_Pretty_URLs.md
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
  doc/Development_Documentation/02_MVC/README.md
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  doc/Development_Documentation/03_Documents/01_Editables/06_Block.md
  doc/Development_Documentation/03_Documents/01_Editables/28_Renderlet.md
  doc/Development_Documentation/03_Documents/03_Navigation.md
  doc/Development_Documentation/03_Documents/07_Predefined_Document_Types.md
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/45_Image_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/50_Localized_Fields.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/80_Select_Types.md
  doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/09_Working_with_Prices/01_Price_Systems_and_getting_Prices.md
  doc/Development_Documentation/10_E-Commerce_Framework/09_Working_with_Prices/03_Tax_Management.md
  doc/Development_Documentation/10_E-Commerce_Framework/09_Working_with_Prices/05_Pricing_Rules.md
  doc/Development_Documentation/10_E-Commerce_Framework/13_Checkout_Manager/07_Integrating_Payment.md
  doc/Development_Documentation/18_Tools_and_Features/19_Newsletter.md
  doc/Development_Documentation/18_Tools_and_Features/30_Rendering_PDFs.md
  doc/Development_Documentation/26_Best_Practice/40_Integrating_Commerce_Data_with_Content.md
  doc/Development_Documentation/26_Best_Practice/85_Using_Tags_for_Filtering.md
Labels: Task

#7467 Support numeric fields in workflow notes.
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitionPanel.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md
Labels: Improvement

#7454 [Core] Template Engine Delegation
  bundles/CoreBundle/EventListener/Frontend/GoogleTagManagerListener.php
  bundles/CoreBundle/Resources/config/documents.yml
  bundles/CoreBundle/Resources/config/templating.yml
  bundles/CoreBundle/Resources/views/Areabrick/wrapper.html.twig
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/AbstractFilterType.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Hobex.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Mpay24Seamless.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php
  bundles/EcommerceFrameworkBundle/Resources/config/filter_service_filter_types.yml
  bundles/EcommerceFrameworkBundle/Resources/config/payment_manager.yml
  lib/Document/Editable/EditableHandler.php
  lib/Navigation/Renderer/AbstractRenderer.php
  lib/Navigation/Renderer/Breadcrumbs.php
  lib/Navigation/Renderer/Menu.php
  lib/Targeting/Code/TargetingCodeGenerator.php
  lib/Targeting/EventListener/ToolbarListener.php
  lib/Templating/DelegatingEngine.php
  lib/Workflow/Notification/NotificationEmailService.php
Labels: Task

#7472 Renderlet::getO() can return null
  models/Document/Editable/Renderlet.php
Labels: Bug

#7469 Fix quantity value comparator
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Bug

#7471 Fix EditableDialog not showing labels of checkboxes
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/checkbox.js
Labels: Bug

#7470 Travis: use Composer v2
  .travis/setup-tests.sh
  composer.json
Labels: Task

#7473 [Document] Removed editable loader BC layer
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/implementation_factories.yml
Labels: BC-BREAK

#7474 Use ErrorHandler Component instead of deprecated Debug Component
  bin/pimcore-install
  lib/Bootstrap.php
Labels: Task

#7476 Removed Generator Bundle
  bundles/GeneratorBundle/Command/BaseGenerateBundleCommand.php
  bundles/GeneratorBundle/Command/BaseGeneratorCommand.php
  bundles/GeneratorBundle/Command/GenerateBundleCommand.php
  bundles/GeneratorBundle/Command/Helper/QuestionHelper.php
  bundles/GeneratorBundle/Command/Validators.php
  bundles/GeneratorBundle/DependencyInjection/PimcoreGeneratorExtension.php
  bundles/GeneratorBundle/Generator/BaseBundleGenerator.php
  bundles/GeneratorBundle/Generator/BundleGenerator.php
  bundles/GeneratorBundle/Generator/Generator.php
  bundles/GeneratorBundle/Manipulator/ConfigurationManipulator.php
  bundles/GeneratorBundle/Manipulator/KernelManipulator.php
  bundles/GeneratorBundle/Manipulator/Manipulator.php
  bundles/GeneratorBundle/Manipulator/RoutingManipulator.php
  bundles/GeneratorBundle/Model/BaseBundle.php
  bundles/GeneratorBundle/Model/Bundle.php
  bundles/GeneratorBundle/PimcoreGeneratorBundle.php
  bundles/GeneratorBundle/Resources/config/services.yml
  bundles/GeneratorBundle/Resources/skeleton/bundle/BaseBundle.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/Bundle.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/Configuration.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/DefaultController.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/DefaultControllerTest.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/Extension.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/index.html.twig.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/routing.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/routing.xml.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/routing.yml.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/services.php.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/services.xml.twig
  bundles/GeneratorBundle/Resources/skeleton/bundle/services.yml.twig
  bundles/GeneratorBundle/Resources/skeleton/js/pimcore/startup.js.twig
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/README.md
  lib/Kernel.php
Labels: BC-BREAK, Task

#7479 Use AbstractController instead of Symfony\Bundle\FrameworkBundle\Controller\Controller
  lib/Controller/Controller.php
Labels: BC-BREAK, Task

#7477 [Documents] Select Editable defaultValue empty fix and docs update
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/select.js
  doc/Development_Documentation/03_Documents/01_Editables/30_Select.md
Labels: Bug, Task

#7480 Fixed Workflow deprecations
  bundles/CoreBundle/Resources/config/services_symfony_workflow.yml
  lib/Workflow/ExpressionService.php
  lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php
  lib/Workflow/MarkingStore/StateTableMarkingStore.php
  lib/Workflow/SupportStrategy/ExpressionSupportStrategy.php
Labels: BC-BREAK, Task

#7478 [Translator] Use Symfony Contracts and remove transChoice()
  lib/Translation/Translator.php
Labels: BC-BREAK, Task

#7483 [Ecommerce] Back Office - Remove unused vendor files & use fontawesome local copy
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootbox.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/config.json
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/css/bootstrap-theme.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/css/bootstrap-theme.min.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/css/bootstrap.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/css/bootstrap.min.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.eot
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.svg
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.ttf
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/js/bootstrap.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/bootstrap/js/bootstrap.min.js
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome-all.min.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/css/fontawesome-all.min.css
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-brands-400.eot
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-brands-400.svg
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-brands-400.ttf
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-brands-400.woff
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-brands-400.woff2
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-regular-400.eot
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-regular-400.svg
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-regular-400.ttf
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-regular-400.woff
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-regular-400.woff2
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-solid-900.eot
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-solid-900.svg
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-solid-900.ttf
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-solid-900.woff
  bundles/EcommerceFrameworkBundle/Resources/public/vendor/fontawesome/webfonts/fa-solid-900.woff2
  bundles/EcommerceFrameworkBundle/Resources/views/back-office.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/voucher_code_tab_error.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/voucher_layout.html.twig
Labels: Task

#7482 [Ecommerce] Fix voucher service undefined notices
  bundles/EcommerceFrameworkBundle/VoucherService/Token/Listing.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php
Labels: Bug

#7486 [AdminBundle] Replace $this->get() calls from Controllers
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/VariantsController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/Document/LinkController.php
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/AdminBundle/Controller/Admin/ElementControllerBase.php
  bundles/AdminBundle/Controller/Admin/MiscController.php
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Controller/AdminController.php
  bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
  bundles/AdminBundle/DependencyInjection/Compiler/SerializerPass.php
  bundles/AdminBundle/Resources/config/serializer.yml
Labels: BC-BREAK, Task

#7491 [Cache/Core] No error message if storeCacheItem() returns false
  lib/Cache/Core/CoreHandler.php
Labels: Task

#7492 Fix formatDebugReceivers for rfc2822 3.6.2 validation
  lib/Helper/Mail.php
Labels: Bug

#7496 [Document] Removed document.tags in config tree
  bundles/CoreBundle/DependencyInjection/Configuration.php
Labels: BC-BREAK, Task

#7498 Removed deprecated config option workflows.initial_place
  bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/01_Placeholder_Example/README.md
  doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md
Labels: BC-BREAK, Task

#7501 Fixed Workflow Deprecations
  lib/Workflow/MarkingStore/DataObjectMultipleStateMarkingStore.php
Labels: Task

#7500 [Data objects] Do not try to load deleted object bricks
  models/DataObject/ClassDefinition/Data/Objectbricks.php
Labels: Task

#7495 Fix Notice: Undefined index: locked
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Task

#7499 Fixed short factory syntax usages
  bundles/CoreBundle/Resources/config/analytics.yml
Labels: Task

#7509 Do not override WebDebugToolbarListener as it will be @final
  bundles/CoreBundle/DependencyInjection/Compiler/WebDebugToolbarListenerPass.php
  bundles/CoreBundle/EventListener/WebDebugToolbarListener.php
  bundles/CoreBundle/PimcoreCoreBundle.php
  bundles/CoreBundle/Resources/config/event_listeners.yml
Labels: BC-BREAK

#7508 Pimcore::Tool wrong merging of parameters in useFrontendOutputFilters
  lib/Tool.php
Labels: Bug

#7510 New RDBMS minimum requirements
  .travis.yml
  .travis/setup-db-server.sh
  doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
Labels: BC-BREAK

#7511 Upgrade sabre/dav to ^4.1.1
  composer.json
Labels: BC-BREAK, Improvement

#7415 [Ecommerce] Deprecate Ecommerce Tracking Php templates
  bundles/EcommerceFrameworkBundle/Tracking/Tracker.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#7513 Fatal with caching on localized fields caused by ElementDescriptor
  models/DataObject/Localizedfield.php
Labels: Bug

#7515 Fixed deprecation in AbstractCacheItemPool
  lib/Cache/Pool/AbstractCacheItemPool.php
Labels: BC-BREAK, Task

#7514 Removed deprecated config option logout_on_user_change
  bundles/CoreBundle/Resources/config/pimcore/security.yml
  tests/Unit/Tool/ConfigMergerTest.php
Labels: Task

#7463 [Templating] ease migration with template helpers
  bundles/CoreBundle/Resources/config/templating_twig.yml
  lib/Templating/Helper/Action.php
  lib/Templating/Helper/HeadLink.php
  lib/Templating/Helper/HeadMeta.php
  lib/Templating/Helper/HeadScript.php
  lib/Templating/Helper/HeadStyle.php
  lib/Templating/Helper/HeadTitle.php
  lib/Templating/Helper/Inc.php
  lib/Templating/Helper/InlineScript.php
  lib/Templating/Helper/Navigation.php
  lib/Templating/Helper/Navigation/Exception/InvalidRendererException.php
  lib/Templating/Helper/Navigation/Exception/RendererNotFoundException.php
  lib/Templating/Helper/PimcoreUrl.php
  lib/Templating/Helper/Placeholder.php
  lib/Templating/Helper/Placeholder/AbstractHelper.php
  lib/Templating/Helper/Placeholder/CacheBusterAware.php
  lib/Templating/Helper/Placeholder/Container.php
  lib/Templating/Helper/Placeholder/ContainerService.php
  lib/Templating/Helper/Traits/TextUtilsTrait.php
  lib/Templating/Helper/Traits/WebLinksTrait.php
  lib/Twig/Extension/Templating/Action.php
  lib/Twig/Extension/Templating/HeadLink.php
  lib/Twig/Extension/Templating/HeadMeta.php
  lib/Twig/Extension/Templating/HeadScript.php
  lib/Twig/Extension/Templating/HeadStyle.php
  lib/Twig/Extension/Templating/HeadTitle.php
  lib/Twig/Extension/Templating/Inc.php
  lib/Twig/Extension/Templating/InlineScript.php
  lib/Twig/Extension/Templating/Navigation.php
  lib/Twig/Extension/Templating/Navigation/Exception/InvalidRendererException.php
  lib/Twig/Extension/Templating/Navigation/Exception/RendererNotFoundException.php
  lib/Twig/Extension/Templating/PimcoreUrl.php
  lib/Twig/Extension/Templating/Placeholder.php
  lib/Twig/Extension/Templating/Placeholder/AbstractExtension.php
  lib/Twig/Extension/Templating/Placeholder/CacheBusterAware.php
  lib/Twig/Extension/Templating/Placeholder/Container.php
  lib/Twig/Extension/Templating/Placeholder/ContainerService.php
  lib/Twig/Extension/Templating/Placeholder/Exception.php
  lib/Twig/Extension/Templating/Traits/TextUtilsTrait.php
  lib/Twig/Extension/Templating/Traits/WebLinksTrait.php
  phpstan-baseline.neon
Labels: Task

#7517 New Controller Reference Support
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/MiscController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js
  bundles/CoreBundle/Command/Migration/ControllerReferenceMigrationCommand.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/commands.yml
  doc/Development_Documentation/03_Documents/01_Editables/28_Renderlet.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Controller/Config/ConfigNormalizer.php
  lib/Controller/Config/ControllerDataProvider.php
  lib/Routing/Staticroute/Router.php
  lib/Tool.php
  lib/Twig/Extension/SubrequestExtension.php
  models/Document/DocType.php
  models/Document/Editable/Renderlet.php
  models/Document/PageSnippet.php
  models/Staticroute.php
Labels: Improvement, Task

#7519 Fix batch edit null error
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
Labels: Bug

#7526 Remove \Pimcore\Model\Element\Reference\Placeholder
  models/Element/Reference/Placeholder.php
Labels: BC-BREAK, Task

#7536 Remove Support for old style controller references & action templating helper
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/Document/RenderletController.php
  bundles/AdminBundle/Controller/Admin/MiscController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
  bundles/CoreBundle/Command/Migration/ControllerReferenceMigrationCommand.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Migrations/Version20201113143914.php
  bundles/CoreBundle/Resources/config/commands.yml
  bundles/CoreBundle/Resources/config/documents.yml
  bundles/CoreBundle/Resources/config/services.yml
  bundles/CoreBundle/Resources/config/templating_twig.yml
  bundles/InstallBundle/Installer.php
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/03_Documents/01_Editables/28_Renderlet.md
  lib/Controller/Config/ConfigNormalizer.php
  lib/Controller/Config/ControllerDataProvider.php
  lib/Document/Editable/EditableHandler.php
  lib/Http/Request/Resolver/TemplateResolver.php
  lib/Routing/Dynamic/DataObjectRouteHandler.php
  lib/Routing/Dynamic/DocumentRouteHandler.php
  lib/Routing/Staticroute/Router.php
  lib/Templating/Renderer/ActionRenderer.php
  lib/Templating/Renderer/IncludeRenderer.php
  lib/Tool.php
  lib/Twig/Extension/SubrequestExtension.php
  lib/Twig/Extension/Templating/Action.php
  models/Document/DocType.php
  models/Document/Editable/Renderlet.php
  models/Document/Editable/Snippet.php
  models/Document/PageSnippet.php
  models/Document/Service.php
  models/Staticroute.php
  tests/_support/Util/TestHelper.php
Labels: BC-BREAK, Task

#7528 [Core] Add Rendering support for Templating Engine
  lib/Controller/Controller.php
  lib/Templating/TwigDefaultDelegatingEngine.php
Labels: Task

#7527 Fix undefined index error
  models/DataObject/Objectbrick/Definition.php
Labels: Bug

#7537 Fixes array_to_html_attribute_string to allow value-less attributes
  lib/helper-functions.php
Labels: Bug

#7556 Removed Migrations Config & Compiler Pass
  bundles/CoreBundle/DependencyInjection/Compiler/DoctrineMigrationsParametersPass.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/PimcoreCoreBundle.php
Labels: BC-BREAK

#7555 Deprecate Installers & Migration Classes & Services
  bundles/CoreBundle/Command/Bundle/UpdateCommand.php
  bundles/CoreBundle/DependencyInjection/Compiler/DoctrineMigrationsParametersPass.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Resources/config/migrations.yml
  lib/Extension/Bundle/Installer/AbstractInstaller.php
  lib/Extension/Bundle/Installer/Exception/UpdateException.php
  lib/Extension/Bundle/Installer/InstallerInterface.php
  lib/Extension/Bundle/Installer/MigrationInstaller.php
  lib/Extension/Bundle/Installer/MigrationInstallerInterface.php
  lib/Extension/Bundle/Installer/OutputWriter.php
  lib/Extension/Bundle/Installer/OutputWriterInterface.php
  lib/Extension/Bundle/PimcoreBundleManager.php
  lib/Migrations/Command/ExecuteCommand.php
  lib/Migrations/Command/GenerateCommand.php
  lib/Migrations/Command/LatestCommand.php
  lib/Migrations/Command/MarkAllDoneCommand.php
  lib/Migrations/Command/MigrateCommand.php
  lib/Migrations/Command/StatusCommand.php
  lib/Migrations/Command/Traits/PimcoreMigrationsConfiguration.php
  lib/Migrations/Command/VersionCommand.php
  lib/Migrations/Configuration/Configuration.php
  lib/Migrations/Configuration/ConfigurationFactory.php
  lib/Migrations/Configuration/InstallConfiguration.php
  lib/Migrations/Configuration/MigrationSetConfiguration.php
  lib/Migrations/InstallVersion.php
  lib/Migrations/Migration.php
  lib/Migrations/Migration/AbstractPimcoreMigration.php
  lib/Migrations/Migration/DryRunMigrationInterface.php
  lib/Migrations/Migration/InstallMigration.php
  lib/Migrations/Migration/PimcoreMigrationInterface.php
  lib/Migrations/MigrationManager.php
  lib/Migrations/SqlFileWriter.php
  lib/Migrations/Version.php
Labels: Task

#7557 Added PHP 8.0 to composer.json and removed manual PHP version check
  composer.json
  lib/Kernel.php
Labels: Task

#7563 Blocks with many entries causes fatal error / probably infinite loop
  models/DataObject/Data/BlockElement.php
Labels: Bug

#7559 Symfony 5
  .travis/phpstan.travis.neon
  bundles/AdminBundle/Security/Firewall/PreAuthenticatedAdminSessionListener.php
  bundles/CoreBundle/DataCollector/PimcoreDataCollector.php
  bundles/CoreBundle/DataCollector/PimcoreTargetingDataCollector.php
  bundles/CoreBundle/DependencyInjection/Compiler/ServiceControllersPass.php
  bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php
  bundles/CoreBundle/Resources/config/commands.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Resources/config/pimcore/dev.yml
  bundles/CoreBundle/Resources/config/routing.yml
  bundles/CoreBundle/Resources/config/routing_dev.yml
  bundles/CoreBundle/Resources/config/services_routing.yml
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Console/ConsoleOutputDecorator.php
  lib/HttpKernel/CacheWarmer/MkdirCacheWarmer.php
  lib/Image/Optimizer/AdvancedPngOptimizer.php
  lib/Image/Optimizer/CjpegOptimizer.php
  lib/Image/Optimizer/JpegoptimOptimizer.php
  lib/Image/Optimizer/PngCrushOptimizer.php
  lib/Image/Optimizer/PngOutOptimizer.php
  lib/Image/Optimizer/ZopflipngOptimizer.php
  lib/Localization/LocaleService.php
  lib/Routing/Loader/FOSJsRoutingLoader.php
  lib/Translation/Translator.php
  lib/Workflow/Dumper/GraphvizDumper.php
  lib/Workflow/ExpressionService.php
  phpstan.neon
Labels: BC-BREAK, Task

#7545 [Workflows] Fix deeplink for workflow notifications
  lib/Workflow/Notification/NotificationEmailService.php
Labels: Bug

#7566 Make Note->addData() chainable
  models/Element/Note.php
Labels: Improvement

#7564 [Application Logger] Support opening FileObject when using stream wrappers in PIMCORE_LOG_FILEOBJECT_DIRECTORY
  bundles/AdminBundle/Controller/Admin/LogController.php
Labels: Improvement

#7546 Add setItems method to CartInterface
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/CartManager/CartInterface.php
Labels: BC-BREAK

#7548 Add getId method to ProductInterface
  bundles/EcommerceFrameworkBundle/Model/ProductInterface.php
Labels: BC-BREAK

#7549 Add getRule method to ModificatedPriceInterface
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
  bundles/EcommerceFrameworkBundle/PriceSystem/ModificatedPriceInterface.php
Labels: BC-BREAK

#7554 [Data Objects] Relation Data-Types: Validation error if object without an ID was assigned
  models/DataObject/ClassDefinition/Data/Relations/AllowAssetRelationTrait.php
  models/DataObject/ClassDefinition/Data/Relations/AllowDocumentRelationTrait.php
  models/DataObject/ClassDefinition/Data/Relations/AllowObjectRelationTrait.php
Labels: BC-BREAK, Task

#7578 [Admin] Fix open action for folder relations
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/abstractRelations.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
Labels: Bug

#7552 [Data Object] Table Data-Type should always return an array
  models/DataObject/ClassDefinition/Data/Table.php
Labels: BC-BREAK

#7589 Remove abstract methods from `Pimcore\Model\DataObject\ClassDefinition\Data` that are also in `Pimcore\Model\DataObject\ClassDefinition\Data\TypeDeclarationSupportInterface`
  models/DataObject/ClassDefinition/Data.php
Labels: Task

#7579 Model::getById() ::getByPath() ... shouldn't catch any exceptions
  models/Asset.php
  models/Asset/Dao.php
  models/DataObject/AbstractObject.php
  models/DataObject/AbstractObject/Dao.php
  models/Document.php
  models/Document/Dao.php
  models/Exception/NotFoundException.php
Labels: BC-BREAK

#7547 Add getArgument method to ElementEventInterface
  lib/Event/Model/ElementEventInterface.php
Labels: BC-BREAK

#7597 Pimcore X Alias
  composer.json
Labels: Task

#7601 [Sent emails] Prevent multiple open panels
  bundles/AdminBundle/Resources/public/js/pimcore/settings/email/log.js
Labels: Bug

#7588 [Translations] Fix shared translations
  lib/Translation/Translator.php
Labels: Bug

#7603 Prevent multiple open panels (sent email, notes)
  bundles/AdminBundle/Resources/public/js/pimcore/element/notes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/email/log.js
Labels: Bug

#7598 [Data objects Grid] Fix search
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Bug

#7594 [Grid] Auto-adjust column width depending on currently shown content
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js
Labels: Improvement

#7584 Consider parameters in fallback translations
  lib/Translation/Translator.php
Labels: Bug

#7604 [Admin Translator] Deprecated transChoice()
  bundles/AdminBundle/Translation/AdminUserTranslator.php
Labels: Task

#7605 Removed AdminUserTranslator::transChoice()
  bundles/AdminBundle/Translation/AdminUserTranslator.php
Labels: BC-BREAK, Task

#7608 Removed cache/tag-interop dependency since it's not longer maintained and doesn't support PHP 8
  composer.json
  lib/Cache/Pool/CacheItem.php
  lib/Cache/Pool/PimcoreCacheItemInterface.php
  lib/Cache/Pool/PimcoreCacheItemPoolInterface.php
Labels: BC-BREAK

#7610 Tags filter not works if tags are uppercase
  bundles/AdminBundle/Controller/Admin/TagsController.php
Labels: Bug

#7618 fix permission checks
  bundles/AdminBundle/Controller/Admin/RedirectsController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
Labels: Bug

#7623 Optimize Dependency::isRequired()
  models/Dependency.php
Labels: Improvement

#7619 Fix: Change the published state, regardless of the previous settings.
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
Labels: Bug

#7625 PHPDoc: Duplicate types
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/Listing.php
  models/DataObject/Listing/Concrete.php
Labels: Task
