Repository pimcore/pimcore, pull requests merged in 2020-04, with the labels that each got.

#6131 [Admin] Token generated links should bypass 2FA
  bundles/AdminBundle/Security/Guard/AdminAuthenticator.php
Labels: Bug

#6092 Import export csv import configurations
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: New Feature

#6157 [Core] Fix Migration 20191114123638
  bundles/CoreBundle/Migrations/Version20191114123638.php
Labels: Bug

#6142 [Admin] Fix saving object should update modification date
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#6143 [DataObjects] When renaming fieldname of Collection Types, tables are…
  bundles/CoreBundle/Resources/config/maintenance.yml
  lib/Maintenance/Tasks/CleanupClassificationstoreTablesTask.php
  lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php
Labels: Bug

#6145 Fixed wrong project root on pimcore-install command
  bin/pimcore-install
Labels: Bug

#6151 Delete job will be executed right after its add to recycle bin job.
  bundles/AdminBundle/Controller/Admin/ElementControllerBase.php
Labels: Improvement

#6137 Allow LIKE operator on Select data type filter condition
  models/DataObject/ClassDefinition/Data/Select.php
Labels: Improvement

#6162 [Asset] Image thumbnail: <picture> tag for SVGs shouldn't have a srcset and had wrong mime-type
  models/Asset/Image/Thumbnail.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#6149 Added support for additional layout types
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/12_Adding_Object_ Layout_types.md
Labels: New Feature

#6153 [Data objects] Geo data fields are not scalable
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/geo/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geo/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geobounds.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopoint.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopolygon.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopolyline.js
  models/DataObject/ClassDefinition/Data/Geo/AbstractGeo.php
Labels: Improvement

#6175 [Search/Backend] Fix Notice: Array to string conversion
  models/Search/Backend/Data.php
Labels: Bug

#6182 [Asset] Thumbnail media query bug fix, regression of #6085
  bundles/CoreBundle/Controller/PublicServicesController.php
  models/Asset/Image/Thumbnail/Config.php
Labels: Bug

#6181 Batch edit with Grid Locking
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
Labels: Bug

#6180 Language selector in Grid options don't change language in view
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/variantsTab.js
Labels: Bug

#6159 [AreaBricks] Add possibility to access editables from brick info
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  models/Document/Tag/Area/Info.php
Labels: Improvement

#5069 [Data objects] Add default value generator service
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/date.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/datetime.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/quantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/select.js
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/README.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/25_Inheritance.md
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Input.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/DefaultValueGeneratorInterface.php
  models/DataObject/ClassDefinition/Helper/DefaultValueGeneratorResolver.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Traits/DefaultValueTrait.php
Labels: New Feature

#6203 [Routing] Locale not set consistently (Translator, ...) when fallback document is used
  bundles/CoreBundle/EventListener/Frontend/ElementListener.php
  lib/Localization/LocaleService.php
Labels: Bug

#6163 [DataObjects Grid] Fix Objectbricks filter query
  bundles/AdminBundle/Helper/GridHelperService.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/Datetime.php
Labels: Bug

#6183 Check classificationstore_data and groups tables for improvements
  bundles/CoreBundle/Migrations/Version20200407120641.php
  models/DataObject/Classificationstore/Dao.php
Labels: Improvement

#6184 [Assets] Upload from zip error handling
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
Labels: Bug

#6186 Check notes table for improvements
  bundles/CoreBundle/Migrations/Version20200407145422.php
  bundles/InstallBundle/Resources/install.sql
  models/Element/Note/Listing/Dao.php
Labels: Improvement

#6206 Check properties table for improvements
  bundles/CoreBundle/Migrations/Version20200410112354.php
  bundles/InstallBundle/Resources/install.sql
  models/Property/Dao.php
Labels: Improvement

#6188 [Asset] Thumbnails: Possibility to change order of media queries
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
  bundles/CoreBundle/Resources/translations/en.extended.json
Labels: Improvement

#6191 Classificationstore: fix undefined index notices + default value
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/InputQuantityValue.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Bug

#6197 [Admin] Document Editmode - Fix Areablock vertical toolbar
  bundles/AdminBundle/Resources/public/css/editmode.css
Labels: Bug

#6202 [DataObjects] Fix default value for localized fields
  models/DataObject/Localizedfield/Dao.php
Labels: Bug

#6195 [QuantityValue] Value should be a float
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Improvement

#6201 Fix namespaces of return types in generated code for Fieldcollections and Objectbricks
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
Labels: Task

#6215 [LocalizedFields] - Exclude from Backend Full Text Search not working
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
Labels: Bug

#6219 Opening object grid in admin throws getPermission() on null error
  models/DataObject/Service.php
Labels: Bug

#6223 [DataObject] Advanced Relations - Fix object cannot be saved with boolean column
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
Labels: Bug

#6222 Update icons.css for Quick Search
  bundles/AdminBundle/Resources/public/css/icons.css
Labels: Bug

#6221 Classdefinition - Block datatype - disable "visible in grid" option
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/block.js
Labels: Bug

#6239 Prevents synchrounous XHttpRequest for update check
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Improvement

#6228 Remove docblock data which changes everytime
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/Fieldcollection/Definition.php
Labels: Improvement

#6227 [Routing] Locale not set consistently (Translator, ...) follow up to #6203
  bundles/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
  bundles/CoreBundle/EventListener/Frontend/ElementListener.php
  lib/Localization/LocaleService.php
Labels: Bug

#6166 [DataObject] [Slider] Improve display of the slider component
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/slider.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: Improvement

#6235 [Admin UI] Add placeholders option in translator t()
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/piwik/settings.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/targeting_toolbar.js
  bundles/CoreBundle/Resources/translations/en.extended.json
Labels: Improvement

#6200 [Full-Page-Cache] Fix: Wrong links in multi site system
  models/Document/Tag/Snippet.php
Labels: Bug

#6254 [Users] Remove all children recursively on delete
  models/User/AbstractUser.php
Labels: Bug

#6246 [Data objects] Default value generator service for URL Slugs
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/urlSlug.js
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/README.md
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
Labels: Improvement

#6244 [Admin UI] Website Settings - Add checks for update/delete requests
  bundles/AdminBundle/Controller/Admin/SettingsController.php
Labels: Bug

#6209 Fix: New Request() in DocumentRenderer clears RequestContext Data
  lib/Document/Renderer/DocumentRenderer.php
  lib/Http/RequestHelper.php
Labels: Bug

#6213 [Core] Changed default permissions from 0775 to 0664
  lib/File.php
  lib/Tool/Admin.php
Labels: Bug

#6212 [Redirects] Fetch target site by domain if no target site set
  lib/Routing/RedirectHandler.php
Labels: Improvement

#6261 [Documents] Targeting - Fix endless loop in Targeting Document
  models/Document/TargetingDocument.php
Labels: Bug

#6225 [DataObject] Fix getBy filter for relation fields
  doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/Concrete.php
Labels: Bug

#6266 [DataObjects] Complete getBy method annotations
  bundles/CoreBundle/Migrations/Version20200421142950.php
  models/DataObject/ClassDefinition.php
Labels: Improvement

#6251 [Bundles] Automatically execute bundle migrations on composer update
  bundles/CoreBundle/Command/Bundle/ListCommand.php
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/01_Installers.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/README.md
  lib/Composer.php
Labels: New Feature

#6236 Cache-Tree is not properly cleared when updating Block-Elements
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/Data/BlockElement.php
  models/Version/ElementDescriptor.php
  tests/model/LazyLoading/ManyToManyObjectRelationTest.php
  tests/model/LazyLoading/ManyToManyRelationTest.php
  tests/model/LazyLoading/ManyToOneRelationTest.php
Labels: Bug

#6272 Check user_workspaces_* table permissions
  bundles/CoreBundle/Migrations/Version20200422090352.php
  bundles/InstallBundle/Resources/install.sql
Labels: Improvement

#6267 Move ElementDescriptor to Pimcore\Model\Element namespace
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Data/BlockElement.php
  models/Element/ElementDescriptor.php
  models/Element/Recyclebin/Item.php
  models/Version.php
  models/Version/ElementDescriptor.php
  models/Version/UnmarshalMatcher.php
Labels: Task

#6274 show validationExceptions for documents correctly as well
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
Labels: Task

#6276 Fixed bug with tabs in read-only fieldcollection
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
Labels: Bug

#6278 Added translation support for longer texts
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
  models/Translation/AbstractTranslation.php
Labels: Improvement

#6281 [Feature] Element Router
  bundles/CoreBundle/Resources/config/services_routing.yml
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/30_Link_Generator.md
  lib/Routing/Element/Router.php
Labels: New Feature

#6207 Search and replace pagination
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/replace_assignments.js
  bundles/CoreBundle/Resources/translations/en.json
  models/Dependency.php
  models/Dependency/Dao.php
Labels: Task

#6294 Correction in applySpecialData fuction for different data types
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/block.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/classificationstore.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/countrymultiselect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/date.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/datetime.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/email.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/externalImage.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/fieldcollections.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/geo/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/hotspotimage.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/inputQuantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/languagemultiselect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/localizedfields.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/objectbricks.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/table.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/textarea.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/time.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/urlSlug.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/user.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/wysiwyg.js
Labels: Bug

#6295 [DataObjects] Respect params passed to Fieldcollections save
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
Labels: Bug

#6297 [Routing] Element Router must implement RouterInterface
  lib/Routing/Element/Router.php
Labels: Improvement

#6302 [Google CSE] fix params as per new definition
  lib/Google/Cse.php
Labels: Bug

#6298 Resolve "[Bug] Texts that are longer than 190 characters cannot be translated"
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
Labels: Bug

#6303 Support for UTF8 URLs in HTTP error log
  bundles/CoreBundle/Migrations/Version20200428082346.php
  bundles/InstallBundle/Resources/install.sql
Labels: Bug

#6269 [Data objects] Override inherited value with same value (break inheritance)
  bundles/CoreBundle/Migrations/Version20200428111313.php
  models/DataObject/ClassDefinition/Data.php
  tests/_support/Helper/Model.php
  tests/model/Inheritance/GeneralTest.php
Labels: Bug

#6310 [Admin] DataObjects - Improve Fieldcollections controls visibility
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
Labels: Bug

#6308 [Asset] Fix content type for SVG rasterized images
  bundles/AdminBundle/Controller/Admin/AssetController.php
Labels: Bug

#6312 [Reports] Flex column width if width not explicitly set
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
Labels: Improvement

#6306 [Redirects] HTML-encode redirect source and target
  bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
Labels: Bug

#6287 [Feature Request] Classification-Store group limitation
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/classificationstore.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/keySelectionWindow.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/15_Classification_Store.md
  doc/Development_Documentation/img/Objects_ClassificationStore_classes.png
  models/DataObject/ClassDefinition/Data/Classificationstore.php
Labels: New Feature

#6313 [Admin] DataObjects - URL Slugs readonly layout fix
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js
  models/DataObject/ClassDefinition/Data/UrlSlug.php
Labels: Bug
