Repository pimcore/pimcore, pull requests merged in 2020-10, with the labels that each got.

#7198 [Documents] Fix Can't change to a template with a required editable
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
Labels: Bug

#7197 Modifing an object having a fieldcollection with inside a localized fields delete the localized values
  models/DataObject/Localizedfield/Dao.php
  tests/Model/LazyLoading/ManyToManyRelationTest.php
  tests/_support/Helper/Model.php
Labels: Bug

#7203 Deprecated \Pimcore\Tool\Archive
  lib/Tool/Archive.php
Labels: Task

#7209 Object with gallery inside localized field inside block throws an error when saving
  models/DataObject/ClassDefinition/Data/Localizedfields.php
Labels: Bug

#7215 Support for Twig in Emails and Web2Print Documents
  doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  lib/Mail.php
  lib/Web2Print/Processor.php
Labels: New Feature

#7211 Deprecated Tag & Snippet Management
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/tagmanagement/item.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/tagmanagement/panel.js
  bundles/CoreBundle/EventListener/Frontend/TagManagerListener.php
  bundles/CoreBundle/Resources/config/event_listeners.yml
  bundles/CoreBundle/Resources/config/maintenance.yml
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Maintenance/Tasks/TagsExpireTask.php
  models/Tool/Tag/Config.php
  models/Tool/Tag/Config/Dao.php
  models/Tool/Tag/Config/Listing.php
  models/Tool/Tag/Config/Listing/Dao.php
Labels: Task

#7225 Deprecated Tool\Tracking\Event
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Tool/Tracking/Event.php
  models/Tool/Tracking/Event/Dao.php
Labels: Task

#7222 [Data Object] Modifing an object having a fieldcollection with inside a localized fields delete the localized values
  models/DataObject/Localizedfield/Dao.php
  tests/Model/LazyLoading/ManyToManyObjectRelationTest.php
  tests/Model/LazyLoading/ManyToManyRelationTest.php
  tests/Model/LazyLoading/ManyToOneRelationTest.php
  tests/_support/Helper/Model.php
  tests/_support/Resources/objects/lazyloading/fieldcollection_LazyLoadingLocalizedTest_export.json
Labels: Bug

#7223 Deprecated Tool\Lock, created Symfony Lock factory service
  bundles/CoreBundle/DependencyInjection/Compiler/LockStoragePass.php
  bundles/CoreBundle/Migrations/Version20201001133558.php
  bundles/CoreBundle/PimcoreCoreBundle.php
  bundles/CoreBundle/Resources/config/services.yml
  bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessQueueCommand.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/Resources/config/checkout_manager.yml
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/19_Development_Tools_and_Details/17_Static_Helpers.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Document/Adapter/LibreOffice.php
  lib/Maintenance/Executor.php
  lib/Maintenance/Tasks/CacheCleanupTask.php
  lib/Maintenance/Tasks/LowQualityImagePreviewTask.php
  lib/Routing/RedirectHandler.php
  lib/Web2Print/Processor.php
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Video/ImageThumbnail.php
  models/Asset/Video/Thumbnail/Processor.php
  models/Tool/Lock.php
  models/Tool/Lock/Dao.php
Labels: Task

#7218 [TEMPLATING] Deprecate PhpEngine & Template Helpers
  bundles/CoreBundle/DependencyInjection/Compiler/PhpTemplatingPass.php
  bundles/CoreBundle/DependencyInjection/Compiler/PimcoreGlobalTemplatingVariablesPass.php
  bundles/CoreBundle/DependencyInjection/Compiler/TemplateVarsProviderPass.php
  bundles/CoreBundle/DependencyInjection/Compiler/TemplatingEngineAwareHelperPass.php
  bundles/CoreBundle/Resources/config/templating_php.yml
  bundles/CoreBundle/Resources/config/templating_php_aliases.yml
  bundles/CoreBundle/Resources/config/templating_twig.yml
  doc/Development_Documentation/02_MVC/02_Template/README.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Dependency_Injection_Tags.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Controller/ArgumentValueResolver/TemplateVarsValueResolver.php
  lib/Controller/Configuration/TemplatePhp.php
  lib/Http/Request/Resolver/TemplateVarsResolver.php
  lib/Templating/GlobalVariables.php
  lib/Templating/Helper/Action.php
  lib/Templating/Helper/BreachAttackRandomContent.php
  lib/Templating/Helper/Cache.php
  lib/Templating/Helper/Device.php
  lib/Templating/Helper/Exception.php
  lib/Templating/Helper/GetAllParams.php
  lib/Templating/Helper/GetParam.php
  lib/Templating/Helper/Glossary.php
  lib/Templating/Helper/HeadLink.php
  lib/Templating/Helper/HeadMeta.php
  lib/Templating/Helper/HeadScript.php
  lib/Templating/Helper/HeadStyle.php
  lib/Templating/Helper/HeadTitle.php
  lib/Templating/Helper/Inc.php
  lib/Templating/Helper/InlineScript.php
  lib/Templating/Helper/Navigation.php
  lib/Templating/Helper/PimcoreUrl.php
  lib/Templating/Helper/Placeholder.php
  lib/Templating/Helper/Placeholder/AbstractHelper.php
  lib/Templating/Helper/Placeholder/CacheBusterAware.php
  lib/Templating/Helper/Placeholder/Container.php
  lib/Templating/Helper/Placeholder/ContainerService.php
  lib/Templating/Helper/TemplatingEngineAwareHelperInterface.php
  lib/Templating/Helper/Traits/TemplatingEngineAwareHelperTrait.php
  lib/Templating/Helper/Translate.php
  lib/Templating/Helper/WebLink.php
  lib/Templating/Helper/WebsiteConfig.php
  lib/Templating/HelperBroker/DocumentEditable.php
  lib/Templating/HelperBroker/DocumentMethod.php
  lib/Templating/HelperBroker/DocumentTag.php
  lib/Templating/HelperBroker/HelperBrokerInterface.php
  lib/Templating/HelperBroker/HelperShortcuts.php
  lib/Templating/HelperBroker/TemplatingHelper.php
  lib/Templating/PhpEngine.php
  lib/Templating/TimedPhpEngine.php
  lib/Templating/Vars/TemplateVarsProviderInterface.php
  lib/Twig/Extension/TemplatingHelperExtension.php
Labels: Task

#7233 [Maintenance] getLastExecution() should check if TmpStore item exists
  lib/Maintenance/Executor.php
Labels: Bug

#7232 Deprecate payment providers
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Heidelpay.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Hobex.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Klarna.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Mpay24Seamless.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/OGone.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPal.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayU.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/QPay.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#7236 Deprecated QRCodes
  bundles/AdminBundle/Controller/Reports/QrcodeController.php
  bundles/AdminBundle/Resources/public/js/pimcore/report/qrcode/item.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/qrcode/panel.js
  bundles/CoreBundle/Controller/PublicServicesController.php
  doc/Development_Documentation/18_Tools_and_Features/23_QR_Codes.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Tool/Qrcode/Config.php
  models/Tool/Qrcode/Config/Dao.php
  models/Tool/Qrcode/Config/Listing.php
  models/Tool/Qrcode/Config/Listing/Dao.php
Labels: Task

#7238 Deprecated GeneratorBundle
  bundles/GeneratorBundle/Command/BaseGenerateBundleCommand.php
  bundles/GeneratorBundle/Command/BaseGeneratorCommand.php
  bundles/GeneratorBundle/Command/GenerateBundleCommand.php
  bundles/GeneratorBundle/Command/Helper/QuestionHelper.php
  bundles/GeneratorBundle/Command/Validators.php
  bundles/GeneratorBundle/DependencyInjection/PimcoreGeneratorExtension.php
  bundles/GeneratorBundle/Generator/BaseBundleGenerator.php
  bundles/GeneratorBundle/Generator/BundleGenerator.php
  bundles/GeneratorBundle/Generator/Generator.php
  bundles/GeneratorBundle/Manipulator/ConfigurationManipulator.php
  bundles/GeneratorBundle/Manipulator/KernelManipulator.php
  bundles/GeneratorBundle/Manipulator/Manipulator.php
  bundles/GeneratorBundle/Manipulator/RoutingManipulator.php
  bundles/GeneratorBundle/Model/BaseBundle.php
  bundles/GeneratorBundle/Model/Bundle.php
  bundles/GeneratorBundle/PimcoreGeneratorBundle.php
  bundles/GeneratorBundle/Resources/config/services.yml
Labels: Task

#7239 Deprecated Zend Query Builder
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderListInterface.php
  lib/Db/ConnectionInterface.php
  lib/Db/PimcoreExtensionsTrait.php
  lib/Db/ZendCompatibility/Expression.php
  lib/Db/ZendCompatibility/QueryBuilder.php
  lib/Db/ZendCompatibility/QueryBuilder/PaginationAdapter.php
  models/Asset/Listing/Dao.php
Labels: Task

#7247 Removed ViewModel and Auto-Rendering
  bundles/AdminBundle/Controller/Admin/Document/RenderletController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/CoreBundle/EventListener/ControllerViewModelListener.php
  bundles/CoreBundle/EventListener/Frontend/ContentTemplateListener.php
  bundles/CoreBundle/EventListener/Frontend/GlobalTemplateVariablesListener.php
  bundles/CoreBundle/EventListener/TemplateControllerListener.php
  bundles/CoreBundle/Resources/config/aliases.yml
  bundles/CoreBundle/Resources/config/argument_resolvers.yml
  bundles/CoreBundle/Resources/config/documents.yml
  bundles/CoreBundle/Resources/config/event_listeners.yml
  bundles/CoreBundle/Resources/config/request_response.yml
  bundles/CoreBundle/Resources/config/templating_php.yml
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/Controller/VoucherController.php
  bundles/EcommerceFrameworkBundle/FilterService/Helper.php
  doc/Development_Documentation/02_MVC/00_Controller.md
  doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
  doc/Development_Documentation/03_Documents/README.md
  lib/Controller/ArgumentValueResolver/ViewModelValueResolver.php
  lib/Controller/FrontendController.php
  lib/Controller/TemplateControllerInterface.php
  lib/Controller/Traits/TemplateControllerTrait.php
  lib/Document/Editable/DelegatingEditableHandler.php
  lib/Document/Editable/EditableHandler.php
  lib/Document/Editable/EditableHandlerInterface.php
  lib/Document/Tag/DelegatingTagHandler.php
  lib/Document/Tag/TagHandlerInterface.php
  lib/Event/Admin/IndexSettingsEvent.php
  lib/Event/AdminEvents.php
  lib/Http/Request/Resolver/DocumentResolver.php
  lib/Http/Request/Resolver/ViewModelResolver.php
  lib/Templating/HelperBroker/DocumentEditable.php
  lib/Templating/HelperBroker/DocumentMethod.php
  lib/Templating/HelperBroker/DocumentTag.php
  lib/Templating/Model/ViewModel.php
  lib/Templating/Model/ViewModelInterface.php
  lib/Templating/PhpEngine.php
  lib/Templating/Renderer/EditableRenderer.php
  models/Document/Editable.php
  models/Document/Editable/Area.php
  models/Document/Editable/Area/AbstractArea.php
  models/Document/Editable/Area/Info.php
  models/Document/Editable/Areablock.php
  models/Document/Editable/Renderlet.php
  models/Document/Editable/Snippet.php
  models/Element/Service.php
Labels: BC-BREAK, Task

#7254 Service Symfony\Component\Lock\Factory needs to be public
  bundles/CoreBundle/Resources/config/services.yml
Labels: Bug

#7144 Improve `Element::resolveDependencies()` implementations
  models/Asset.php
  models/DataObject/Concrete.php
  models/Document/Hardlink.php
  models/Document/Link.php
  models/Document/PageSnippet.php
  models/Element/AbstractElement.php
Labels: Improvement

#7255 Fixed Monolog Bundle incompatibility cased by 3.6.0 release of symfony/monolog-bundle
  composer.json
Labels: Bug, Task, Third Party Bug

#7259 Removed Tool\Tracking\Event
  bundles/CoreBundle/Migrations/Version20201008082752.php
  bundles/InstallBundle/Resources/install.sql
  models/Tool/Tracking/Event.php
  models/Tool/Tracking/Event/Dao.php
Labels: BC-BREAK, Task

#7260 Removed Pimcore\Tool\Archive
  lib/Tool/Archive.php
Labels: BC-BREAK, Task

#7262 Removed QR Codes
  bundles/AdminBundle/Controller/Reports/QrcodeController.php
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/qrcode/item.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/qrcode/panel.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/Controller/PublicServicesController.php
  bundles/CoreBundle/Migrations/Version20201008091131.php
  bundles/CoreBundle/Resources/config/routing.yml
  bundles/InstallBundle/Installer.php
  config/dao-classmap.php
  doc/Development_Documentation/18_Tools_and_Features/23_QR_Codes.md
  models/Tool/Qrcode/Config.php
  models/Tool/Qrcode/Config/Dao.php
  models/Tool/Qrcode/Config/Listing.php
  models/Tool/Qrcode/Config/Listing/Dao.php
Labels: BC-BREAK, Task

#7261 Removed Placeholder support
  doc/Development_Documentation/18_Tools_and_Features/19_Newsletter.md
  doc/Development_Documentation/19_Development_Tools_and_Details/23_Placeholders/01_Object_Placeholder.md
  doc/Development_Documentation/19_Development_Tools_and_Details/23_Placeholders/02_Text_Placeholder.md
  doc/Development_Documentation/19_Development_Tools_and_Details/23_Placeholders/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
  doc/Development_Documentation/img/newsletter_token_url.png
  lib/Mail.php
  lib/Placeholder.php
  lib/Placeholder/AbstractPlaceholder.php
  lib/Placeholder/DataObject.php
  lib/Placeholder/Text.php
  lib/Web2Print/Processor.php
Labels: BC-BREAK, Task

#7264 Removed MigrateElementNamesCommand
  bundles/CoreBundle/Command/Targeting/MigrateElementNamesCommand.php
  bundles/CoreBundle/Resources/config/commands.yml
Labels: Task

#7263 Renamed DB Table documents_elements to documents_editables
  bundles/CoreBundle/Migrations/Version20201008101817.php
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/19_Development_Tools_and_Details/05_Database_Model.md
  models/Document/Editable/Dao.php
  models/Document/PageSnippet/Dao.php
  models/Document/Targeting/TargetingDocumentDaoTrait.php
Labels: BC-BREAK, Task

#7268 [Followup] Fixed Monolog Bundle incompatibility caused by 3.6.0 release of symfony/monolog-bundle
  composer.json
Labels: Improvement

#7269 Remove Linfo Integration
  bundles/AdminBundle/Controller/Admin/External/LinfoController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/EventListener/CsrfProtectionListener.php
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  composer.json
Labels: BC-BREAK, Task

#7270 Remove BC layer for custom list properties in listing classes
  bundles/EcommerceFrameworkBundle/CartManager/Cart/Listing.php
  bundles/EcommerceFrameworkBundle/CartManager/CartCheckoutData/Listing.php
  bundles/EcommerceFrameworkBundle/CartManager/CartItem/Listing.php
  bundles/EcommerceFrameworkBundle/PricingManager/Rule/Listing.php
  bundles/EcommerceFrameworkBundle/VoucherService/Token/Listing.php
  models/Asset/Listing.php
  models/DataObject/ClassDefinition/CustomLayout/Listing.php
  models/DataObject/ClassDefinition/Listing.php
  models/DataObject/Classificationstore/CollectionConfig/Listing.php
  models/DataObject/Classificationstore/CollectionGroupRelation/Listing.php
  models/DataObject/Classificationstore/GroupConfig/Listing.php
  models/DataObject/Classificationstore/KeyConfig/Listing.php
  models/DataObject/Classificationstore/KeyGroupRelation/Listing.php
  models/DataObject/Classificationstore/StoreConfig/Listing.php
  models/DataObject/Listing.php
  models/DataObject/Listing/Concrete.php
  models/DataObject/QuantityValue/Unit/Listing.php
  models/Document/Listing.php
  models/Element/Note/Listing.php
  models/Element/Recyclebin/Item/Listing.php
  models/Element/Tag/Listing.php
  models/Element/WorkflowState/Listing.php
  models/Glossary/Listing.php
  models/GridConfig/Listing.php
  models/GridConfigFavourite/Listing.php
  models/GridConfigShare/Listing.php
  models/ImportConfig/Listing.php
  models/ImportConfigShare/Listing.php
  models/Notification/Listing.php
  models/Redirect/Listing.php
  models/Schedule/Task/Listing.php
  models/Search/Backend/Data/Listing.php
  models/Site/Listing.php
  models/Tool/Email/Blacklist/Listing.php
  models/Tool/Email/Log/Listing.php
  models/Tool/Targeting/Rule/Listing.php
  models/Tool/Targeting/TargetGroup/Listing.php
  models/Translation/AbstractTranslation/Listing.php
  models/User/Listing/AbstractListing.php
  models/User/Permission/Definition/Listing.php
  models/Version/Listing.php
Labels: BC-BREAK

#7272 [Ecommerce][IndexService] Removed FactFinder integration -
  bundles/EcommerceFrameworkBundle/DependencyInjection/IndexService/DefaultWorkerConfigMapper.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/MultiSelect.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/NumberRange.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/Select.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/FactFinder/SelectCategory.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/FactFinderConfigInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/FindologicConfigInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/IFactFinderConfig.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/Legacy/InterfaceLoader.php
  bundles/EcommerceFrameworkBundle/Resources/config/index_service_configs_workers.yml
  bundles/EcommerceFrameworkBundle/Resources/config/pimcore/config.yml
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/03_Assortment_Tenant_Configuration.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/07_Product_List.md
Labels: BC-BREAK

#7273 Removed Tool\Lock
  bundles/CoreBundle/DependencyInjection/Compiler/LockStoragePass.php
  bundles/CoreBundle/Migrations/Version20201008132324.php
  bundles/CoreBundle/PimcoreCoreBundle.php
  bundles/CoreBundle/Resources/config/services.yml
  bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessQueueCommand.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/19_Development_Tools_and_Details/17_Static_Helpers.md
  lib/Document/Adapter/LibreOffice.php
  lib/Maintenance/Executor.php
  lib/Maintenance/Tasks/CacheCleanupTask.php
  lib/Maintenance/Tasks/LowQualityImagePreviewTask.php
  lib/Pimcore.php
  lib/Routing/RedirectHandler.php
  lib/Web2Print/Processor.php
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Video/ImageThumbnail.php
  models/Asset/Video/Thumbnail/Processor.php
  models/Tool/Lock.php
  models/Tool/Lock/Dao.php
Labels: BC-BREAK, Task

#7274 Removed HybridAuth Integration
  bundles/CoreBundle/Controller/PublicServicesController.php
  bundles/CoreBundle/Resources/config/routing.yml
  composer.json
  lib/Tool/HybridAuth.php
Labels: BC-BREAK, Task

#7281 Remove legacy service aliases
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/CoreBundle/Resources/config/aliases.yml
  bundles/CoreBundle/Resources/config/event_listeners.yml
  bundles/CoreBundle/Resources/config/l10n.yml
  bundles/CoreBundle/Resources/config/templating_php.yml
  bundles/CoreBundle/Resources/config/templating_php_aliases.yml
  bundles/CoreBundle/Resources/config/templating_twig.yml
  bundles/CoreBundle/Resources/config/templating_twig_aliases.yml
  bundles/EcommerceFrameworkBundle/Model/Currency.php
  bundles/EcommerceFrameworkBundle/Resources/config/voucher_service.yml
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/AbstractTokenManager.php
  lib/Extension/Bundle/Traits/StateHelperTrait.php
  lib/Google/Cse.php
  lib/Tool.php
  lib/Tool/Admin.php
  lib/Tool/Frontend.php
  lib/Tool/Transliteration.php
  models/Asset.php
  models/DataObject/ClassDefinition/Data/Country.php
  models/DataObject/ClassDefinition/Data/Countrymultiselect.php
  models/DataObject/Data/QuantityValue.php
  models/DataObject/Listing/Concrete/Dao.php
  models/DataObject/Localizedfield.php
  models/DataObject/Service.php
  models/Document/Editable/Video.php
  models/Document/PageSnippet.php
  models/Element/AdminStyle.php
  models/Translation/AbstractTranslation.php
  models/Translation/Admin.php
  tests/_support/Util/TestHelper.php
Labels: BC-BREAK

#7282 [Document] Remove support for edit.php on Area-Bricks
  bundles/AdminBundle/Resources/public/css/editmode.css
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
  bundles/CoreBundle/Resources/views/Areabrick/wrapper.html.twig
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
  doc/Development_Documentation/03_Documents/01_Editables/04_Area.md
  lib/Document/Editable/EditableHandler.php
  lib/Extension/Document/Areabrick/AbstractAreabrick.php
  lib/Extension/Document/Areabrick/AbstractTemplateAreabrick.php
  lib/Extension/Document/Areabrick/AreabrickInterface.php
  lib/Extension/Document/Areabrick/TemplateAreabrickInterface.php
Labels: BC-BREAK, Task

#7284 [DataObject] Undefined notice warning for $params['language']
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/InputQuantityValue.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Video.php
Labels: Bug

#7285 [Core] Do not statically set error reporting level
  .travis.yml
  bin/pimcore-install
  doc/Development_Documentation/19_Development_Tools_and_Details/07_Logging.md
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  lib/Bootstrap.php
  stubs/dynamic-constants.php
Labels: Task

#7295 [Glossary] Removed support for acronyms
  bundles/AdminBundle/Resources/public/js/pimcore/settings/glossary.js
  bundles/CoreBundle/Migrations/Version20201012154224.php
  bundles/CoreBundle/Resources/translations/en.json
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/18_Tools_and_Features/21_Glossary.md
  lib/Tool/Glossary/Processor.php
  models/Glossary.php
Labels: BC-BREAK, Task

#7296 [Core] Use ElementInterface instead of AbstractElement
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/Document/RenderletController.php
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/info-table.html.php
  bundles/CoreBundle/EventListener/ElementTagsListener.php
  bundles/CoreBundle/EventListener/WorkflowManagementListener.php
  bundles/EcommerceFrameworkBundle/IndexService/Interpreter/DefaultRelations.php
  doc/Development_Documentation/18_Tools_and_Features/39_Sitemaps.md
  lib/Config.php
  lib/Sitemap/Document/Filter/DocumentTypeFilter.php
  lib/Sitemap/Document/Filter/SiteRootFilter.php
  lib/Sitemap/Element/AbstractElementGenerator.php
  lib/Sitemap/Element/Filter/PropertiesFilter.php
  lib/Sitemap/Element/Filter/PublishedFilter.php
  lib/Sitemap/Element/FilterInterface.php
  lib/Sitemap/Element/Processor/ModificationDateProcessor.php
  lib/Sitemap/Element/Processor/PropertiesProcessor.php
  lib/Sitemap/Element/ProcessorInterface.php
  lib/Workflow/ActionsButtonService.php
  lib/Workflow/EventSubscriber/NotesSubscriber.php
  lib/Workflow/EventSubscriber/NotificationSubscriber.php
  lib/Workflow/Manager.php
  lib/Workflow/Notification/NotificationEmailService.php
  lib/Workflow/Notification/PimcoreNotificationService.php
  lib/Workflow/Service.php
  models/Asset/MetaData/ClassDefinition/Data/Asset.php
  models/Asset/MetaData/ClassDefinition/Data/DataObject.php
  models/Asset/MetaData/ClassDefinition/Data/Document.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/Data/ElementMetadata.php
  models/Element/ElementInterface.php
  phpstan-baseline.neon
  tests/_support/Util/TestHelper.php
Labels: Task

#7299 [Element] Added setProperties() and setProperty() to ElementInterface
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
  models/Element/ElementInterface.php
Labels: BC-BREAK, Task

#7304 [Document] Document in session is not used in templates
  bundles/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
  bundles/CoreBundle/EventListener/Frontend/ElementListener.php
  bundles/CoreBundle/EventListener/Frontend/GlobalTemplateVariablesListener.php
Labels: Bug

#7303 [Document] Removed Naming Strategy Support
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
  bundles/CoreBundle/Command/Document/MigrateTagNamingStrategyCommand.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/documents.yml
  doc/Development_Documentation/03_Documents/13_Editable_Naming_Strategies.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Document/Editable/UsageRecorderSubscriber.php
  lib/Document/Tag/NamingStrategy/AbstractNamingStrategy.php
  lib/Document/Tag/NamingStrategy/Exception/TagNameException.php
  lib/Document/Tag/NamingStrategy/LegacyNamingStrategy.php
  lib/Document/Tag/NamingStrategy/Migration/AbstractMigrationStrategy.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/ConflictResolver.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/ConflictResolverInterface.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/AbstractBlock.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/AbstractElement.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/Areablock.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/Block.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/Element/Editable.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/ElementTree.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/Exception/BuildEditableException.php
  lib/Document/Tag/NamingStrategy/Migration/Analyze/Exception/LogicException.php
  lib/Document/Tag/NamingStrategy/Migration/AnalyzeMigrationStrategy.php
  lib/Document/Tag/NamingStrategy/Migration/Exception/NameMappingException.php
  lib/Document/Tag/NamingStrategy/Migration/MappingError.php
  lib/Document/Tag/NamingStrategy/Migration/Render/MigrationSubscriber.php
  lib/Document/Tag/NamingStrategy/Migration/RenderMigrationStrategy.php
  lib/Document/Tag/NamingStrategy/NamingStrategyInterface.php
  lib/Document/Tag/NamingStrategy/NestedNamingStrategy.php
  models/Document/Editable.php
  models/Document/Editable/Area.php
  models/Document/Editable/Block/AbstractBlockItem.php
  phpstan.neon
  tests/Unit/Document/Tag/NamingStrategy/AbstractNamingStrategyTest.php
  tests/Unit/Document/Tag/NamingStrategy/LegacyNamingStrategyTest.php
  tests/Unit/Document/Tag/NamingStrategy/Migration/Analyze/MappingConflictResolver.php
  tests/Unit/Document/Tag/NamingStrategy/Migration/ElementTreeTest.php
  tests/Unit/Document/Tag/NamingStrategy/NestedNamingStrategyTest.php
Labels: BC-BREAK, Task

#7311 [Document] Make editable properties protected
  models/Document/Editable/Areablock.php
  models/Document/Editable/Block.php
  models/Document/Editable/Checkbox.php
  models/Document/Editable/Date.php
  models/Document/Editable/Embed.php
  models/Document/Editable/Image.php
  models/Document/Editable/Input.php
  models/Document/Editable/Link.php
  models/Document/Editable/Multiselect.php
  models/Document/Editable/Numeric.php
  models/Document/Editable/Pdf.php
  models/Document/Editable/Relation.php
  models/Document/Editable/Relations.php
  models/Document/Editable/Renderlet.php
  models/Document/Editable/Select.php
  models/Document/Editable/Snippet.php
  models/Document/Editable/Table.php
  models/Document/Editable/Textarea.php
  models/Document/Editable/Video.php
  models/Document/Editable/Wysiwyg.php
Labels: BC-BREAK, Task

#7307 [Ecommerce] [IndexService] Fix the Pimcore TagsGetter
  bundles/EcommerceFrameworkBundle/IndexService/Getter/TagsGetter.php
Labels: Bug

#7315 [Data Objects] Classification-Store: quote relationIds used in listing
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
Labels: Bug, Task

#7305 [Core] Use TranslatorInterface for DI - #7276
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/CoreBundle/Resources/config/event_listeners.yml
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/AbstractTokenManager.php
  models/Element/AdminStyle.php
Labels: Task

#7308 [Data Objects] Removed BC Layers in Data-Types
  models/DataObject/ClassDefinition/Dao.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Href.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Multihref.php
  models/DataObject/ClassDefinition/Data/MultihrefMetadata.php
  models/DataObject/ClassDefinition/Data/Nonownerobjects.php
  models/DataObject/ClassDefinition/Data/Objects.php
  models/DataObject/ClassDefinition/Data/ObjectsMetadata.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/ReverseManyToManyObjectRelation.php
  models/DataObject/Concrete.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Fieldcollection/Data/AbstractData.php
  models/DataObject/Fieldcollection/Definition/Dao.php
  models/DataObject/Localizedfield.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Data/AbstractData.php
  models/DataObject/Objectbrick/Definition/Dao.php
  tests/Model/Relations/MultipleAssigmentTest.php
Labels: BC-BREAK

#7316 Removed Cookie Policy Info Bar Integration
  .travis/app/config/system.yml
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/EventListener/Frontend/CookiePolicyNoticeListener.php
  bundles/CoreBundle/Resources/config/event_listeners.yml
  bundles/CoreBundle/Resources/misc/cookie-policy-default-template.html
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/18_Tools_and_Features/25_System_Settings.md
  doc/Development_Documentation/img/system-settings-sample.png
  doc/Development_Documentation/img/system-settings2.png
  lib/Config.php
Labels: BC-BREAK, Task

#7319 Removed \Pimcore\Browser class
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
  lib/Browser.php
Labels: BC-BREAK, Task

#7317 [Document] PageSnippet::setEditable() remove name from signature (redundant)
  lib/Templating/Renderer/EditableRenderer.php
  lib/Translation/ImporterService/Importer/DocumentImporter.php
  models/Document/PageSnippet.php
  models/Document/TargetingDocument.php
Labels: BC-BREAK, Task

#7320 Removed Tag & Snippet Management
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/tagmanagement/item.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/tagmanagement/panel.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/EventListener/Frontend/TagManagerListener.php
  bundles/CoreBundle/Migrations/Version20201014101437.php
  bundles/CoreBundle/Resources/config/event_listeners.yml
  bundles/CoreBundle/Resources/config/maintenance.yml
  bundles/CoreBundle/Resources/translations/aliases.json
  bundles/CoreBundle/Resources/translations/en.json
  bundles/InstallBundle/Installer.php
  lib/Maintenance/Tasks/TagsExpireTask.php
  models/Tool/Tag/Config.php
  models/Tool/Tag/Config/Dao.php
  models/Tool/Tag/Config/Listing.php
  models/Tool/Tag/Config/Listing/Dao.php
Labels: Bug, Task

#7325 Removed EventedControllerInterface
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Controller/Admin/External/AdminerController.php
  bundles/AdminBundle/Controller/Admin/External/OpcacheController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Admin/LogController.php
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Controller/Admin/PortalController.php
  bundles/AdminBundle/Controller/Admin/RecyclebinController.php
  bundles/AdminBundle/Controller/Admin/TargetingController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Controller/Admin/WorkflowController.php
  bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
  bundles/AdminBundle/Controller/GDPR/AdminController.php
  bundles/AdminBundle/Controller/GDPR/AssetController.php
  bundles/AdminBundle/Controller/GDPR/DataObjectController.php
  bundles/AdminBundle/Controller/GDPR/PimcoreUsersController.php
  bundles/AdminBundle/Controller/GDPR/SentMailController.php
  bundles/AdminBundle/Controller/Reports/AnalyticsController.php
  bundles/CoreBundle/EventListener/EventedControllerListener.php
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/Controller/PricingController.php
  bundles/EcommerceFrameworkBundle/Controller/VoucherController.php
  lib/Controller/EventedControllerInterface.php
  lib/Controller/FrontendController.php
Labels: BC-BREAK, Task

#7331 [DataObject] GridOptions ... DB error when adding objectbrick fields
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Bug

#7334 [Redirects] Fix CSV import error
  lib/Routing/Redirect/Csv.php
Labels: Bug

#7332 fixed some undefined notices
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
Labels: Bug

#7328 [Admin] Fix multiselect inside not rendered tabs in Fieldcollections lose data
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/multiselect.js
Labels: Bug

#7329 Fixed encoding detection
  composer.json
  lib/Tool/Text.php
Labels: Improvement

#7318 Untouched relations get lost when contained in localizes fields in object bricks on save
  models/DataObject/Localizedfield/Dao.php
  tests/Model/LazyLoading/AdvancedManyToManyObjectRelationTest.php
  tests/Model/LazyLoading/AdvancedManyToManyRelationTest.php
  tests/Model/LazyLoading/ManyToManyObjectRelationTest.php
  tests/Model/LazyLoading/ManyToManyRelationTest.php
  tests/Model/LazyLoading/ManyToOneRelationTest.php
Labels: Bug

#7342 [Document] AbstractBlockItem - Deprecate getElement()
  models/Document/Editable/Block/AbstractBlockItem.php
  models/Document/Editable/Block/Item.php
Labels: Bug, Task

#7345 [Asset] Fix Stream error when saving an asset to an S3 bucket
  models/Asset.php
  models/Asset/Service.php
Labels: Bug

#7340 [Translations] Add alias to "bundles" key for plugins, extensions
  bundles/CoreBundle/Resources/translations/aliases.json
Labels: Task

#7362 Added link to reasons why REST API was deprecated
  doc/Development_Documentation/24_Web_Services/README.md
Labels: Task

#7379 Fixed "Illegal offset type" error in Input.php caused by getting Obje…
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/Input.php
Labels: Bug

#7361 Change Alignment of input data type label from right to left
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js
Labels: Bug

#7381 [Data Objects] Links in Blocks will not be cleaned up when Target Document is deleted
  models/DataObject/ClassDefinition/Data/Link.php
Labels: Bug

#7360 "owner missing" error after upgrading from 6.0.x/6.6.9 to current 6.7.2
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/Localizedfield.php
Labels: Bug

#7380 [Maintenance] Fix versions cleanup stacktrace db task
  lib/Maintenance/Tasks/VersionsCleanupStackTraceDbTask.php
Labels: Bug

#7398 Fixed PHPStan issues
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  lib/Google/Api.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/Document/Link.php
  phpstan-baseline.neon
Labels: Task

#7386 [Maintenance] fix parallel execution of maintenance tasks
  lib/Maintenance/Executor.php
Labels: Bug

#7400 [Document] Link editable can generate invalid type="" attribute
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/link.js
  models/Document/Editable/Link.php
Labels: Bug

#7393 generate public url through asset listeners
  bundles/AdminBundle/Controller/Admin/AssetController.php
  models/Asset.php
Labels: Bug

#7403 Order Details Tab - fix inconsistent permission check
  bundles/EcommerceFrameworkBundle/Resources/public/js/bundle.js
Labels: Bug

#7131 [Dependencies] - Sort dependencies by type and path
  models/Dependency/Dao.php
  tests/Model/Element/DependenciesTest.php
Labels: Improvement

#7406 [Documents] Fix content of unpublished documents lost
  models/Document/Editable.php
  models/Document/PageSnippet.php
Labels: Bug

#7387 [Translations] Fix %count% parameter translations
  lib/Translation/Translator.php
Labels: Bug

#7405 [Maintenance] fix not updating TmpStore on executing maintenance task
  lib/Maintenance/Executor.php
Labels: Bug

#7335 [Ecommerce Framework] IntlFormatter tried to resolve locale before LocaleListener
  lib/Localization/IntlFormatter.php
Labels: Bug

#7392 [DataObject] ObjectBrick/FieldCollection - Fix error when importing json definition
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
Labels: Bug

#7388 [XLIFF Export] Fix exporting localizedfields inside fieldcollections and objectbricks
  lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
Labels: Bug

#7412 Admin login is not recognizing Edge correctly anymore and hides the login form
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
Labels: Bug

#7404 Make "GoogleTagManager::formatPrice()" compatible with its default value
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/GoogleTagManager.php
Labels: Bug

#7351 Add all default formats of Symfonys OutputFormatter to AbstractCommand
  doc/Development_Documentation/19_Development_Tools_and_Details/11_Console_CLI.md
  lib/Console/AbstractCommand.php
Labels: Improvement

#7368 [Permissions] Allow setting permission category after creating it
  models/User/Permission/Definition/Dao.php
Labels: Improvement

#7291 [Roles] Sort permissions by label
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/role/settings.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js
Labels: Improvement

#7289 [Data Objects] Support selecting multiple items for relational fields
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
Labels: Improvement

#7170 [Twig] Add template helpers to get elements by path
  doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
  lib/Twig/Extension/PimcoreObjectExtension.php
Labels: Improvement

#7075 Support animated gif thumbnails
  bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  lib/Image/Adapter.php
  lib/Image/Adapter/Imagick.php
  models/Asset/Image/Thumbnail/Config.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: New Feature

#7416 [Ecommerce] Migrate Ecommerce Tracking templates to Twig
  bundles/EcommerceFrameworkBundle/Resources/config/tracking_manager.yml
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/classic/checkout_complete.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/classic/checkout_complete.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/checkout.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/checkout.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/checkout_complete.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/checkout_complete.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/checkout_option.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/checkout_option.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/dependencies.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/dependencies.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/product_action.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/product_action.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/product_impression.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/product_impression.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/product_view.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/product_view.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/track_event.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/track_event.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/tagManager/call.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/universal/checkout_complete.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/universal/checkout_complete.js.twig
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/piwik/calls.js.php
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/piwik/calls.js.twig
  bundles/EcommerceFrameworkBundle/Tracking/Tracker.php
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/Piwik.php
Labels: BC-BREAK, Task

#7407 [Grid config] Error when opening saved configuration which contains fields of deleted object brick
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  models/DataObject/Listing/Concrete/Dao.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Service.php
Labels: Bug

#6864 fixed Ecommerce: Incorrect calculation of order sum with voucher (rounding error)
  bundles/EcommerceFrameworkBundle/PricingManager/Action/CartDiscount.php
Labels: BC-BREAK, Bug

#7418 Fixed locking - follow up to #7386
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  lib/Maintenance/Tasks/CacheCleanupTask.php
  lib/Maintenance/Tasks/LowQualityImagePreviewTask.php
  models/Asset/Document/ImageThumbnail.php
Labels: Bug
