Repository pimcore/pimcore, pull requests merged in 2020-05, with the labels that each got.

#6291 Problem saving objects with inherited mandatory attributes
  models/DataObject/ClassDefinition/Data/Localizedfields.php
Labels: Bug

#6288 Added classification-store translation support
  bundles/AdminBundle/Resources/public/js/pimcore/helpers/generic-grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/columnConfigDialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/keySelectionWindow.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/relationSelectionWindow.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
  models/DataObject/ClassDefinition/Data/Classificationstore.php
Labels: Improvement

#6337 [Admin] Asset Custom Metadata grid - fix data for rows with same name
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/grid.js
Labels: Bug

#6326 [Asset] Image previews with duplicate id params
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/image.js
Labels: Bug

#6327 [Sitemap] Ignore hardlinks
  lib/Sitemap/Document/Filter/DocumentTypeFilter.php
Labels: Bug

#6342 [Data Objects] [Inheritance] Values at child not getting inherited from parent.
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  models/DataObject/Traits/DefaultValueTrait.php
Labels: Bug

#6351 [Admin] DataObjects - Disable reordering for not editable Advanced Relations
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
Labels: Bug

#6358 [DataObject] Dataloss when saving localized fields in field collections
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/Localizedfield/Dao.php
  tests/_support/Helper/Model.php
  tests/_support/Resources/objects/fieldcollection-import.json
  tests/model/DataType/LocalizedFieldTest.php
Labels: Bug

#6354 [DataObject] Fix OmitMandatoryCheck for Grids
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#6353 [DataObject] ObjectBrick/FieldCollection - Add Maximum limit validation in API
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
Labels: Bug

#6375 [Asset] Fix - Unable to save in image editor
  bundles/AdminBundle/Resources/public/js/lib/PIMCORE_MODIFICATIONS.txt
  bundles/AdminBundle/Resources/public/js/lib/minipaint/PIMCORE_MODIFICATIONS.txt
  bundles/AdminBundle/Resources/public/js/lib/minipaint/dist/bundle.js
Labels: Bug

#6380 [PHPStan] Fix current errors after phpstan update
  bundles/EcommerceFrameworkBundle/Command/CleanupPendingOrdersCommand.php
  bundles/EcommerceFrameworkBundle/Command/Voucher/CleanupReservationsCommand.php
  bundles/EcommerceFrameworkBundle/Command/Voucher/CleanupStatisticsCommand.php
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/AbstractOrder.php
  bundles/GeneratorBundle/Command/BaseGenerateBundleCommand.php
  bundles/GeneratorBundle/Command/GenerateBundleCommand.php
  models/Asset/WebDAV/File.php
  models/Asset/WebDAV/Folder.php
  models/DataObject/Objectbrick/Dao.php
  models/Document/Hardlink/Wrapper.php
  models/Document/Tag.php
  models/Document/Tag/Area.php
  models/Document/Tag/Areablock.php
  models/Document/Tag/Block.php
  models/Document/Tag/TagInterface.php
  phpstan-baseline.neon
Labels: Task

#6378 Change API URL for Datatrans
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
Labels: Bug

#6377 [Ecommerce][Indexservice] Utilize transactions for avoiding deadlocks
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
Labels: Improvement

#6393 [Admin] Documents - Fix "save, publish & close" option
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
Labels: Bug

#6397 Typo fixed and new function getAllCartsForCurrentUser
  bundles/EcommerceFrameworkBundle/CartManager/MultiCartManager.php
Labels: Improvement

#6402 [Workflow] Fix saving document workflow state
  lib/Workflow/MarkingStore/StateTableMarkingStore.php
Labels: Approved, Bug

#6399 [Asset] fix download-filename when file extension of Asset is uppercased
  bundles/AdminBundle/Controller/Admin/AssetController.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: Bug

#6317 Bottom margin added for advanced image container
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js
Labels: Improvement

#6410 <fix> Set default value for "handle_pending_payment_strategy"
  bundles/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
Labels: Bug

#6426 Fix: Data::isEmpty() methods have wrong PHP docs
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionField.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/Extension/Text.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Time.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/Fieldcollection.php
Labels: Task

#6422 Update Listing.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
Labels: Bug

#6394 Avoid Pimcore::getContainer() in Controller/Commands
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/MiscController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/CoreBundle/Command/InternalUnicodeCldrLanguageTerritoryGeneratorCommand.php
  bundles/CoreBundle/Command/Targeting/MigrateElementNamesCommand.php
  bundles/CoreBundle/Resources/config/aliases.yml
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  phpstan-baseline.neon
Labels: Task

#6388 [Image / Video thumbnails] Make thumbnail deletion compatible with stream wrappers
  models/Asset/Image.php
  models/Asset/Thumbnail/ClearTempFilesTrait.php
  models/Asset/Video.php
Labels: Improvement

#6448 Removed obsolete html2text references - see also #6067
  .travis/app/config/parameters.example.yml
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
  lib/Tool/Requirements.php
Labels: Task

#6438 Fix on object variant grid: batch edit for 'select' fields + batch edit all with selected items
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
Labels: Bug

#6461 [Tracking] fix quantity for trackCartProductActionAdd
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/GoogleTagManager.php
Labels: Bug

#6431 Fix uncorrect CSV/XLS export for 'Operator Merge' values
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#6471 fix flatpickr compatibility
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
Labels: Bug

#6480 Ecommerce fix notice filter
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectFromMultiSelect.php
Labels: Improvement
