Repository pimcore/pimcore, pull requests merged in 2020-01, with the labels that each got.

#5509 InheritanceHelper: Replace stclass with array
  models/DataObject/Concrete/Dao/InheritanceHelper.php
Labels: Improvement

#5510 [Targeting] Performance tuning multiple targeting rules check
  lib/Targeting/VisitorInfoResolver.php
Labels: Improvement

#5502 Localizefield\Listing: added invalid locale check
  models/DataObject/Listing/Concrete/Dao.php
  tests/model/Inheritance/LocalizedFieldTest.php
Labels: Task

#5513 FIX: DatatransRequest now extending AbstractRequest
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/StartPaymentRequest/DatatransRequest.php
Labels: Bug

#5515 [Targeting] Removed MaxMind GeoIP automatic update task
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/targeting/condition/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/targeting/conditions.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/targeting/rules/item.js
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/maintenance.yml
  doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Maintenance/Tasks/DownloadMaxMinDbTask.php
Labels: BC-BREAK, Task

#5507 [Recycle Bin] Optimize relations serialization with ElementDescriptor
  models/Element/Recyclebin/Item.php
Labels: Improvement

#5482 [Assets] Set type to unknown for assets without data
  lib/Model/Listing/AbstractListing.php
  models/Asset.php
  models/Asset/Listing/Dao.php
Labels: Task

#5468 [Translations] XLIFF Export - Add translated target values
  lib/Translation/AttributeSet/Attribute.php
  lib/Translation/AttributeSet/AttributeSet.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
  lib/Translation/ExportService/Exporter/Xliff12Exporter.php
Labels: Improvement

#5448 [Core] Add new config for full-page cache
  .travis/app/config/system.yml
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
  bundles/CoreBundle/Resources/migrations/Version20191213115045.php
  bundles/InstallBundle/SystemConfig/ConfigWriter.php
  doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Config.php
Labels: Bug

#5471 Consistently getFieldDefinition(s) method name
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Helper/GridHelperService.php
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/13_Locking_Fields.md
  lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/Concrete.php
  models/DataObject/Fieldcollection/Dao.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Localizedfield.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Service.php
Labels: Task

#5347 [Ecommerce][Tracking] TrackingManager improvements
  bundles/EcommerceFrameworkBundle/EventListener/Frontend/TrackingCodeFlashMessageListener.php
  bundles/EcommerceFrameworkBundle/Resources/config/event_listeners.yml
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/analytics/enhanced/track_event.js.php
  bundles/EcommerceFrameworkBundle/Tracking/TrackEventInterface.php
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/Analytics/EnhancedEcommerce.php
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/GoogleTagManager.php
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/Piwik.php
  bundles/EcommerceFrameworkBundle/Tracking/TrackingCodeAwareInterface.php
  bundles/EcommerceFrameworkBundle/Tracking/TrackingManager.php
  bundles/EcommerceFrameworkBundle/Tracking/TrackingManagerInterface.php
Labels: BC-BREAK, Improvement

#5514 FIX: PayPalSmartPaymentButton
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
Labels: Improvement

#5503 [Data Objects] Add Before/After options for Blocks & Field-collections
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/block.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
Labels: Improvement

#5278 [Many-to-many object relation] add option to restrict "Allow to create a new object in relation field"
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
Labels: Improvement

#5533 Increase process timeout for asset installation
  lib/Tool/AssetsInstaller.php
Labels: Task

#5531 [PHPSTAN] Ignore EventDispatcherInterface errors
  phpstan.neon
Labels: Task

#5487 [Webservice] Convert stdclass metadata items to associative array
  models/Asset.php
  models/Webservice/Data/Asset.php
Labels: Bug

#5530 [PHPSTAN] Fix: PHPDoc tag param references unknown parameter
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/RecyclebinController.php
  bundles/AdminBundle/Controller/Rest/AbstractRestController.php
  bundles/AdminBundle/GDPR/DataProvider/Assets.php
  bundles/AdminBundle/Helper/GridHelperService.php
  bundles/CoreBundle/EventListener/Frontend/EditmodeListener.php
  bundles/EcommerceFrameworkBundle/CartManager/CartItem/Dao.php
  bundles/EcommerceFrameworkBundle/CartManager/CartManagerInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
  bundles/EcommerceFrameworkBundle/Model/AbstractOrder.php
  bundles/EcommerceFrameworkBundle/Model/AbstractPaymentInformation.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing/Filter/CustomerObject.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManagerInterface.php
  lib/Db/ZendCompatibility/QueryBuilder.php
  lib/Db/ZendCompatibility/QueryBuilder/PaginationAdapter.php
  lib/Event/Model/ElementEvent.php
  lib/Event/Model/ResolveElementEvent.php
  lib/Http/Request/Resolver/OutputTimestampResolver.php
  lib/Templating/Helper/HeadMeta.php
  lib/Templating/Helper/HeadScript.php
  lib/Templating/Helper/HeadStyle.php
  lib/Templating/Helper/Placeholder.php
  lib/Translation/AttributeSet/AttributeSet.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
  lib/Translation/ExportDataExtractorService/ExportDataExtractorService.php
  lib/Translation/ExportDataExtractorService/ExportDataExtractorServiceInterface.php
  lib/Workflow/EventSubscriber/NotificationSubscriber.php
  lib/Workflow/Manager.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/Document/Service/Dao.php
  models/Element/Tag.php
  models/Element/WorkflowState/Dao.php
  models/User.php
Labels: Task

#5526 [PHPSTAN] Fix: Wrong binary operations
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayU.php
  lib/helper-functions.php
  models/Asset.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/Document/Tag/Video.php
  models/Webservice/Data/Document/Element.php
Labels: Task

#5524 refactor testsetup
  tests/_support/Helper/AbstractDefinitionHelper.php
  tests/_support/Helper/ClassManager.php
  tests/_support/Helper/Model.php
  tests/model/Classificationstore/AbstractClassificationStoreTest.php
  tests/model/Classificationstore/GeneralTest.php
  tests/model/Inheritance/LocalizedFieldTest.php
  tests/model/LazyLoading/AbstractLazyLoadingTest.php
  tests/model/LazyLoading/AdvancedManyToManyObjectRelationTest.php
  tests/model/LazyLoading/AdvancedManyToManyRelationTest.php
  tests/model/LazyLoading/ManyToManyObjectRelationTest.php
  tests/model/LazyLoading/ManyToManyRelationTest.php
  tests/model/LazyLoading/ManyToOneRelationTest.php
  tests/model/Relations/MultipleAssigmentTest.php
  tests/rest/AssetTest.php
Labels: Task

#5536 Deprecated array_key_exists in cache Runtime.php
  lib/Cache/Runtime.php
Labels: Bug

#5522 Inheritance fixes
  models/DataObject/Concrete/Dao.php
  models/DataObject/Concrete/Dao/InheritanceHelper.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
  tests/model/Inheritance/LocalizedFieldTest.php
Labels: Bug, Improvement

#5542 [PHPSTAN] Fix AdminBundle PHP Docs
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/AdminBundle/Controller/Admin/ElementControllerBase.php
  bundles/AdminBundle/Controller/Admin/EmailController.php
  bundles/AdminBundle/Controller/Admin/External/AdminerController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Admin/LogController.php
  bundles/AdminBundle/Controller/Admin/PortalController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Controller/Admin/TagsController.php
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Controller/AdminController.php
  bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php
  bundles/AdminBundle/Controller/Reports/AnalyticsController.php
  bundles/AdminBundle/Controller/Rest/AbstractRestController.php
  bundles/AdminBundle/Controller/Rest/Element/AbstractElementController.php
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/EventListener/AdminExceptionListener.php
  bundles/AdminBundle/EventListener/CsrfProtectionListener.php
  bundles/AdminBundle/EventListener/GridConfigListener.php
  bundles/AdminBundle/EventListener/ImportConfigListener.php
  bundles/AdminBundle/EventListener/Traits/ControllerTypeTrait.php
  bundles/AdminBundle/GDPR/DataProvider/Elements.php
  bundles/AdminBundle/Helper/QueryParams.php
Labels: Task

#5543 [PHPSTAN] Fix CoreBundle PHP Docs
  bundles/CoreBundle/Command/CacheWarmingCommand.php
  bundles/CoreBundle/Command/Definition/Import/AbstractStructureImportCommand.php
  bundles/CoreBundle/Command/Definition/Import/ClassCommand.php
  bundles/CoreBundle/Command/Definition/Import/CustomLayoutCommand.php
  bundles/CoreBundle/Command/Definition/Import/FieldCollectionCommand.php
  bundles/CoreBundle/Command/Definition/Import/ObjectBrickCommand.php
  bundles/CoreBundle/Command/InternalNewsletterDocumentSendCommand.php
  bundles/CoreBundle/Command/ThumbnailsVideoCommand.php
  bundles/CoreBundle/Controller/PublicServicesController.php
  bundles/CoreBundle/DependencyInjection/Compiler/AreabrickPass.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/EventListener/Frontend/CookiePolicyNoticeListener.php
  bundles/CoreBundle/EventListener/Frontend/ElementListener.php
  bundles/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php
  bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
  bundles/CoreBundle/EventListener/MaintenancePageListener.php
  bundles/CoreBundle/EventListener/PimcoreContextListener.php
  bundles/CoreBundle/Resources/migrations/Version20181115114003.php
  bundles/CoreBundle/Resources/migrations/Version20181128074035.php
  bundles/CoreBundle/Resources/migrations/Version20190527121800.php
  bundles/CoreBundle/Resources/migrations/Version20191230104529.php
Labels: Task

#5544 [PHPSTAN] Fix GeneratorBundle/InstallBundle PHP Docs
  bundles/GeneratorBundle/Command/Validators.php
  bundles/GeneratorBundle/Manipulator/ConfigurationManipulator.php
  bundles/GeneratorBundle/Model/Bundle.php
  bundles/InstallBundle/Installer.php
Labels: Task

#5545 [PHPSTAN] Upgrade to version ^0.12
  .travis/phpstan.s4.travis.neon
  .travis/phpstan.travis.neon
  bundles/AdminBundle/Controller/AdminController.php
  bundles/AdminBundle/Security/User/User.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Mpay24Seamless.php
  bundles/EcommerceFrameworkBundle/PriceSystem/LazyLoadingPriceInfo.php
  bundles/EcommerceFrameworkBundle/VoucherService/DefaultService.php
  composer.json
  lib/Document/Tag/NamingStrategy/Migration/Analyze/ElementTree.php
  lib/Migrations/Command/Traits/PimcoreMigrationsConfiguration.php
  lib/Placeholder.php
  lib/Templating/Helper/HeadLink.php
  lib/Tool/Transliteration.php
  lib/Translation/Translator.php
  models/Element/Service.php
  phpstan.neon
Labels: Task

#5549 [Workflows] Transition notification user / role should be optional
  bundles/CoreBundle/DependencyInjection/Configuration.php
  lib/Workflow/Notification/AbstractNotificationService.php
Labels: Bug

#5554 [Core] Generic Data Object Param Converter
  bundles/CoreBundle/Request/ParamConverter/DataObjectParamConverter.php
  bundles/CoreBundle/Resources/config/services.yml
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
Labels: New Feature

#5560 [PHPSTAN] Fix wrong classId type
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/Listing/Concrete.php
  models/GridConfigFavourite.php
Labels: Task

#5561 Fix deprecated (PHP 7.4) parameter order of implode()
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/NumberRangeSelection.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/NumberRangeSelection.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractWorker.php
Labels: Task

#5557 Updated testing docs
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/01_Application_Testing.md
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/README.md
  doc/Development_Documentation/img/travis_artifact.png
Labels: Task

#5556 Grid displayed empty if all attributes are assigned to operators #3978
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
Labels: Bug

#5555 Cleanup generator bundle
  bundles/GeneratorBundle/Command/BaseGenerateBundleCommand.php
  bundles/GeneratorBundle/Command/BaseGeneratorCommand.php
  bundles/GeneratorBundle/Command/GenerateBundleCommand.php
  bundles/GeneratorBundle/Command/Validators.php
  bundles/GeneratorBundle/Generator/BaseBundleGenerator.php
  bundles/GeneratorBundle/Generator/BundleGenerator.php
  bundles/GeneratorBundle/Generator/DoctrineCrudGenerator.php
  bundles/GeneratorBundle/Manipulator/RoutingManipulator.php
  bundles/GeneratorBundle/Resources/config/services.yml
Labels: Task

#5569 [Areabrick] Add some top padding
  bundles/AdminBundle/Resources/public/css/editmode.css
Labels: Improvement

#5571 [PHPSTAN] Fill empty php doc param types (Document)
  models/Document.php
  models/Document/Dao.php
  models/Document/DocType.php
  models/Document/DocType/Dao.php
  models/Document/Email.php
  models/Document/Hardlink.php
  models/Document/Hardlink/Service.php
  models/Document/Link.php
  models/Document/Listing.php
  models/Document/Listing/Dao.php
  models/Document/Page.php
  models/Document/PageSnippet.php
  models/Document/PageSnippet/Dao.php
  models/Document/PrintAbstract.php
  models/Document/Service.php
  models/Document/Service/Dao.php
  models/Document/Tag.php
  models/Document/Tag/Area/AbstractArea.php
  models/Document/Tag/Areablock.php
  models/Document/Tag/Block.php
  models/Document/Tag/Block/AbstractBlockItem.php
  models/Document/Tag/Block/Item.php
  models/Document/Tag/Checkbox.php
  models/Document/Tag/Date.php
  models/Document/Tag/Embed.php
  models/Document/Tag/Image.php
  models/Document/Tag/Input.php
  models/Document/Tag/Link.php
  models/Document/Tag/Multiselect.php
  models/Document/Tag/Numeric.php
  models/Document/Tag/Pdf.php
  models/Document/Tag/Relation.php
  models/Document/Tag/Relations.php
  models/Document/Tag/Renderlet.php
  models/Document/Tag/Scheduledblock.php
  models/Document/Tag/Select.php
  models/Document/Tag/Snippet.php
  models/Document/Tag/Table.php
  models/Document/Tag/TagInterface.php
  models/Document/Tag/Textarea.php
  models/Document/Tag/Video.php
  models/Document/Tag/Wysiwyg.php
  models/Document/Traits/ScheduledTasksTrait.php
Labels: Task

#5550 [Documents|Objects] Fix children and siblings result cache
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Model/Listing/AbstractListing.php
  models/DataObject/AbstractObject.php
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/Listing.php
  models/DataObject/Listing/Concrete.php
  models/Document.php
  models/Document/Dao.php
  tests/model/DataObject/ListingTest.php
  tests/model/DataObject/ObjectTest.php
  tests/model/Document/DocumentTest.php
Labels: Bug

#5558 [Workflows] add option to force a object layout after a transition or global action was performed
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitionPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitions.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md
  lib/Workflow/ActionsButtonService.php
  lib/Workflow/EventSubscriber/NotificationSubscriber.php
  lib/Workflow/GlobalAction.php
  lib/Workflow/Notes/NotesAwareTrait.php
  lib/Workflow/Transition.php
Labels: Approved, Improvement

#5576 Fix wrong objectbricks phpdoc type
  models/DataObject/ClassDefinition/Data/Objectbricks.php
Labels: Bug

#5439 Save applied pricing Rule ID in the order / OrderPriceModification Fieldcollection
  bundles/CoreBundle/Resources/migrations/Version20200113120101.php
  bundles/EcommerceFrameworkBundle/CartManager/CartPriceModificator/Discount.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/PriceSystem/ModificatedPrice.php
Labels: Improvement

#5211 [Object grid] Quantity value filter
  bundles/AdminBundle/Helper/GridHelperService.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/QuantityValue/DefaultConverter.php
Labels: Improvement

#5541 Add configuration for the initial_markings to replace the deprecated …
  bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md
Labels: Improvement

#5578 Object Preview doesn't work with relations
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/CoreBundle/EventListener/Frontend/ElementListener.php
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/02_Preview_Iframe.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/05_Preview.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/15_Link_Generator.md
  doc/Development_Documentation/img/classes-preview1.png
  doc/Development_Documentation/img/classes-preview2.png
  doc/Development_Documentation/img/linkgenerator1.png
  doc/Development_Documentation/img/linkgenerator2.png
  doc/Development_Documentation/img/linkgenerator2a.png
  doc/Development_Documentation/img/linkgenerator3.png
  doc/Development_Documentation/img/linkgenerator_class.png
  doc/Development_Documentation/img/linkgenerator_document.png
  models/DataObject/Service.php
  models/Element/Service.php
Labels: Bug

#5591 fix wrong file in voucher controller
  bundles/EcommerceFrameworkBundle/Controller/VoucherController.php
Labels: Bug

#5587 [Block] Localized fields inside Block cannot be updated via API
  models/DataObject/Localizedfield.php
Labels: Bug

#5592 Make the housekeeping maintenance task configurable
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/maintenance.yml
  lib/Maintenance/Tasks/HousekeepingTask.php
Labels: Improvement

#5590 respect error reporting in installer
  bin/pimcore-install
Labels: Bug

#5595 Only use active env to rebuild cache in system settings save action
  bundles/AdminBundle/Controller/Admin/SettingsController.php
Labels: Task

#5567 [Web2Print] Fix Notices: Undefined index, Save template errors in lastGenerateMessage
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  lib/Web2Print/Processor.php
  lib/Web2Print/Processor/PdfReactor8.php
  lib/Web2Print/Processor/WkHtmlToPdf.php
  models/Document/PrintAbstract.php
Labels: Task

#5596 [Admin] Clear cache functionality only for available Symfony environments
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  lib/Tool.php
Labels: Improvement

#5600 [Webservice] Add API key header option for REST
  bundles/AdminBundle/Security/Guard/WebserviceAuthenticator.php
  doc/Development_Documentation/24_Web_Services/README.md
Labels: Improvement, Task

#5597 [Translation] Fix pluralization
  lib/Translation/Translator.php
Labels: Bug

#5608 [Ecommerce][IndexService] Errorhandling: add subObjectId to error event
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
  lib/Event/Model/Ecommerce/IndexService/PreprocessErrorEvent.php
Labels: Improvement

#5598 AdminStyle for Documents and Assets #5147
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/EmailController.php
  bundles/AdminBundle/Controller/Admin/Document/FolderController.php
  bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
  bundles/AdminBundle/Controller/Admin/Document/LinkController.php
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/folder.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/hardlink.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/link.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/07_Custom_Icons.md
  doc/Development_Documentation/18_Tools_and_Features/02_Custom_Icons.md
  doc/Development_Documentation/img/asset-tree-custom-icon.png
  doc/Development_Documentation/img/classes-icons2.png
  doc/Development_Documentation/img/classes-icons3.png
  lib/Event/Admin/ElementAdminStyleEvent.php
  lib/Event/AdminEvents.php
  models/DataObject/AbstractObject.php
  models/Element/AdminStyle.php
  models/Element/AdminStyleTrait.php
  models/Element/Service.php
Labels: New Feature

#5537 Inheritance performance issue #4997 - Improve dirty detection
  models/DataObject/Localizedfield.php
Labels: Improvement

#5588 [Recycle Bin] Optimize relations serialization
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/ClassDefinition/Data/CustomRecyclingMarshalInterface.php
  models/Element/Recyclebin/Item.php
  models/Version.php
  models/Version/PimcoreClassDefinitionMatcher.php
  tests/model/Element/RecyclebinTest.php
Labels: Improvement

#5594 [Data Object] Default values should be also set to database on create
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/date.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/datetime.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/quantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/block.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/date.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/datetime.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/objectbricks.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
  models/DataObject/Traits/DefaultValueTrait.php
Labels: Improvement

#5619 Fix: AdminStyle throws PHP Error when having sites in project
  models/Element/AdminStyle.php
Labels: Bug

#5634 [Assets][Metadata] - Fix missing config for editmode
  bundles/AdminBundle/Controller/Admin/AssetController.php
Labels: Bug

#5622 [Documents][Editable Link] Merge admin & code configuration
  models/Document/Tag/Link.php
Labels: Bug

#5632 [DOCS] navigation
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/05_Blocks.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/10_Calculated_Value_Type.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/15_Classification_Store.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/20_Consent.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/25_Date_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/30_Dynamic_Select_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/35_Fieldcollections.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/40_Geographic_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/45_Image_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/50_Localized_Fields.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/55_Number_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/60_Object_Bricks.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/65_Others.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/70_Relation_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/75_Reverse_Many_To_Many_Object_Relation_Type.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/80_Select_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/85_Structured_Table.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/90_Table.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/95_Text_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/98_Video_Type.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/README.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/01_Dynamic_Text_Labels.md
  doc/Development_Documentation/06_Multi_Language_i18n/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/01_Filter_Classification_Store.md
  doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
  doc/Development_Documentation/26_Best_Practice/03_Object_Bricks_vs_Classification_Store.md
  doc/User_Documentation/13_Administration_of_Pimcore/01_Data_Protection_and_GDPR.md
Labels: Task

#5620 [Data objects] Open element when double-clicking relation item
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/abstractRelations.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseManyToManyObjectRelation.js
Labels: Improvement

#5642 Remove unused JavaScript code
  bundles/EcommerceFrameworkBundle/Resources/public/js/bundle.js
Labels: Task

#5643 Remove JavaScript function duplicates
  bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
Labels: Task

#4530 [Objects] Quantity value tooltip showing value in compatible units
  bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: Prio-Backlog

#5652 JavaScript: Fix condition
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tags/date.js
Labels: Bug

#5674 [Pimcore 5.8][Ecommerce] OnlineShopOrder class: change column length of field cartId to 190
  bundles/CoreBundle/Resources/migrations/Version20200124170034.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md
Labels: Improvement

#5669 [Web2Print] Add memory_limit config for pdf-creation command
  bundles/CoreBundle/Command/Web2PrintPdfCreationCommand.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#5672 [DOCS] PHPStan
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  doc/Samples/phpstan.local.neon
Labels: Task

#5666 [Asset] Fix: Video dimensions don't correct after new video version
  models/Asset/Video.php
Labels: Bug

#5675 [Scheduler] Check user permissions on task execution
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/EmailController.php
  bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
  bundles/AdminBundle/Controller/Admin/Document/LinkController.php
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
  bundles/AdminBundle/Controller/Traits/ApplySchedulerDataTrait.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/scheduler.js
  bundles/CoreBundle/Resources/migrations/Version20200127102432.php
  bundles/InstallBundle/Resources/install.sql
  lib/Maintenance/Tasks/ScheduledTasksTask.php
  models/Element/AbstractElement.php
  models/Schedule/Task.php
Labels: Bug

#5679 [Ecommerce] Log and display index update errors
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
Labels: Improvement

#5677 [PHPStan] more level 2 fixes
  models/DataObject/AbstractObject.php
  models/DataObject/Concrete.php
Labels: Task

#5291 [Asset] Add option to delete Image Features
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/asset/image.js
  bundles/CoreBundle/Resources/translations/en.json
  models/Asset/Image.php
Labels: Improvement

#5694 [Thumbnails] Reduce probability of missing LowQualityPlaceholders
  bundles/CoreBundle/Resources/config/maintenance.yml
  lib/Maintenance/Tasks/HousekeepingTask.php
  lib/Maintenance/Tasks/LowQualityImagePreviewTask.php
Labels: Improvement

#5663 [Tags] server side filtering
  bundles/AdminBundle/Controller/Admin/TagsController.php
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/tag/tree.js
  bundles/CoreBundle/Resources/migrations/Version20200129102132.php
  bundles/InstallBundle/Resources/install.sql
Labels: Bug

#5696 [DataObjects] Layout Component - Dynamic Text refactoring
  doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/01_Dynamic_Text_Labels.md
  doc/Development_Documentation/img/dynamic_textlabel_1.png
  doc/Development_Documentation/img/dynamic_textlabel_2.png
  models/DataObject/ClassDefinition/Helper/DynamicTextResolver.php
  models/DataObject/ClassDefinition/Layout/DynamicTextLabelInterface.php
  models/DataObject/ClassDefinition/Layout/Text.php
  models/DataObject/Service.php
Labels: Improvement

#5704 Fix error with Paypal Smart Button integration when using the Credit/Debit card payment option
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
Labels: Improvement

#5703 Remove calls to $fielddefinition->isRemoteOwner
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/ReverseManyToManyObjectRelation.php
Labels: BC-BREAK, Task
