Repository pimcore/pimcore, pull requests merged in 2020-02, with the labels that each got.

#5702 [Ecommerce] Back Office Ordering - fix price rule filter
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
Labels: Bug

#5658 [Data objects] Inheritance from "grandparents"
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Concrete.php
  tests/model/Inheritance/GeneralTest.php
Labels: BC-BREAK, Improvement

#5610 prevent invalid foreach argument if table has no rows
  models/DataObject/ClassDefinition/Data/Table.php
Labels: Pending

#5710 Deprecated Cookie Info Bar
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/EventListener/Frontend/CookiePolicyNoticeListener.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#5693 [Data Object] Custom URL-Slug for Data Objects
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Helper/GridHelperService.php
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/data.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/urlSlug.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Resources/config/services_routing.yml
  bundles/CoreBundle/Resources/migrations/Version20200121095650.php
  bundles/CoreBundle/Resources/translations/en.extended.json
  bundles/CoreBundle/Resources/translations/en.json
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/65_Others.md
  lib/Http/Request/Resolver/DocumentResolver.php
  lib/Routing/DataObjectRoute.php
  lib/Routing/Dynamic/DataObjectRouteHandler.php
  lib/Targeting/EventListener/DocumentTargetGroupListener.php
  models/DataObject/ClassDefinition/Dao.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/Concrete.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Data/UrlSlug.php
  models/DataObject/Fieldcollection/Dao.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Service.php
  models/DataObject/Traits/ContextPersistenceTrait.php
  models/Site/Dao.php
  tests/_support/Helper/DataType/TestDataHelper.php
  tests/_support/Helper/Model.php
  tests/_support/Test/DataType/AbstractDataTypeTestCase.php
Labels: New Feature

#5712 [Documents] Fix getChildren() for hardlink & hardlink wrapper
  models/Document.php
  models/Document/Hardlink.php
  models/Document/Hardlink/Wrapper.php
Labels: Bug

#5288 [Documents] Add required option for editables
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Resources/public/css/editmode.css
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/edit.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tag.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/textarea.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tags/wysiwyg.js
  bundles/CoreBundle/Resources/migrations/Version20200121131304.php
  bundles/CoreBundle/Resources/translations/en.json
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/03_Documents/01_Editables/16_Input.md
  doc/Development_Documentation/03_Documents/01_Editables/24_Numeric.md
  doc/Development_Documentation/03_Documents/01_Editables/36_Textarea.md
  doc/Development_Documentation/03_Documents/01_Editables/40_WYSIWYG.md
  models/Document/PageSnippet.php
Labels: Improvement

#5727 Use PDO MySQL Driver Option PDO::ATTR_EMULATE_PREPARES - Doctrine sho…
  bundles/CoreBundle/Resources/config/pimcore/default.yml
Labels: Task

#5728 [Asset] Image Thumbnails: use transparent 1x1 GIF as a fallback if no LQIP file exists, but lowQualityPlaceholder is set to true
  models/Asset/Image/Thumbnail.php
Labels: Task

#5665 [Assets] Metadata Grid - Add Tags filter #5162
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Helper/GridHelperService.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/gridTabAbstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridTabAbstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/tag/configuration.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/tag/tree.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
Labels: New Feature

#5729 Error when sorting product list with sub tenants
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultMysql.php
Labels: Bug

#5733 [Document|Data Object] consider latest version for copying elements
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
Labels: Bug

#5716 [Ecommerce][IndexService] add pre-send-data event in FilterDefinition Object
  bundles/EcommerceFrameworkBundle/Controller/IndexController.php
  lib/Event/Ecommerce/AdminEvents.php
Labels: Improvement

#5743 [PHPSTAN] Fix level 2 errors
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
  bundles/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php
  bundles/CoreBundle/EventListener/Frontend/GoogleSearchConsoleVerificationListener.php
  bundles/CoreBundle/EventListener/Frontend/GoogleTagManagerListener.php
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/Input.php
  bundles/InstallBundle/SystemConfig/ConfigWriter.php
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/50_Localized_Fields.md
  lib/Analytics/Google/Config/Config.php
  lib/Analytics/Google/Config/ConfigProvider.php
  lib/Analytics/Google/Tracker.php
  lib/Analytics/Piwik/Config/Config.php
  lib/Analytics/Piwik/Config/ConfigProvider.php
  lib/Config.php
  lib/Db/ZendCompatibility/QueryBuilder.php
  lib/Db/ZendCompatibility/QueryBuilder/PaginationAdapter.php
  lib/Document/Adapter.php
  lib/Google/Webmastertools.php
  lib/Model/DataObject/ClassDefinition/ClassLayoutDefinitionManager.php
  lib/Placeholder/DataObject.php
  lib/Routing/RedirectHandler.php
  lib/Web2Print/Processor.php
  lib/Web2Print/Processor/PdfReactor8.php
  lib/Web2Print/Processor/WkHtmlToPdf.php
  lib/Workflow/EventSubscriber/NotesSubscriber.php
  lib/Workflow/EventSubscriber/NotificationSubscriber.php
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/DataObject/Localizedfield.php
  models/Document.php
  models/Document/Service.php
Labels: Task

#5747 [Document] Navigation: Possibility to specify depth + introduced new param config based build() method
  doc/Development_Documentation/02_MVC/02_Template/00_Twig.md
  doc/Development_Documentation/03_Documents/03_Navigation.md
  lib/Navigation/Builder.php
  lib/Templating/Helper/Navigation.php
  lib/Twig/Extension/NavigationExtension.php
Labels: Improvement

#5750 [Ecommerce][Indexservice] Fix doPreIndexDataModification call
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
Labels: Bug

#5757 [Data Object] make relations caching layer the standard, remove option to disable it
  .travis.yml
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/CoreBundle/Resources/migrations/Version20200210101048.php
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/05_Cache_Raw_Relation_Data.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  doc/Development_Documentation/img/cache_raw_relation_data.png
  models/DataObject/AbstractObject.php
  models/DataObject/CacheRawRelationDataInterface.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Concrete.php
  models/DataObject/Traits/CacheRawRelationDataTrait.php
  models/Webservice/Data/ClassDefinition.php
  tests/_support/Resources/objects/lazyloading/class_LazyLoading_export.json
Labels: Improvement

#5762 [Versions] drop unused DB index binaryFileId on table versions
  bundles/CoreBundle/Resources/migrations/Version20200210164037.php
  bundles/InstallBundle/Resources/install.sql
Labels: Improvement

#5769 [DataObjects] Recheck indices on relations table
  bundles/CoreBundle/Resources/migrations/Version20200211115044.php
  models/DataObject/ClassDefinition/Dao.php
Labels: Improvement

#5638 [Data objects] Add listing filter methods for system fields
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/Listing.php
  models/DataObject/Listing/Concrete.php
Labels: Improvement

#5768 [XLIFF] Import - bypass element not found exceptions
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  lib/Translation/ImportDataExtractor/ImportDataExtractorInterface.php
  lib/Translation/ImportDataExtractor/Xliff12DataExtractor.php
Labels: Bug

#5760 [DataObject][CSV Import] Add option 'skip when existing' for imports with resolver strategy code #5579
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/configDialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/reportTab.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/import/resolverSettingsTab.js
  bundles/CoreBundle/Resources/translations/en.json
  doc/User_Documentation/05_DataObjects/02_CSV_Import/01_Resolver/04_GetByAttribute.md
  doc/User_Documentation/img/csvimport/filename_resolver.png
  doc/User_Documentation/img/csvimport/fullpath_resolver.png
  doc/User_Documentation/img/csvimport/getByAttribute_resolver.png
  lib/DataObject/Import/Resolver/Code.php
  lib/DataObject/Import/Resolver/Filename.php
  lib/DataObject/Import/Resolver/Fullpath.php
  lib/DataObject/Import/Resolver/GetBy.php
  lib/DataObject/Import/Resolver/Id.php
  lib/DataObject/Import/Resolver/ImportErrorException.php
  lib/DataObject/Import/Resolver/ImportWarningException.php
  models/DataObject/ClassDefinition/Helper/ImportClassResolver.php
  models/DataObject/ImportDataServiceInterface.php
Labels: Improvement

#5758 [Data Objects] Possibility to configure Interfaces on Class Definitio…
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/img/classes-class-inheritance.png
  lib/Tool.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
  models/Webservice/Data/ClassDefinition.php
Labels: Improvement

#5784 [Redirect] Performance & Usability Optimizations
  bundles/AdminBundle/Controller/Admin/RedirectsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
  bundles/CoreBundle/Resources/migrations/Version20200212130011.php
  bundles/CoreBundle/Resources/translations/en.json
  bundles/InstallBundle/Resources/install.sql
  lib/Routing/RedirectHandler.php
  models/Redirect.php
  models/Redirect/Dao.php
Labels: Improvement

#5777 [PHPStan] Fix level 2 errors
  .travis.yml
  .travis/run-stan.sh
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/EmailController.php
  bundles/AdminBundle/Controller/Admin/Document/FolderController.php
  bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
  bundles/AdminBundle/Controller/Admin/Document/LinkController.php
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/RenderletController.php
  bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/AdminBundle/Controller/Admin/MiscController.php
  composer.json
  lib/DataObject/Import/Service.php
  lib/Document/Adapter.php
  lib/Document/Adapter/Ghostscript.php
  lib/Model/AbstractModel.php
  lib/Model/ModelInterface.php
  lib/Tool.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
  lib/Translation/ImporterService/Importer/DataObjectImporter.php
  lib/Video/Adapter.php
  models/Asset.php
  models/DataObject/Data/UrlSlug.php
  models/DataObject/Fieldcollection.php
  models/Document.php
  models/Document/Hardlink/Service.php
  models/Document/Hardlink/Wrapper/WrapperInterface.php
  models/Document/Listing.php
  models/Document/Service.php
  models/Element/ElementInterface.php
Labels: Task

#5781 [Data Object] Objectbricks shouldn't extend from Field Collections #5774
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Definition.php
  models/DataObject/Traits/FieldcollectionObjectbrickDefinitionTrait.php
Labels: Task

#5786 [DataObjects] When renaming fieldname of object brick, brick tables a…
  bundles/CoreBundle/Resources/config/maintenance.yml
  lib/Maintenance/Tasks/CleanupBrickTablesTask.php
Labels: Bug

#5790 [PHPStan] Baseline feature
  .travis.yml
  .travis/run-stan.sh
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  lib/Cache/Pool/SymfonyAdapterProxy.php
  models/DataObject/Traits/FieldcollectionObjectbrickDefinitionTrait.php
  phpstan-baseline.neon
  phpstan.neon
Labels: Task

#5798 add objects prefix to non admin additional users_workspaces_object condition
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#5804 DeleteUnusedLocaleDataCommand: Fix wrong SHOW TABLES
  bundles/CoreBundle/Command/DeleteUnusedLocaleDataCommand.php
Labels: Bug

#5801 [Bug] (Reverse) ManyToManyRelation tables stuck in refresh loop #5644
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseManyToManyObjectRelation.js
Labels: Bug

#5805 VideoTag add more valid youtube params
  models/Document/Tag/Video.php
Labels: Improvement

#5803 [PHPStan] Fix level 2 errors
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/TagsController.php
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/Controller/Traits/ApplySchedulerDataTrait.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Heidelpay.php
  lib/Model/Listing/Dao/AbstractDao.php
  lib/Tool/Newsletter.php
  lib/Translation/ImporterService/Importer/DocumentImporter.php
  models/DataObject/AbstractObject.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/ClassDefinition/CustomLayout/Listing.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/CustomRecyclingMarshalInterface.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/Extension/ColumnType.php
  models/DataObject/ClassDefinition/Data/Extension/QueryColumnType.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Layout.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Classificationstore/Dao.php
  models/DataObject/Classificationstore/Service.php
  models/DataObject/Concrete.php
  models/DataObject/Fieldcollection.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Localizedfield.php
  models/DataObject/Service.php
  models/DataObject/Traits/FieldcollectionObjectbrickDefinitionTrait.php
  models/Document/Hardlink/Wrapper/WrapperInterface.php
  models/Element/ElementInterface.php
  models/Element/Service.php
  models/Translation/AbstractTranslation/Listing/Dao.php
  models/Webservice/Data/ClassDefinition.php
  phpstan-baseline.neon
  tests/_support/Helper/Model.php
Labels: Task

#5818 Documentation for full package Google Services - best practices
  doc/Development_Documentation/19_Development_Tools_and_Details/32_Google_Services_Integration.md
Labels: Task

#5823 [PHPStan] Fix errors
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Controller/Admin/WorkflowController.php
  bundles/AdminBundle/Controller/Reports/AnalyticsController.php
  lib/Cache/Pool/AbstractCacheItemPool.php
  lib/Cache/Pool/CacheItem.php
  lib/Cache/Pool/Redis.php
  lib/Log/ApplicationLogger.php
  models/Asset.php
  models/Asset/Image.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Classificationstore.php
  models/DataObject/Concrete.php
  models/Element/AbstractElement.php
  models/Element/ElementInterface.php
  models/Element/Recyclebin/Item.php
  models/Translation/AbstractTranslation/Listing.php
  models/Translation/AbstractTranslation/Listing/Dao.php
  models/Translation/Admin/Listing/Dao.php
  models/Translation/Website/Listing/Dao.php
  phpstan-baseline.neon
Labels: Task

#5836 [Data Object] Encrypted Field: Data shouldn't go into the search index
  models/DataObject/ClassDefinition/Data/EncryptedField.php
Labels: Bug

#5832 [Bundles] Add install migration to available migrations
  lib/Migrations/Configuration/Configuration.php
Labels: Improvement

#5812 [Core] Refactor System Configuration - Libraries
  lib/Analytics/Piwik/Api/SitesManager.php
  lib/Analytics/SiteId/SiteId.php
  lib/Google/Api.php
  lib/Http/ClientFactory.php
  lib/Image/Adapter/Imagick.php
  lib/Mail.php
  lib/Maintenance/Tasks/CheckErrorLogsDbTask.php
  lib/Maintenance/Tasks/LogArchiveTask.php
  lib/Maintenance/Tasks/LogMailMaintenanceTask.php
  lib/Maintenance/Tasks/VersionsCleanupTask.php
  lib/Routing/Dynamic/DocumentRouteHandler.php
  lib/Routing/Staticroute/Router.php
  lib/Tool.php
  lib/Tool/Console.php
  lib/Tool/Newsletter.php
Labels: Task

#5787 [Core] Refactor System Configuration - Models
  models/Asset.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/Concrete.php
  models/Document.php
  models/Document/PageSnippet.php
  models/Document/Service.php
  models/Document/Traits/RedirectHelperTrait.php
  models/Tool/UUID.php
  models/Translation/Admin.php
Labels: Task

#5838 Error when batch editing relationship column with path formatter #5820
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#5842 Fix HardlinkController setValuesToDocument function
  bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
Labels: Bug

#5817 [Data Object] Improved lazy loading
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/Concrete/Dao.php
Labels: Task

#5839 [Ecommerce][Productlist] Consider ElasticSearch reverse nested aggregations
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
Labels: Improvement

#5844 [Redirects] Filter by Test-URL
  bundles/AdminBundle/Controller/Admin/RedirectsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
  bundles/CoreBundle/Resources/translations/en.json
  lib/Routing/RedirectHandler.php
Labels: New Feature

#5845 removed dead code
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
Labels: Task

#5840 [Admin UI] mark ts() as deprecated
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#5849 [Users] Doctype: Return type for getBy*
  models/User/AbstractUser.php
Labels: Task

#5851 [Redirects] Improvements for Auto-Create when Document is moved
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Resources/migrations/Version20200218104052.php
  bundles/CoreBundle/Resources/translations/en.extended.json
  bundles/CoreBundle/Resources/translations/en.json
  bundles/InstallBundle/Resources/install.sql
  bundles/InstallBundle/SystemConfig/ConfigWriter.php
  lib/Config.php
  models/Document/Hardlink.php
  models/Document/Listing/Dao.php
  models/Document/Page.php
  models/Document/Traits/RedirectHelperTrait.php
  models/Redirect.php
  models/Redirect/Dao.php
Labels: Improvement, New Feature

#5854 [DataObjects] Quantity Value - fix conversion response if unit is invalid
  bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
Labels: Bug

#5822 [Grids] refactor params generation for export and batch jobs #5792
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
Labels: Bug

#5847 [Mail] Update docs
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  lib/Mail.php
Labels: Task

#5808 Filter stays active while changing classes #5802
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/variantsTab.js
Labels: Bug

#5850 [Data objects] unique index for field type "User"
  models/DataObject/ClassDefinition/Data/User.php
Labels: Improvement

#5858 Clean up data that is not really necessary for a clone
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/DataObject/Concrete.php
  models/Document.php
Labels: Task

#5878 [Core] System Config email settings
  bundles/AdminBundle/Controller/Admin/IndexController.php
  lib/Config.php
Labels: Bug

#5837 Asset|Document Listing getCount with Limit and Offset always returns 0
  lib/Model/Listing/AbstractListing.php
  models/Asset/Listing/Dao.php
  models/DataObject/Listing.php
  models/DataObject/Listing/Dao.php
  models/Document/Listing/Dao.php
  tests/model/Asset/ListingTest.php
  tests/model/DataObject/ListingTest.php
  tests/model/Document/ListingTest.php
Labels: Bug

#5883 [Document] editables: unset certain properties on clone
  models/Document/Tag.php
Labels: Bug

#5864 [Elements] get rid of of `userPermission` property and setter + code cleanup
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/EmailController.php
  bundles/AdminBundle/Controller/Admin/Document/FolderController.php
  bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
  bundles/AdminBundle/Controller/Admin/Document/LinkController.php
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
Labels: Task

#5856 [Data Object] Automatically create redirects for changed URL slugs
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/Data/UrlSlug.php
Labels: New Feature

#5873 [Data Object] Unique and Index option should be only available on data-types th…
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/data.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/user.js
  bundles/CoreBundle/Resources/translations/en.extended.json
Labels: Task

#5852 [DataObjects] Refactor multiple assignments check for Advanced relation types
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/Concrete.php
  models/Element/Service.php
Labels: Task

#5886 [Asset] WebP thumbnails with media-queries are not working for cropped images
  models/Asset/Image/Thumbnail.php
Labels: Bug

#5884 Check if redirect_to_maindomain is set to true
  bundles/CoreBundle/EventListener/Frontend/FrontendRoutingListener.php
Labels: Bug

#5889 [Core] System Config - fix pull page cache & UUID listener #5745
  .travis/app/config/system.yml
  bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
  bundles/CoreBundle/EventListener/UUIDListener.php
  models/Document/Service.php
Labels: Bug

#5867 [Document] "Create Page" dialog: title should be the first field, the rest should be pre-filled
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
Labels: Improvement

#5882 [Element] unify getQuery() method on listing DAOs
  models/Asset/Listing/Dao.php
  models/DataObject/Listing/Concrete/Dao.php
  models/DataObject/Listing/Dao.php
  models/Document/Listing/Dao.php
Labels: Task

#5910 [System-Config]: fix email settings detection
  bundles/AdminBundle/Controller/Admin/IndexController.php
Labels: Bug

#5912 Exceptions did not trigger an error message box
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#5917 Cache definition in Classification Store Service
  models/DataObject/Classificationstore/Service.php
Labels: Improvement
