Repository pimcore/pimcore, pull requests merged in 2020-12, with the labels that each got.

#7636 Removed PHP 7.3 support
  .travis.yml
  composer.json
Labels: Task

#7640 Areabrick names are not translated
  lib/Document/Editable/EditableHandler.php
Labels: Bug

#7624 PHPDoc: Missing returns
  bundles/EcommerceFrameworkBundle/VoucherService/Token/Listing.php
  doc/Development_Documentation/26_Best_Practice/70_Open_By-External_Id.md
  models/Asset/MetaData/ClassDefinition/Data/Data.php
  models/Asset/MetaData/ClassDefinition/Data/Date.php
  models/GridConfigFavourite/Listing.php
  models/GridConfigShare/Listing.php
  models/ImportConfigShare/Listing.php
Labels: Task

#7626 PHPDoc: Redundant var tags
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
  bundles/AdminBundle/Controller/Admin/PortalController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Controller/Admin/TargetingController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
  bundles/AdminBundle/GDPR/DataProvider/Assets.php
  bundles/CoreBundle/Command/RequirementsCheckCommand.php
  bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculator.php
  bundles/EcommerceFrameworkBundle/IndexService/IndexUpdateService.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/CatalogCategory.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
  bundles/InstallBundle/Installer.php
  lib/Config.php
  lib/Console/ConsoleCommandPluginTrait.php
  lib/Http/Context/PimcoreContextGuesser.php
  lib/Navigation/Container.php
  lib/Routing/Redirect/Csv.php
  lib/Sitemap/Document/DocumentTreeGenerator.php
  lib/Sitemap/Document/Filter/SiteRootFilter.php
  lib/Targeting/EventListener/FullPageCacheCookieCleanupListener.php
  lib/Targeting/Session/SessionConfigurator.php
  lib/Twig/Extension/Templating/PimcoreUrl.php
  lib/Workflow/Notification/AbstractNotificationService.php
  models/Asset/Service.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/Classificationstore/Dao.php
  models/DataObject/Fieldcollection/Definition/Dao.php
  models/DataObject/Objectbrick/Definition/Dao.php
  models/DataObject/QuantityValue/Unit.php
  models/User/AbstractUser.php
  tests/Model/Element/DependenciesTest.php
  tests/Model/Inheritance/GeneralTest.php
  tests/Model/Inheritance/LocalizedFieldTest.php
  tests/Model/Inheritance/ObjectbrickTest.php
  tests/Model/LazyLoading/ManyToManyRelationTest.php
  tests/_support/Helper/DataType/TestDataHelper.php
Labels: Task

#7612 Add a service CSRF protection and deprecate event listener methods
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Controller/AdminController.php
  bundles/AdminBundle/EventListener/CsrfProtectionListener.php
  bundles/AdminBundle/Resources/config/event_listeners.yml
  bundles/AdminBundle/Resources/config/security_services.yml
  bundles/AdminBundle/Security/CsrfProtectionHandler.php
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
Labels: Task

#7637 [Core] Implementation Loaders - Classmap loader takes priority over Prefix loader
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/09_Adding_Document_Editables.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#7629 Upgrade PHPUnit and codeception/phpunit-wrapper to latest version
  composer.json
  tests/Cache/Core/AbstractCoreHandlerTest.php
  tests/Ecommerce/DependencyInjection/Config/Processor/TenantProcessorTest.php
  tests/Ecommerce/PriceSystem/TaxCalculationTest.php
  tests/Ecommerce/Type/DecimalTest.php
  tests/Model/DataObject/ListingTest.php
  tests/Model/DataObject/ObjectTest.php
  tests/Model/DataType/BlockTest.php
  tests/Model/DataType/ClassificationStore/GeneralTest.php
  tests/Model/DataType/LocalizedFieldTest.php
  tests/Model/Element/DependenciesTest.php
  tests/Model/Element/RecyclebinTest.php
  tests/Model/Inheritance/GeneralTest.php
  tests/Model/Inheritance/LocalizedFieldTest.php
  tests/Model/Inheritance/ObjectbrickTest.php
  tests/Model/LazyLoading/AbstractLazyLoadingTest.php
  tests/Model/Relations/FieldcollectionTest.php
  tests/Model/Relations/MultipleAssigmentTest.php
  tests/Service/Element/VersionTest.php
  tests/Unit/Analytics/Code/CodeCollectorTest.php
  tests/Unit/Cache/RuntimeTest.php
  tests/Unit/Document/Tag/Block/BlockStateTest.php
  tests/Unit/HttpKernel/BundleCollection/BundleCollectionTest.php
  tests/Unit/HttpKernel/BundleCollection/LazyLoadedItemTest.php
  tests/Unit/HttpKernel/Response/CodeInjectorTest.php
  tests/Unit/Notification/Service/NotificationServiceTest.php
  tests/Unit/Tool/ConfigMergerTest.php
  tests/Unit/Tool/PlaceholderProcessorTest.php
  tests/_support/Test/ModelTestCase.php
  tests/_support/Test/TestCase.php
  tests/_support/Util/TestHelper.php
Labels: BC-BREAK

#7644 Replace html2text/html2text with soundasleep/html2text and removed deprecated methods from Mail
  composer.json
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  lib/Mail.php
Labels: BC-BREAK, Task

#7642 Model::getByName shouldn't catch any exceptions
  models/Asset/Image/Thumbnail/Config.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Video/Thumbnail/Config.php
  models/Asset/Video/Thumbnail/Config/Dao.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/ClassDefinition/Dao.php
  models/DataObject/Classificationstore/CollectionConfig.php
  models/DataObject/Classificationstore/CollectionConfig/Dao.php
  models/DataObject/Classificationstore/GroupConfig.php
  models/DataObject/Classificationstore/GroupConfig/Dao.php
  models/DataObject/Classificationstore/KeyConfig.php
  models/DataObject/Classificationstore/KeyConfig/Dao.php
  models/DataObject/Classificationstore/StoreConfig.php
  models/DataObject/Classificationstore/StoreConfig/Dao.php
  models/Metadata/Predefined.php
  models/Metadata/Predefined/Dao.php
  models/Staticroute.php
  models/Staticroute/Dao.php
  models/Tool/CustomReport/Config.php
  models/Tool/CustomReport/Config/Dao.php
  models/Tool/Targeting/Rule.php
  models/Tool/Targeting/Rule/Dao.php
  models/Tool/Targeting/TargetGroup.php
  models/Tool/Targeting/TargetGroup/Dao.php
  models/User/AbstractUser.php
  models/User/AbstractUser/Dao.php
  models/WebsiteSetting.php
  models/WebsiteSetting/Dao.php
Labels: BC-BREAK, Task

#7652 composer.json: removed doctrine/common requirement
  composer.json
Labels: BC-BREAK

#7643 Symfony 5.2 requirement
  composer.json
Labels: Task

#7653 Fixed wrong annotation
  models/DataObject/ClassDefinition/Data.php
Labels: Task

#7662 Webp deprecations
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Tool/Frontend.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: Task

#7661 [Asset] Thumbnails: <picture> tag should be the new default and use loading="lazy" by default
  bundles/CoreBundle/Command/ThumbnailsImageCommand.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
  doc/Development_Documentation/03_Documents/01_Editables/14_Image.md
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  lib/Templating/Renderer/IncludeRenderer.php
  lib/Tool/Frontend.php
  lib/Twig/Extension/CacheExtension.php
  models/Asset/Image/Thumbnail.php
  models/Asset/Image/Thumbnail/Config.php
  models/Asset/Image/Thumbnail/Processor.php
  models/Document/Editable/Image.php
  models/Document/Editable/Snippet.php
Labels: BC-BREAK, Improvement, Task

#7553 Make AbstractOrder/AbstractOrderItem methods abstract and add missing methods
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/Model/AbstractOrder.php
  bundles/EcommerceFrameworkBundle/Model/AbstractOrderItem.php
  bundles/EcommerceFrameworkBundle/Model/AbstractProduct.php
  bundles/EcommerceFrameworkBundle/Model/DefaultMockup.php
  bundles/EcommerceFrameworkBundle/OfferTool/AbstractOfferToolProduct.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPal.php
  phpstan-baseline.neon
Labels: BC-BREAK, Task

#7664 Cannot read property 'syncContent' of null
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/booleanSelect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/consent.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/date.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/datetime.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/externalImage.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopoint.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/imagegallery.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/inputQuantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/link.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/multiselect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/rgbaColor.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/structuredTable.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/table.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/time.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/video.js
Labels: Bug

#7658 Fix asset metadata conversion
  models/Asset.php
Labels: Bug

#7583 [Data Objects] Data-Types: remove getPhpdocType() BC layer
  bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelection.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Geo/AbstractGeo.php
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
  models/DataObject/ClassDefinition/Data/Geopolygon.php
  models/DataObject/ClassDefinition/Data/Geopolyline.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/Input.php
  models/DataObject/ClassDefinition/Data/InputQuantityValue.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/Slider.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/ClassDefinition/Data/Textarea.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/ClassDefinition/NullablePhpdocReturnTypeTrait.php
Labels: BC-BREAK, Task

#5625 [Ecommerce][FilterService] Improve extensibility of filter types
  bundles/EcommerceFrameworkBundle/FilterService/FilterService.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/AbstractFilterType.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/SelectCategory.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/SelectClassificationStoreAttributes.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/MultiSelect.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/MultiSelectRelation.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/NumberRange.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/NumberRangeSelection.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/SelectCategory.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/Findologic/SelectRelation.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/Input.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelect.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectCategory.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectFromMultiSelect.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/MultiSelectRelation.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/NumberRange.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/NumberRangeSelection.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/Select.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectCategory.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectFromMultiSelect.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/SelectRelation.php
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/02_Filter_Nested_Documents.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  phpstan-baseline.neon
Labels: BC-BREAK, Improvement, Prio-Backlog

#7133 Fixed object relation select values
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
Labels: Bug

#7615 [Navigation] Improve active trail fallback code
  lib/Navigation/Builder.php
Labels: Improvement

#7580 OwnerAwareFieldInterface: add setters and getters
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/InputQuantityValue.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/Data/BlockElement.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/OwnerAwareFieldInterface.php
  models/DataObject/Traits/OwnerAwareFieldTrait.php
Labels: BC-BREAK, Improvement

#7675 Deprecate pimcore.translations.case_insensitive
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/06_Multi_Language_i18n/04_Shared_Translations.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#7684 Add startup logic to installer
  bin/pimcore-install
Labels: Bug, Improvement

#7682 Removed pimcore.translations.case_insensitive support
  bundles/AdminBundle/Controller/Admin/MiscController.php
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  doc/Development_Documentation/06_Multi_Language_i18n/04_Shared_Translations.md
  lib/Translation/Translator.php
  models/Translation/AbstractTranslation/Dao.php
Labels: BC-BREAK, Task

#7686 [Ecommerce] Removed legacy scripts
  bundles/EcommerceFrameworkBundle/cli/license-updater.php
  bundles/EcommerceFrameworkBundle/cli/sampleIndexUpdater.php
  bundles/EcommerceFrameworkBundle/cli/sampleProcessPreparationQueueUpdater.php
  bundles/EcommerceFrameworkBundle/cli/sampleProcessUpdateIndexQueueUpdater.php
Labels: Task

#7694 Fix Ghostscript::getVersion()
  lib/Document/Adapter/Ghostscript.php
Labels: Bug

#7685 Asset Metadata not being displayed
  bundles/CoreBundle/Migrations/Version20201207132025.php
  models/Asset/Dao.php
Labels: Bug

#7687 [DataObject] Fix Cannot save object with RGBA color field inside classification-store
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/Classificationstore/Dao.php
Labels: Bug

#7736 Localized fields in bricks translation import bugfix
  lib/Translation/ImporterService/Importer/DataObjectImporter.php
Labels: Bug

#7745 [Admin UI] Fixed issue when running not in debug mode
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  lib/Twig/Extension/AdminExtension.php
Labels: Bug

#7705 [DataObject] Fix Cannot save object with RGBA color field inside classification-store
  models/DataObject/ClassDefinition/Data/RgbaColor.php
Labels: Bug

#7749 Localized field in Objectbrick breaks the context for all the following non-localized fields
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#7733 [DataObject] Fix HotspotImage modal window background issue with white transparent image
  bundles/AdminBundle/Resources/public/js/pimcore/element/tag/imagecropper.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/tag/imagehotspotmarkereditor.js
Labels: Bug

#7734 [Settings] Fulltext search in locale dropdown
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
Labels: Improvement

#7747 [Data Objects] Retry transaction when tables for newly added locale do not exist yet
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/editorSettings.js
  models/DataObject/AbstractObject.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Localizedfield/LanguageTableDoesNotExistException.php
Labels: Bug, Improvement

#7756 Revert "Fix batch edit null error"
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
Labels: Bug

#7759 Symfony Cache Tags
  lib/Cache/Core/CoreCacheHandler.php
Labels: Bug

#7757 [Ecommerce][Productindex][Elasticsearch] fix execution of process update index queue command with multiple tenants
  bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessUpdateIndexQueueCommand.php
Labels: Bug

#7755 [Data Objects] Version preview from session
  models/DataObject/Concrete.php
Labels: Bug

#7762 [UUID] Fix PhpDoc in Listing Dao
  models/Tool/UUID/Listing/Dao.php
Labels: Improvement

#7767 install cache on installation
  bundles/CoreBundle/Resources/config/cache.yml
  bundles/InstallBundle/Installer.php
  bundles/InstallBundle/Resources/config/services.yml
Labels: Improvement

#7769 [Assets] Fix "allowed memory size exhausted" error
  bundles/AdminBundle/Controller/Admin/AssetController.php
Labels: Improvement

#7674 Fix wrong QuantityValue PHPDocs
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/Data/AbstractQuantityValue.php
  models/DataObject/Data/InputQuantityValue.php
  models/DataObject/Data/QuantityValue.php
  phpstan-baseline.neon
Labels: Improvement

#7773 Revert "install cache on installation"
  bundles/CoreBundle/Resources/config/cache.yml
  bundles/InstallBundle/Installer.php
  bundles/InstallBundle/Resources/config/services.yml
Labels: Bug

#7774 Create cache table on install
  bundles/InstallBundle/Installer.php
Labels: Improvement

#7775 Fixed position of the Symfony toolbar icon in admin interface
  bundles/AdminBundle/Resources/public/css/admin.css
Labels: Bug

#7777 Fix date editable
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/date.js
  models/Document/Editable/Date.php
Labels: Bug

#7776 Allow to create editables in new `pimcore.document.editables` namespace
  bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
Labels: Bug

#7596 PaymentProvider Hobex : webhook support
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Hobex.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/Config/HobexConfig.php
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/11_Hobex.md
Labels: Improvement

#7706 Deep copy in Version::marshalData() corrupts in-memory Document object
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Document/PageSnippet.php
Labels: Bug

#7768 Fix Wrong High-Res Images when using specific Image Area
  models/Asset/Image/Thumbnail/Processor.php
Labels: Bug

#7751 [Templating] Fix setCharset error on helpers
  lib/Templating/Helper/HelperCharsetTrait.php
  lib/Twig/Extension/Templating/Action.php
  lib/Twig/Extension/Templating/Inc.php
  lib/Twig/Extension/Templating/Navigation.php
  lib/Twig/Extension/Templating/PimcoreUrl.php
  lib/Twig/Extension/Templating/Placeholder/AbstractExtension.php
Labels: Task

#7781 Drop migration_versions table on install
  bundles/InstallBundle/Resources/install.sql
Labels: Task

#7720 Boolean select preview
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/Concrete.php
Labels: Bug

#7758 [Data Objects] ManyToMany Relation Types should proper validate multiple assignments
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php
  tests/Model/Relations/MultipleAssigmentTest.php
Labels: BC-BREAK

#7792 [Ecommerce][Productindex][Elasticsearch] fix reindex mode locking
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
Labels: Bug

#7794 Update minimal supported browser versions for admin backend
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.php
Labels: Bug

#7795 [Newsletter] Fix to avoid updating creationDate for existing e-mail in subscribe
  lib/Tool/Newsletter.php
Labels: Bug

#7789 [Admin] Data Object - Validate required attributes for ObjectBrickGetter & FieldCollectionGetter
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/FieldCollectionGetter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/ObjectBrickGetter.js
Labels: Bug

#7799 Add ES7 Support
  bundles/EcommerceFrameworkBundle/IndexService/Config/ElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/DefaultElasticSearch7.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch6.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch7.php
  bundles/EcommerceFrameworkBundle/Resources/config/index_service_configs_workers.yml
  composer.json
  doc/Development_Documentation/10_E-Commerce_Framework/04_Configuration/01_PimcoreEcommerceFrameworkBundle_Configuration_Reference.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/03_Assortment_Tenant_Configuration.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/05_Data_Architecture_and_Indexing_Process.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/01_Configuration_Details.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/02_Synonyms.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/01_Filter_Classification_Store.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/02_Filter_Nested_Documents.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/03_Elastic_Search/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/README.md
Labels: Improvement

#7829 [Data Objects] user data-type: do not persist user data in class definition files
  models/DataObject/ClassDefinition/Data/User.php
Labels: Bug
