Repository pimcore/pimcore, pull requests merged in 2021-05, with the labels that each got.

#8970 fixed migration classname
  bundles/CoreBundle/Migrations/Version20210408153226.php
Labels: Bug

#8949 make Controller Reference Migrations directly with SQL
  bundles/CoreBundle/Command/Migration/ControllerReferenceMigrationCommand.php
Labels: Improvement

#8973 [PDFreactor] added conenctionSettings for cookie information of pdf reactor cloud service
  lib/Web2Print/Processor/PdfReactor.php
Labels: Bug

#8977 Bugfix mail
  lib/Helper/Mail.php
Labels: Bug

#8978 Removed legacy code from Cache\Runtime
  lib/Cache/Runtime.php
  lib/Document/Editable/Block/BlockStateStack.php
  tests/Unit/Cache/RuntimeTest.php
Labels: Task

#8979 [Pimcore X][ClassDefinition] quantityValue unit selection broken
  bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
Labels: Bug

#8980 [UI] Custom logo needs to be stored in Flysystem storage
  bundles/AdminBundle/Controller/Admin/SettingsController.php
Labels: Task

#8968 Ecommerce | Cart | order is lost when more than one items are added within one second
  bundles/CoreBundle/Migrations/Version20210430124911.php
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCartItem.php
  bundles/EcommerceFrameworkBundle/Tools/Installer.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: BC-BREAK, Improvement

#8791 [Ecommerce][PricingManager] Add ProductActionInterface to identify actions that modify product prices
  bundles/EcommerceFrameworkBundle/CartManager/CartPriceCalculator.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/CartActionInterface.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/CartDiscount.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/FreeShipping.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/Gift.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/GiftInterface.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/ProductActionInterface.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/ProductDiscount.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/ProductDiscountInterface.php
  bundles/EcommerceFrameworkBundle/PricingManager/ActionInterface.php
  bundles/EcommerceFrameworkBundle/PricingManager/Rule.php
  bundles/EcommerceFrameworkBundle/PricingManager/RuleInterface.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: BC-BREAK, Improvement

#8983 [Data object grid] Validate grid export form on submit
  bundles/AdminBundle/Resources/public/js/pimcore/asset/gridexport/csv.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#8906 Fix PHPStan level 4 errors
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
  bundles/AdminBundle/GDPR/DataProvider/Assets.php
  bundles/CoreBundle/Controller/PublicServicesController.php
  bundles/CoreBundle/DependencyInjection/Compiler/LongRunningHelperPass.php
  bundles/CoreBundle/DependencyInjection/Compiler/MonologPsrLogMessageProcessorPass.php
  bundles/CoreBundle/PimcoreCoreBundle.php
  bundles/EcommerceFrameworkBundle/PriceSystem/AttributePriceSystem.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/Gift.php
  composer.json
  lib/DataObject/GridColumnConfig/Operator/AbstractOperator.php
  lib/DataObject/GridColumnConfig/Operator/Factory/DefaultOperatorFactory.php
  lib/DataObject/GridColumnConfig/Operator/Factory/OperatorFactoryInterface.php
  lib/DataObject/GridColumnConfig/Operator/TranslateValue.php
  lib/DataObject/GridColumnConfig/Service.php
  lib/DataObject/GridColumnConfig/Value/DefaultValue.php
  lib/Google/Cse.php
  lib/HttpKernel/BundleCollection/BundleCollection.php
  lib/Image/Adapter.php
  lib/Image/Adapter/GD.php
  lib/Logger.php
  lib/Mail.php
  lib/Security/Encoder/EncoderFactory.php
  lib/Targeting/DataProvider/GeoIp.php
  lib/Targeting/EventListener/DocumentTargetGroupListener.php
  lib/Targeting/Storage/SessionStorage.php
  lib/Tool/Frontend.php
  lib/Tool/Session.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Extension/PositionSortTrait.php
  models/DataObject/Data/BlockElement.php
  models/Element/AbstractElement.php
  models/Element/Service.php
  models/Tool/CustomReport/Adapter/CustomReportAdapterInterface.php
  models/Tool/CustomReport/Adapter/Sql.php
  models/User.php
  phpstan-baseline.neon
  phpstan-parameters.neon
Labels: Improvement

#8981 [Maintenance] Remove duplicate maintenance job CheckErrorLogsDbTask
  bundles/CoreBundle/Resources/config/maintenance.yml
  lib/Maintenance/Tasks/CheckErrorLogsDbTask.php
Labels: Bug

#8997 Fixed property type definition
  models/Document/Editable/Snippet.php
Labels: Bug

#8998 [Documents] Translations can cause errors on document creation
  models/Document/PageSnippet.php
Labels: Bug

#9013 Revert "Bugfix for incorrect maxDepth comparison"
  lib/Navigation/Builder.php
Labels: Bug

#8990 Fix: NotificationService::sendToGroup() has unsafe role condition
  models/Notification/Service/NotificationService.php
Labels: Improvement

#9000 HeadlessChrome Processor: Fix EventDispatcher call
  lib/Web2Print/Processor/HeadlessChrome.php
Labels: Bug

#9014 Element\Service::getSafeCopyName() created deprecated alias and removed unnecessary argument
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset/Service.php
  models/DataObject/Service.php
  models/Document/Service.php
  models/Element/Service.php
Labels: Bug

#9016 [Mail] renamed setHtml/TextBody() back to the original name, deprecat…
  bundles/AdminBundle/Controller/Admin/EmailController.php
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Mail.php
  lib/Mail/Plugins/RedirectingPlugin.php
  lib/Maintenance/Tasks/LogMailMaintenanceTask.php
  lib/Tool/Newsletter.php
  lib/Workflow/Notification/NotificationEmailService.php
  tests/Unit/Mail/MailTest.php
Labels: Bug

#9018 Make AbstractCommand public
  lib/Console/AbstractCommand.php
Labels: Task

#9009 Fix: Assets Paths not working for Login Sreen Image after update to 6.9
  bundles/AdminBundle/Resources/views/Admin/Login/layout.html.php
Labels: Bug

#9012 Fix: Assets Paths not working for Login Sreen Image after update to Pimcore X
  bundles/AdminBundle/Resources/views/Admin/Login/layout.html.twig
Labels: Bug

#9011 Don't log cache logs into console
  bundles/CoreBundle/Resources/config/pimcore/dev.yml
Labels: Task

#9021 [DataObjects] Fix column type change for date fields
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
Labels: Bug

#9022 [Documents] Assigning folder to Renderlet does not work anymore
  models/Document/Editable/Renderlet.php
Labels: Bug

#9023 [Docs] Fix upgrade instructions
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
Labels: Bug

#9026 [Docs] Symfony 5 does only support 1 config file with symfony firewalls
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
Labels: Improvement

#9025 [DataObjects] Fix Display of ManyToOne relation broken
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
Labels: Bug

#9006 Xliff Import add a line break before and after the content of transla…
  lib/Translation/Escaper/Xliff12Escaper.php
Labels: Bug

#9036 Make AdminAuthenticationDoubleCheckListener additionally use the Pimcore context
  bundles/AdminBundle/EventListener/AdminAuthenticationDoubleCheckListener.php
Labels: Improvement

#9032 Get exclusive lock when writing files
  lib/File.php
Labels: Task

#9035 Update pimcore image gallery hotspots from database type text to longtext
  models/DataObject/ClassDefinition/Data/ImageGallery.php
Labels: Bug

#9034 [Workflows] Error when adding elements via CLI when workflow with supports strategy is active
  bundles/CoreBundle/Resources/config/services_workflow.yml
  lib/Workflow/ExpressionService.php
Labels: Bug

#7752 [Data objects] Fallback to first matching locale if requested language does not exist
  models/DataObject/Localizedfield.php
Labels: Improvement

#9038 [CustomViews] Do not load
  models/DataObject/Listing/Dao.php
  models/Element/Service.php
Labels: Bug

#9041 Fix: No thumbnail for PDF documents with ) sign again
  lib/Document/Adapter/Ghostscript.php
Labels: Bug

#9042 [DataObjects] fix multiselect in dataobject - javascript error item.getId is not a function
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/multiselect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/select.js
Labels: Bug

#9005 [WebDAV] Performance improvement
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/CoreBundle/Migrations/Version20210505093841.php
  bundles/InstallBundle/Resources/install.sql
  lib/Db/ConnectionInterface.php
Labels: Improvement

#9043 Fix: getText not work with ghostscript only
  lib/Document/Adapter/Ghostscript.php
Labels: Bug

#9046 Fix video editable undefined index warnings
  models/Document/Editable/Video.php
Labels: Bug

#9045 Show not found executables only in verbose and without complete stack trace
  lib/Document/Adapter/Ghostscript.php
  lib/Document/Adapter/LibreOffice.php
Labels: Bug

#9028 [Workflows] Fix object not unpublished with force_unpublished option
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Workflow/Manager.php
Labels: Bug

#9053 [EDITABLES] Fix wrong array key check
  bundles/AdminBundle/Controller/Admin/Document/RenderletController.php
Labels: Bug

#9056 [CI] Add PHP CS Fixer workflow
  .github/workflows/codeception.yml
  .github/workflows/docs.yml
  .github/workflows/php-cs-fixer.yml
  .github/workflows/static-analysis.yml
  .gitignore
Labels: Task

#9033 [DataObjects] Fix Advanced ManyToMany Relations field checkbox metadata column editor
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
Labels: Bug

#9060 [Document] Check if adding "document" and "editmode" as global Twig variables works
  bundles/CoreBundle/EventListener/Frontend/GlobalTemplateVariablesListener.php
Labels: Bug

#9071 Fixed PhpStan error in EmailController
  bundles/AdminBundle/Controller/Admin/EmailController.php
Labels: Task

#9068 [Workflows] Deprecated uasort usage
  lib/Workflow/Manager.php
Labels: Task

#9061 [ExtJS] Form Validation missing icon
  bundles/AdminBundle/Resources/public/extjs/css/PimcoreApp-all_1.css
Labels: Bug

#9069 [DOCS] Storage configuration: added some more information & explanations
  bundles/CoreBundle/Resources/config/pimcore/flysystem.yml
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/03_File_Storage_Setup.md
Labels: Task

#9075 [Ecommerce] Backoffice - fix Order listing page & voucher service
  bundles/EcommerceFrameworkBundle/Controller/VoucherController.php
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/list.html.twig
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php
Labels: Bug

#9062 [Glossary] Fix Processor xmlParseEntityRef: noname warning
  lib/Tool/Glossary/Processor.php
Labels: Bug

#9070 Also include yaml files in bundle config locator
  lib/Config/BundleConfigLocator.php
Labels: Improvement

#9077 Removed "symfony-" prefixed extra config support in composer.json
  composer.json
  lib/Composer.php
Labels: BC-BREAK, Task

#9082 [Data Object] Remove ObjectBrickGetter completely
  bundles/AdminBundle/Resources/config/export.yml
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/ObjectBrickGetter.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  doc/User_Documentation/05_DataObjects/01_Grid_Configuration_Operators/Extractors/ObjectBrickGetter.md
  doc/User_Documentation/img/gridconfig/operator_objectbrickgetter_sample.png
  doc/User_Documentation/img/gridconfig/operator_objectbrickgetter_symbol.png
Labels: Task

#9083 [EDITABLE] - Video - various fixes to make the video editable work
  models/Asset.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
  models/Document/Editable/Video.php
Labels: Bug

#9093 Fix XLSX Export - remove unnecessary setEnclosure call for default value
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#9099 Fix: Asset\Listing::getTotalCount() returns wrong count after update to 6.9
  lib/Model/Listing/Dao/QueryBuilderHelperTrait.php
Labels: Bug

#9097 [Admin] Cleanup deprecated pimcore_tag_ css
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/wysiwyg.js
Labels: Task

#9114 PHP 8 is not supported
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
Labels: Task

#9105 [Data Object] Fixed some warnings for video & image data-type
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/Video.php
Labels: Bug

#9110 Fix migration error when upgrading from 6.9.3 to 10.0
  bundles/CoreBundle/Migrations/Version20210324152821.php
  bundles/CoreBundle/Migrations/Version20210324152822.php
Labels: Bug

#9117 Use Symfony Lock Factory service for Parallelization trait
  lib/Console/Traits/Parallelization.php
Labels: Improvement

#9128 [Admin] System Settings - Fix display of zero values
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
Labels: Bug

#9118 [Commands] Parallelization trait - Add option to configure batch-size
  lib/Console/Traits/Parallelization.php
Labels: Improvement

#9049 Pass extra arguments to post-add/update events
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
Labels: Improvement

#8972 [Data Objects] introduce onContainerSaved method
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/DataContainerAwareInterface.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
  models/DataObject/Traits/ClassSavedTrait.php
Labels: Improvement

#9140 fix mail sender on GUI + enrich doc for email address format
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
  lib/Helper/Mail.php
Labels: Bug

#9139 fix mail doc to remove old deprecated methods
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
Labels: Bug

#9147 [Tags] Fix Tag::getElementsForTag undefined array key - resolves #9146
  models/Element/Tag/Dao.php
Labels: Bug

#9130 [Admin] Fix Custom Login Background Image is not saved
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
Labels: Bug

#9133 [Admin] Fix email settings check and documentation
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
  lib/Mail.php
Labels: Bug

#9151 [Docs] Fix E-Commerce Framework Configuration not working
  doc/Development_Documentation/10_E-Commerce_Framework/04_Configuration/01_PimcoreEcommerceFrameworkBundle_Configuration_Reference.md
Labels: Bug

#9152 [Web2print] Fix Headless Chrome adapter test
  lib/Web2Print/Processor/HeadlessChrome.php
Labels: Bug

#9161 [Class Definition] Fix Icons in Region or Panel cannot be saved
  models/DataObject/ClassDefinition/Layout/Traits/IconTrait.php
Labels: Bug

#9157 [ClassDefinition] Can not delete field if marked as unique inside localizedfields
  models/DataObject/ClassDefinition/Helper/Dao.php
  models/DataObject/Localizedfield/Dao.php
Labels: Bug

#9180 [Docs] Pimcore X - Update Create First Project
  doc/Development_Documentation/01_Getting_Started/06_Create_a_First_Project.md
  doc/Development_Documentation/img/Pimcore_Elements_check_homepage.png
  doc/Development_Documentation/img/Pimcore_Elements_homepage_edit_tab.png
  doc/Development_Documentation/img/Pimcore_Elements_homepage_settings.png
Labels: Task

#9186 Youtube Video Error (no query)
  models/Document/Editable/Video.php
Labels: Bug

#9148 [DataObject] Error Handling for wrong formatted value for date datatypes
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/date.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/datetime.js
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
Labels: Bug

#9182 Asset: fixed issue when data and filename changes in one transaction
  models/Asset.php
Labels: Bug

#9184 Fixes broken sorting in HTTP Errors view
  bundles/AdminBundle/Controller/Admin/MiscController.php
Labels: Bug

#9209 New Classificationstore groups added to variant is not visible
  models/DataObject/ClassDefinition/Data/Classificationstore.php
Labels: Bug

#9205 [Docs] Pimcore X - Update Routing & Custom Routes section
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/README.md
  doc/Development_Documentation/img/Routing_grid2.png
  doc/Development_Documentation/img/custom-routes.png
  doc/Development_Documentation/img/custom-routes2.png
Labels: Task

#9181 [Areablocks] Update manual mode example & docs
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
  doc/Development_Documentation/img/areablock_editmode1.png
  doc/Development_Documentation/img/areablock_editmode2.png
  doc/Development_Documentation/img/areablock_editmode3.png
  models/Document/Editable/Areablock.php
Labels: Bug, Improvement

#9183 [Documents] Fix Areablock manual mode
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
  models/Document/Editable/Areablock.php
Labels: Bug

#9214 Cannot edit / open target groups
  bundles/AdminBundle/Controller/Admin/TargetingController.php
Labels: Bug

#9188 fix: locales-all checking
  lib/Tool/Requirements.php
Labels: Bug

#9196 fix: chrome halt halfway on admin
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Bug

#9193 [Glossary] Fix content missing when wrapped in glossary tags
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  lib/Tool/Glossary/Processor.php
Labels: Bug

#9219 [Sitemaps] Revert public dir override, remove experimental notice in docs & drop 1.x support
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  composer.json
  doc/Development_Documentation/18_Tools_and_Features/39_Sitemaps.md
Labels: Bug, Improvement

#9225 [Document] Fixed nested block editables
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/block.js
  lib/Document/Editable/EditmodeEditableDefinitionCollector.php
Labels: Bug

#9224 [WebDAV] Fix child paths
  models/Asset/WebDAV/Folder.php
Labels: Bug

#9159 [Data Objects] Fix loading lazy loaded localized fields on save versio…
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/Localizedfield.php
Labels: Bug

#9230 [Assets] Do not override filename in version data
  models/Asset.php
  models/Element/Service.php
Labels: Bug

#9228 [DataObject] LocalizedField nested in Block causes error when containing data
  models/DataObject/Localizedfield.php
Labels: Bug

#9137 [Commands][Thumbnails] Make batch-size configurable
  bundles/CoreBundle/Command/ThumbnailsImageCommand.php
  bundles/CoreBundle/Command/ThumbnailsVideoCommand.php
Labels: Improvement

#9234 fix(assets): use Flysystem for size determination
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
Labels: Bug

#9236 [Admin UI] Fixed grids stripe rows styling
  bundles/AdminBundle/Resources/public/css/ext-modifications.css
Labels: Bug

#9241 [Custom Reports] Do not make adpater classes final
  models/Tool/CustomReport/Adapter/Analytics.php
  models/Tool/CustomReport/Adapter/Sql.php
Labels: Task

#9239 [Documents] Table Editable - do not allow columns to be draggable
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/table.js
Labels: Bug

#9235 update upgrade Notes
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
Labels: Improvement

#9192 Less aggressive stripping of backend data during indexing
  models/Search/Backend/Data.php
Labels: Improvement

#9220 [Data objects] Disable mouse wheel scrolling for numeric, quantity value fields
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
Labels: Improvement

#9254 Fix missing service monolog processor psr log message 10.0
  bundles/CoreBundle/DependencyInjection/Compiler/MonologPsrLogMessageProcessorPass.php
  bundles/CoreBundle/PimcoreCoreBundle.php
Labels: Bug

#9259 Update DefaultElasticSearch6.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch6.php
Labels: Bug

#9244 Remove redundant entry
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/README.md
Labels: Improvement

#9261 [QuickSearch] refix shorten path in quick-search
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
Labels: Bug

#9262 [InstallBundle] InstallKernel improvements
  bundles/InstallBundle/InstallerKernel.php
  doc/Development_Documentation/01_Getting_Started/01_Advanced_Installation_Topics.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#9227 [Cache] Performance improvements
  lib/Cache/Core/CoreCacheHandler.php
  tests/Cache/Core/AbstractCoreHandlerTest.php
Labels: Improvement

#9257 [Core] unmark internals
  bundles/EcommerceFrameworkBundle/Tools/SessionConfigurator.php
  models/Document/Hardlink/Service.php
  models/Element/Service.php
Labels: Task
