Repository pimcore/pimcore, pull requests merged in 2021-12, with the labels that each got.

#10927 [Tests] PHP 8.1: Remove league/csv:9.x-dev requirement
  .github/workflows/static-analysis.yml
Labels: Task

#10945 CustomReportController: Send HTTP Status 404 if report configs not found
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
Labels: Bug

#10920 Bug fix: Fixed faulty classification store active groups filtering
  bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/previewVersion.html.twig
  bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/object.html.twig
Labels: Bug

#10956 [Documents] Video Editable - Add setter for type & poster properties and update docs
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/98_Video_Type.md
  models/Document/Editable/Video.php
Labels: Improvement

#10928 [Messenger] fix queue names for messenger transports
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Bug

#10929 [Messenger] Create custom messenger bus for pimcore core
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/CoreBundle/DependencyInjection/Compiler/MessageBusPublicPass.php
  bundles/CoreBundle/EventListener/SearchBackendListener.php
  bundles/CoreBundle/Resources/config/maintenance.yaml
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  lib/Maintenance/Executor.php
  lib/Web2Print/Processor.php
  models/Asset.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Video/Thumbnail/Config/Dao.php
  models/Asset/Video/Thumbnail/Processor.php
  models/DataObject/Concrete.php
  models/Dependency/Dao.php
  models/Document/PageSnippet.php
Labels: Bug

#10963 ClientFactory: Fix proxy uri
  lib/Http/ClientFactory.php
Labels: Bug

#10962 No edit button for empty EditableDialogBoxConfiguration
  models/Document/Editable/Areablock.php
Labels: Bug

#10968 [DataObject] Classification store - Fix filter by empty name "Undefined property stdclass
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
Labels: Bug

#10988 [sabre\dav] Add to conflicts 4.2.2 to avoid BC break
  composer.json
Labels: Task

#10989 [Admin UI] Escape query on Search Window
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
Labels: Task

#10987 [Admin] Logout action should use POST method
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  bundles/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.twig
Labels: Task

#10946 Fix set stream for asset model
  models/Asset.php
Labels: Bug

#10950 fixes #10949: Objectbrick::getLocalizedTableName() returns wrong value
  models/DataObject/Objectbrick/Definition.php
  models/DataObject/Objectbrick/Definition/Dao.php
Labels: Bug

#10894 fixes #10893: Tabpanel allows to set tabPosition to null, but throws …
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/localizedfields.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/tabpanel.js
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Layout/Tabpanel.php
Labels: Bug

#10991 [Admin UI] DataObject Class - escape general settings input values
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
Labels: Task

#10965 Fix PhpDoc: Listing::current() can be false
  bundles/EcommerceFrameworkBundle/CartManager/Cart/Listing.php
  bundles/EcommerceFrameworkBundle/CartManager/CartCheckoutData/Listing.php
  bundles/EcommerceFrameworkBundle/CartManager/CartItem/Listing.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderListInterface.php
  bundles/EcommerceFrameworkBundle/PricingManager/Rule/Listing.php
  bundles/EcommerceFrameworkBundle/VoucherService/Token/Listing.php
  models/Asset/Listing.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/CustomLayout/Listing.php
  models/DataObject/ClassDefinition/Listing.php
  models/DataObject/Classificationstore/CollectionConfig/Listing.php
  models/DataObject/Classificationstore/CollectionGroupRelation/Listing.php
  models/DataObject/Classificationstore/GroupConfig/Listing.php
  models/DataObject/Classificationstore/KeyConfig/Listing.php
  models/DataObject/Classificationstore/KeyGroupRelation/Listing.php
  models/DataObject/Classificationstore/StoreConfig/Listing.php
  models/DataObject/Listing.php
  models/DataObject/Listing/Concrete.php
  models/DataObject/QuantityValue/Unit/Listing.php
  models/Document/Listing.php
  models/Element/Note/Listing.php
  models/Element/Recyclebin/Item/Listing.php
  models/Element/Tag/Listing.php
  models/Element/WorkflowState/Listing.php
  models/Glossary/Listing.php
  models/GridConfig/Listing.php
  models/GridConfigFavourite/Listing.php
  models/GridConfigShare/Listing.php
  models/Redirect/Listing.php
  models/Schedule/Task/Listing.php
  models/Search/Backend/Data/Listing.php
  models/Site/Listing.php
  models/Tool/Email/Blacklist/Listing.php
  models/Tool/Email/Log/Listing.php
  models/Tool/Targeting/Rule/Listing.php
  models/Tool/Targeting/TargetGroup/Listing.php
  models/Translation/Listing.php
  models/User/Listing/AbstractListing.php
  models/User/Permission/Definition/Listing.php
  models/Version/Listing.php
Labels: Improvement

#10992 Hide empty groups in the areablock menu
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
Labels: Bug

#11003 [DOC] Official documentation corrections for Routing and URLs
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/README.md
Labels: Bug

#10993 Add index to application_logs.maintenanceChecked
  bundles/CoreBundle/Migrations/Version20211209131141.php
  bundles/InstallBundle/Resources/install.sql
  lib/Maintenance/Tasks/LogMailMaintenanceTask.php
Labels: Improvement

#10909 [Symfony] Session - do not use deprecated features
  bundles/AdminBundle/Session/Handler/AdminSessionHandler.php
  bundles/CoreBundle/Resources/config/services.yaml
  bundles/EcommerceFrameworkBundle/CartManager/SessionCart.php
  bundles/EcommerceFrameworkBundle/EventListener/Frontend/TrackingCodeFlashMessageListener.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
  bundles/EcommerceFrameworkBundle/SessionEnvironment.php
  bundles/EcommerceFrameworkBundle/Tools/SessionConfigurator.php
  composer.json
  doc/Development_Documentation/10_E-Commerce_Framework/13_Checkout_Manager/07_Integrating_Payment.md
  doc/Development_Documentation/19_Development_Tools_and_Details/35_Working_with_Sessions.md
  lib/Targeting/Session/SessionConfigurator.php
  lib/Targeting/Storage/SessionStorage.php
  tests/Model/Document/DocumentTest.php
  tests/_support/Test/ModelTestCase.php
Labels: Improvement

#11018 Don't return Document from runtime cache when `$force` parameter is true in `Document::getByPath()`
  models/Document.php
Labels: Bug

#10846 [Symfony 6] Return type preparations
  bundles/AdminBundle/Controller/AdminController.php
  bundles/AdminBundle/DependencyInjection/Configuration.php
  bundles/AdminBundle/HttpFoundation/JsonResponse.php
  bundles/AdminBundle/Security/User/User.php
  bundles/AdminBundle/Serializer/Normalizer/ReferenceLoopNormalizer.php
  bundles/AdminBundle/Translation/AdminUserTranslator.php
  bundles/CoreBundle/DataCollector/PimcoreDataCollector.php
  bundles/CoreBundle/DataCollector/PimcoreTargetingDataCollector.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Request/ParamConverter/DataObjectParamConverter.php
  bundles/EcommerceFrameworkBundle/Controller/VoucherController.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Console/ConsoleOutputDecorator.php
  lib/Controller/ArgumentValueResolver/DocumentValueResolver.php
  lib/Controller/ArgumentValueResolver/EditmodeValueResolver.php
  lib/Controller/ArgumentValueResolver/WebsiteConfigValueResolver.php
  lib/Controller/Controller.php
  lib/Controller/FrontendController.php
  lib/Db/PimcoreExtensionsTrait.php
  lib/HttpKernel/CacheWarmer/MkdirCacheWarmer.php
  lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php
  lib/Routing/DataObjectRoute.php
  lib/Routing/DocumentRoute.php
  lib/Routing/DynamicRouteProvider.php
  lib/Routing/Element/Router.php
  lib/Routing/Loader/BundleRoutingLoader.php
  lib/Routing/Staticroute/Router.php
  lib/Templating/TwigDefaultDelegatingEngine.php
  lib/Test/KernelTestCase.php
  lib/Test/WebTestCase.php
  lib/Translation/Translator.php
  lib/Twig/Extension/AdminExtension.php
  lib/Twig/Extension/DataObjectHelperExtensions.php
  lib/Twig/Extension/DocumentEditableExtension.php
  lib/Twig/Extension/DumpExtension.php
  lib/Twig/Extension/HelpersExtension.php
  lib/Twig/Extension/PimcoreObjectExtension.php
  lib/Twig/Extension/PimcoreToolExtension.php
  lib/Twig/Extension/SubrequestExtension.php
  lib/Twig/Extension/WebsiteConfigExtension.php
  lib/Workflow/Dumper/GraphvizDumper.php
  lib/Workflow/Dumper/StateMachineGraphvizDumper.php
  lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php
  lib/Workflow/MarkingStore/StateTableMarkingStore.php
Labels: Task

#11034 [Symfony 6] Fix return value of normalizer
  bundles/AdminBundle/Serializer/Normalizer/ReferenceLoopNormalizer.php
  lib/Tool/Serialize.php
Labels: Bug

#10588 Fix xliff export
  lib/Translation/Escaper/Xliff12Escaper.php
  lib/Translation/ExportService/Exporter/Xliff12Exporter.php
Labels: Improvement

#11023 [Documents] Move page preview generation to message queue
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  bundles/CoreBundle/Resources/config/message_handler.yaml
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  bundles/CoreBundle/Resources/translations/en.extended.json
  lib/Messenger/GeneratePagePreviewMessage.php
  lib/Messenger/Handler/GeneratePagePreviewHandler.php
Labels: Improvement

#11033 Bugfix: add UTF-8 support to Input regex validation
  models/DataObject/ClassDefinition/Data/Input.php
Labels: Bug

#11041 Revert Changes from #10909 - Session service injection
  bundles/AdminBundle/Session/Handler/AdminSessionHandler.php
  bundles/EcommerceFrameworkBundle/CartManager/SessionCart.php
  bundles/EcommerceFrameworkBundle/EventListener/Frontend/TrackingCodeFlashMessageListener.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
  bundles/EcommerceFrameworkBundle/SessionEnvironment.php
  doc/Development_Documentation/10_E-Commerce_Framework/13_Checkout_Manager/07_Integrating_Payment.md
  tests/Model/Document/DocumentTest.php
  tests/_support/Test/ModelTestCase.php
Labels: Task

#10938 Support link generator for mockup objects
  bundles/EcommerceFrameworkBundle/Model/DefaultMockup.php
  bundles/EcommerceFrameworkBundle/Model/LinkGeneratorAwareInterface.php
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/30_Link_Generator.md
  lib/Twig/Extension/Templating/PimcoreUrl.php
  models/DataObject/ClassDefinition/LinkGeneratorInterface.php
Labels: Improvement

#11016 Remove Document from runtime path cache after it was deleted
  models/Document.php
  models/Document/Dao.php
Labels: Bug

#11026 Fix has children detection
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Traits/DocumentTreeConfigTrait.php
  models/Asset/Dao.php
  models/DataObject/AbstractObject/Dao.php
  models/Document/Dao.php
Labels: Bug

#11046 [Image Thumbnails] Fix system image thumbnails generation when no thumbnails are configured
  bundles/CoreBundle/Command/ThumbnailsImageCommand.php
Labels: Bug

#11056 fix: add UTF-8 support to javascript regex validation
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js
Labels: Bug

#11058 Add missing type check to the Document path cache
  models/Document.php
Labels: Bug

#11055 Class field rename save error
  models/DataObject/ClassDefinition/Service.php
Labels: Bug

#11064 Add option go generate avif thumbnails with pimcore:thumbnail:image command
  bundles/CoreBundle/Command/ThumbnailsImageCommand.php
Labels: Improvement

#11043 [Core] Check (and fix) Dao & Models for redundant data-setters
  models/Document/PageSnippet/Dao.php
  models/Element/Traits/VersionDaoTrait.php
Labels: Task

#11062 [Classification Store] Properly escape values on grids & titles
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers/generic-grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/collectionsPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/groupsPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/propertiesPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/storeTree.js
Labels: Bug

#10943 Do not initialize db schema in constructor.
  bundles/EcommerceFrameworkBundle/Tools/Installer.php
  lib/Db/ConnectionInterface.php
Labels: Bug

#11050 Pricing Rules - Saving pricing rule with date range condition leads to "setTime() on bool" error
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/DateRange.php
  bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js
Labels: Bug

#11061 [DataObjects] PCX update consider empty tables
  models/DataObject/ClassDefinition/Data/Table.php
Labels: Bug

#10964 Fix PHP 8.1 deprecations
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/OrderByFields.php
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/FilterService/ListHelper.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultMysql.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/Model/AbstractPaymentInformation.php
  bundles/EcommerceFrameworkBundle/OrderManager/AbstractOrderList.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderAgent.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/StartPaymentRequest/AbstractRequest.php
  bundles/EcommerceFrameworkBundle/VoucherService/Token/Listing.php
  doc/Development_Documentation/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  lib/Cache/Runtime.php
  lib/Config.php
  lib/Config/Config.php
  lib/DependencyInjection/CollectionServiceLocator.php
  lib/DependencyInjection/ServiceCollection.php
  lib/Document/Editable/Block/BlockName.php
  lib/Document/Editable/Block/BlockStateStack.php
  lib/Extension/Document/Areabrick/EditableDialogBoxConfiguration.php
  lib/Google/Cse.php
  lib/Model/Listing/AbstractListing.php
  lib/Navigation/Container.php
  lib/Targeting/Model/VisitorInfo.php
  lib/Tool/Requirements/Check.php
  lib/Twig/Extension/Templating/HeadLink.php
  lib/Twig/Extension/Templating/HeadMeta.php
  lib/Twig/Extension/Templating/HeadScript.php
  lib/Twig/Extension/Templating/HeadStyle.php
  lib/Twig/Extension/Templating/Placeholder/AbstractExtension.php
  models/Asset/Listing.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/Data/ImageGallery.php
  models/DataObject/Fieldcollection.php
  models/DataObject/Listing.php
  models/Document/Editable/Relations.php
  models/Document/Listing.php
  models/Element/Data/MarkerHotspotItem.php
  models/Tool/CustomReport/Config.php
Labels: Task

#11017 [Thumbnails] Support Asset Image for overlay transformations
  bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
  lib/Image/Adapter/Imagick.php
  models/Asset/Image/Thumbnail/Config.php
Labels: Improvement

#10979 [Translations] Merge Admin & Shared translations into single UI
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/admin.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/translationmerger.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/website.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  bundles/CoreBundle/Resources/translations/en.extended.json
  models/Translation.php
  models/Translation/Dao.php
  models/Translation/Listing/Dao.php
Labels: Improvement

#11048 Editable PDF: getElement() can be null
  models/Document/Editable/Pdf.php
Labels: Bug

#11072 [Assets] Metadata - Use foreign keys for ON DELETE
  bundles/CoreBundle/Migrations/Version20211221152344.php
  bundles/InstallBundle/Resources/install.sql
  models/Asset.php
  models/Asset/Dao.php
Labels: Improvement

#11103 [Imagick] Performance optimization when dealing with RGB color spaces
  lib/Image/Adapter/Imagick.php
Labels: Bug

#11101 Fix: document as pimcore_build_nav param not possible anymore
  lib/Twig/Extension/NavigationExtension.php
Labels: Bug

#11106 [Asset] Folder preview: do not skip if thumbnail for a child doesn't exist
  models/Asset/Folder.php
Labels: Bug

#11098 [Element] Performance optimization for getting cache tags of elements
  lib/Config.php
  lib/Tool/Text.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/Element/AbstractElement.php
  models/Element/Service.php
Labels: Improvement

#11083 [Admin] Search - Use globalmanager for element subtypes restrictions
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/selector.js
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Bug
