Repository pimcore/pimcore, pull requests merged in 2021-01, with the labels that each got.

#7847 Incompatibilities due to fixed Doctrine server_version
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/InstallBundle/Resources/install.sql
Labels: Bug

#7848 DB mapping types should be written by installer and not set in defaults
  .github/ci/files/config/packages/test/config.yaml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/InstallBundle/Installer.php
Labels: Task

#7849 Fix: new Process() only accepts array as first constructor argument
  lib/Composer.php
Labels: Task

#7851 Deprecated PartsBuilder
  bundles/InstallBundle/Installer.php
  lib/Cache/Symfony/CacheClearer.php
  lib/Process/PartsBuilder.php
  lib/Tool/AssetsInstaller.php
  tests/Unit/Process/PartsBuilderTest.php
Labels: Task

#7853 Removed PartsBuilder
  lib/Process/PartsBuilder.php
  tests/Unit/Process/PartsBuilderTest.php
Labels: BC-BREAK

#7805 [CustomReport] Fix mixed grid/drilldown filters in SQL Adapter
  models/Tool/CustomReport/Adapter/Sql.php
Labels: Bug

#7850 [DataObject][Custom Layouts] Missing layout components
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/layout.js
Labels: Improvement

#7862 Remove deprecated Bootstrap::boostrap method
  lib/Bootstrap.php
Labels: BC-BREAK

#7861 Remove deprecated Pimcore\Image\Optimizer::optimize method
  lib/Image/Optimizer.php
Labels: BC-BREAK

#7863 Remove deprecated Pimcore\Tool\StopWatch class
  lib/Tool/StopWatch.php
Labels: BC-BREAK

#7865 Remove DeepCopy BC layer
  models/DataObject/Data/BlockElement.php
  models/Element/DeepCopy/MarshalMatcher.php
  models/Element/DeepCopy/PimcoreClassDefinitionMatcher.php
  models/Element/DeepCopy/PimcoreClassDefinitionReplaceFilter.php
  models/Element/DeepCopy/UnmarshalMatcher.php
  models/Element/ElementDescriptor.php
  models/Version/ElementDescriptor.php
  models/Version/MarshalMatcher.php
  models/Version/PimcoreClassDefinitionMatcher.php
  models/Version/PimcoreClassDefinitionReplaceFilter.php
  models/Version/UnmarshalMatcher.php
Labels: BC-BREAK

#7868 Remove deprecated getElement() method on NotificationEvent and TranslationEvent
  lib/Event/Model/NotificationEvent.php
  lib/Event/Model/TranslationEvent.php
Labels: BC-BREAK

#7869 ocramius/package-versions: ^2.0
  composer.json
Labels: Task

#7860 Remove data type BC layer ('multihrefMetadata','objectsMetadata','objects','multihref','href','nonownerobjects')
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseManyToManyObjectRelation.js
  bundles/CoreBundle/Resources/translations/aliases.json
Labels: BC-BREAK

#7873 webmozarts/console-parallelization: ^1.2.0
  composer.json
Labels: Task

#7857 Add missing field pricingRuleId to field collection OrderPriceModification
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_OrderPriceModifications_export.json
Labels: Bug

#7876 Make all UserRole setters chainable
  models/User/UserRole.php
Labels: Task

#7874 Relations::setDataFromEditmode() doesn't reset elements array
  models/Document/Editable/Relations.php
Labels: Bug

#7879 Removed colon-in-path-workaround for imagemagick
  lib/Image/Adapter/Imagick.php
Labels: Task

#7667 Support Custom HTML in Workflow Notes
  bundles/AdminBundle/Controller/Admin/WorkflowController.php
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitionPanel.js
  bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md
  lib/Workflow/GlobalAction.php
  lib/Workflow/Manager.php
  lib/Workflow/Notes/AbstractCustomHtmlService.php
  lib/Workflow/Notes/CustomHtmlServiceInterface.php
  lib/Workflow/Notes/NotesAwareInterface.php
  lib/Workflow/Notes/NotesAwareTrait.php
Labels: Improvement

#7800 [Translations] Deprecated Translation\Website|Admin and Introduced new Translation model
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/CoreBundle/Migrations/Version20201222101114.php
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/19_Development_Tools_and_Details/05_Database_Model.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Event/Model/TranslationEvent.php
  lib/Model/Translation/AbstractTranslation.php
  models/Translation.php
  models/Translation/AbstractTranslation/Dao.php
  models/Translation/AbstractTranslation/Dao/DaoInterface.php
  models/Translation/AbstractTranslation/Listing.php
  models/Translation/AbstractTranslation/Listing/Dao.php
  models/Translation/AbstractTranslation/Listing/Dao/DaoInterface.php
  models/Translation/Admin.php
  models/Translation/Admin/Dao.php
  models/Translation/Admin/Listing.php
  models/Translation/Admin/Listing/Dao.php
  models/Translation/Dao.php
  models/Translation/Listing.php
  models/Translation/Listing/Dao.php
  models/Translation/TranslationInterface.php
  models/Translation/Website.php
  models/Translation/Website/Dao.php
  models/Translation/Website/Listing.php
  models/Translation/Website/Listing/Dao.php
Labels: Task

#7808 [Translations] Consolidate Translation models & remove deprecated classes
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/CoreBundle/Migrations/Version20201222101114.php
  bundles/EcommerceFrameworkBundle/Tools/Installer.php
  config/dao-classmap.php
  lib/Model/Translation/AbstractTranslation.php
  lib/Translation/Translator.php
  models/Translation.php
  models/Translation/AbstractTranslation/Dao.php
  models/Translation/AbstractTranslation/Dao/DaoInterface.php
  models/Translation/AbstractTranslation/Listing.php
  models/Translation/AbstractTranslation/Listing/Dao.php
  models/Translation/AbstractTranslation/Listing/Dao/DaoInterface.php
  models/Translation/Admin.php
  models/Translation/Admin/Dao.php
  models/Translation/Admin/Listing.php
  models/Translation/Admin/Listing/Dao.php
  models/Translation/Dao.php
  models/Translation/Listing.php
  models/Translation/Listing/Dao.php
  models/Translation/TranslationInterface.php
  models/Translation/Website.php
  models/Translation/Website/Dao.php
  models/Translation/Website/Listing.php
  models/Translation/Website/Listing/Dao.php
Labels: BC-BREAK, Task

#7898 Fix Notice: Undefined index: data
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/grid.js
Labels: Bug

#7900 Asset tree preview for folders: performance improvement + reduced amount of requests
  bundles/AdminBundle/Controller/Admin/AssetController.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  models/Asset/Folder.php
Labels: Improvement

#7877 GitHub Actions for 6.x branch
  .gitattributes
  .github/ci/files/.my.cnf
  .github/ci/files/app/AppKernel.php
  .github/ci/files/app/config/config.yml
  .github/ci/files/app/config/config_dev.yml
  .github/ci/files/app/config/config_test.yml
  .github/ci/files/app/config/parameters.example.yml
  .github/ci/files/app/config/routing.yml
  .github/ci/files/app/config/routing_dev.yml
  .github/ci/files/app/config/services.yml
  .github/ci/files/app/config/system.yml
  .github/ci/files/bin/console
  .github/ci/files/extensions.template.php
  .github/ci/files/phpstan-bootstrap.php
  .github/ci/files/phpstan.actions.neon
  .github/ci/files/phpstan.s4.actions.neon
  .github/ci/files/web/.htaccess
  .github/ci/files/web/app_test.php
  .github/ci/scripts/docs.sh
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/ci/scripts/setup-server.sh
  .github/ci/scripts/static-analysis.sh
  .github/server-config/apache-fpm.conf
  .github/workflows/codeception.yml
  .github/workflows/docs.yml
  .github/workflows/static-analysis.yml
  .travis.yml
  .travis/app/config/local/database.yml
  .travis/app/config/security.yml
  .travis/php-fpm.conf
  .travis/php.ini
  .travis/phpstan.s4.travis.neon
  .travis/phpstan.travis.neon
  .travis/run-docs.sh
  .travis/run-stan.sh
  .travis/run-tests.sh
  .travis/setup-db-server.sh
  .travis/setup-fpm.sh
  .travis/setup-functional-tests.sh
  .travis/setup-php.sh
  .travis/setup-sudo.sh
  .travis/setup-tests.sh
  README.md
  composer.json
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  doc/Samples/phpstan.local.neon
  phpstan.neon
Labels: Task

#7859 Remove Data::isEqual BC Layer
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/Localizedfield.php
  tests/_support/Helper/DataType/TestDataHelper.php
Labels: BC-BREAK, Task

#7143 Extends the configurability of custom views
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/20_Custom_Views.md
  lib/Config.php
  lib/Tool.php
Labels: Improvement

#7174 [ClassificationStore] Provide group and key models
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/15_Classification_Store.md
  models/DataObject/Classificationstore.php
  models/DataObject/Classificationstore/Group.php
  models/DataObject/Classificationstore/Key.php
Labels: Improvement

#7918 Update docs: Section on .env files
  doc/Development_Documentation/21_Deployment/03_Multi_Environment.md
Labels: Improvement

#7904 Remove operator from first condition
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/Bracket.php
Labels: Bug

#7817 Introduced support for Doctrine Query builder on listing classes
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/OrderManager/AbstractOrderList.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing/Filter/OrderDateTime.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing/Filter/OrderSearch.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing/Filter/ProductType.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderListInterface.php
  lib/Model/Listing/Dao/QueryBuilderHelperTrait.php
  models/Asset/Listing.php
  models/Asset/Listing/Dao.php
  models/DataObject/Listing/Concrete/Dao.php
  models/DataObject/Listing/Dao.php
Labels: New Feature

#7912 [Object bricks] Brick container class might contain removed brick types after unserializing
  models/DataObject/Objectbrick.php
Labels: Bug

#7927 Explicitly generate non-HDPI and HDPI system thumbnails
  bundles/CoreBundle/Command/ThumbnailsImageCommand.php
Labels: Improvement

#7943 Upgrade to scheb/2fa
  bundles/AdminBundle/EventListener/TwoFactorListener.php
  bundles/AdminBundle/Security/User/User.php
  bundles/CoreBundle/Resources/config/pimcore/two_factor_authentication.yml
  composer.json
Labels: BC-BREAK, Task

#7932 Follow up to #7817 - Doctrine Query Builder
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset/Listing/Dao.php
  models/DataObject/Listing/Dao.php
  models/Document/Listing/Dao.php
  models/Translation/Listing/Dao.php
Labels: Task

#7942 [DataObjects] Implement checkValidity for geo datatypes
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
  models/DataObject/ClassDefinition/Data/Geopolygon.php
  models/DataObject/ClassDefinition/Data/Geopolyline.php
Labels: BC-BREAK

#7928 Maintainance Task VersionCleanup: set default steps to 10
  lib/Maintenance/Tasks/VersionsCleanupTask.php
Labels: Bug

#7646 [Thumbnails] Throw exception if requested thumbnail definition does not exist
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Image/Thumbnail.php
  models/Asset/Video.php
  models/Asset/Video/ImageThumbnail.php
Labels: BC-BREAK, Task

#7935 wysiwyg.js and pimcore_disable_thumbnail
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/wysiwyg.js
Labels: Bug

#7913 Use KnpPaginatorBundle for listing pagination
  bundles/CoreBundle/Resources/config/paginator.yml
  bundles/CoreBundle/Resources/config/services.yml
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFactFinder.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/DefaultMysql.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ProductListInterface.php
  bundles/EcommerceFrameworkBundle/OrderManager/AbstractOrderList.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderListInterface.php
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/list.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/includes/paging.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/voucher_code_tab_pattern.html.twig
  bundles/EcommerceFrameworkBundle/VoucherService/Token/Listing.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php
  composer.json
  doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/07_Product_List.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/17_Order_Manager/01_Working_with_Order_Lists.md
  doc/Development_Documentation/10_E-Commerce_Framework/19_Tracking_Manager.md
  doc/Development_Documentation/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Google/Cse.php
  lib/Model/Paginator/EventSubscriber/PaginateListingSubscriber.php
  lib/Model/Paginator/PaginateListingInterface.php
  models/Asset/Listing.php
  models/DataObject/Listing.php
  models/Document/Listing.php
Labels: Improvement

#7954 Follow up to #7817 - Use onCreateQueryBuilder for Doctrine QB
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Helper/GridHelperService.php
  models/Asset/Listing.php
  models/DataObject/Listing.php
  models/Document/Listing.php
  models/Element/Service.php
  models/Translation/Listing.php
Labels: Task

#7953 [Assets] Show asset filesizes in UI when using stream wrappers + [WebDAV] Bugfix uploading new files + show assets without files
  models/Asset.php
  models/Asset/Service.php
  models/Asset/WebDAV/File.php
  models/Asset/WebDAV/Folder.php
Labels: Bug

#7952 Remove Laminas Packages
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php
  composer.json
  lib/Db/ZendCompatibility/QueryBuilder/PaginationAdapter.php
  lib/Model/Paginator/PaginateListingInterface.php
  models/Asset/Listing.php
  models/DataObject/Listing.php
  models/Document/Listing.php
Labels: BC-BREAK, Task

#7962 Many-To-Many Relation: Could not add Folder
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
Labels: Bug

#7972 Follow up: deprecated Zend Query Builder
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
  lib/Model/Listing/AbstractListing.php
  lib/Model/Listing/Dao/AbstractDao.php
  models/DataObject/Listing/Concrete/Dao.php
  models/DataObject/Listing/Dao.php
  models/Document/Listing/Dao.php
Labels: Task

#7971 Remove Zend Compatibility Query Builder
  bundles/EcommerceFrameworkBundle/OrderManager/AbstractOrderList.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing/Filter/OrderDateTime.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing/Filter/OrderSearch.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing/Filter/ProductType.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderListInterface.php
  doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
  doc/Development_Documentation/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  lib/Db/ConnectionInterface.php
  lib/Db/PimcoreExtensionsTrait.php
  lib/Db/ZendCompatibility/Expression.php
  lib/Db/ZendCompatibility/QueryBuilder.php
  lib/Db/ZendCompatibility/QueryBuilder/PaginationAdapter.php
  lib/Model/Listing/AbstractListing.php
  lib/Model/Listing/Dao/AbstractDao.php
  lib/Model/Listing/Dao/QueryBuilderHelperTrait.php
  lib/Model/Listing/JsonListing.php
  models/Asset/Listing/Dao.php
  models/DataObject/Listing.php
  models/DataObject/Listing/Concrete/Dao.php
  models/DataObject/Listing/Dao.php
  models/Document/Listing/Dao.php
  models/Element/Tag/Dao.php
  models/Translation/Listing/Dao.php
Labels: BC-BREAK, Task

#7977 [Docs] Bugfix docs about translation parameters
  doc/Development_Documentation/06_Multi_Language_i18n/04_Shared_Translations.md
Labels: Bug

#7981 [Versions] Show current database version for unpublished elements
  bundles/AdminBundle/Resources/public/js/pimcore/document/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: Improvement

#7988 [Ecommerce][Productindex][Elasticsearch] do not close index on index creation
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
Labels: Bug

#7990 Deprecate TemplatingHelperExtension
  bundles/CoreBundle/Resources/config/templating_twig.yml
  lib/Twig/Extension/CacheExtension.php
  lib/Twig/Extension/HeaderExtension.php
  lib/Twig/Extension/HelpersExtension.php
  lib/Twig/Extension/PimcoreToolExtension.php
  lib/Twig/Extension/TemplatingHelperExtension.php
Labels: Task

#7975 Added Locking to prevent generating same thumbnail in concurent requests
  models/Asset/Image/Thumbnail/Processor.php
Labels: Improvement

#7996 get correct path of documents from multiple sites in pimcore
  models/Document.php
Labels: Bug

#7985 InputQuantityValue does not persist any data anymore
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/Data/AbstractQuantityValue.php
Labels: Bug

#8004 Typehint wrong for IndexFieldSelection data type
  bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelection.php
Labels: Bug
