Repository pimcore/pimcore, pull requests merged in 2021-09, with the labels that each got.

#10207 [Admin] Dataobject - Fix save and close action
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
Labels: Bug

#10181 Update `.gitattributes` to save space and trees
  .gitattributes
Labels: Improvement

#10209 [Docs] Add Document: Implementing Product Information Management
  doc/Development_Documentation/26_Best_Practice/02_Implementing_Product_Information_Management.md
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture1.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture10.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture11.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture12.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture13.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture14.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture15.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture16.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture17.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture18.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture2.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture3.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture4.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture5.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture6.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture7.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture8.png
  doc/Development_Documentation/26_Best_Practice/img/pim_management/Picture9.png
Labels: Improvement

#10202 [Ecommerce] Fix Order list row count
  bundles/EcommerceFrameworkBundle/OrderManager/AbstractOrderList.php
Labels: Bug

#10150 Fix PhpDoc: getByField methods can return null
  .github/ci/files/var/classes/DataObject/FilterDefinition.php
  .github/ci/files/var/classes/DataObject/OnlineShopOrder.php
  .github/ci/files/var/classes/DataObject/OnlineShopOrderItem.php
  .github/ci/files/var/classes/DataObject/OnlineShopTaxClass.php
  .github/ci/files/var/classes/DataObject/OnlineShopVoucherSeries.php
  .github/ci/files/var/classes/DataObject/OnlineShopVoucherToken.php
  bundles/CoreBundle/Migrations/Version20210901130000.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/Objectbrick/Definition.php
Labels: Bug

#10130 [DataObjects] Fix Links in Blocks in Fieldcollections wrong after update to Pimcore X
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Link.php
Labels: Bug

#10147 [DataObject] Added isEmpty to QuanitiyValue data types
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Bug

#10216 [Grid Operator Required By] Use database index
  lib/DataObject/GridColumnConfig/Operator/RequiredBy.php
Labels: Bug

#10218 Fix Warning: Undefined array key "definitions"
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Video/Thumbnail/Config/Dao.php
  models/Tool/CustomReport/Config/Dao.php
Labels: Bug

#10167 [DataObjects][DataTypes] Clarify and eventually unify enrichFieldDefinition vs. enrichLayoutDefinition
  models/DataObject/ClassDefinition/Data/FieldDefinitionEnrichmentInterface.php
  models/DataObject/ClassDefinition/Data/LayoutDefinitionEnrichmentInterface.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/DynamicOptionsProvider/SelectionProviderTrait.php
Labels: Improvement

#10224 Fix Multiselect getVersionPreview array_map argument order
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug

#10163 Url slug route fix, Resolves #10005
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/EventListener/Frontend/ElementListener.php
  lib/Routing/Dynamic/DataObjectRouteHandler.php
  lib/Routing/Staticroute/Router.php
Labels: Improvement

#10243 Fixed gzcompressfile() - use gz*() functions instead of deflate_*() w…
  lib/helper-functions.php
Labels: Bug

#10250 [Select field] Throw exception when manually creating options with wrong parameter structure
  models/DataObject/ClassDefinition/Data/Select.php
Labels: Bug

#10256 [Cache] Fix Warning in edit mode when using pimcore_cache
  lib/Twig/Extension/CacheExtension.php
Labels: Bug

#10262 [Data Object] Data-Types: do not use `and` - use `&&` instead
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/ClassDefinition/Data/TargetGroup.php
Labels: Bug

#10263 [DataObject] Fixed ImageGallery mandatory check
  models/DataObject/ClassDefinition/Data/ImageGallery.php
Labels: Bug

#10264 Changed `and` to `&&` and `or` to `||`
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/GDPR/DataProvider/DataObjects.php
  bundles/CoreBundle/Command/SearchBackendReindexCommand.php
  bundles/CoreBundle/EventListener/SearchBackendListener.php
  lib/Model/Listing/Dao/AbstractDao.php
  lib/Navigation/Builder.php
  lib/Tool/Authentication.php
  models/Asset/Dao.php
  models/Asset/Folder.php
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Relations/AllowDocumentRelationTrait.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
  models/DataObject/ClassDefinition/Data/Slider.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/User.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
  models/DataObject/Service.php
  models/Document/Dao.php
  models/Document/Editable/Dao.php
  models/Document/Editable/Image.php
  models/Document/Editable/Renderlet.php
  models/Document/Editable/Video.php
  models/Document/Hardlink.php
  models/Document/Link.php
  models/Document/PageSnippet.php
  models/Element/Sanitycheck.php
  models/Translation.php
  models/User/UserRole/Folder.php
  models/Version.php
Labels: Bug

#10267 Update 05_Deployment_Tools.md
  doc/Development_Documentation/21_Deployment/05_Deployment_Tools.md
Labels: Improvement

#10270 improvement: remove advanced relation double click event
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
Labels: Improvement

#10268 [DataObject] Added mandatory check for ExternalImage data type
  models/DataObject/ClassDefinition/Data/ExternalImage.php
Labels: Bug

#10271 [Admin] Grids & lists: use loading=lazy on all <img> tags
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/js/pimcore/asset/folder.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/externalImage.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/imagegallery.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/video.js
Labels: Bug

#10241 [Translations] Fix fallback language not used in shared translations …
  lib/Translation/Translator.php
  tests/Unit/Translation/TranslatorTest.php
Labels: Bug

#10196 Configuration improvements - Web2Print
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/web2print.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
  lib/Config.php
  lib/Config/LocationAwareConfigRepository.php
  lib/Kernel.php
  lib/Web2Print/Config.php
  tests/_bootstrap.php
Labels: Improvement

#10274 Fixed autoincrement when no elements are in list
  lib/Model/Dao/AutoIncrementTrait.php
Labels: Bug

#10276 [Select field] Support stdclass in select options
  models/DataObject/ClassDefinition/Data/Select.php
Labels: Bug

#10240 Bugfix/order of export buttons
  bundles/AdminBundle/Resources/public/js/pimcore/asset/listfolder.js
Labels: Bug

#10281 Fix column filter
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Bug

#10269 Fixed bug - Relation in EditableDialogBox is cut off (#10247)
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/relation.js
Labels: Bug

#10277 [Cache] Do not return data from cache if disabled
  lib/Cache/Core/CoreCacheHandler.php
Labels: Bug

#10280 [DataObjects] Fix (Advanced)ManyToManyObjectRelation Create object via relation field, assigns duplicate entry
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
Labels: Bug

#10230 [Custom Reports] Filter on alias columns should work
  models/Tool/CustomReport/Adapter/Sql.php
Labels: Bug

#10288 Fix JS error in scheduledblock editable
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/block.js
Labels: Bug

#10265 [Classification Store] Add static getById methods
  models/DataObject/Classificationstore/CollectionGroupRelation.php
  models/DataObject/Classificationstore/CollectionGroupRelation/Dao.php
  models/DataObject/Classificationstore/KeyGroupRelation.php
Labels: Improvement

#10290 [DataObjects] Fix Table data type does not use the table config
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/table.js
Labels: Bug

#10282 [UI] Only generate @2x/hdpi previews
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Traits/DocumentTreeConfigTrait.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/asset.html.twig
  bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/document.html.twig
  bundles/CoreBundle/Command/ThumbnailsImageCommand.php
  models/Asset/Folder.php
  models/Asset/Image/Thumbnail/Config.php
  models/Document/Page.php
  models/Document/Service.php
Labels: Improvement

#10301 [Templating] Fix ActionRenderer to use params as request attributes -…
  lib/Templating/Renderer/ActionRenderer.php
Labels: Bug

#10299 [Data Object] CRM Consent-Type not visible because of CSS-Class
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/consent.js
  models/DataObject/ClassDefinition/Data/Consent.php
Labels: Bug

#10296 Sorter in initial sorting of classificationstore groups in collections not considered
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
Labels: Bug

#10326 Use Service::getElementType() and trigger deprecated warning
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/CoreBundle/EventListener/WorkflowManagementListener.php
  lib/Maintenance/Tasks/SanitizeElementsTask.php
  lib/Workflow/EventSubscriber/NotificationSubscriber.php
  lib/Workflow/MarkingStore/StateTableMarkingStore.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/Data/BlockElement.php
  models/DataObject/Data/ElementMetadata.php
  models/Document/Editable/Renderlet.php
  models/Element/AbstractElement.php
  models/Element/DeepCopy/MarshalMatcher.php
  models/Element/Note.php
  models/Element/Recyclebin/Item.php
  models/Element/Service.php
  models/Element/Traits/VersionDaoTrait.php
  models/Search/Backend/Data/Id.php
Labels: Improvement

#10325 Hotfix get options from provider
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug

#10293 UrlSlug table name constant and cache fix
  bundles/AdminBundle/Helper/GridHelperService.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/Concrete.php
  models/DataObject/Data/UrlSlug.php
Labels: Improvement

#10320 Fix Scheduled Tasks
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Controller/Admin/Document/HardlinkController.php
  bundles/AdminBundle/Controller/Admin/Document/LinkController.php
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/scheduler.js
  models/Asset.php
  models/Asset/Dao.php
  models/DataObject/Concrete.php
  models/DataObject/Concrete/Dao.php
  models/Document/Dao.php
  models/Document/Hardlink.php
  models/Document/Link.php
  models/Document/PageSnippet.php
  models/Element/Traits/ScheduledTasksDaoTrait.php
  models/Element/Traits/ScheduledTasksTrait.php
Labels: Bug

#10291 Use NotFoundException for all getById methods
  bundles/EcommerceFrameworkBundle/CartManager/Cart.php
  bundles/EcommerceFrameworkBundle/CartManager/Cart/Dao.php
  bundles/EcommerceFrameworkBundle/PricingManager/Rule.php
  bundles/EcommerceFrameworkBundle/PricingManager/Rule/Dao.php
  bundles/EcommerceFrameworkBundle/VoucherService/Statistic.php
  bundles/EcommerceFrameworkBundle/VoucherService/Statistic/Dao.php
  doc/Development_Documentation/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  models/DataObject/AbstractObject.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
  models/DataObject/Classificationstore/CollectionConfig.php
  models/DataObject/Classificationstore/CollectionConfig/Dao.php
  models/DataObject/Classificationstore/GroupConfig.php
  models/DataObject/Classificationstore/GroupConfig/Dao.php
  models/DataObject/Classificationstore/KeyConfig.php
  models/DataObject/Classificationstore/KeyConfig/Dao.php
  models/DataObject/Classificationstore/StoreConfig.php
  models/DataObject/Classificationstore/StoreConfig/Dao.php
  models/Element/Note.php
  models/Element/Note/Dao.php
  models/Element/Recyclebin/Item.php
  models/Element/Recyclebin/Item/Dao.php
  models/Element/Tag.php
  models/Element/Tag/Dao.php
  models/Glossary.php
  models/Glossary/Dao.php
  models/GridConfig.php
  models/GridConfig/Dao.php
  models/Metadata/Predefined.php
  models/Metadata/Predefined/Dao.php
  models/Notification.php
  models/Notification/Dao.php
  models/Property/Predefined.php
  models/Property/Predefined/Dao.php
  models/Redirect.php
  models/Redirect/Dao.php
  models/Schedule/Task.php
  models/Schedule/Task/Dao.php
  models/Site.php
  models/Site/Dao.php
  models/Staticroute.php
  models/Staticroute/Dao.php
  models/Tool/Targeting/Rule.php
  models/Tool/Targeting/Rule/Dao.php
  models/Tool/Targeting/TargetGroup.php
  models/Tool/Targeting/TargetGroup/Dao.php
  models/User/AbstractUser.php
  models/User/AbstractUser/Dao.php
  models/Version.php
  models/Version/Dao.php
  models/Workflow.php
  models/Workflow/Dao.php
Labels: Improvement

#10328 Configuration Improvements - add writeable checks #10180
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
  lib/Web2Print/Config.php
Labels: Improvement

#10336 Fix deprecations
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  models/Document/Hardlink/Wrapper/Link.php
  models/Document/Link.php
  tests/Model/Document/DocumentTest.php
Labels: Improvement

#10337 Fixed getMasterRequest() deprecations
  bundles/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
  bundles/CoreBundle/EventListener/Frontend/ElementListener.php
  bundles/CoreBundle/EventListener/WorkflowManagementListener.php
  lib/Config.php
  lib/Http/Request/Resolver/AbstractRequestResolver.php
  lib/Http/Request/Resolver/OutputTimestampResolver.php
  lib/Http/RequestHelper.php
  lib/Localization/LocaleService.php
  lib/Navigation/Builder.php
  lib/Routing/Element/Router.php
  lib/Targeting/Document/DocumentTargetingConfigurator.php
  lib/Tool.php
  lib/Tool/Glossary/Processor.php
  lib/Twig/Extension/Templating/PimcoreUrl.php
  models/Document.php
  models/Document/PageSnippet.php
Labels: Task

#10338 composer.json: bumped symfony/http-foundation to ^5.3.0
  composer.json
Labels: Task

#10356 Fixes Key/name labels on Properties
  bundles/AdminBundle/Resources/public/js/pimcore/element/properties.js
Labels: Bug

#10361 Assets: Clicking on image in preview grid does not open image
  bundles/AdminBundle/Resources/public/js/pimcore/asset/folder.js
Labels: Bug

#10351 Add checkbox to disable/enable to create new object in advanced many to many object relation
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyObjectRelation.js
Labels: Improvement

#10362 Fix for validation errors with subItems without context stack
  models/DataObject/Concrete.php
Labels: Bug

#10355 Make pimcore mail instantiation more robust
  lib/Mail.php
Labels: Bug

#10370 FIX vimeo and dailymotion video editables
  models/Document/Editable/Video.php
Labels: Bug

#10334 [Bug]: Search exception when data object with classification store data exists
  bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/previewVersion.html.twig
  bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/object.html.twig
Labels: Bug

#10376 Fix invisible field inside block element
  models/DataObject/ClassDefinition/Data/Block.php
Labels: Bug

#10379 [Maintenance] Delegate verbosity level to messenger:consume
  bundles/CoreBundle/Command/MaintenanceCommand.php
Labels: Task

#10381 [MessageBus] Fixed public service/alias compiler pass
  bundles/CoreBundle/DependencyInjection/Compiler/MessageBusPublicPass.php
  models/Asset/Video/Thumbnail/Processor.php
Labels: Bug

#10383 Use MessageBus for cleaning up image/video thumbnails
  bundles/CoreBundle/Resources/config/message_handler.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  lib/Messenger/CleanupThumbnailsMessage.php
  lib/Messenger/Handler/CleanupThumbnailsHandler.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Video/Thumbnail/Config/Dao.php
Labels: Improvement

#10292 Fix/Remove wrong PhpDocs
  .github/ci/files/var/classes/DataObject/OnlineShopOrder/PaymentProvider.php
  bundles/EcommerceFrameworkBundle/CartManager/MultiCartManager.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CheckoutManager.php
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/Controller/PricingController.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderListInterface.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderAgent.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/FreeShipping.php
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/Bracket.php
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/CatalogCategory.php
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/CatalogProduct.php
  bundles/EcommerceFrameworkBundle/PricingManager/PriceInfo.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
  bundles/EcommerceFrameworkBundle/PricingManager/Rule.php
  bundles/EcommerceFrameworkBundle/PricingManager/RuleInterface.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/AbstractTokenManager.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php
  lib/Security/Encoder/PasswordFieldEncoder.php
  lib/Security/Hasher/PasswordFieldHasher.php
  lib/Translation/ImporterService/Importer/DataObjectImporter.php
Labels: Improvement

#10388 Fix batch edit in grid when using object brick filter, resolves #10380
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
Labels: Bug

#10261 [Shared Translations] Show all languages for admin users
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/user/settings.js
  models/User.php
Labels: Improvement

#10394 Kernel: consider APP_CACHE_DIR in getCacheDir()
  lib/Kernel.php
Labels: Improvement

#10393 [Asset] Image thumbnails for updated images were not written to the storage
  models/Asset/Image/Thumbnail/Processor.php
Labels: Bug

#10404 [Configuration Improvements] click on checkbox shouldn't trigger any updates
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js
Labels: Bug

#10367 Fix Bug: Object Scheduled Tasks
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#10407 [Ecommerce] Fix install admin translation csv line ending to CRLF
  bundles/EcommerceFrameworkBundle/Resources/install/admin-translations/init.csv
Labels: Bug

#10378 [SentMails] Fix document reference in sent email logs
  lib/Helper/Mail.php
  lib/Mail.php
Labels: Bug

#10390 Use MessageBus for processing Asset updates (thumbnails, meta-data, ...)
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/CoreBundle/Resources/config/message_handler.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/InstallBundle/Installer.php
  lib/Maintenance/Tasks/AssetDocumentConversionTask.php
  lib/Messenger/AssetUpdateTasksMessage.php
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
  models/Asset.php
  models/Asset/Document.php
  models/Asset/Folder.php
  models/Asset/Image.php
  models/Asset/MetaData/EmbeddedMetaDataTrait.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
  models/Asset/Video.php
Labels: Improvement

#10425 Clean up maintenance services - remove AssetDocumentConversionTask
  bundles/CoreBundle/Resources/config/maintenance.yml
Labels: Bug

#10437 [Cache] Set cache.app to pimcore.cache.pool as default
  bundles/CoreBundle/DependencyInjection/Compiler/CacheFallbackPass.php
  bundles/CoreBundle/Resources/config/cache.yml
Labels: Improvement

#10423 Use Symfony Messenger for Search Backend Data
  bundles/CoreBundle/EventListener/SearchBackendListener.php
  bundles/CoreBundle/Resources/config/message_handler.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  lib/Messenger/Handler/SearchBackendHandler.php
  lib/Messenger/SearchBackendMessage.php
Labels: Improvement

#10433 [DataObjects] Do not load admin-mode master layout for Remembered tabs
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
Labels: Bug

#10444 Fixed regression of #10401 that broke the installer
  lib/Tool/Console.php
Labels: Bug

#10456 [Email] Allow external image in HTML preview
  bundles/AdminBundle/Controller/Admin/EmailController.php
Labels: Bug

#10458 IncludeRenderer and Snippet Editable cache should be kept with admin changes
  lib/Templating/Renderer/IncludeRenderer.php
  models/Document/Editable/Snippet.php
Labels: Bug

#10439 Migrated Sanity Check to Messenger
  bundles/CoreBundle/Migrations/Version20210928135248.php
  bundles/CoreBundle/Resources/config/maintenance.yml
  bundles/CoreBundle/Resources/config/message_handler.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/InstallBundle/Resources/install.sql
  config/dao-classmap.php
  doc/Development_Documentation/19_Development_Tools_and_Details/05_Database_Model.md
  lib/Messenger/Handler/SanityCheckHandler.php
  lib/Messenger/SanityCheckMessage.php
  models/Dependency/Dao.php
  models/Element/Sanitycheck.php
  models/Element/Sanitycheck/Dao.php
Labels: Improvement
