Repository pimcore/pimcore, pull requests merged in 2021-07, with the labels that each got.

#9610 [Document] Possibility to configure image, video, link and select editable as required
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/link.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/select.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/video.js
  doc/Development_Documentation/03_Documents/01_Editables/14_Image.md
  doc/Development_Documentation/03_Documents/01_Editables/18_Link.md
  doc/Development_Documentation/03_Documents/01_Editables/30_Select.md
  doc/Development_Documentation/03_Documents/01_Editables/38_Video.md
Labels: Improvement

#9603 [Workflows] Fixes error response
  bundles/AdminBundle/Controller/Admin/WorkflowController.php
Labels: Bug

#9643 [Admin] HTTP errors - fix list when no sorting provided
  bundles/AdminBundle/Controller/Admin/MiscController.php
Labels: Bug

#9659 [Admin] Documents / Areabricks - Disable areabricks dnd button for inherited documents
  bundles/AdminBundle/Resources/public/js/pimcore/document/edit.js
Labels: Bug

#9661 [DataObjects] ClassDefinition::generateClassFiles() change visibility to public again and mark internal
  models/DataObject/ClassDefinition.php
Labels: Task

#9633 [DataObjects] Data fields forbiddenNames check on server side
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
Labels: Improvement

#9660 [Documents] Auto Save - Do not run for types not supporting versioning
  bundles/AdminBundle/Resources/public/js/pimcore/element/abstract.js
Labels: Bug

#9674 [DataObjects] FieldCollection - Fix interference of draft when saving object with FieldCollection
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
Labels: Bug

#9679 [Asset] Setting focal point breaks image asset
  models/Asset/Image.php
Labels: Bug

#9657 [Documents] Routing - use latest document settings to build route when in admin mode
  lib/Routing/Dynamic/DocumentRouteHandler.php
Labels: Bug

#9640 [CacheWarmingCommand] Pass classes option to Warming job
  bundles/CoreBundle/Command/CacheWarmingCommand.php
Labels: Bug

#9639 FIX: Thumbnail::getMimeType() fix (#9638)
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#9681 [Asset] Reverts #9639 and implemented a proper fix for pathReference cache
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#9654 Fix: ObjectBrick with multiple Localized fields are broken after update to 6.9/10.0
  bundles/CoreBundle/Migrations/Version20210706090823.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
Labels: Bug

#9683 Variant classificationstore fields are not marked as inherited unless one field is set
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#9634 Allow Concrete::__callStatic() to retrieve variants in getters
  bundles/CoreBundle/Migrations/Version20210702102100.php
  doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
  models/DataObject/ClassDefinition.php
  models/DataObject/Concrete.php
Labels: Improvement

#9574 [Admin] tree override - do not update paging twice on itemupdate & renderRow
  bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
Labels: Bug

#9693 [Assets] Update children path on remote storage
  models/Asset.php
Labels: Bug

#9697 [Asset] Video preview generation - Do not generate tmp files for inprogress & finished jobs
  models/Asset/Video/Thumbnail/Processor.php
Labels: Bug

#9678 [Admin Translations] Translations keys should be wrapped with + sign if translated value is missing
  lib/Translation/Translator.php
Labels: Bug

#9699 [Assets] Custom download - rasterize svg in defined file format
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
Labels: Bug

#9700 [Assets] Set remote stream results in 0-byte file
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
  models/Asset.php
Labels: Bug

#9663 [Glossary] Add Twig filter
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/README.md
  doc/Development_Documentation/18_Tools_and_Features/21_Glossary.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Twig/Extension/GlossaryExtension.php
  lib/Twig/Node/GlossaryNode.php
  lib/Twig/TokenParser/GlossaryTokenParser.php
Labels: Improvement

#9694 Element Router with string name
  lib/Routing/Element/Router.php
  lib/Routing/Staticroute/Router.php
Labels: Bug, Task

#9710 [Docs] Fix default rounding mode
  doc/Development_Documentation/10_E-Commerce_Framework/09_Working_with_Prices/09_Calculate_with_Prices.md
Labels: Bug

#9616 Move Marketing Settings to SettingsStore
  bundles/AdminBundle/Controller/Reports/SettingsController.php
  bundles/CoreBundle/Migrations/Version20210630062445.php
  lib/Config.php
  lib/Config/ReportConfigWriter.php
Labels: Improvement

#9711 [DataObjects] Re-introduce BC layer for ReverseManyToManyObjectRelation
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
Labels: Bug

#9689 Support endroid/qr-code 4
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#9703 [Core] Add Command to migrate content between storages
  bundles/CoreBundle/Command/MigrateStorageCommand.php
  bundles/CoreBundle/Resources/config/commands.yml
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/03_File_Storage_Setup.md
  doc/Development_Documentation/img/migratingstorage.png
Labels: Improvement

#9715 [Bug]: Upgrading from 6.9.x to 10.0.6 - issue Undefined array key \"subContainerType\" in admin/element/get-nice-path
  bundles/AdminBundle/Controller/Admin/ElementController.php
Labels: Bug

#9717 [Login][Events] Added event before redirecting to login page
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Resources/views/Admin/Login/deeplink.html.twig
  bundles/AdminBundle/Security/Guard/AdminAuthenticator.php
  lib/Event/Admin/Login/LoginRedirectEvent.php
  lib/Event/AdminEvents.php
Labels: New Feature

#9724 Fix current PhpStan errors in 10.0 branch
  lib/DataObject/GridColumnConfig/Operator/AnyGetter.php
  lib/Model/AbstractModel.php
  lib/Workflow/EventSubscriber/NotesSubscriber.php
Labels: Task

#9726 Report config is optional - follow up to #9616
  lib/Config.php
Labels: Bug

#9728 Parallelization trait fix
  lib/Console/Traits/Parallelization.php
Labels: Bug

#9736 Properly encode values in properties and notes grid
  bundles/AdminBundle/Resources/public/js/pimcore/element/notes.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/properties.js
Labels: Bug

#9718 Update doc for migration from Pimcore 6 to 10 to switch PHP version
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
Labels: Improvement

#9740 Twig breach helper was not used correctly on login pages
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.twig
  bundles/AdminBundle/Resources/views/Admin/Login/lostpassword.html.twig
  bundles/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.twig
Labels: Bug

#9741 CSRF Service: avoid duplicate code
  bundles/AdminBundle/Security/CsrfProtectionHandler.php
Labels: Task

#9764 Fixed CSRF token refresh on login page
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.twig
Labels: Bug

#9763 [DataObject] ClassesRebuildCommand - Fix error: Argument #1 ($key) must be of type string, null given
  lib/Model/DataObject/ClassDefinition/ClassDefinitionManager.php
Labels: Bug

#9765 Temp. files for QR codes should be stored in /var/tmp instead of /tmp…
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
Labels: Bug

#9769 [Asset] Not possible to open asset if there's an editlock on it
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
Labels: Bug

#9768 [Thumbnails] Do not prefix & encode path if used in admin interface
  models/Asset/Image.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
  models/Asset/Video.php
Labels: Bug

#9770 Fix new phpstan error with Symfony 5.4-dev
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Controller/Admin/EmailController.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/Classificationstore/KeyConfig/Listing/Dao.php
  models/Staticroute.php
Labels: Task

#9558 PhpStan: Add missing models
  .github/ci/files/var/classes/DataObject/Customer.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterCategory.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterCategoryMultiselect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterInputfield.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterMultiRelation.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterMultiSelect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterMultiSelectFromMultiSelect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterNumberRange.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterNumberRangeSelection.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterRelation.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterSelect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterSelectFromMultiSelect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/OrderPriceModifications.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/PaymentInfo.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/PricingRule.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/TaxEntry.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/VoucherTokenTypePattern.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/VoucherTokenTypeSingle.php
  .github/ci/files/var/classes/DataObject/FilterDefinition.php
  .github/ci/files/var/classes/DataObject/OnlineShopOrder.php
  .github/ci/files/var/classes/DataObject/OnlineShopOrderItem.php
  .github/ci/files/var/classes/DataObject/OnlineShopTaxClass.php
  .github/ci/files/var/classes/DataObject/OnlineShopVoucherSeries.php
  .github/ci/files/var/classes/DataObject/OnlineShopVoucherToken.php
  .github/workflows/static-analysis.yml
  bundles/EcommerceFrameworkBundle/Model/AbstractVoucherTokenType.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/AbstractTokenManager.php
  composer.json
  phpstan-baseline.neon
  phpstan-parameters.neon
Labels: Task

#9753 Consistent behaviour for document title/navigation/key
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/document_language_overview.js
Labels: Improvement

#9767 [Data objects] Grid: Flexible field width for class selection dropdown list
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
Labels: Improvement

#9730 Non-parsable SQL query checking grid permissions
  models/DataObject/AbstractObject/Dao.php
Labels: Bug

#9760 [DataObject] User - Fix data of user fields empty again after reloading the data object
  models/DataObject/ClassDefinition/Data/User.php
Labels: Bug

#9447 [Documents] Static Page Generator
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/img/flat-color-icons/static_page.svg
  bundles/AdminBundle/Resources/public/js/pimcore/document/pages/settings.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
  bundles/CoreBundle/Command/GenerateStaticPagesCommand.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
  bundles/CoreBundle/EventListener/Frontend/GoogleAnalyticsCodeListener.php
  bundles/CoreBundle/EventListener/Frontend/InternalWysiwygHtmlAttributeFilterListener.php
  bundles/CoreBundle/EventListener/Frontend/StaticPageGeneratorListener.php
  bundles/CoreBundle/EventListener/Traits/StaticPageContextAwareTrait.php
  bundles/CoreBundle/Migrations/Version20210616114744.php
  bundles/CoreBundle/Resources/config/documents.yml
  bundles/CoreBundle/Resources/config/event_listeners.yml
  bundles/CoreBundle/Resources/config/maintenance.yml
  bundles/CoreBundle/Resources/config/pimcore/flysystem.yml
  bundles/CoreBundle/Resources/config/request_response.yml
  bundles/CoreBundle/Resources/translations/en.json
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/19_Development_Tools_and_Details/20_Static_Page_Generator.md
  doc/Development_Documentation/img/static_page1.png
  doc/Development_Documentation/img/static_page2.png
  lib/Document/StaticPageGenerator.php
  lib/Http/Request/Resolver/StaticPageResolver.php
  lib/Maintenance/Tasks/StaticPagesGenerationTask.php
  lib/Routing/Dynamic/DocumentRouteHandler.php
  lib/Targeting/EventListener/TargetingListener.php
  models/Document/DocType.php
  models/Document/DocType/Dao.php
  models/Document/PageSnippet.php
  models/Element/AdminStyle.php
Labels: New Feature

#9793 [Core] Lost Password - handle password recovery emails errors gracefully
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Resources/views/Admin/Login/lostpassword.html.twig
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#9780 Fix: labelWidth must be an integer
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/classificationstore.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/localizedfields.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/structuredTable.js
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Layout/Traits/LabelTrait.php
Labels: Bug

#9789 fixed speed - better to split into 2 queries then use OR condition
  models/DataObject/Fieldcollection/Dao.php
Labels: Bug

#9794 [Feature][Admin UI] Add data attribute with app environment to body element
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
Labels: Improvement

#9716 [DataObjects] Fix localized calculated fields
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
Labels: Bug

#9785 [Documents] Blocks - Refresh controls on adding blocks
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/block.js
Labels: Bug

#9798 Added table copy all functionality
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/table.js
Labels: Improvement

#9797 Fix wrong PhpDocs
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderAgent.php
  lib/Cache/Core/CacheQueueItem.php
  lib/Cache/Core/CoreCacheHandler.php
  lib/DataObject/GridColumnConfig/Value/AbstractValue.php
  lib/DataObject/GridColumnConfig/Value/Factory/ValueFactoryInterface.php
  lib/Db/ConnectionInterface.php
  lib/Db/PimcoreExtensionsTrait.php
  lib/Model/Listing/AbstractListing.php
  models/Asset.php
  models/Asset/Document.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Time.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/Data/ElementMetadata.php
  models/DataObject/Data/ObjectMetadata.php
  models/DataObject/Listing.php
  models/Site.php
Labels: Bug

#9501 [DataObjects] Deny option values with comma for multiselect field type
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug

#9799 Fixed CSS issue in Firefox: drop target icon is misplaced
  bundles/AdminBundle/Resources/public/css/admin.css
Labels: Bug

#9800 [Docs] Make pdo_mysql a required module
  doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
Labels: Bug

#9801 [Installer] Only mark core migrations as done on install
  bundles/InstallBundle/Installer.php
Labels: Bug

#9804 [Document] Areablock groups are using wrong language
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
  models/Document/Editable/Areablock.php
Labels: Bug

#9637 Consistent method name getMimeType/setMimeType
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Resources/views/Admin/Asset/showVersionImage.html.twig
  bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/info-table.html.twig
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  models/Asset.php
  models/Asset/Image.php
  models/Asset/WebDAV/File.php
Labels: Task

#9814 Fix deprecation warnings
  bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php
  bundles/CoreBundle/Resources/config/services.yml
  bundles/CoreBundle/Resources/config/templating.yml
Labels: Bug

#9823 [Admin] Fix Deeplink gets lost after login
  bundles/AdminBundle/Controller/Admin/LoginController.php
Labels: Bug

#9838 Remove document from mail object before sending
  lib/Mail.php
Labels: Bug

#9859 [Admin] Fix warning when creating dashboard
  bundles/AdminBundle/Controller/Admin/PortalController.php
Labels: Bug

#9877 Fixed PHPStan issues
  bundles/AdminBundle/Controller/Admin/WorkflowController.php
Labels: Bug

#9874 [Adminer] Establish SSL connection if SSL driver options are configured
  bundles/AdminBundle/Controller/Admin/External/AdminerController.php
Labels: Bug

#9873 Fix undefined index backend warning in ecommerce abstract worker
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractWorker.php
Labels: Bug

#9880 [DataObject] Wysiwyg - Do not try to rewrite Ids when data is empty
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
Labels: Bug

#9868 Fix option-provider inside classification-store on grid-view (#9847)
  models/DataObject/ClassDefinition/Data/Select.php
Labels: Bug

#9869 Changing "Sort children by" on folder that contains folder breaks
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#9884 [Data Objects] Password field: added optional minimum password length
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/password.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  models/DataObject/ClassDefinition/Data/Password.php
Labels: Bug

#9885 [Session] Cookie SameSite should be strict by default
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#9886 [Documents] Fix issue - there are no indexes to pop from as index list is empty
  models/Document/Editable/Block.php
Labels: Bug

#9816 [Core] Changes to support headless documents
  bundles/AdminBundle/Resources/public/js/pimcore/document/folder.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/link.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/page.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/properties.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  lib/Model/Document/Editable/Loader/EditableLoader.php
  lib/Routing/Dynamic/DocumentRouteHandler.php
  lib/Templating/Renderer/EditableRenderer.php
  models/Document.php
  models/Document/Dao.php
Labels: Task

#9807 Fix wrong PhpDocs
  lib/Tool.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/Document.php
  models/Document/Editable/Renderlet.php
  models/Document/Service.php
  models/Element/Data/MarkerHotspotItem.php
  models/Search/Backend/Data.php
Labels: Bug

#9881 convertToWebPath can return null
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#9635 Quicksearch: use class icons when available
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/Controller/Traits/AdminStyleTrait.php
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
  lib/Event/Admin/ElementAdminStyleEvent.php
Labels: Improvement

#9893 Check if array is empty before imploding
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Bug

#9870 Fixed ExtJS resize frame on Valid Units in Quantity Values (#9864)
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/inputQuantityValue.js
Labels: Bug

#9662 [DataObjects][Calculated Value] Add option to define calculation via symfony expression language
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/calculatedValue.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/10_Calculated_Value_Type.md
  doc/Development_Documentation/img/classes-datatypes-calculated-definition.png
  doc/Development_Documentation/img/classes-datatypes-calculated.png
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/Service.php
  tests/_support/Helper/Model.php
  tests/_support/Test/DataType/AbstractDataTypeTestCase.php
Labels: Improvement

#9827 [Document] Show limit of bricks
  bundles/AdminBundle/Resources/public/css/editmode.css
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
Labels: Improvement

#9875 [Ecommerce] Do not allow negative amounts in cart
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCartItem.php
Labels: Bug

#9892 Deadlock when updating elastic search store
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractMockupCacheWorker.php
Labels: Bug

#9896 [Documents] Fix Block first add button is not visible anymore
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/block.js
Labels: Bug

#9898 [Documents] Areablock - Refresh controls on adding blocks
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
Labels: Bug

#9907 Bug disableWidthHeightAttributes fixed
  models/Asset/Image/Thumbnail.php
Labels: Bug

#9903 Fix type error
  models/DataObject/Data/ObjectMetadata.php
Labels: Improvement

#9911 [Notifications] Use proper REST methods (CSRF)
  bundles/AdminBundle/Controller/Admin/NotificationController.php
  bundles/AdminBundle/Resources/public/js/pimcore/notification/helper.js
Labels: Bug

#9883 [Admin] Dataobject tree - Fix duplicate pagination issue
  bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
Labels: Bug
