Repository pimcore/pimcore, pull requests merged in 2021-10, with the labels that each got.

#10478 [Documents] Fix adding Blank documents without DocType
  models/Document/DocType/Dao.php
Labels: Bug

#10303 [Docs] Add performance best practices guide with benchmarks
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/09_Performance_Guide.md
Labels: Improvement

#10480 [Email] Do not send email in case of mailer exception
  lib/Mail.php
Labels: Bug

#10479 Grid filter label localized
  bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
Labels: Bug

#10451 [Elements] Versions delete asynchronous queue with Symfony Messenger
  bundles/CoreBundle/Resources/config/message_handler.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  lib/Messenger/Handler/VersionDeleteHandler.php
  lib/Messenger/VersionDeleteMessage.php
  models/Asset.php
  models/DataObject/Concrete.php
  models/Document/PageSnippet.php
Labels: Improvement

#10464 [Admin] Fix User with only List and View permissions can not see Documents Editables
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
Labels: Bug

#10455 Use Symfony Messenger for Web2Print Pdf generation
  bundles/CoreBundle/Command/Web2PrintPdfCreationCommand.php
  bundles/CoreBundle/Resources/config/message_handler.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  lib/Messenger/GenerateWeb2PrintPdfMessage.php
  lib/Messenger/Handler/GenerateWeb2PrintPdfHandler.php
  lib/Web2Print/Processor.php
Labels: Improvement

#10461 Move ImageOptimize maintenance task to Symfony Messenger
  bundles/CoreBundle/Resources/config/maintenance.yml
  bundles/CoreBundle/Resources/config/message_handler.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  lib/Maintenance/Tasks/ImageOptimizeTask.php
  lib/Messenger/Handler/OptimizeImageHandler.php
  lib/Messenger/OptimizeImageMessage.php
  models/Asset/Image/Thumbnail/Processor.php
Labels: Improvement

#10460 GridConfig::getById() should return null instead of throw NotFoundException
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  models/GridConfig.php
Labels: Improvement

#10492 Access `property.description` as object not array in element/properties.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/properties.js
Labels: Bug

#10491 [Config] Use UUIDs instead of error-prone auto-increment implementation
  lib/Model/Dao/AutoIncrementTrait.php
  models/Document/DocType/Dao.php
  models/Metadata/Predefined/Dao.php
  models/Property/Predefined/Dao.php
Labels: Bug

#10490 [DataObject][Search] Fix object brick attributes filter conditions
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
Labels: Bug

#10488 Fix Predefined getByKey and getByName methods
  models/Metadata/Predefined/Dao.php
  models/Property/Predefined.php
  models/Property/Predefined/Dao.php
Labels: Bug

#10494 Fix sending to debug e-mail-addresses
  lib/Mail/Plugins/RedirectingPlugin.php
Labels: Bug

#9862 [Actions] Added PHP 8.1 support
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  bundles/EcommerceFrameworkBundle/OrderManager/AbstractOrderList.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/StartPaymentRequest/AbstractRequest.php
  bundles/EcommerceFrameworkBundle/VoucherService/Token/Listing.php
  composer.json
  lib/Cache/Runtime.php
  lib/Config.php
  lib/Config/Config.php
  lib/DependencyInjection/CollectionServiceLocator.php
  lib/Document/Editable/Block/BlockStateStack.php
  lib/Extension/Document/Areabrick/EditableDialogBoxConfiguration.php
  lib/Model/Listing/AbstractListing.php
  lib/Targeting/Model/VisitorInfo.php
  lib/Tool/Requirements/Check.php
  models/Asset/Listing.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/Fieldcollection.php
  models/DataObject/Listing.php
  models/Document/Listing.php
  models/Tool/CustomReport/Config.php
Labels: Task

#10497 [Documents] Editable Dialog Box - destroy dialog box on removing editable from areablock
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area_abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
Labels: Bug

#10510 Generate HDPI variant/srcset for images used in WYSIWYG
  lib/Tool/Text.php
Labels: Improvement

#10511 [CoreBundle] Update config files *.yml to *.yaml
  bundles/CoreBundle/DependencyInjection/Compiler/WorkflowPass.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/aliases.yaml
  bundles/CoreBundle/Resources/config/analytics.yaml
  bundles/CoreBundle/Resources/config/argument_resolvers.yaml
  bundles/CoreBundle/Resources/config/cache.yaml
  bundles/CoreBundle/Resources/config/commands.yaml
  bundles/CoreBundle/Resources/config/documents.yaml
  bundles/CoreBundle/Resources/config/event_listeners.yaml
  bundles/CoreBundle/Resources/config/extensions.yaml
  bundles/CoreBundle/Resources/config/image_optimizers.yaml
  bundles/CoreBundle/Resources/config/implementation_factories.yaml
  bundles/CoreBundle/Resources/config/l10n.yaml
  bundles/CoreBundle/Resources/config/logging.yaml
  bundles/CoreBundle/Resources/config/maintenance.yaml
  bundles/CoreBundle/Resources/config/marshaller.yaml
  bundles/CoreBundle/Resources/config/message_handler.yaml
  bundles/CoreBundle/Resources/config/migrations.yaml
  bundles/CoreBundle/Resources/config/paginator.yaml
  bundles/CoreBundle/Resources/config/pimcore/config.yaml
  bundles/CoreBundle/Resources/config/pimcore/config.yml
  bundles/CoreBundle/Resources/config/pimcore/config_dev.yaml
  bundles/CoreBundle/Resources/config/pimcore/config_dev.yml
  bundles/CoreBundle/Resources/config/pimcore/config_prod.yaml
  bundles/CoreBundle/Resources/config/pimcore/config_prod.yml
  bundles/CoreBundle/Resources/config/pimcore/config_test.yaml
  bundles/CoreBundle/Resources/config/pimcore/config_test.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  bundles/CoreBundle/Resources/config/pimcore/dev.yaml
  bundles/CoreBundle/Resources/config/pimcore/flysystem.yaml
  bundles/CoreBundle/Resources/config/pimcore/prod.yaml
  bundles/CoreBundle/Resources/config/pimcore/test.yaml
  bundles/CoreBundle/Resources/config/pimcore/two_factor_authentication.yaml
  bundles/CoreBundle/Resources/config/profiler.yaml
  bundles/CoreBundle/Resources/config/request_response.yaml
  bundles/CoreBundle/Resources/config/services.yaml
  bundles/CoreBundle/Resources/config/services_routing.yaml
  bundles/CoreBundle/Resources/config/services_symfony_workflow.yaml
  bundles/CoreBundle/Resources/config/services_workflow.yaml
  bundles/CoreBundle/Resources/config/sitemaps.yaml
  bundles/CoreBundle/Resources/config/targeting.yaml
  bundles/CoreBundle/Resources/config/targeting/listeners.yaml
  bundles/CoreBundle/Resources/config/targeting/services.yaml
  bundles/CoreBundle/Resources/config/targeting/session.yaml
  bundles/CoreBundle/Resources/config/templating.yaml
  bundles/CoreBundle/Resources/config/templating_twig.yaml
Labels: Task

#10512 [AdminBundle] Update config files *.yml to *.yaml
  bundles/AdminBundle/DependencyInjection/PimcoreAdminExtension.php
  bundles/AdminBundle/Resources/config/aliases.yaml
  bundles/AdminBundle/Resources/config/event_listeners.yaml
  bundles/AdminBundle/Resources/config/export.yaml
  bundles/AdminBundle/Resources/config/security_abstract_services.yaml
  bundles/AdminBundle/Resources/config/security_services.yaml
  bundles/AdminBundle/Resources/config/serializer.yaml
  bundles/AdminBundle/Resources/config/services.yaml
Labels: Task

#10513 [EcommerceFrameworkBundle] Update config files *.yml to *.yaml
  bundles/EcommerceFrameworkBundle/Controller/FindologicController.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  bundles/EcommerceFrameworkBundle/Resources/config/availability_systems.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/cart_manager.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/checkout_manager.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/commands.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/environment.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/event_listeners.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/factory.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/filter_service.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/filter_service_filter_types.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/index_service.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/index_service_configs_workers.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/index_service_synonym_providers.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/maintenance.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/offer_tool.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/order_manager.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/payment_manager.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/pimcore/config.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/price_systems.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/pricing_manager.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/services.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/tracking_manager.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/voucher_service.yaml
Labels: Task

#10514 [Core & InstallBundle] Update config files *.yml to *.yaml
  .editorconfig
  bundles/InstallBundle/DependencyInjection/PimcoreInstallExtension.php
  bundles/InstallBundle/InstallerKernel.php
  bundles/InstallBundle/Resources/config/config.yaml
  bundles/InstallBundle/Resources/config/services.yaml
  doc/Development_Documentation/01_Getting_Started/03_Configuration.md
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/01_HeadLink.md
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/30_Dynamic_Select_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/55_Number_Types.md
  doc/Development_Documentation/06_Multi_Language_i18n/07_Admin_Translations.md
  doc/Development_Documentation/10_E-Commerce_Framework/04_Configuration/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/07_Filter_Service/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/09_Working_with_Prices/01_Price_Systems_and_getting_Prices.md
  doc/Development_Documentation/10_E-Commerce_Framework/10_Working_with_Availabilities.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/10_Recurring_Payments.md
  doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/09_Targeting_Storage.md
  doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/README.md
  doc/Development_Documentation/18_Tools_and_Features/39_Sitemaps.md
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/01_Authenticate_Pimcore_Objects.md
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/11_Console_CLI.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/32_Google_Services_Integration.md
  doc/Development_Documentation/19_Development_Tools_and_Details/35_Working_with_Sessions.md
  doc/Development_Documentation/19_Development_Tools_and_Details/37_Migrations.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/01_Loading_Service_Definitions.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/03_Auto_Loading_Config_And_Routing_Definitions.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/01_Installers.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/09_Adding_Document_Editables.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/README.md
  lib/Config/BundleConfigLocator.php
Labels: Task

#10485 Add autoScroll to add scrollbar if necessary
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/data.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/localizedfields.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/button.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/iframe.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/layout.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/panel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/text.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
Labels: Improvement

#10518 Renamed routing.yml to routing.yaml on AdminBundle and EcommerceFBundle
  bundles/AdminBundle/Resources/config/pimcore/routing.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/pimcore/routing.yaml
Labels: Task
