Repository pimcore/pimcore, pull requests merged in 2021-02, with the labels that each got.

#8019 Fix InputQuantityValue issues
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/Data/AbstractQuantityValue.php
Labels: Bug

#8041 Unit listing missing condition variables fix
  models/DataObject/QuantityValue/Unit/Listing/Dao.php
Labels: Bug

#8048 [Document - Editable Dialog Box] Fix Relation editable buttons
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/relation.js
Labels: Bug

#8043 [Image Thumbnail] Do not generate error image in vendor folder when requested file extension is different
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Bug

#8000 change detector improvements
  bundles/AdminBundle/Resources/public/js/pimcore/element/abstract.js
Labels: Bug

#8001 Fix resend email for old log entries e.g. example@demain.com (example)
  lib/Helper/Mail.php
Labels: Bug

#8022 Imagick adapter: support s3:// URL
  lib/Image/Adapter/Imagick.php
Labels: Bug

#8023 Fix CSRF Attack warning when using wrong custom login screen
  bundles/AdminBundle/Resources/views/Admin/Login/layout.html.php
Labels: Bug

#8026 Use searchSring instead of filter in website translation activation
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation/website.js
Labels: Bug

#8035 Rectify payment provider deprecations
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Heidelpay.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Hobex.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Klarna.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Mpay24Seamless.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/OGone.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPal.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayU.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/QPay.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php
Labels: Task

#8042 [CSV Export] restrict AnyGetter to Pimcore Elements (Asset/Document/Object) and check user permission
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/DataObject/GridColumnConfig/Operator/AnyGetter.php
Labels: BC-BREAK

#8054 Fix: No thumbnail for PDF documents with ) sign
  lib/Document/Adapter/Ghostscript.php
Labels: Bug

#8034 [Data Object] Remove Grid Operator ObjectBrick Getter
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/DataObject/GridColumnConfig/Operator/Factory/DefaultOperatorFactory.php
  lib/DataObject/GridColumnConfig/Operator/Factory/OperatorFactoryInterface.php
  lib/DataObject/GridColumnConfig/Operator/ObjectBrickGetter.php
  lib/DataObject/GridColumnConfig/Service.php
Labels: BC-BREAK

#8053 Fix: Class 'ColorSpace' not found
  lib/Web2Print/Processor/PdfReactor8.php
Labels: Bug

#8056 Catch cache clear exception on installation
  bundles/InstallBundle/Installer.php
Labels: Bug

#8061 Fix JSON parse error, when clicking on edit button of a brick
  models/Document/Editable/Areablock.php
Labels: Bug

#8060 Fix Translations Error
  lib/Translation/Translator.php
  models/Translation.php
  models/Translation/Dao.php
  models/Translation/Listing.php
Labels: Bug

#7995 [Ecommerce] Refactor Payment Providers - remove or move to a Bundle
  bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/Compiler/RegisterConfiguredServicesPass.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Datatrans.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Heidelpay.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Hobex.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Klarna.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/Mpay24Seamless.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/OGone.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPal.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayPalSmartPaymentButton.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PayU.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PaymentInterface.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/QPay.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/WirecardSeamless.php
  bundles/EcommerceFrameworkBundle/PaymentManager/PaymentManager.php
  bundles/EcommerceFrameworkBundle/PaymentManager/PaymentManagerInterface.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/Config/HobexConfig.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/RecurringPaymentInterface.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/StartPaymentRequest/DatatransRequest.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/StartPaymentRequest/HeidelpayRequest.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/StartPaymentRequest/HobexRequest.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/StartPaymentRequest/QPayRequest.php
  bundles/EcommerceFrameworkBundle/Resources/config/payment_manager.yml
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_PaymentInfo_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderDatatrans_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderHeidelPay_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderHobex_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderMpay24_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderOGone_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderPayPalSmartButton_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderPayPal_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderQpay_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/objectbrick_sources/objectbrick_PaymentProviderWirecardSeamless_export.json
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/detail.html.twig
  bundles/EcommerceFrameworkBundle/Tools/Installer.php
  bundles/EcommerceFrameworkBundle/Tools/PaymentProviderInstaller.php
  composer.json
  doc/Development_Documentation/10_E-Commerce_Framework/13_Checkout_Manager/07_Integrating_Payment.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/01_Wirecard_QPay.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/02_Wirecard_Seamless.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/03_Datatrans.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/04_PayPal.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/05_Klarna.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/06_OGone.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/07_MPay24.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/08_PayU.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/09_Heidelpay.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/10_Recurring_Payments.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/11_Hobex.md
  doc/Development_Documentation/10_E-Commerce_Framework/15_Payment/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  phpstan-baseline.neon
Labels: Task

#8071 [Ecommerce] remove unnecessary instanceof checks in OrderManager
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
Labels: Task

#8074 Guzzle 7 - Drop Guzzle 6
  composer.json
Labels: BC-BREAK

#8078 [CoreBundle] Invalid definition for service GeoIp : lint:container
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
Labels: Bug

#8075 [Ecommerce] Unify Cart Item Counting
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/CartManager/Cart.php
  bundles/EcommerceFrameworkBundle/CartManager/CartInterface.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  tests/Ecommerce/CartManager/SessionCartTest.php
Labels: Improvement

#8076 [Static Routes] Do not merge request params on static-route generate
  lib/Routing/Staticroute/Router.php
  models/Staticroute.php
Labels: BC-BREAK, Improvement

#8083 [Ecommerce] Fixed cleanup of cart amount cache-variables
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/CartManager/SessionCart.php
Labels: Bug

#8082 [Ecommerce] Remove BC Layer for Cart Counting
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/CartManager/Cart.php
  bundles/EcommerceFrameworkBundle/CartManager/CartInterface.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  tests/Ecommerce/CartManager/SessionCartTest.php
Labels: BC-BREAK, Task

#8065 [Ecommerce] Remove Elasticsearch5 support
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/DefaultElasticSearch5.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch5.php
  bundles/EcommerceFrameworkBundle/Resources/config/index_service_configs_workers.yml
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: BC-BREAK, Task

#8085 [Ecommerce] Add deprecation commands to old checkout manager architecture
  bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManagerInterface.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManagerInterface.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PaymentInterface.php
Labels: Task

#8040 [Ecommerce] Activated generateTypeDeclarations for ecommerce framework data object classes
  bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/Model/AbstractCategory.php
  bundles/EcommerceFrameworkBundle/Model/AbstractFilterDefinition.php
  bundles/EcommerceFrameworkBundle/Model/AbstractFilterDefinitionType.php
  bundles/EcommerceFrameworkBundle/Model/AbstractOrder.php
  bundles/EcommerceFrameworkBundle/Model/AbstractOrderItem.php
  bundles/EcommerceFrameworkBundle/Model/AbstractPaymentInformation.php
  bundles/EcommerceFrameworkBundle/Model/AbstractProduct.php
  bundles/EcommerceFrameworkBundle/Model/AbstractSetProduct.php
  bundles/EcommerceFrameworkBundle/Model/CategoryFilterDefinitionType.php
  bundles/EcommerceFrameworkBundle/Model/CheckoutableInterface.php
  bundles/EcommerceFrameworkBundle/Model/DefaultMockup.php
  bundles/EcommerceFrameworkBundle/Model/IndexableInterface.php
  bundles/EcommerceFrameworkBundle/Model/ProductInterface.php
  bundles/EcommerceFrameworkBundle/OfferTool/AbstractOffer.php
  bundles/EcommerceFrameworkBundle/OfferTool/AbstractOfferItem.php
  bundles/EcommerceFrameworkBundle/OfferTool/AbstractOfferToolProduct.php
  bundles/EcommerceFrameworkBundle/OfferTool/DefaultService.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_FilterDefinition_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolCustomProduct_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOfferItem_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOffer_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrderItem_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopTaxClass_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherSeries_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherToken_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterCategoryMultiselect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterCategory_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterInputfield_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterMultiRelation_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterMultiSelectFromMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterNumberRangeSelection_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterNumberRange_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterRelation_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterSelectClsStoreAttributes_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterSelectFromMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_OrderByFields_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_OrderPriceModifications_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_PaymentInfo_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_PricingRule_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_SimilarityField_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_TaxEntry_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_VoucherTokenTypePattern_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_VoucherTokenTypeSingle_export.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  tests/Ecommerce/CartTaxManagementTest.php
Labels: BC-BREAK, Task

#7844 PHP 8 Support
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  bundles/CoreBundle/Command/Bundle/ListCommand.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/DefaultMysqlSubTenantConfig.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
  bundles/EcommerceFrameworkBundle/Tracking/TrackingManager.php
  composer.json
  lib/Image/Adapter/GD.php
  models/DataObject/Data/ElementMetadata.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Service.php
  models/Notification/Service/NotificationService.php
Labels: BC-BREAK

#8086 Fix Doctrine QueryBuilder applyjoins
  models/DataObject/Listing/Concrete/Dao.php
Labels: Bug

#8094 [Versions] renewReferences() restores current key even if $doNotRestoreKeyAndPath is true
  models/Element/Service.php
Labels: Bug

#8098 [DataObject Grid] inputQuantityValue - Fix grid view renderer -
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/inputQuantityValue.js
Labels: Bug

#8099 [Documents][Blocks] Possible undefined notice in manual mode
  models/Document/Editable/Block.php
Labels: Bug

#8100 fixed some undefined notice errors
  bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php
  lib/Web2Print/Processor/WkHtmlToPdf.php
Labels: Bug

#8103 [Static Routes] Merge router.request_context params e.g._locale
  models/Staticroute.php
Labels: Bug

#8066 [Notifications] Prevent exception when trying to open deleted notification
  bundles/AdminBundle/Controller/Admin/NotificationController.php
  bundles/AdminBundle/Resources/public/js/pimcore/notification/helper.js
  models/Notification/Service/NotificationService.php
Labels: Bug

#8120 Consider existing parameters in DataObject Linkgenerators
  models/Document/Editable/Link.php
Labels: Bug

#8141 Fix the problem that not all fields are shown in "Visible Fields" at…
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#8139 added async option to headscript
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/03_HeadScript.md
  lib/Twig/Extension/Templating/HeadScript.php
Labels: Improvement

#8153 [Admin] Fix Can't open object in AdvManyToManyRelation
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
Labels: Bug

#8134 Custom Login screen - Fix and support external image URL
  bundles/AdminBundle/Resources/views/Admin/Login/layout.html.php
Labels: Bug

#8135 Custom Login screen - Fix and support external image URL for Pimcore 10
  bundles/AdminBundle/Resources/views/Admin/Login/layout.html.twig
Labels: Bug

#8055 Add better layout possibilities for editable dialog box of a brick
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
Labels: Improvement

#8157 Fixed sending newsletters
  lib/Mail.php
Labels: Bug

#8091 [Ecommerce] Remove legacy checkout manager
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCart.php
  bundles/EcommerceFrameworkBundle/CartManager/Cart.php
  bundles/EcommerceFrameworkBundle/CartManager/CartFactory.php
  bundles/EcommerceFrameworkBundle/CartManager/CartFactoryInterface.php
  bundles/EcommerceFrameworkBundle/CartManager/CartInterface.php
  bundles/EcommerceFrameworkBundle/CartManager/MultiCartManager.php
  bundles/EcommerceFrameworkBundle/CartManager/SessionCart.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManager.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManagerFactory.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManagerFactoryInterface.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CheckoutManagerInterface.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessorInterface.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CheckoutManager.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CheckoutManagerInterface.php
  bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CommitOrderProcessor.php
  bundles/EcommerceFrameworkBundle/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  bundles/EcommerceFrameworkBundle/Factory.php
  bundles/EcommerceFrameworkBundle/Model/AbstractOrder.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Agent.php
  bundles/EcommerceFrameworkBundle/OrderManager/Order/AgentFactory.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderAgentInterface.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManager.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManagerInterface.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManagerLocator.php
  bundles/EcommerceFrameworkBundle/OrderManager/OrderManagerLocatorInterface.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderAgent.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManagerInterface.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/AbstractPayment.php
  bundles/EcommerceFrameworkBundle/PaymentManager/Payment/PaymentInterface.php
  bundles/EcommerceFrameworkBundle/PaymentManager/PaymentManager.php
  bundles/EcommerceFrameworkBundle/PaymentManager/PaymentManagerInterface.php
  bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/PaymentInterface.php
  bundles/EcommerceFrameworkBundle/Resources/config/checkout_manager.yml
  bundles/EcommerceFrameworkBundle/Resources/config/order_manager.yml
  bundles/EcommerceFrameworkBundle/Resources/config/v7_configurations.yml
  doc/Development_Documentation/10_E-Commerce_Framework/13_Checkout_Manager/07_Integrating_Payment.md
  doc/Development_Documentation/10_E-Commerce_Framework/13_Checkout_Manager/08_Checkout_Manager_Details.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Event/Model/Ecommerce/CheckoutManagerStepsEvent.php
  lib/Event/Model/Ecommerce/OrderManagerEvent.php
Labels: BC-BREAK, Task

#8116 [DataObject] Classificationstore + QuantityValue not properly restored
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/inputQuantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
  bundles/CoreBundle/Migrations/Version20210211152319.php
  models/DataObject/ClassDefinition/Data/InputQuantityValue.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Bug

#8073 [Ecommerce][IndexService] change default behavior for index-service to throw exceptions
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Event/Model/Ecommerce/IndexService/PreprocessAttributeErrorEvent.php
Labels: BC-BREAK, Task

#8148 [Ecommerce][PricingRules] Fix first condition is always ignored
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/Bracket.php
  tests/Ecommerce/PricingManager/CombinedRuleTest.php
  tests/Ecommerce/PricingManager/Rule/AbstractRuleTest.php
Labels: Bug

#8093 [Tests] Documents CRUD operations, editables, inheritance, ....
  models/Document/Link.php
  tests/Model/Document/DocumentTest.php
  tests/Model/Document/EditableTest.php
  tests/_support/Helper/AbstractTestDataHelper.php
  tests/_support/Helper/DataType/TestDataHelper.php
  tests/_support/Helper/Document/TestDataHelper.php
  tests/_support/Util/TestHelper.php
Labels: Improvement

#8126 Replace Swiftmailer with Symfony Mailer Component
  .github/ci/files/config/system.yml
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/AdminBundle/Controller/Admin/EmailController.php
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Resources/config/pimcore/test.yml
  bundles/CoreBundle/Resources/config/services.yml
  bundles/CoreBundle/Resources/translations/en.extended.json
  bundles/InstallBundle/SystemConfig/ConfigWriter.php
  composer.json
  doc/Development_Documentation/19_Development_Tools_and_Details/17_Static_Helpers.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Config.php
  lib/Event/DocumentEvents.php
  lib/Event/MailEvents.php
  lib/Helper/Mail.php
  lib/Kernel.php
  lib/Log/Handler/Mail.php
  lib/Mail.php
  lib/Mail/Mailer.php
  lib/Mail/Plugins/RedirectingPlugin.php
  lib/Maintenance/Tasks/CheckErrorLogsDbTask.php
  lib/Maintenance/Tasks/LogMailMaintenanceTask.php
  lib/Tool.php
  lib/Tool/Newsletter.php
  lib/Workflow/Notification/NotificationEmailService.php
  tests/Unit/Mail/MailTest.php
Labels: BC-BREAK, Task

#8166 [Custom Reports] Adding custom SQL statements to SELECT field does not work anymore
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
  models/Tool/CustomReport/Adapter/Sql.php
Labels: Bug

#8175 [Documents] Page::setEditable remove params in method signature
  lib/Templating/Renderer/EditableRenderer.php
  lib/Translation/ImporterService/Importer/DocumentImporter.php
  models/Document/PageSnippet.php
  models/Document/TargetingDocument.php
  models/Webservice/Data/Document/PageSnippet.php
  phpstan-baseline.neon
Labels: Task

#8177 [Documents] Backport Editable::buildChildEditableName() to v6.9
  models/Document/Editable.php
Labels: Task

#8090 [Document/DataObject] Type Groups are not translated and sorted
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Improvement

#8037 Allowed many to one relation in reverse relation
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/img/flat-color-icons/reverse_object_relation.svg
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseObjectRelation.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.php
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Resources/translations/aliases.json
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/75_Reverse_Object_Relation_Type.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/README.md
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data/Nonownerobjects.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/ReverseManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
  models/DataObject/Concrete/Dao.php
  tests/_support/Helper/Model.php
  tests/_support/Resources/objects/class-import.json
  tests/_support/Util/TestHelper.php
Labels: Improvement

#8185 Remove ReverseManyToManyObjectRelation BC Layer
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseObjectRelation.js
  models/DataObject/ClassDefinition/Data/ReverseManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
Labels: Task

#8187 DocumentDataExtractor editable check
  lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
Labels: Bug

#8186 Don't merge Symfony/Security config + Use Symfony MicroKernel & fully support flex config
  .github/ci/files/config/config.yaml
  .github/ci/files/config/packages/doctrine_migrations.yaml
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/routes/test/routes.yaml
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/pimcore/config.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Resources/config/pimcore/dev.yml
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/README.md
  lib/DependencyInjection/ConfigMerger.php
  lib/Kernel.php
  lib/Tool/ArrayUtils.php
  tests/Unit/Tool/ConfigMergerTest.php
Labels: BC-BREAK, Task

#8191 Added missing @font-face for Open Sans
  bundles/AdminBundle/Resources/public/extjs/css/PimcoreApp-all_1.css
Labels: Bug

#8202 composer.json: Removed abandoned twig/extensions
  bundles/CoreBundle/Resources/config/templating_twig.yml
  bundles/CoreBundle/Resources/views/Targeting/toolbar/toolbar.html.twig
  composer.json
Labels: BC-BREAK

#8193 Fix Cannot save QuantityValues in ClassificationStore
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Bug

#8189 Fix Wrong language used if key equals translation in shared translations
  lib/Translation/Translator.php
  tests/Unit/Translation/TranslatorTest.php
Labels: Bug

#8181 Proper method name and fewer if-checks in Imagick adapter
  lib/Image/Adapter/Imagick.php
Labels: Improvement

#8199 [Data Object] Generate Type Declarations should be on by default
  models/DataObject/ClassDefinition.php
  models/DataObject/Traits/FieldcollectionObjectbrickDefinitionTrait.php
Labels: Improvement

#8192 Opcache Preloading Integration
  bundles/CoreBundle/Resources/config/services.yml
  lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php
Labels: New Feature

#8210 sensio/framework-extra-bundle: ^6.1
  composer.json
Labels: BC-BREAK, Task

#8211 Twig 3
  bundles/CoreBundle/Resources/config/templating_twig.yml
  composer.json
Labels: BC-BREAK

#8215 Deprecate Matomo Integration
  bundles/AdminBundle/Controller/Reports/PiwikController.php
  bundles/AdminBundle/Resources/public/js/pimcore/analytics/piwik/widget_store_provider.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/piwik.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/piwik/dashboard_iframe.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/piwik/settings.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/targeting/conditions.js
  bundles/CoreBundle/Resources/config/analytics.yml
  bundles/EcommerceFrameworkBundle/Resources/config/tracking_manager.yml
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/Piwik.php
  doc/Development_Documentation/18_Tools_and_Features/28_Marketing_Settings/07_Piwik.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Analytics/Piwik/Api/ApiClient.php
  lib/Analytics/Piwik/Api/Exception/ApiException.php
  lib/Analytics/Piwik/Api/SitesManager.php
  lib/Analytics/Piwik/Api/VisitorClient.php
  lib/Analytics/Piwik/Config/Config.php
  lib/Analytics/Piwik/Config/ConfigProvider.php
  lib/Analytics/Piwik/Dto/ReportConfig.php
  lib/Analytics/Piwik/Dto/WidgetConfig.php
  lib/Analytics/Piwik/Dto/WidgetReference.php
  lib/Analytics/Piwik/Event/ReportConfigEvent.php
  lib/Analytics/Piwik/Event/TrackingDataEvent.php
  lib/Analytics/Piwik/EventListener/CacheListener.php
  lib/Analytics/Piwik/EventListener/IndexSettingsListener.php
  lib/Analytics/Piwik/EventListener/TrackingCodeListener.php
  lib/Analytics/Piwik/ReportBroker.php
  lib/Analytics/Piwik/Tracker.php
  lib/Analytics/Piwik/WidgetBroker.php
  lib/Event/Analytics/PiwikEvents.php
  lib/Targeting/Condition/Piwik/VisitedPageBefore.php
  lib/Targeting/EventListener/PiwikVisitorIdListener.php
Labels: Task

#8218 egulias/email-validator: ^3.0.0
  composer.json
Labels: BC-BREAK

#8221 matomo/device-detector: ^4.0
  composer.json
  lib/Targeting/DataProvider/Device.php
Labels: Task

#8216 Remove Matomo Integration
  bundles/AdminBundle/Controller/Reports/PiwikController.php
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/analytics/piwik/widget_store_provider.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/piwik.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/piwik/dashboard_iframe.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/piwik/settings.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  bundles/CoreBundle/DependencyInjection/Compiler/DebugStopwatchPass.php
  bundles/CoreBundle/Migrations/Version20210218142556.php
  bundles/CoreBundle/Resources/config/analytics.yml
  bundles/CoreBundle/Resources/config/pimcore/default.yml
  bundles/CoreBundle/Resources/config/targeting.yml
  bundles/CoreBundle/Resources/config/targeting/listeners.yml
  bundles/CoreBundle/Resources/translations/en.extended.json
  bundles/CoreBundle/Resources/translations/en.json
  bundles/CoreBundle/Resources/views/Analytics/Tracking/Piwik/trackingCode.html.twig
  bundles/EcommerceFrameworkBundle/Controller/Reports/PiwikController.php
  bundles/EcommerceFrameworkBundle/Reports/Piwik/PiwikReportsProvider.php
  bundles/EcommerceFrameworkBundle/Resources/config/pimcore/config.yml
  bundles/EcommerceFrameworkBundle/Resources/config/services.yml
  bundles/EcommerceFrameworkBundle/Resources/config/tracking_manager.yml
  bundles/EcommerceFrameworkBundle/Resources/public/js/bundle.js
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/Piwik.php
  bundles/InstallBundle/Installer.php
  doc/Development_Documentation/10_E-Commerce_Framework/19_Tracking_Manager.md
  doc/Development_Documentation/18_Tools_and_Features/28_Marketing_Settings/07_Piwik.md
  doc/Development_Documentation/18_Tools_and_Features/28_Marketing_Settings/README.md
  doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/01_Visitor_Info.md
  doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/11_Frontend_Javascript.md
  lib/Analytics/Piwik/Api/ApiClient.php
  lib/Analytics/Piwik/Api/Exception/ApiException.php
  lib/Analytics/Piwik/Api/SitesManager.php
  lib/Analytics/Piwik/Api/VisitorClient.php
  lib/Analytics/Piwik/Config/Config.php
  lib/Analytics/Piwik/Config/ConfigProvider.php
  lib/Analytics/Piwik/Dto/ReportConfig.php
  lib/Analytics/Piwik/Dto/WidgetConfig.php
  lib/Analytics/Piwik/Dto/WidgetReference.php
  lib/Analytics/Piwik/Event/ReportConfigEvent.php
  lib/Analytics/Piwik/Event/TrackingDataEvent.php
  lib/Analytics/Piwik/EventListener/CacheListener.php
  lib/Analytics/Piwik/EventListener/IndexSettingsListener.php
  lib/Analytics/Piwik/EventListener/TrackingCodeListener.php
  lib/Analytics/Piwik/ReportBroker.php
  lib/Analytics/Piwik/Tracker.php
  lib/Analytics/Piwik/WidgetBroker.php
  lib/Event/Analytics/PiwikEvents.php
  lib/Targeting/Condition/Piwik/VisitedPageBefore.php
  lib/Targeting/DataProvider/Piwik.php
  lib/Targeting/EventListener/PiwikVisitorIdListener.php
Labels: BC-BREAK

#8222 ramsey/uuid: ^4.0
  composer.json
  models/Tool/UUID.php
Labels: Task

#8223 Use Symfony/Uuid instead of Ramsey/Uuid
  composer.json
  models/Tool/UUID.php
Labels: BC-BREAK

#8245 deprecated Elasticsearch 6 support
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/DefaultElasticSearch6.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch6.php
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#8247 Remove Elasticsearch v6 Support
  bundles/EcommerceFrameworkBundle/DependencyInjection/IndexService/DefaultWorkerConfigMapper.php
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/DefaultElasticSearch6.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/DefaultElasticSearch6.php
  bundles/EcommerceFrameworkBundle/Resources/config/index_service_configs_workers.yml
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: BC-BREAK, Task

#8251 [Ecommerce] Remove Legacy BatchProcessing workermode
  bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessPreparationQueueCommand.php
  bundles/EcommerceFrameworkBundle/Command/IndexService/ProcessQueueCommand.php
  bundles/EcommerceFrameworkBundle/Command/IndexService/ResetQueueCommand.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
  bundles/EcommerceFrameworkBundle/DependencyInjection/PimcoreEcommerceFrameworkExtension.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/ConfigInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/DefaultMysql.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/MysqlConfigInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/Tool/IndexUpdater.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/AbstractBatchProcessingWorker.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/BatchProcessingWorkerInterface.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/OptimizedMysql.php
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ProductCentricBatchProcessingWorker.php
  bundles/EcommerceFrameworkBundle/Resources/config/index_service_configs_workers.yml
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: BC-BREAK, Task

#8254 [Web2Print] deprecate PdfReactor8
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  doc/Development_Documentation/18_Tools_and_Features/30_Rendering_PDFs.md
  doc/Development_Documentation/26_Best_Practice/90_Web2Print_Extending_Config_for_PDFX_conformance.md
  lib/Web2Print/Processor.php
  lib/Web2Print/Processor/PdfReactor.php
  lib/Web2Print/Processor/PdfReactor8.php
  phpstan.neon
Labels: Task

#8259 [Web2Print] add client-API for PDFreactor 11
  bundles/AdminBundle/Resources/public/js/pimcore/settings/web2print.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Web2Print/Processor/PdfReactor.php
  lib/Web2Print/Processor/PdfReactor8.php
  lib/Web2Print/Processor/api/PDFreactor.class.php
  lib/Web2Print/Processor/api/v10.0/PDFreactor.class.php
  lib/Web2Print/Processor/api/v8.0/PDFreactor.class.php
  lib/Web2Print/Processor/api/v8.1/PDFreactor.class.php
  lib/Web2Print/Processor/api/v9.0/PDFreactor.class.php
  phpstan.neon
Labels: BC-BREAK, Task

#8258 Fixed cache warmer if Pimcore isn't set up yet
  lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php
Labels: Bug

#8267 Fix recycle-bin restore for objects with non-existent parent
  models/Element/Recyclebin/Item.php
Labels: Bug

#8263 fix twig 3.0 bc breaks
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/detail.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/list.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/back-office.html.twig
  bundles/EcommerceFrameworkBundle/Resources/views/voucher/voucher_layout.html.twig
Labels: Bug

#8280 Deprecate JWT Decoder
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Targeting/Storage/Cookie/JWT/Decoder.php
Labels: Task

#8273 composer.json: suggest Imagick Version ^3.2.0
  composer.json
Labels: BC-BREAK

#8276 [Core] Security - mark BruteforceProtectionHandler internal
  bundles/AdminBundle/Controller/BruteforceProtectedControllerInterface.php
  bundles/AdminBundle/EventListener/BruteforceProtectionListener.php
  bundles/AdminBundle/Security/BruteforceProtectionHandler.php
  bundles/AdminBundle/Security/Exception/BruteforceProtectionException.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#8279 Bump lcobucci/jwt to ^4.0
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Targeting/Storage/Cookie/JWT/Decoder.php
  lib/Targeting/Storage/Cookie/JWTCookieSaveHandler.php
Labels: BC-BREAK, Task

#8286 added file uri scheme in mail helper for absolute paths
  lib/Helper/Mail.php
Labels: Improvement
