Repository pimcore/pimcore, pull requests merged in 2022-09, with the labels that each got.

#12853 [Improvement]: Generate return types for setters in data objects
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/DataObject/ClassBuilder/ObjectBrickContainerClassBuilder.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  tests/Model/DataObject/ClassDefinitionTest.php
Labels: Improvement

#13032 [Task]: Remove Pimcore\Config\Config, adds missing $config assignment on cache init
  lib/Config.php
Labels: Task

#12779 [Core] Migrate Custom Layout definition files to use LocationAwareConfigRepository
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
  bundles/CoreBundle/Command/CustomLayoutRebuildCommand.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Migrations/Version20220617145524.php
  bundles/CoreBundle/Migrations/Version20220809154926.php
  bundles/CoreBundle/Resources/config/commands.yaml
  bundles/CoreBundle/Resources/config/services.yaml
  bundles/InstallBundle/Installer.php
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Bootstrap.php
  lib/Kernel.php
  lib/Model/DataObject/ClassDefinition/ClassLayoutDefinitionManager.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
  models/DataObject/ClassDefinition/CustomLayout/Listing.php
  models/DataObject/ClassDefinition/CustomLayout/Listing/Dao.php
  stubs/dynamic-constants.php
  tests/_bootstrap.php
Labels: Task, BC-BREAK

#13033 Docs - Refactor IAM permissions from AWS S3 setup docs
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/03_File_Storage_Setup.md
Labels: Bug, Task

#13045 Fix new PhpStan errors
  bundles/InstallBundle/Installer.php
  composer.json
  lib/Twig/Extension/Templating/HeadStyle.php
  models/DataObject/ClassDefinition/Data/InputQuantityValue.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/Tool/CustomReport/Adapter/Sql.php
  phpstan-baseline.neon
Labels: Bug

#13055 [Bug]: Unable to create Data Object class
  models/DataObject/ClassDefinition.php
Labels: Bug

#13056 [Bug]: Installer fails because of incorrect quotes
  lib/Tool/Requirements.php
Labels: Bug

#13035 [DataObject] Video - Fix adding multiple video data types & container enrichment
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/video.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/video.js
  models/DataObject/ClassDefinition/Data/Video.php
Labels: Bug

#13029 Update thumbnail forwarding path for docs
  doc/Development_Documentation/04_Assets/07_Restricting_Public_Asset_Access.md
Labels: Bug

#13060 Fix issue with trying to get cart with empty id when setting values
  bundles/EcommerceFrameworkBundle/CartManager/AbstractCartItem.php
Labels: Bug

#13058 Remove MissingDependencyException
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Exception/MissingDependencyException.php
Labels: Improvement, BC-BREAK

#13030 [Task]: Remove ReverseManyToManyObjectRelation alias
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/ReverseManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
Labels: Task, BC-BREAK

#13039 Log error and return null when ffmpeg couldn't read dimensions/duration
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
  lib/Video/Adapter.php
  lib/Video/Adapter/Ffmpeg.php
  models/Asset/Video.php
Labels: Bug

#13018 [Workflows] Add option to define what to do with unsaved changes when applying a transition
  bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/07_Workflow_Management/01_Configuration_Details/README.md
  lib/Workflow/ActionsButtonService.php
  lib/Workflow/Transition.php
Labels: Improvement

#13059 [Maintenance] Deprecate --force param in command
  bundles/CoreBundle/Command/MaintenanceCommand.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#12992 [Task]: Add Migration command for LocationAwareConfigRepository
  bundles/CoreBundle/Migrations/Version20220829132224.php
Labels: Task

#12994 [Task]: Remove legacy config support from LocationAwareConfigRepository
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Config/LocationAwareConfigRepository.php
  lib/CustomView/Config.php
  lib/Model/Dao/PimcoreLocationAwareConfigDao.php
  lib/Perspective/Config.php
  lib/Web2Print/Config.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Video/Thumbnail/Config/Dao.php
  models/Document/DocType/Dao.php
  models/Metadata/Predefined/Dao.php
  models/Property/Predefined/Dao.php
  models/Staticroute/Dao.php
  models/Tool/CustomReport/Config/Dao.php
Labels: Task

#13068 Add upgrade note for deprecated MissingDependencyException
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#13080 Add upgrade note for getRootDir()
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Bug

#13012 [Task]: Removing deprecated getMasterRequest, in favor of getMainRequest
  bundles/CoreBundle/EventListener/Frontend/DocumentFallbackListener.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Http/Request/Resolver/AbstractRequestResolver.php
  lib/Http/RequestHelper.php
  lib/Localization/LocaleService.php
  models/Document.php
Labels: Task

#12995 [Assets] Auto create upload path if not exist
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  doc/Development_Documentation/03_Documents/01_Editables/14_Image.md
Labels: Improvement

#13046 Add upgrade notes for the second parameter in getByPath() method
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Bug

#13048 Page Snippet - Add validate param to setContentMasterDocumentId()
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Document/PageSnippet.php
Labels: Task, BC-BREAK

#13050 [Reports] Support selecting functions without alias
  models/Tool/CustomReport/Adapter/Sql.php
Labels: Bug

#13042 [Maintenance] Removed --async option
  bundles/CoreBundle/Command/MaintenanceCommand.php
  bundles/CoreBundle/Resources/config/maintenance.yaml
  doc/Development_Documentation/01_Getting_Started/00_Installation.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Maintenance/Executor.php
  lib/Maintenance/ExecutorInterface.php
  lib/Messenger/Handler/MaintenanceTaskHandler.php
  lib/Messenger/MaintenanceTaskMessage.php
Labels: Task, BC-BREAK

#13011 [Task]: Remove pimcoreglossary tag
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/README.md
  doc/Development_Documentation/18_Tools_and_Features/21_Glossary.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Twig/Extension/GlossaryExtension.php
  lib/Twig/Node/GlossaryNode.php
  lib/Twig/TokenParser/GlossaryTokenParser.php
Labels: Task

#13044 [Assets] Image editor for non-browser-compatible images did not work
  bundles/AdminBundle/Resources/views/Admin/Asset/imageEditor.html.twig
Labels: Bug

#12982 Removed deprecated and legacy iframe attributes, added title, allow, and data-type
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Document/Editable/Video.php
Labels: Improvement, BC-BREAK

#13053 Remove force boolean param
  bundles/EcommerceFrameworkBundle/OfferTool/AbstractOfferToolProduct.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/Service.php
Labels: Improvement, BC-BREAK

#13100 Changing tab-bar color to make scrolling arrows visible
  bundles/AdminBundle/Resources/public/css/ext-modifications.css
Labels: Bug

#13076 [Bug]: Missing context in grouped objectbricks
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
Labels: Bug

#13103 Fix height of classification store groups
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
Labels: Bug

#13069 fix: if error_pages undef, exception render uses invalid keys
  bundles/CoreBundle/EventListener/ResponseExceptionListener.php
Labels: Bug

#13061 [Improvement] Concrete::__callStatic should support variants
  doc/Development_Documentation/05_Objects/03_Working_with_PHP_API.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/DataObject/ClassBuilder/ClassBuilder.php
  models/DataObject/AbstractObject.php
  models/DataObject/Concrete.php
Labels: Improvement, BC-BREAK

#13022 [Task]: Remove Workflows classes
  config/dao-classmap.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Workflow.php
  models/Workflow/Dao.php
  models/Workflow/Listing.php
  models/Workflow/Listing/Dao.php
Labels: Task, BC-BREAK

#13114 fix: cache warmer must not use the database or application cache
  lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php
Labels: Bug

#13070 [Bug]: Overriding "From" in newsletter for test mail does not work
  bundles/AdminBundle/Controller/Admin/EmailController.php
Labels: Bug

#13136 Use hash_equals() rather than direct string comparison for password fields
  models/DataObject/ClassDefinition/Data/Password.php
Labels: Bug

#13116 Reflect latest skeleton nginx config changes in the docs
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Labels: Task

#13129 [Admin] escape values on UI
  bundles/AdminBundle/Resources/public/js/pimcore/element/properties.js
  bundles/AdminBundle/Resources/public/js/pimcore/notification/helper.js
  bundles/AdminBundle/Resources/public/js/pimcore/notification/panel.js
Labels: Bug

#13075 [DataObject] Owner Info is missing on denormalize for Geo DataTypes
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
  models/DataObject/ClassDefinition/Data/Geopolygon.php
  models/DataObject/ClassDefinition/Data/Geopolyline.php
  tests/Model/DataType/NormalizerTest.php
Labels: Bug

#13078 Removed Kernel::getRootDir
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Kernel.php
Labels: Task, BC-BREAK

#12907 [Feature][DataObject] add title to class definition
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
  doc/Development_Documentation/05_Objects/01_Object_Classes/README.md
  models/DataObject/ClassDefinition.php
Labels: Improvement

#13073 [Recycle bin] Add date index
  bundles/CoreBundle/Migrations/Version20220906111031.php
  bundles/InstallBundle/Resources/install.sql
Labels: Improvement

#13145 [BUG] wrong translation of title and description xliff-Export -- fixed
  lib/Translation/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
Labels: Bug

#13097 [Core] composer.json: Cleanup Symfony packages
  .github/ci/scripts/symfony-require-dev.sh
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Localization/IntlFormatter.php
Labels: Task, BC-BREAK

#13065 [Admin] JS events - Fix param names for events
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/metadata/editor.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/email.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/folder.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/hardlink.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/link.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/newsletter.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/page.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/page_snippet.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/printabstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/snippet.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/events.js
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
Labels: Bug

#13171 [Tests] Fix GeoBounds test by stripping fixtures
  tests/_support/Helper/DataType/TestDataHelper.php
Labels: Bug

#12742 improvement: don't catch exceptions in ClassResolver
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Helper/ClassResolver.php
Labels: BC-BREAK

#13148 Removed deprecated property $types from Documents
  doc/Development_Documentation/03_Documents/09_Working_with_PHP_API.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Document.php
Labels: Task, BC-BREAK

#13124 [Unit Conversion] Do not use ContainerInterface
  models/DataObject/ClassDefinition/Helper/UnitConverterResolver.php
  models/DataObject/QuantityValue/UnitConversionService.php
Labels: Task, BC-BREAK

#13179 [Task]: Migration class name not matching the filename
  bundles/CoreBundle/Migrations/Version20220829132224.php
Labels: Task

#13084 [TASK]: Remove "childs" bc layer
  bundles/AdminBundle/src/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/src/Controller/Admin/Document/DocumentController.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Layout.php
Labels: Task, BC-BREAK

#13016 [Task]: Remove PhpArrayTable
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Model/Dao/PhpArrayTable.php
Labels: Task, BC-BREAK

#13183 Navigation Builder shouldn't load from Cache if cache is disabled
  lib/Navigation/Builder.php
Labels: Bug

#13182 Add upgrade Note
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#13187 AdvancedManyToManyObjectRelation: Cast to boolean
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
Labels: Improvement

#13144 [Feature][DataObject] add confirm dialog to delete in manyToManyRelation
  bundles/AdminBundle/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/manyToManyRelation.js
Labels: Improvement

#13175 chore: add deprecation warning for class resolver exceptions
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Helper/ClassResolver.php
Labels: Task

#13160 [Calculated value fields] In grid view do not strip HTML tags if display type is "HTML"
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/calculatedValue.js
Labels: Bug

#13180 Fix demo link in docs
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/01_Authenticate_Pimcore_Objects.md
Labels: Bug

#13185 [Improvement][Dataobject] Add possiblity to disable creation of new object in reverseRelation
  bundles/AdminBundle/public/js/pimcore/object/classes/data/reverseObjectRelation.js
Labels: Improvement

#13192 [Task]: Encode `path` column in Users > Workspaces
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/workspace/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/workspace/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/user/workspace/object.js
Labels: Task

#13093 [Data objects] Dynamically update select fields options when using dynamic options provider
  bundles/AdminBundle/public/js/pimcore/object/tags/multiselect.js
  bundles/AdminBundle/public/js/pimcore/object/tags/select.js
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
  bundles/CoreBundle/Resources/translations/en.json
  models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php
Labels: Improvement

#12831 Fix VR video viewer
  bundles/AdminBundle/public/js/pimcore/asset/video.js
Labels: Bug

#13177 Remove the BC layer which allows the getNavigation() method call with extra arguments
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Navigation/Builder.php
Labels: Task, BC-BREAK

#13172 Fix external link detection in link edit panel
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#13117 Remove useless exception handling in Area(Block)::buildInfoObject()
  models/Document/Editable/Area.php
  models/Document/Editable/Areablock.php
Labels: Task

#13157 [Docs / Wysiwyg fields] Fix wysiwyg editor example config
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/wysiwyg.js
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/95_Text_Types.md
Labels: Bug

#13164 Fieldcollection/Objectbrick/CustomLayout/Bulk Export: Cleanup BlockedVars and Dynamic Options like ClassDefinition
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  models/DataObject/ClassDefinition/Service.php
Labels: Bug

#13225 Add support for 2FA with new authenticator
  bundles/AdminBundle/EventListener/TwoFactorListener.php
  bundles/AdminBundle/Security/Authentication/Token/TwoFactorRequiredToken.php
  bundles/CoreBundle/Resources/config/authenticator_security.yaml
  composer.json
Labels: Bug

#12800 Refactored getMetadata method of Asset to include unused parameters
  doc/Development_Documentation/04_Assets/01_Working_with_PHP_API.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
  tests/Model/Asset/Metadata/NormalizerTest.php
Labels: Improvement

#13165 [InstallBundle] Refactored as per modern bundle structure
  bundles/InstallBundle/config/config.yaml
  bundles/InstallBundle/config/services.yaml
  bundles/InstallBundle/dump/install.sql
  bundles/InstallBundle/src/Command/InstallCommand.php
  bundles/InstallBundle/src/DependencyInjection/Configuration.php
  bundles/InstallBundle/src/DependencyInjection/PimcoreInstallExtension.php
  bundles/InstallBundle/src/Event/InstallerStepEvent.php
  bundles/InstallBundle/src/Installer.php
  bundles/InstallBundle/src/InstallerKernel.php
  bundles/InstallBundle/src/PimcoreInstallBundle.php
  bundles/InstallBundle/src/SystemConfig/ConfigWriter.php
  composer.json
Labels: Task, BC-BREAK

#13205 [Reverse object relation] Do not allow to search for folders
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseObjectRelation.js
Labels: Bug

#13188 Fix: DataObjectController::updateAction()
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#13213 [Assets] Support uploading files whose MIME-Type cannot be determined
  models/Asset.php
Labels: Bug

#13229 [Bug] listing getTotalCount() column already exists
  lib/Model/Listing/Dao/QueryBuilderHelperTrait.php
Labels: Bug

#13221 [Docs] Fix workflow tutorial
  doc/Development_Documentation/07_Workflow_Management/05_Workflow_Tutorial.md
Labels: Bug

#13151 Make editmodeImagePreview available for YouTube videos
  models/Document/Editable/Video.php
Labels: Bug

#13130 [Improvement]: Add multiselect filtering support on grid for classification store
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug
