Repository pimcore/pimcore, pull requests merged in 2022-01, with the labels that each got.

#11039 [Assets] Close stream when saving
  models/Asset.php
Labels: Bug

#11125 Fix: [Bug]: SQL exception on obscure URL with encoded entities
  models/Document/Dao.php
Labels: Bug

#11123 Added recyclebin cleanup command
  bundles/CoreBundle/Command/RecyclebinCleanupCommand.php
Labels: Improvement, New Feature

#11127 [Imagick] Performance optimization for detecting clipping paths
  lib/Image/Adapter/Imagick.php
Labels: Improvement

#11126 [LocationAwareConfig] Cleanup cache when saving or deleting configuration
  lib/Model/Dao/PimcoreLocationAwareConfigDao.php
Labels: Bug

#11089 Added svg icons inline to html in order to reduce concurrent requests
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/MiscController.php
  bundles/AdminBundle/Resources/views/Admin/Misc/iconList.html.twig
  lib/Twig/Extension/AdminExtension.php
Labels: Improvement

#11121 [Asset] Provide option to disable image optimizers on thumbnails
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset/Image/Thumbnail/Processor.php
Labels: Bug

#11009 ElementInterface: add setParent method as annotation
  models/Element/ElementInterface.php
Labels: Task

#11133 [Documents] Possibility to configure an URL prefix for generating the preview
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  models/Document/Service.php
Labels: Task

#11111 Fix getChildren/hasChildren/getSiblings/hasSiblings on unsaved new models
  models/Asset.php
  models/Asset/Dao.php
  models/Asset/Folder.php
  models/DataObject/AbstractObject.php
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/Classificationstore/GroupConfig.php
  models/DataObject/Classificationstore/GroupConfig/Dao.php
  models/Document.php
  models/Document/Dao.php
  models/Element/Tag.php
  models/User/AbstractUser/Dao.php
  models/User/Folder.php
  models/User/UserRole/Folder.php
Labels: Bug

#11146 Fix `preg_match()` usage in condition
  lib/Navigation/Container.php
Labels: Bug

#11156 [Objects] Tree order by "index": validate sort order
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#11143 Fix: Unable to edit/save a document when it contains an empty property of type document/object
  models/Asset/Service.php
  models/DataObject/AbstractObject.php
  models/DataObject/Service.php
  models/Document.php
  models/Document/Service.php
Labels: Bug

#11164 [Mail settings check] check for debug mail addresses only in debug mode
  bundles/AdminBundle/Controller/Admin/IndexController.php
Labels: Improvement

#10087 [Data Objects] Save default values to versions
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Fieldcollection/Data/Dao.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
  tests/Model/DataObject/ObjectTest.php
  tests/Model/DataType/BlockTest.php
  tests/_support/Helper/Model.php
  tests/_support/Resources/objects/class-import.json
Labels: Improvement

#11159 ON DUPLICATE KEY UPDATE will set row id to 0 if 2 processes try to insert the same value at the same time
  lib/Db/PimcoreExtensionsTrait.php
Labels: Bug

#11180 [DB] Added PK cache to DB insertOrUpdate()
  lib/Db/PimcoreExtensionsTrait.php
Labels: Improvement

#11172 Parameter &?pimcore_nocache dosn't work
  bundles/CoreBundle/Resources/config/cache.yaml
Labels: Bug

#11165 Remove superfluous `array_merge()` call
  lib/Db/PimcoreExtensionsTrait.php
Labels: Bug

#11177 [Image gallery] Only load image gallery items with an image / Remove gallery item when deleting image asset
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  tests/_support/Helper/DataType/TestDataHelper.php
Labels: Bug

#11148 PimcoreLocationAwareConfigDao: Possibility to set defaultWriteLocation
  lib/Model/Dao/PimcoreLocationAwareConfigDao.php
Labels: Improvement

#11134 Composer: Bump requirements to the lowest possible version
  composer.json
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
Labels: Improvement

#11137 Wrong website settings in multi site environment
  models/WebsiteSetting/Dao.php
  phpstan-bootstrap.php
  tests/Model/WebsiteSetting/WebsiteSettingTest.php
  tests/_bootstrap.php
Labels: Bug

#11195 Fix: Decode quotation marks to make exact search working
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
Labels: Bug

#11141 Fix: Predefined Properties doesn't respect ctype
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  lib/Model/Listing/JsonListing.php
  models/Asset/Image/Thumbnail/Config/Listing/Dao.php
  models/Document/DocType/Listing/Dao.php
  models/Metadata/Predefined/Listing/Dao.php
  models/Property/Predefined/Listing/Dao.php
  models/Staticroute/Listing/Dao.php
Labels: Bug

#11149 Optimize finding active pages when building the navigation
  lib/Navigation/Builder.php
  lib/Navigation/Iterator/PrefixRecursiveFilterIterator.php
Labels: Improvement

#11168 [Translations] follow up to #10979
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translationEditor.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/06_Multi_Language_i18n/04_Shared_Translations.md
  doc/Development_Documentation/img/translation_pluralization1.png
  doc/Development_Documentation/img/translation_pluralization1b.png
  models/Translation.php
Labels: Improvement, Bug

#11203 [Ecommerce] Validate pricing rule names
  bundles/CoreBundle/Resources/translations/en.json
  bundles/EcommerceFrameworkBundle/Controller/PricingController.php
  bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/panel.js
Labels: Bug

#11202 [Custom Reports] Validate & escape CSS classes and names
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/item.js
Labels: Bug

#11206 [Ecommerce] Discounts shouldn't be negative
  bundles/EcommerceFrameworkBundle/PricingManager/Action/CartDiscount.php
  bundles/EcommerceFrameworkBundle/PricingManager/Action/ProductDiscount.php
  bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js
Labels: Bug

#11218 [Bug] Headless Chrome settings not read
  lib/Web2Print/Processor/HeadlessChrome.php
Labels: Bug

#11217 disallow html entity names on import
  models/DataObject/ClassDefinition/Service.php
Labels: Bug

#11204 [Data Object] Classification Store quote filtering
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
Labels: Bug

#11207 [Thumbnail] Validate media query name
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
Labels: Bug

#11205 [Targeting] Escape/validate names of rules properly
  bundles/AdminBundle/Controller/Admin/TargetingController.php
Labels: Bug

#11208 [Settings] Validate SVG uploads for branding
  bundles/AdminBundle/Controller/Admin/SettingsController.php
Labels: Bug

#11170 fixed custom report bar and line chart labels, as well as tooltips
  bundles/AdminBundle/Resources/public/js/pimcore/layout/portlets/customreports.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
Labels: Bug

#11225 [Thumbnails] Escape group text properly
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/thumbnail/item.js
Labels: Bug

#11226 Document Types list breaks when showing creation or modification date
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
Labels: Bug

#11211 [Documents] Added NGINX configuration docs
  doc/Development_Documentation/19_Development_Tools_and_Details/20_Static_Page_Generator.md
Labels: Task

#11241 [Docs] SettingsStore: Fix wrong param order
  doc/Development_Documentation/19_Development_Tools_and_Details/42_Settings_Store.md
Labels: Bug

#11219 [GridConfig] Use foreign keys for ON DELETE #10654
  bundles/CoreBundle/Migrations/Version20220119082511.php
  bundles/InstallBundle/Resources/install.sql
  models/GridConfig.php
Labels: Improvement

#11236 [Documents] Use foreign keys for ON DELETE
  bundles/CoreBundle/Migrations/Version20220120121803.php
  bundles/InstallBundle/Resources/install.sql
  models/Document/Email/Dao.php
  models/Document/Hardlink/Dao.php
  models/Document/Link/Dao.php
  models/Document/Newsletter/Dao.php
  models/Document/Page.php
  models/Document/Page/Dao.php
  models/Document/PageSnippet/Dao.php
  models/Document/Service/Dao.php
  models/Document/Snippet/Dao.php
Labels: Improvement

#11238 [User Workspaces] Use foreign keys for ON DELETE
  bundles/CoreBundle/Migrations/Version20220120162621.php
  bundles/InstallBundle/Resources/install.sql
  models/Asset.php
  models/Asset/Dao.php
  models/DataObject/AbstractObject.php
  models/DataObject/AbstractObject/Dao.php
  models/Document.php
  models/Document/Dao.php
  models/User/Dao.php
Labels: Improvement

#11214 Copy DataObject: Check also localized fields for unique
  models/DataObject/Service.php
Labels: Bug

#11258 [BugFix]: Layout Element "Text" fails to load in object class configuration (settingsconfiguration) #11188
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/text.js
Labels: Bug

#11260 ClassDefinition Import ignores previewGeneratorReference, showFieldLookup and enableGridLocking
  models/DataObject/ClassDefinition/Service.php
Labels: Bug

#11263 PhpStan: Generate baseline on failure
  .github/workflows/static-analysis.yml
Labels: Improvement

#11221 Sorting bug in classification store
  models/DataObject/ClassDefinition/Data/Classificationstore.php
Labels: Bug

#11262 [Perspective] Omit "not allowed perspective"-warning with perspective as GET
  bundles/AdminBundle/EventListener/UserPerspectiveListener.php
Labels: Bug

#11239 Fix insertOrUpdate on tables without primary keys
  lib/Db/PimcoreExtensionsTrait.php
Labels: Bug

#11261 [Documents] Refactor page preview generation to queue in Page::save()
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/page.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  models/Document/Page.php
Labels: Improvement

#11252 Set Layout properties to internal
  models/DataObject/ClassDefinition/Layout.php
  models/DataObject/ClassDefinition/Layout/Accordion.php
  models/DataObject/ClassDefinition/Layout/Button.php
  models/DataObject/ClassDefinition/Layout/Fieldcontainer.php
  models/DataObject/ClassDefinition/Layout/Fieldset.php
  models/DataObject/ClassDefinition/Layout/Iframe.php
  models/DataObject/ClassDefinition/Layout/Panel.php
  models/DataObject/ClassDefinition/Layout/Region.php
  models/DataObject/ClassDefinition/Layout/Tabpanel.php
  models/DataObject/ClassDefinition/Layout/Text.php
Labels: Task

#11271 [Bug][Dashboards] Buttons of Portlets are not clearly visible
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/css/ext-modifications.css
Labels: Bug

#11279 added escape function to the icon field
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
Labels: Task

#11257 [Doc] Add custom logo migration to Update Notes
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
Labels: Bug

#11250 FIX: invisible fields saved incorectly when fieldcollections swap places
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
Labels: Bug

#11300 Fix: Recyclebin delete on null
  bundles/AdminBundle/Controller/Admin/RecyclebinController.php
Labels: Bug

#11298 Fix: Version delete handler log
  lib/Messenger/Handler/VersionDeleteHandler.php
Labels: Bug

#11299 Fix: Undefined array key in editable link
  models/Document/Editable/Link.php
Labels: Bug

#11291 [Assets] Handle exceptions thrown by PDO adapter when rolling back a transaction
  models/Asset.php
Labels: Bug

#11312 fix select search
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
Labels: Bug

#11020 [Assets] Add dialog to overwrite assets on upload
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: New Feature

#11273 Fix Migration fails due to foreign key constraints
  bundles/CoreBundle/Migrations/Version20211018104331.php
  bundles/CoreBundle/Migrations/Version20211221152344.php
  bundles/CoreBundle/Migrations/Version20220119082511.php
  bundles/CoreBundle/Migrations/Version20220120162621.php
Labels: Bug

#11313 Add missing backslash in front of FQCN in the docs
  doc/Development_Documentation/04_Assets/01_Working_with_PHP_API.md
Labels: Task
