Repository pimcore/pimcore, pull requests merged in 2022-02, with the labels that each got.

#11269 [Docs] Configuration Storage Locations - revalidating existing configurations on prod
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
Labels: Improvement

#11303 Fix: Exception thrown in "Search Assets" window
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
Labels: Bug

#11302 Fix: "Predefined Document Type"-Select not working
  bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
Labels: Bug

#11292 [DataObjects] Handle exceptions thrown by PDO adapter when rolling back a transaction
  models/DataObject/AbstractObject.php
  models/DataObject/Localizedfield/Dao.php
Labels: Bug

#11142 Feature: Typeahead for Predefined Property ComboBox
  bundles/AdminBundle/Controller/Admin/ElementController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/properties.js
Labels: Improvement

#11309 making sure that ownerClassId in Reverse Object Relation has legacy data, to avoid null error
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
Labels: Bug

#11286 Delete unused `DocumentStack` and `DocumentStackListener`
  bundles/CoreBundle/EventListener/Frontend/DocumentStackListener.php
  bundles/CoreBundle/Resources/config/documents.yaml
  bundles/CoreBundle/Resources/config/event_listeners.yaml
  lib/Document/DocumentStack.php
Labels: Task

#11334 Minor edits to README
  README.md
  doc/README.md
Labels: Task

#11318 data object tab reload, maskEl error
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
Labels: Bug

#11296 [Tests] Git should ignore object resources
  .gitignore
  tests/_support/Helper/ClassManager.php
  tests/_support/Resources/objects/block-import.json
  tests/_support/Resources/objects/brick-import.json
  tests/_support/Resources/objects/class-allfields.json
  tests/_support/Resources/objects/class-import.json
  tests/_support/Resources/objects/classificationstore.json
  tests/_support/Resources/objects/fieldcollection-import.json
  tests/_support/Resources/objects/inheritance.json
  tests/_support/Resources/objects/lazyloading/class_LazyLoading_export.json
  tests/_support/Resources/objects/lazyloading/fieldcollection_LazyLoadingLocalizedTest_export.json
  tests/_support/Resources/objects/lazyloading/fieldcollection_LazyLoadingTest_export.json
  tests/_support/Resources/objects/lazyloading/objectbrick_LazyLoadingLocalizedTest_export.json
  tests/_support/Resources/objects/lazyloading/objectbrick_LazyLoadingTest_export.json
  tests/_support/Resources/objects/relations/class_MultipleAssignments_export.json
  tests/_support/Resources/objects/relations/class_RelationTest_export.json
Labels: Task

#11233 [DataObjects] Remove @internal from getRelationData()
  models/DataObject/Concrete.php
Labels: Task

#11145 Remove unnecessary `iterator_to_array()` call in `Pimcore\Navigation\Container::addPages()`
  lib/Navigation/Container.php
Labels: Task

#11254 #11144: adding cache invalidation for classification store KeyConfig
  lib/Cache/RuntimeCacheTrait.php
  models/DataObject/Classificationstore/CollectionConfig.php
  models/DataObject/Classificationstore/GroupConfig.php
  models/DataObject/Classificationstore/KeyConfig.php
Labels: Bug

#11270 classification store getter must not load store from parent object
  bundles/CoreBundle/Migrations/Version20220201132131.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  tests/Model/Inheritance/ClassificationstoreTest.php
  tests/_support/Helper/Model.php
Labels: Bug

#11265 Search and move improvement (#11110)
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/asset.js
Labels: Improvement

#11147 Don't add the same page multiple times in `Pimcore\Navigation\Container::findAllBy()`
  lib/Navigation/Container.php
Labels: Bug

#11268 [DataObject] Link fields accept strings
  models/DataObject/ClassDefinition/Data/Link.php
  tests/Model/DataType/BlockTest.php
  tests/Model/DataType/LinkTest.php
  tests/_support/Helper/Model.php
Labels: Bug

#11326 fixing bug for create method on classification store group and collec…
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Classificationstore/CollectionGroupRelation.php
  models/DataObject/Classificationstore/KeyGroupRelation.php
Labels: Bug

#11189 Pass editmode as attribute to document render events
  lib/Document/Renderer/DocumentRenderer.php
Labels: Improvement

#11336 Fix issue #11327 (rebased)
  models/DataObject/ClassDefinition/Data/UrlSlug.php
Labels: Bug

#11367 Fix current phpstan error
  .github/ci/scripts/symfony-require-dev.sh
Labels: Bug

#10824 Fix: Deprecations with childs properties
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/ElementControllerBase.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/gridConfigDialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/asset/helpers/metadataTree.js
  bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/data.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/structuredTable.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/layout.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridConfigDialog.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/layout.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
  bundles/CoreBundle/Migrations/Version20211117173000.php
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_FilterDefinition_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolCustomProduct_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOfferItem_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOffer_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrderItem_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopTaxClass_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherSeries_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherToken_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterCategoryMultiselect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterCategory_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterInputfield_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterMultiRelation_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterMultiSelectFromMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterNumberRangeSelection_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterNumberRange_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterRelation_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterSelectClsStoreAttributes_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterSelectFromMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_OrderByFields_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_OrderPriceModifications_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_PaymentInfo_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_PricingRule_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_SimilarityField_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_TaxEntry_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_VoucherTokenTypePattern_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_VoucherTokenTypeSingle_export.json
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Layout.php
  models/DataObject/ClassDefinition/Service.php
  models/Element/ChildsCompatibilityTrait.php
Labels: Improvement

#11365 [Documents] fix Listing cachekey empty string
  models/Document.php
Labels: Bug

#11389 Remove legacy piwik settings check
  bundles/AdminBundle/Controller/Reports/SettingsController.php
Labels: Bug

#11388 Fix: db.inc.php:89 - Warning: Cannot modify header information - head…
  bundles/AdminBundle/Controller/Admin/External/AdminerController.php
Labels: Bug

#11369 Fix messenger configuration
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
Labels: Bug

#11394 [Asset] Fix for setting the focal point in the admin ui
  bundles/AdminBundle/Resources/public/css/admin.css
Labels: Bug

#11395 [Asset] only run facedetect if source thumbnail exists
  models/Asset/Image.php
Labels: Bug

#11364 [Custom Report] Allow . in niceName/group fields
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/item.js
Labels: Improvement

#11348 Added information about calling getImageTag
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
Labels: Improvement

#11408 Fixed the bug concerning missing data in city array for geoip targeting
  lib/Targeting/Condition/Country.php
Labels: Bug

#11406 Fix for PIMCORE_CONFIG_STORAGE_DIR_ env variables
  lib/Perspective/Config.php
  models/Asset/Video/Thumbnail/Config/Dao.php
  models/Staticroute/Dao.php
Labels: Bug

#11405 [Improvement]: Documentation for config storage path - follow up
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
Labels: Improvement

#11409 Allow to open log file object when using custom PIMCORE_PRIVATE_VAR
  bundles/AdminBundle/Controller/Admin/LogController.php
Labels: Bug

#11402 Fix mimetype guessing for PSDs when used AWS S3 as storage
  models/Asset.php
Labels: Bug

#11401 Fix pdf preview generation for documents with non-local storage
  lib/Document/Adapter/LibreOffice.php
Labels: Bug

#11342 add method Relations to class collectionConfig
  models/DataObject/Classificationstore/CollectionConfig.php
Labels: Improvement

#11343 Fix for exception in Table.php
  models/DataObject/ClassDefinition/Data/Table.php
Labels: Bug

#11417 fix object reload and maskEl error
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
Labels: Bug

#11436 [Improvement] Show unpublished elements in dependency-list consistently with line-through
  bundles/AdminBundle/Resources/public/js/pimcore/element/dependencies.js
  models/Element/Service.php
Labels: Bug

#11432 asset tmp file to be created on local instead of the flysystem
  models/Asset.php
Labels: Improvement

#11399 [Messenger] Process certain messages in batches to speed things up
  composer.json
  lib/Messenger/Handler/CleanupThumbnailsHandler.php
  lib/Messenger/Handler/HandlerHelperTrait.php
  lib/Messenger/Handler/OptimizeImageHandler.php
  lib/Messenger/Handler/SanityCheckHandler.php
  lib/Messenger/Handler/SearchBackendHandler.php
  lib/Messenger/Handler/VersionDeleteHandler.php
Labels: Improvement

#11439 Fix: translation CSV download ignoring filters
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
Labels: Bug

#11443 Remove duplicate function call
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseObjectRelation.js
Labels: Bug

#11445 [Docs] Cache config file needs to be put in local/ folder to get loaded with default config.yaml
  doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/09_Performance_Guide.md
Labels: Bug

#11418 Tool::getHostname() -> return configured website domain when not in HTTP request context
  lib/Tool.php
Labels: Bug

#11435 Fix Deprecations from Codeception/Symfony
  bundles/AdminBundle/EventListener/GridConfigListener.php
  bundles/AdminBundle/EventListener/ImportConfigListener.php
  bundles/CoreBundle/EventListener/ElementTagsListener.php
  bundles/CoreBundle/EventListener/UUIDListener.php
  bundles/EcommerceFrameworkBundle/EventListener/IndexUpdateListener.php
  codeception.dist.yml
  lib/Console/Application.php
  lib/Mail.php
  lib/Session/Attribute/LockableAttributeBag.php
  lib/Tool/DomCrawler.php
  lib/Twig/TokenParser/AssetCompressParser.php
  lib/Twig/TokenParser/GlossaryTokenParser.php
Labels: Bug

#11442 Remove forbidden names from definition file
  models/DataObject/ClassDefinition/Data.php
Labels: Bug

#11387 [Admin] Escape properties properly
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js
Labels: Bug

#11410 [QuantityValue] Add convenience method for quantity value unit conversion
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/55_Number_Types.md
  models/DataObject/Data/AbstractQuantityValue.php
  models/DataObject/QuantityValue/UnitConversionService.php
Labels: Improvement

#11453 composer.json: enshrined/svg-sanitize: ^0.15.0
  composer.json
Labels: Bug

#11420 [Translations] Only auto-create if currently no translation for key exists -> not on every exception
  models/Translation.php
  models/Translation/Dao.php
Labels: Bug

#11358 Fix deprecations with jsonSerialize() methods
  bundles/AdminBundle/HttpFoundation/JsonResponse.php
  bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelectionCombo.php
  bundles/EcommerceFrameworkBundle/Tracking/AbstractData.php
  doc/Development_Documentation/26_Best_Practice/20_Building_Custom_Rest_APIs.md
  lib/Document/Editable/Block/BlockState.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/Gender.php
  models/DataObject/ClassDefinition/Data/Language.php
  models/DataObject/ClassDefinition/Data/Languagemultiselect.php
  models/DataObject/ClassDefinition/Data/LayoutDefinitionEnrichmentInterface.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/TargetGroup.php
  models/DataObject/ClassDefinition/Data/TargetGroupMultiselect.php
  models/DataObject/ClassDefinition/Data/User.php
  models/DataObject/ClassDefinition/Layout/Iframe.php
  models/DataObject/ClassDefinition/Layout/Text.php
Labels: Bug

#11370 [Bug]: Zoom in Image Standard Preview after using 360° Viewer
  bundles/AdminBundle/Resources/public/js/pimcore/asset/image.js
Labels: Bug

#11444 Feature/add nullable check
  bundles/AdminBundle/Controller/AdminController.php
Labels: Bug

#11450 [Asset] Do not clear thumbnails on create
  models/Asset.php
  models/Asset/Document.php
  models/Asset/Image.php
  models/Asset/Video.php
Labels: Bug

#11464 [DataObjects] Localizedfields - throw meaningful exception when non existing attribute is requested in getLocalizedValue resolves
  models/DataObject/Localizedfield.php
Labels: Bug

#11426 Pimcore Translator Closes Transaction - fixes #11004
  bundles/CoreBundle/EventListener/DumpTranslationEntriesListener.php
  bundles/CoreBundle/Resources/config/event_listeners.yaml
  bundles/CoreBundle/Resources/config/services.yaml
  lib/Translation/TranslationEntriesDumper.php
  lib/Translation/Translator.php
  models/Translation.php
Labels: Bug

#11376 Asset selection fixes
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/asset.js
Labels: Bug

#11455 Fix file permissions
  .github/ci/files/config/services.yaml
  .github/ci/files/public/.htaccess
  .github/ci/files/public/index_test.php
  models/DataObject/ClassDefinition/Data/Geo/AbstractGeo.php
Labels: Bug

#11477 [Docs] Improved docs regarding cron setup
  doc/Development_Documentation/01_Getting_Started/00_Installation.md
Labels: Bug

#11498 [Admin] Translations - use session for file import to prevent path traversal
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
Labels: Bug

#11378 [Feature]: add PRE_COPY event
  lib/Event/AssetEvents.php
  lib/Event/DataObjectEvents.php
  lib/Event/DocumentEvents.php
  models/Asset/Service.php
  models/DataObject/Service.php
  models/Document/Service.php
Labels: Improvement

#11494 [ImageOptimization] Route ImageOptimization messages to separate transport
  bundles/CoreBundle/Command/MaintenanceCommand.php
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#11521 Fix: The Calculated Field cloning skips Type and Expression
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/calculatedValue.js
Labels: Bug

#11520 Fix: Quicksearch exception if brick found
  bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/object.html.twig
Labels: Bug

#11487 [DataObject] Classdefinition - Fix available sites selection in url slug field
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/urlSlug.js
Labels: Bug

#11527 [Asset] Thumbnails should only be optimized when "auto" format was selected
  models/Asset/Image/Thumbnail/Processor.php
Labels: Bug

#11459 Asset tree optimization
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Resources/public/css/admin.css
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/CoreBundle/Resources/config/message_handler.yaml
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  lib/Messenger/AssetPreviewImageMessage.php
  lib/Messenger/Handler/AssetPreviewImageHandler.php
  models/Asset/Folder.php
Labels: Improvement

#11503 [Actions] Added MariaDB 10.6 and 10.7 to the Codeception tests
  .github/workflows/codeception.yml
Labels: Improvement

#11518 Fix Use current player position as preview for 0 second
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  lib/Video/Adapter/Ffmpeg.php
  models/Asset/Video/ImageThumbnail.php
Labels: Bug

#11523 [Asset folder] Go to list view if there are no previewable assets inside
  bundles/AdminBundle/Resources/public/js/pimcore/asset/folder.js
Labels: Improvement

#10242 [Data objects] Add getter method for reverse relation field type
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/reverseObjectRelation.js
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
  tests/_support/Helper/Model.php
  tests/_support/Test/DataType/AbstractDataTypeTestCase.php
Labels: Improvement

#11524 Added nullcheck before method_exists
  bundles/EcommerceFrameworkBundle/IndexService/Interpreter/IdList.php
Labels: Bug

#11501 [Bug][Assets] Uploading invalid zip just hangs without error message
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#11465 [Versions] Add grid filters for version tabs
  bundles/AdminBundle/Resources/public/js/pimcore/asset/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/versions.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/versions.js
Labels: Improvement

#11534 [Asset] Thumbnails: read size from existing thumbnail file if it exis…
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#11469 [GDPR Data Extractor] DataObject - Allow extending dataObjects provider with custom search and download url
  bundles/AdminBundle/GDPR/DataProvider/Exporter.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/gdpr/dataproviders/dataObjects.js
Labels: Bug

#11506 [DataObject] Do not update search backend when auto save or only saving version
  bundles/CoreBundle/EventListener/SearchBackendListener.php
Labels: Bug

#11545 Add missing dao method annotations
  models/Tool/Targeting/TargetGroup.php
  models/User/Listing/AbstractListing.php
Labels: Bug

#11542 missing callback on folder/links autosave
  bundles/AdminBundle/Resources/public/js/pimcore/element/abstract.js
Labels: Bug
