Repository pimcore/pimcore, pull requests merged in 2022-06, with the labels that each got.

#12084 Custom layout for object bricks
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/objectbricks.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/objectbricks.js
  models/DataObject/Service.php
Labels: Improvement

#12255 [Ecommerce] make customerclass configurable
  bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderManager.php
Labels: Improvement

#12320 Added @returns and @param to docblocks to lib/Sitemap
  lib/Sitemap/Document/DocumentUrlGenerator.php
  lib/Sitemap/Element/GeneratorContext.php
  lib/Sitemap/Element/GeneratorContextInterface.php
  lib/Sitemap/Element/Processor/ModificationDateProcessor.php
  lib/Sitemap/Element/Processor/PropertiesProcessor.php
  lib/Sitemap/EventListener/SitemapGeneratorListener.php
  lib/Sitemap/UrlGenerator.php
  lib/Sitemap/UrlGeneratorInterface.php
Labels: Task

#12314 [Task] Add @param and @return php doc types to /lib/Navigation
  lib/Navigation/Builder.php
  lib/Navigation/Page.php
  lib/Navigation/Page/Document.php
  lib/Navigation/Renderer/Breadcrumbs.php
Labels: Task

#11857 [Listing] Question mark and colon in condition in addConditionParam() are always interpreted as prepated statement parameters
  lib/Model/Listing/AbstractListing.php
  models/DataObject/Listing.php
  tests/Model/DataObject/ListingTest.php
Labels: Bug

#12338 Fix: Display wrong icon if you move document between other documents
  bundles/AdminBundle/Resources/public/css/ext-modifications.css
  bundles/AdminBundle/Resources/public/extjs/css/PimcoreApp-all_1.css
  bundles/AdminBundle/Resources/public/extjs/css/PimcoreApp-all_2.css
Labels: Bug

#12303 [ContentSecurityPolicyHandler] Fix Admin views - Deeplink, ImageEditor, PreviewVideoError
  bundles/AdminBundle/Resources/views/Admin/Asset/getPreviewVideoError.html.twig
  bundles/AdminBundle/Resources/views/Admin/Asset/imageEditor.html.twig
  bundles/AdminBundle/Resources/views/Admin/Login/deeplink.html.twig
  bundles/AdminBundle/Resources/views/Admin/Login/layout.html.twig
Labels: Bug

#12256 [Improvement] use composer name for packagename
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/README.md
  lib/Extension/Bundle/Traits/PackageVersionTrait.php
Labels: Improvement

#12344 [Documents] Fix saving scheduled task for unpublished documents
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Controller/Admin/Document/EmailController.php
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
Labels: Bug

#12301 [Docs] Application testing - update docs to avoid loading default env file
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/01_Application_Testing.md
Labels: Bug

#12278 Update 00_Installation.md to add maintenance job option pimcore_image_optimize
  doc/Development_Documentation/01_Getting_Started/00_Installation.md
Labels: Improvement

#12279 Added @returns and @param to docblocks to models/Document
  models/Document/Editable.php
Labels: Task

#12249 Added @param and @returns to docblocks in lib/Extension
  lib/Extension/Bundle/Installer/SettingsStoreAwareInstaller.php
  lib/Extension/Bundle/Traits/PackageVersionTrait.php
Labels: Task

#12267 [Bug]: CSV/XLSX Export temp file moved to Flysystem
  .github/ci/files/minio-flysystem.yml
  .github/workflows/codeception.yml
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/CoreBundle/Resources/config/pimcore/flysystem.yaml
Labels: Bug

#12261 [TASK] add possibility to add additional class to block in blockStart
  doc/Development_Documentation/03_Documents/01_Editables/06_Block.md
  models/Document/Editable/Block.php
  models/Document/Editable/Scheduledblock.php
Labels: Improvement

#12360 [BUG] Fix Undefined array key warning for hidden fields in custom layouts
  models/DataObject/Service.php
Labels: Bug

#12355 ThumbnailTrait getStream can return null and should be handled
  models/Asset/Image.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#12361 Add configName to PERSPECTIVE_POST_GET_RUNTIME event
  lib/Event/AdminEvents.php
  lib/Perspective/Config.php
Labels: Bug

#12352 [Documentation] Feature: fixed doc blocks
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/05_Blocks.md
Labels: Task

#12350 [Documents] Use main request for generating page snippet urls
  lib/Routing/Dynamic/DocumentRouteHandler.php
Labels: Bug

#12347 [Bug]: Deleted components in Custom Layouts
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Layout.php
  tests/Model/DataObject/DefinitionModifierTest.php
Labels: Bug

#12364 - [Bug] Symfony Messenger consume command ignores Pimcore Maintenance Mode
  doc/Development_Documentation/19_Development_Tools_and_Details/11_Console_CLI.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Console/AbstractCommand.php
  lib/Console/Application.php
Labels: Bug

#12289 [Task] Add @param and @return php doc types to /lib/Log
  lib/Log/ApplicationLogger.php
  lib/Log/Processor/ApplicationLoggerProcessor.php
Labels: Task

#12318 Added @param and @returns to docblocks to lib/Tool
  lib/Tool/Admin.php
  lib/Tool/ArrayNormalizer.php
Labels: Task

#12280 Added @param and @returns to models/DataObject
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
  models/DataObject/ClassDefinition/DynamicOptionsProvider/CountryOptionsProvider.php
  models/DataObject/ClassDefinition/Helper/CalculatorClassResolver.php
  models/DataObject/ClassDefinition/Helper/ClassResolver.php
  models/DataObject/ClassDefinition/Helper/DefaultValueGeneratorResolver.php
  models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php
  models/DataObject/ClassDefinition/Layout.php
  models/DataObject/Data/BlockElement.php
Labels: Task

#12306 Added @param and @returns to docblocks for models/Asset
  models/Asset/Image.php
  models/Asset/MetaData/ClassDefinition/Data/Data.php
  models/Asset/MetaData/EmbeddedMetaDataTrait.php
Labels: Task

#12316 [Task][Permissions] IsAllowed considering system permissions and adding related tests
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Element/AbstractElement.php
  tests/Model/Permissions/ModelDataObjectPermissionsTest.php
  tests/_support/Util/TestHelper.php
Labels: Bug, Task

#12383 Fix Phpstan errors
  bundles/EcommerceFrameworkBundle/VoucherService/DefaultService.php
  lib/Config.php
Labels: Bug

#12376 Static Class Builder should not call "classSaved"
  lib/DataObject/ClassBuilder/FieldDefinitionBuilder.php
  models/DataObject/ClassDefinition.php
Labels: Bug

#12295 [Task] Add @param and @return php doc types to /lib/Model
  lib/Model/Asset/Metadata/Loader/DataLoaderInterface.php
  lib/Model/Dao/AbstractDao.php
  lib/Model/Listing/AbstractListing.php
Labels: Task

#12304 [Symfony] Fix some deprecations from version 5
  bundles/AdminBundle/PimcoreAdminBundle.php
  bundles/AdminBundle/Security/Factory/PreAuthenticatedAdminSessionFactory.php
  bundles/AdminBundle/Security/User/UserProvider.php
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Localization/IntlFormatter.php
  lib/Security/User/ObjectUserProvider.php
  lib/Workflow/ExpressionService.php
Labels: Task

#12394 [Elements] Fix getUserPermissions
  models/Element/AbstractElement.php
Labels: Bug

#12395 [Bug]: prevents fatal error when getCurrentUser is null in getUserPermissions
  models/Element/AbstractElement.php
Labels: Bug

#12298 [Task] Add @param and @return php doc types to /models/Element
  models/Element/AbstractElement.php
  models/Element/Service.php
Labels: Task

#12343 CMS Feature: Brick Preview Tooltip
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  lib/Document/Editable/EditableHandler.php
  lib/Extension/Document/Areabrick/PreviewAwareInterface.php
Labels: Improvement, New Feature

#12392 [Improvement]: extend PIMCORE_CLASS_DEFINITION_WRITABLE to be globally read-only
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
  doc/Development_Documentation/21_Deployment/05_Deployment_Tools.md
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
Labels: Improvement

#12384 [Bug]: LocationAwareConfigRepository to check $_SERVER instead on $_ENV
  lib/Bootstrap.php
  lib/Config/LocationAwareConfigRepository.php
Labels: Bug

#12385 Deprecated `RuntimeCacheTrait` and replaced its usage
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Cache/RuntimeCacheTrait.php
  models/DataObject/Classificationstore/CollectionConfig.php
  models/DataObject/Classificationstore/GroupConfig.php
  models/DataObject/Classificationstore/KeyConfig.php
Labels: Task

#12390 Fix: Error thrown while handling message Pimcore\Messenger\AssetUpdateTasksMessage
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
Labels: Bug

#12380 [Task] Add @param and @return php doc types to /lib/Routing
  lib/Routing/Dynamic/DocumentRouteHandler.php
  lib/Routing/RedirectHandler.php
Labels: Task

#12402 Stop further processing of the video thumbnail if ffmpeg fails to generate it
  models/Asset/Video/Thumbnail/Processor.php
Labels: Bug

#12389 Fix updating application_logs table entries in LogMailMaintenanceTask
  lib/Maintenance/Tasks/LogMailMaintenanceTask.php
Labels: Bug

#12391 [Bug]: Cleanup FC and Bricks Stores on lower-case DB Servers
  lib/Maintenance/Tasks/CleanupBrickTablesTask.php
  lib/Maintenance/Tasks/CleanupClassificationstoreTablesTask.php
  lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Dao.php
  tests/Model/DataObject/DefinitionModifierTest.php
Labels: Bug

#12319 Added @params and @returns to docblocks to lib/Targeting
  lib/Targeting/DataProvider/GeoIp.php
  lib/Targeting/Debug/Util/OverrideAttributeResolver.php
  lib/Targeting/EventListener/DocumentTargetGroupListener.php
  lib/Targeting/EventListener/FullPageCacheCookieCleanupListener.php
  lib/Targeting/EventListener/TargetingListener.php
  lib/Targeting/EventListener/ToolbarListener.php
  lib/Targeting/Model/GeoLocation.php
  lib/Targeting/Model/VisitorInfo.php
  lib/Targeting/Session/SessionConfigurator.php
  lib/Targeting/Storage/CookieStorage.php
  lib/Targeting/Storage/DbStorage.php
  lib/Targeting/Storage/FallbackStorage.php
  lib/Targeting/Storage/RedisStorage.php
  lib/Targeting/Storage/SessionStorage.php
  lib/Targeting/Storage/TargetingStorageInterface.php
Labels: Task

#12349 Objectbrick: Allow localized block fields again
  models/DataObject/Objectbrick/Definition.php
Labels: Bug

#12401 [Task] Add @param and @return php doc types to /lib/Workflow
  lib/Workflow/ExpressionService.php
  lib/Workflow/GlobalAction.php
  lib/Workflow/Manager.php
  lib/Workflow/MarkingStore/DataObjectMultipleStateMarkingStore.php
  lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php
  lib/Workflow/Notes/AbstractCustomHtmlService.php
  lib/Workflow/Notes/NotesAwareTrait.php
  lib/Workflow/Notification/AbstractNotificationService.php
  lib/Workflow/Place/OptionsProvider.php
  lib/Workflow/Place/PlaceConfig.php
  lib/Workflow/Place/StatusInfo.php
  lib/Workflow/SupportStrategy/ExpressionSupportStrategy.php
  lib/Workflow/Transition.php
Labels: Improvement

#12354 ClassDefinition: maxItems property should be int or null
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/ExternalImage.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Slider.php
  models/DataObject/ClassDefinition/Data/Table.php
Labels: Bug

#12425 Fix some typos in the PHPDoc description of events
  lib/Event/AssetEvents.php
  lib/Event/DataObjectEvents.php
Labels: Task

#11866 Add JavaScript events for "preDelete" and "postDelete" for Assets, Documents and Data objects.
  bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Plugin_Backend_UI.md
Labels: Improvement

#12405 Cookies should be auto-secure
  bundles/AdminBundle/Security/Authenticator/AdminAbstractAuthenticator.php
  bundles/AdminBundle/Security/Event/LogoutListener.php
  bundles/AdminBundle/Security/Guard/AdminAuthenticator.php
  bundles/CoreBundle/Controller/PublicServicesController.php
  lib/Targeting/Storage/Cookie/AbstractCookieSaveHandler.php
Labels: Bug

#12312 [Ecommerce] Add Event to GetFields-Method of IndexController
  bundles/EcommerceFrameworkBundle/Controller/IndexController.php
  lib/Event/Ecommerce/AdminEvents.php
Labels: Improvement

#12444 [Security] SQL Injection in Data Hub GraphQL
  lib/Model/Listing/AbstractListing.php
Labels: Task

#12410 Fixed the integrity constraint violation issue when deleting classification store group
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/groupsPanel.js
Labels: Bug

#12434 Don't cache thumbnail urls with error image
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Bug

#12418 [Bug]: Fix batch append/remove doesn't work on CS attributes
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#12449 Fix FFMPEG with durations like 00:00:11.04 (milliseconds)
  lib/Video/Adapter.php
  lib/Video/Adapter/Ffmpeg.php
Labels: Bug

#12447 [Bug]: Grid returns empty when searching Assets Metadata
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Bug

#12458 [PHP 8.1] fix Passing null to parameter #1 ($string) of type string is deprecate
  models/Staticroute.php
Labels: Bug

#12454 [Bug][Backend]: Wrong Date and DateTime value - adding timezone configuration to the docs
  doc/Development_Documentation/01_Getting_Started/01_Advanced_Installation_Topics.md
Labels: Bug

#12448 XLIFF: fixing import when working with html entities
  lib/Translation/Escaper/Xliff12Escaper.php
  models/Translation.php
Labels: Bug

#12428 [Core] Migrate Custom Layout definition files to use LocationAwareConfigRepository
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
  bundles/CoreBundle/Command/CustomLayoutRebuildCommand.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Migrations/Version20220617145524.php
  bundles/InstallBundle/Installer.php
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
  lib/Kernel.php
  lib/Model/Dao/PimcoreLocationAwareConfigDao.php
  lib/Model/DataObject/ClassDefinition/ClassLayoutDefinitionManager.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
  models/DataObject/ClassDefinition/CustomLayout/Listing.php
  models/DataObject/ClassDefinition/CustomLayout/Listing/Dao.php
  tests/_bootstrap.php
Labels: Improvement

#12368 [IMPROVEMENT] add min, max, decimalsize and -precision to quantityValue
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/quantityValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Improvement

#12426 [Admin] Fix UI does not recover from maintenance mode
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Bug

#12443 [Improvement]: Remove/deprecate some folder creation by MkdirCacheWarmer
  lib/Bootstrap.php
  lib/HttpKernel/CacheWarmer/MkdirCacheWarmer.php
  stubs/dynamic-constants.php
Labels: Improvement

#12483 Glossary: allow html entities like &nbsp; or &copy;
  lib/Tool/Glossary/Processor.php
  tests/Unit/Document/Glossary/GlossaryTest.php
Labels: Bug

#12420 [Improvement] add name to export / set name of custom layout on import if na…
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
Labels: Improvement

#12545 Fixed installer
  bundles/InstallBundle/Installer.php
  lib/Tool/Requirements.php
Labels: Bug

#12541 Glossary fix for &lt; &gt; and &amp;
  lib/Tool/Glossary/Processor.php
  tests/Unit/Document/Glossary/GlossaryTest.php
Labels: Bug

#12502 Fix Error when removing classification group which has key relationships
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/groupsPanel.js
Labels: Bug

#12499 [Bug]: Cannot filter on multiple CS keys on object grid
  bundles/AdminBundle/Helper/GridHelperService.php
  tests/Model/DataType/ClassificationStore/GeneralTest.php
Labels: Bug

#12452 [Improvement]: Refactor navigation builder to use param style arguments
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Navigation/Builder.php
  lib/Twig/Extension/Templating/Navigation.php
Labels: Improvement

#12564 Error message while selecting logs in LogController
  bundles/AdminBundle/Controller/Admin/LogController.php
Labels: Bug

#12445 Add an option "allowedTypes" to the video editable.
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  doc/Development_Documentation/03_Documents/01_Editables/38_Video.md
  models/Document/Editable/Video.php
Labels: Improvement

#12356 Support modern bundle structure
  bundles/CoreBundle/DependencyInjection/Compiler/AreabrickPass.php
  lib/Config/BundleConfigLocator.php
  lib/Controller/Config/ControllerDataProvider.php
  lib/Document/Editable/EditableHandler.php
  lib/HttpKernel/WebPathResolver.php
Labels: Improvement
