Repository pimcore/pimcore, pull requests merged in 2022-05, with the labels that each got.

#11999 Fix for QuickSearch regression for user accounts without cid
  models/Element/Service.php
Labels: Bug

#12013 Fixed logout button, GitHub button, 2FA logout, login page scripts (CSRF token refresh, ...)
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  bundles/AdminBundle/Resources/views/Admin/Login/login.html.twig
  bundles/AdminBundle/Resources/views/Admin/Login/twoFactorAuthentication.html.twig
  bundles/AdminBundle/Security/ContentSecurityPolicyHandler.php
Labels: Bug

#11976 [PhpStan] Fix PreAuthenticatedAdminToken roles parameter
  bundles/AdminBundle/Security/Firewall/PreAuthenticatedAdminSessionListener.php
  phpstan-baseline.neon
Labels: Improvement

#12008 Fix: Document/Page::setPrettyUrl should be nullable
  models/Document/Page.php
  models/Document/Service.php
Labels: Bug

#12009 Fix: targetGroupIds Field in documents_page db table should not nullable
  bundles/CoreBundle/Migrations/Version20220502104200.php
  bundles/InstallBundle/Resources/install.sql
Labels: Bug

#11977 [PhpStan] Use DoctrineDbalAdapter instead of PdoAdapter
  bundles/InstallBundle/Installer.php
  composer.json
  models/DataObject/Concrete.php
  phpstan-baseline.neon
Labels: Improvement

#12028 Fix new PhpStan error
  models/DataObject/Traits/ElementWithMetadataComparisonTrait.php
Labels: Bug

#12017 [Bug]: Fixes anchor-only links not rendered in edit mode
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/link.js
Labels: Bug

#11980 [PhpStan] Fix AdminExceptionListener:recursiveAddValidationExceptionSubItems()
  bundles/AdminBundle/EventListener/AdminExceptionListener.php
  phpstan-baseline.neon
Labels: Improvement

#11978 [PhpStan] Fix errors with Symfony Request/Response object
  bundles/CoreBundle/EventListener/TranslationDebugListener.php
  lib/Http/ResponseHelper.php
  lib/Targeting/EventListener/ToolbarListener.php
  phpstan-baseline.neon
Labels: Improvement

#11971 Custom Reports: Send drilldownFilters to createCSVAction
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
Labels: Improvement

#11826 Fix PhpStan level 5 errors
  bundles/AdminBundle/EventListener/AdminExceptionListener.php
  bundles/AdminBundle/GDPR/DataProvider/Manager.php
  bundles/AdminBundle/Security/User/User.php
  bundles/CoreBundle/Command/Bundle/ListCommand.php
  bundles/CoreBundle/Command/Definition/Import/ClassCommand.php
  bundles/CoreBundle/Command/Definition/Import/FieldCollectionCommand.php
  bundles/CoreBundle/Command/Definition/Import/ObjectBrickCommand.php
  bundles/CoreBundle/Command/InternalMigrationHelpersCommand.php
  bundles/CoreBundle/EventListener/ResponseExceptionListener.php
  composer.json
  lib/Cache/Tool/Warming.php
  lib/DataObject/GridColumnConfig/Operator/TranslateValue.php
  lib/DataObject/GridColumnConfig/Value/DefaultValue.php
  lib/Google/Api.php
  lib/Google/Cse.php
  lib/Image/Adapter.php
  lib/Image/Adapter/Imagick.php
  lib/Messenger/GenerateWeb2PrintPdfMessage.php
  lib/Messenger/Handler/GenerateWeb2PrintPdfHandler.php
  lib/Targeting/ConditionFactory.php
  lib/Targeting/ConditionMatcher.php
  lib/Targeting/DataProvider/GeoLocation.php
  lib/Templating/Renderer/IncludeRenderer.php
  lib/Tool.php
  lib/Tool/Glossary/Processor.php
  lib/Tool/Text/Csv.php
  lib/Translation/Escaper/Xliff12Escaper.php
  lib/Translation/ImporterService/Importer/DataObjectImporter.php
  lib/Translation/TranslationItemCollection/TranslationItemCollection.php
  lib/Video/Adapter/Ffmpeg.php
  lib/helper-functions.php
  models/Asset/Folder.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/Classificationstore/Service.php
  models/DataObject/Data/ImageGallery.php
  models/DataObject/Data/UrlSlug.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
  models/DataObject/Service.php
  models/Document/Editable/Image.php
  models/Document/Editable/Video.php
  models/Document/Hardlink/Wrapper/Link.php
  models/Document/Service.php
  models/Document/Service/Dao.php
  models/Element/Service.php
  models/Translation.php
  phpstan-baseline.neon
  tests/_support/Helper/AbstractDefinitionHelper.php
Labels: Improvement

#12031 [Bug]: Object Preview not hiding the loading mask
  bundles/AdminBundle/Resources/public/js/pimcore/object/preview.js
Labels: Bug

#12012 Fix: Areablock in Block editable works only after reloading
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/block.js
Labels: Bug

#12018 [Actions] Use actions/stale instead of Stale App
  .github/stale.yml
  .github/workflows/stale.yml
Labels: Task

#12025 [Bug]: Keyboard shortcut to save causes error within folders
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
Labels: Bug

#12049 Fix: LQIP srcset
  models/Asset/Image/Thumbnail.php
Labels: Bug

#12014 [Bug]: Added search test with empty roles/no user level rules, fixed potential empty implode problem
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  models/Element/Service.php
  tests/Model/Permissions/ModelDataObjectPermissionsTest.php
Labels: Bug

#12026 Fix: AbstractUser::getById() doesn't check the type
  models/Asset.php
  models/Document.php
  models/User/AbstractUser.php
  models/User/Service.php
Labels: Bug

#12032 [Bug]: Fix Objectbrick unique field overwriting
  models/DataObject/Objectbrick/Data/Dao.php
Labels: Bug

#12058 Fix wrong regex in PublicServicesController
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Bug

#12050 Fix: Save permissions keybindings
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#12072 [Bug][Revert]: Cannot drag&drop on dataobject
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#12022 [Authentication] Do not close session on authenticateSession
  bundles/AdminBundle/Session/Handler/AdminSessionHandler.php
Labels: Bug

#12085 [Bug]: Content page scrolls up by itself
  bundles/AdminBundle/Resources/public/js/pimcore/document/edit/startup.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editable.js
Labels: Bug

#12100 Add CalculatorClassInterface requirement to Pimcore X Update Notes
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Bug

#12080 Removed duplicate properties
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#12027 Bump doctrine/doctrine-bundle to 2.5
  composer.json
Labels: Improvement

#12033 Bump symfony/doctrine-messenger to ^6.0
  composer.json
Labels: Improvement

#12114 Fix issue on custom views for non admin users for v10.4
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#12128 [Documents] Reset draft changes on applying Content Master Document
  bundles/AdminBundle/Resources/public/js/pimcore/document/settings_abstract.js
Labels: Bug

#12124 Added test cases for Block and Wysiwyg Editables
  tests/Model/Document/EditableTest.php
  tests/_support/Helper/Document/TestDataHelper.php
Labels: Task

#12137 Refactored duplicate o_id property
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Improvement

#12104 Fix: Cannot instantiate abstract class Pimcore\Model\Document\PrintAbstract
  models/Document.php
  tests/Model/Document/DocumentTest.php
Labels: Bug

#12105 Update 06_Create_a_First_Project.md
  doc/Development_Documentation/01_Getting_Started/06_Create_a_First_Project.md
Labels: Bug, Task

#12020 [Task:] Update presta/sitemap-bundle to version 3
  composer.json
  doc/Development_Documentation/18_Tools_and_Features/39_Sitemaps.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Kernel.php
Labels: Task

#12148 [EcommerceFramework] Configuration - fix examples and update docs
  bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/10_E-Commerce_Framework/04_Configuration/01_PimcoreEcommerceFrameworkBundle_Configuration_Reference.md
Labels: Bug

#12141 Translate titles of notes if needed and workflow note window title
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitionPanel.js
  models/Element/Service.php
Labels: Bug

#12090 [Improvement] Core: Support key and index in backend search
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/object.js
  bundles/CoreBundle/Migrations/Version20220511085800.php
  bundles/InstallBundle/Resources/install.sql
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Search/Backend/Data.php
  models/Search/Backend/Data/Dao.php
  models/Search/Backend/Data/Listing/Dao.php
Labels: Improvement

#12155 Refactored duplicate o_userOwner/userOwner properties and related method
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#12164 Refactored duplicate o_creationDate/creationDate
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#12159 Refactored duplicate o_path/path properties and related methods
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#12110 Refactored duplicate o_parent/parent properties
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#12171 Refactored duplicate o_locked/locked properties and related methods
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#12169 Fix: Variants were not displayed in the variants tab
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectActionsTrait.php
  bundles/AdminBundle/Controller/Admin/DataObject/VariantsController.php
Labels: Bug

#12125 Refactor duplicate __sleep and __wakeup methods
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#12170 Refactored duplicate o_modificationDate/modificationDate
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#12161 [Asset upload] Prevent creation of __MACOS folder when uploading a zip file which got created with MacOS
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
Labels: Bug

#12188 Fix: Localizedfield DAO improperly checks the DBMS error message
  models/DataObject/Localizedfield/Dao.php
Labels: Bug

#12092 Delete uuid - query update to reduce locking
  models/Tool/UUID/Dao.php
Labels: Improvement

#12196 Fix Phpstan error
  lib/Targeting/ConditionFactory.php
Labels: Bug

#12190 Refactored duplicate o_parentId/parentId properties and methods
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#12150 [Bug]: Perspective Editor unexpected behavior
  lib/CustomView/Config.php
Labels: Bug

#12153 [DataObjects] Fix blocks in localizedfields causes infinite loop/memory
  models/DataObject/ClassDefinition/Data/Block.php
Labels: Bug

#12204 [Reports] Regard drilldown filters on export
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
Labels: Bug

#12144 [Bug]: Reverse Object Relation only valid for ManyToMany Object relation
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
Labels: Bug

#12202 Fix custom entrypoint login link
  bundles/AdminBundle/Controller/Admin/UserController.php
  bundles/AdminBundle/DependencyInjection/Configuration.php
  bundles/AdminBundle/DependencyInjection/PimcoreAdminExtension.php
  doc/Development_Documentation/19_Development_Tools_and_Details/40_Custom_Admin_Login_Entry_Point.md
Labels: Bug

#12200 [DataObject Tree] Allow expand and collapse on expandable property
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
Labels: Bug

#12069 Fix/dynamic multiselect options not loaded in grid
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/grid.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/multiselect.js
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug

#12208 [User] Add tip for Disable unsaved content warning unused on auto save
  doc/Development_Documentation/18_Tools_and_Features/02_Auto_Save_Drafts.md
Labels: Bug

#12207 Added latestVersion to forbiddenNames
  models/DataObject/ClassDefinition/Data.php
Labels: Bug

#12191 [Task]: Added types and docblocks for lib/Translation
  lib/Translation/ExportDataExtractorService/DataExtractor/AbstractElementDataExtractor.php
  lib/Translation/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
  lib/Translation/ExportDataExtractorService/ExportDataExtractorService.php
  lib/Translation/ExportDataExtractorService/ExportDataExtractorServiceInterface.php
  lib/Translation/Translator.php
Labels: Task

#12121 [Docs] Filter by relation
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
  doc/User_Documentation/05_DataObjects/01_Grid_Configuration_General.md
  doc/User_Documentation/img/gridconfig/filter_date_type_img.png
  doc/User_Documentation/img/gridconfig/filter_number_type_img.png
  doc/User_Documentation/img/gridconfig/filter_relation_type_img.png
  doc/User_Documentation/img/gridconfig/filter_relation_type_img2.png
  doc/User_Documentation/img/gridconfig/filter_select_type_img.png
  doc/User_Documentation/img/gridconfig/filter_text_type_img.png
  models/DataObject/ClassDefinition/Data/Extension/RelationFilterConditionParser.php
Labels: Bug

#12088 Handle non redirect status codes
  lib/Event/RedirectEvents.php
  lib/Routing/RedirectHandler.php
Labels: Improvement

#12250 Added @param and @returns docblocks to lib/Event
  lib/Event/Admin/Report/SettingsEvent.php
  lib/Event/BundleManager/PathsEvent.php
  lib/Event/Model/TargetGroupEvent.php
  lib/Event/Workflow/GlobalActionEvent.php
Labels: Task

#12254 Added docblocks to the missing methods and properties for lib/DataObject
  lib/DataObject/GridColumnConfig/ResultContainer.php
Labels: Task

#12247 Added @returns and @param to missing method docblocks inside lib/Http
  lib/Http/ClientFactory.php
Labels: Task

#12244 Added parameter and return type docblocks for lib/Controller
  lib/Controller/FrontendController.php
  lib/Controller/Traits/ElementEditLockHelperTrait.php
Labels: Task

#12245 [Task] Add @param and @return php doc types to /lib/Analytics
  lib/Analytics/Code/CodeBlock.php
  lib/Analytics/Google/Config/SiteConfigProvider.php
  lib/Analytics/Google/Tracker.php
  lib/Analytics/GoogleTagManager/EventSubscriber/TrackingCodeSubscriber.php
Labels: Task

#12264 Fix new PhpStan errors
  bundles/AdminBundle/DependencyInjection/Compiler/ContentSecurityPolicyUrlsPass.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/EcommerceFrameworkBundle/Controller/ConfigController.php
  composer.json
  doc/Development_Documentation/26_Best_Practice/75_Security_Concept.md
  lib/Bootstrap.php
  lib/CustomView/Config.php
  lib/Perspective/Config.php
  lib/Web2Print/Config.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Video/Thumbnail/Config/Dao.php
  models/Document/DocType/Dao.php
  models/Metadata/Predefined/Dao.php
  models/Property/Predefined/Dao.php
  models/Staticroute/Dao.php
  models/Tool/CustomReport/Config/Dao.php
  models/Translation/Dao.php
Labels: Bug

#12099 Allow skipping the loading of the `.env*` file
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
  lib/Bootstrap.php
Labels: Improvement

#12248 [Task] Add @param and @return php doc types to /models/User
  models/User/UserRole.php
Labels: Task

#12260 [TASK] add getter for items to Localizedfield.php
  models/DataObject/Localizedfield.php
Labels: Improvement

#12218 Use DoctrineDbalAdapter cache adapter
  bundles/CoreBundle/DependencyInjection/Compiler/CacheFallbackPass.php
  bundles/CoreBundle/Resources/config/cache.yaml
  doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  tests/Cache/Core/DoctrineDbalCoreHandlerTest.php
Labels: Task

#12258 Annotate static getContainer method as deprecated
  lib/Pimcore.php
Labels: Improvement
