Repository pimcore/pimcore, pull requests merged in 2022-08, with the labels that each got.

#12764 Fix return type of ImageThumbnailTrait::getAsFormat()
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#12748 LogErrorCleanupTask: fixed query
  lib/Maintenance/Tasks/LogErrorCleanupTask.php
Labels: Bug

#12743 documentation: add example for predefinedDataTemplate image config
  doc/Development_Documentation/03_Documents/01_Editables/14_Image.md
Labels: Task

#12770 use local file name in text extraction
  lib/Document/Adapter/LibreOffice.php
Labels: Bug

#12771 Send a console error when using deprecated js functions
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
Labels: Bug

#12769 Renew o_* references on cloning
  models/DataObject/AbstractObject.php
  tests/Model/DataObject/ObjectTest.php
Labels: Bug

#12786 Fix object bricks control menu for grouped bricks
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/objectbricks.js
Labels: Bug

#12801 [Bug] Renaming data object classes crashes system
  models/DataObject/ClassDefinition/Dao.php
  tests/Model/DataObject/ClassDefinitionTest.php
Labels: Bug

#12794 Fix: use the `RuntimeCache` instead of a static array to cache `UrlSlug`s
  models/DataObject/Data/UrlSlug.php
Labels: Bug

#12767 Video Editable: Fix undefined array key "v"
  models/Document/Editable/Video.php
Labels: Bug

#12799 Transfer the task with the pimcore.events.postSaveObject Event in ExtJs
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
Labels: Bug

#12802 [Documents] Image - Fix editing markers or hotspots breaks UI
  models/Document/Editable/Image.php
Labels: Bug

#12766 Fix: ImageThumbnailTrait::readDimensionsFromFile()
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#12756 [Translations] Fix permissions check and add userOwner & userModification columns
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
  bundles/CoreBundle/Migrations/Version20220725154615.php
  bundles/InstallBundle/Resources/install.sql
  models/Translation.php
  models/Translation/Dao.php
Labels: Improvement, Bug

#12760 Fix: Incorrect dimension style in Video::getEmptyCode()
  models/Document/Editable/Video.php
Labels: Bug

#12810 Fix Error thrown while handling message Pimcore\Messenger\GenerateWeb2PrintPdfMessage
  lib/Messenger/Handler/GenerateWeb2PrintPdfHandler.php
  lib/Web2Print/Exception/CancelException.php
  lib/Web2Print/Exception/NotPreparedException.php
  lib/Web2Print/Processor.php
Labels: Bug

#12811 [Documents] Fix inheritance for editables in a dialog box
  bundles/AdminBundle/Resources/public/js/pimcore/document/editable.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/block.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/checkbox.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/date.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/embed.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/link.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/manager.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/multiselect.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/numeric.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/pdf.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/relation.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/relations.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/renderlet.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/scheduledblock.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/select.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/snippet.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/table.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/textarea.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/video.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/wysiwyg.js
Labels: Bug

#12736 downloadXlsxFileAction(): Use loadSpreadsheetFromString() to avoid the extra temp file
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  composer.json
Labels: Improvement

#12821 Fix: Wrong Test if type of addReferencedField is a function
  bundles/AdminBundle/Resources/public/js/pimcore/object/edit.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/block.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/objectbricks.js
Labels: Bug

#12823 [Session] Do not register session bag if session already started
  bundles/AdminBundle/EventListener/AdminSessionBagListener.php
  bundles/EcommerceFrameworkBundle/EventListener/SessionBagListener.php
  lib/Targeting/EventListener/TargetingSessionBagListener.php
Labels: Bug

#12824 Update 3rd-party-licenses.md
  3rd-party-licenses.md
Labels: Task

#12820 Fix: explode_and_trim() returns empty array
  lib/helper-functions.php
Labels: Bug

#12570 New video thumbnail filter - cut, mute, fps, colorchanelmixer
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/video.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/videothumbnail/item.js
  bundles/AdminBundle/Resources/views/Admin/Asset/getPreviewVideoDisplay.html.twig
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/03_Video_Thumbnails.md
  lib/Video/Adapter/Ffmpeg.php
  models/Asset/Video/Thumbnail/Processor.php
Labels: Improvement

#12841 Fix Bug: .m4a files are not handled as audio files
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/asset/audio.js
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Labels: Bug

#12825 Fix link to the ExtJS docs
  doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/README.md
Labels: Bug

#12817 Update developer doc example HTML in layout.html.twig
  doc/Development_Documentation/01_Getting_Started/06_Create_a_First_Project.md
Labels: Improvement

#12826 Remove deprecated JS functions
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#12836 DocType/Staticroute: module and action are not allowed properties anymore
  models/Document/DocType/Dao.php
  models/Staticroute/Dao.php
Labels: Bug

#12727 Fix: Document\DocType::$staticGeneratorEnabled should be bool
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Migrations/Version20220809164000.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Document/DocType.php
  models/Document/PageSnippet.php
Labels: Bug, BC-BREAK

#12812 [Bug]: Manual sorting of object does not work
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
Labels: Bug

#12874 Fix missing scope in DocType migration
  bundles/CoreBundle/Migrations/Version20220809164000.php
Labels: Bug

#12888 Fixes missing class reference in built Listing classes
  lib/DataObject/ClassBuilder/ListingClassBuilder.php
Labels: Bug

#12864 [Bug][CustomViews] Allow objects - empy does not allow all
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
Labels: Bug

#12834 Restricted the option to set pages as content master document to each other
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  models/Document/PageSnippet.php
  models/Document/Service.php
  tests/Model/Document/DocumentTest.php
Labels: Bug

#12839 [Version preview] Prevent E_DEPRECATED error when having input field = null
  models/DataObject/ClassDefinition/Data/Extension/Text.php
Labels: Bug

#12894 [Bug]: Error Autowire $bruteforceProtectionHandler on Forgot Password Page
  bundles/AdminBundle/Controller/Admin/LoginController.php
Labels: Bug

#12897 [Bug]: Fallback for parentId not working anymore
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
Labels: Bug

#12850 [Bug]: Saved sql condition in grid doesn't work on grid recall
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
Labels: Bug

#12849 Document/Video ImageThumbnail should return error image if it couldn't be generated
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Video/ImageThumbnail.php
Labels: Bug

#12880 [Bug]: Asset Folder Preview tab supporting audio files and other files formats
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
Labels: Bug

#12851 [Admin] Image HotspotItem - Rewrite Markers/Hotspots relation data
  models/Document/Editable/Image.php
Labels: Bug

#12854 [Bug] getTotalCount() on listings should return correct count on grouped queries
  .gitignore
  doc/Development_Documentation/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  lib/Model/Listing/Dao/QueryBuilderHelperTrait.php
  models/Asset/Listing/Dao.php
  models/DataObject/Listing/Dao.php
  models/Document/Listing/Dao.php
  tests/Model/Asset/ListingTest.php
  tests/_support/Util/TestHelper.php
Labels: Bug

#12846 [Bug]: Fix Video Datatype not supporting allowedTypes
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/video.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/video.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  models/DataObject/ClassDefinition/Data/Video.php
Labels: Bug

#12852 [Data Object] Remove method_exists() BC layers
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/DataObject/BlockDataMarshaller/EncryptedField.php
  lib/DataObject/ClassificationstoreDataMarshaller/EncryptedField.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/Classificationstore.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Localizedfield.php
  models/DataObject/Objectbrick/Definition.php
  models/DataObject/Service.php
Labels: Task

#12877 [Task]: Remove JsonListing class
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Model/Listing/JsonListing.php
  models/Asset/Image/Thumbnail/Config/Listing.php
  models/Asset/Video/Thumbnail/Config/Listing.php
  models/Document/DocType/Listing.php
  models/Metadata/Predefined/Listing.php
  models/Property/Predefined/Listing.php
  models/Staticroute/Listing.php
  models/Tool/CustomReport/Config/Listing.php
  models/Workflow/Listing.php
Labels: Task

#12757 Marked traits in /lib/Extension/Bundle/Traits as @internal
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Extension/Bundle/Traits/PackageVersionTrait.php
  lib/Extension/Bundle/Traits/StateHelperTrait.php
Labels: Task

#12844 Removed deprecated RuntimeCacheTrait and the old Pimcore\Cache\Runtime
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Cache/Runtime.php
  lib/Cache/RuntimeCacheTrait.php
Labels: Task, BC-BREAK

#12872 Admin Events: Remove Plugin Broker BC layer
  bundles/AdminBundle/Resources/public/js/pimcore/events.js
  bundles/AdminBundle/Resources/public/js/pimcore/plugin/broker.js
  bundles/AdminBundle/Resources/public/js/pimcore/plugin/plugin.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, BC-BREAK

#12881 [Data Objects]: Remove "generate type declarations" in class definitions
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollections/field.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/objectbricks/field.js
  bundles/CoreBundle/Resources/translations/en.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_FilterDefinition_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolCustomProduct_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOfferItem_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OfferToolOffer_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrderItem_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopOrder_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopTaxClass_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherSeries_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/class_sources/class_OnlineShopVoucherToken_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterCategoryMultiselect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterCategory_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterInputfield_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterMultiRelation_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterMultiSelectFromMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterNumberRangeSelection_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterNumberRange_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterRelation_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterSelectClsStoreAttributes_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterSelectFromMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_FilterSelect_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_OrderByFields_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_OrderPriceModifications_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_PaymentInfo_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_PricingRule_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_SimilarityField_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_TaxEntry_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_VoucherTokenTypePattern_export.json
  bundles/EcommerceFrameworkBundle/Resources/install/fieldcollection_sources/fieldcollection_VoucherTokenTypeSingle_export.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Traits/FieldcollectionObjectbrickDefinitionTrait.php
  tests/Model/DataType/LinkTest.php
  tests/_support/Helper/Model.php
Labels: BC-BREAK

#12922 [Admin] Translations - properly escape key on roweditor
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
Labels: Bug

#12912 [Improvement]: Remove dead code - nodeMoved
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
  bundles/AdminBundle/Resources/public/js/pimcore/elementservice.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
Labels: Improvement

#12914 [Improvement][SystemSettings] Drag and Drop asset to pimcore backend login screen background
  bundles/AdminBundle/Resources/public/js/pimcore/settings/system.js
Labels: Improvement

#12919 PimcoreExtensionsTrait: Trigger Deprecations and remove usage in core
  bundles/AdminBundle/Controller/Admin/LogController.php
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
  lib/Db/Helper.php
  lib/Db/PimcoreExtensionsTrait.php
  models/Asset/Dao.php
  models/DataObject/Concrete/Dao.php
  tests/Model/Inheritance/LocalizedFieldTest.php
  tests/_support/Helper/Pimcore.php
  tests/_support/Test/DataType/AbstractDataTypeTestCase.php
Labels: Bug

#12925 [PhpStan] Fix: InMemory::plainText() expects non-empty-string, string given
  lib/Targeting/Storage/Cookie/JWTCookieSaveHandler.php
Labels: Bug

#12759 Removed migration script from composer.json on post update
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/README.md
  lib/Composer.php
Labels: Task

#11753 [DataObjects] Add new range data types
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/dateRange.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/numericRange.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/quantityValueRange.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/dateRange.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/numericRange.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValueRange.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  bundles/CoreBundle/Resources/translations/en.extended.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/25_Date_Types.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/55_Number_Types.md
  doc/Development_Documentation/img/classes-datatypes-date3.jpg
  doc/Development_Documentation/img/classes-datatypes-number7.jpg
  doc/Development_Documentation/img/classes-datatypes-number8.jpg
  models/DataObject/ClassDefinition/Data/DateRange.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/NumericRange.php
  models/DataObject/ClassDefinition/Data/QuantityValueRange.php
  models/DataObject/Data/NumericRange.php
  models/DataObject/Data/QuantityValueRange.php
Labels: New Feature

#12908 [Bug]: Null value displayed from field in object brick (object grid view)
  lib/DataObject/GridColumnConfig/Value/DefaultValue.php
Labels: Bug

#12873 [Ecommerce] Pricing Manager - Remove Token condition & session getter/setter from Environment
  bundles/CoreBundle/Resources/translations/en.json
  bundles/EcommerceFrameworkBundle/PricingManager/Condition/Token.php
  bundles/EcommerceFrameworkBundle/PricingManager/Environment.php
  bundles/EcommerceFrameworkBundle/PricingManager/EnvironmentInterface.php
  bundles/EcommerceFrameworkBundle/PricingManager/PricingManager.php
  bundles/EcommerceFrameworkBundle/Resources/config/pimcore/config.yaml
  bundles/EcommerceFrameworkBundle/Resources/public/css/pricing.css
  bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  tests/Ecommerce/CartTaxManagementTest.php
  tests/Ecommerce/PriceSystem/TaxCalculationTest.php
  tests/Ecommerce/PricingManager/Rule/AbstractRuleTest.php
  tests/Ecommerce/ProductTaxManagementTest.php
Labels: Task, BC-BREAK

#12940 parameters.secret should be longer -> causing issues with JWT library
  .github/ci/files/config/services.yaml
  lib/Composer.php
Labels: Bug

#12830 [Docs]: Complete preparation guide for v11
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
Labels: Improvement

#12941 [Bug]: Class.create with undefined parameter crashes js
  bundles/AdminBundle/Resources/public/js/lib/class.js
Labels: Bug

#12595 [Advanced relations] Do not check for type equality of meta fields
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Traits/ElementWithMetadataComparisonTrait.php
Labels: Bug

#12949 Fix: Missing return for non-admin users when renaming objects
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#12911 [TASK]: Remove Pimcore\Config\Config
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Controller/Reports/AnalyticsController.php
  bundles/AdminBundle/Controller/Reports/ReportsControllerBase.php
  bundles/AdminBundle/Controller/Reports/SettingsController.php
  bundles/CoreBundle/Controller/PublicServicesController.php
  bundles/CoreBundle/EventListener/Frontend/GoogleSearchConsoleVerificationListener.php
  bundles/CoreBundle/EventListener/Frontend/GoogleTagManagerListener.php
  bundles/CoreBundle/Migrations/Version20210323110055.php
  bundles/CoreBundle/Migrations/Version20210630062445.php
  bundles/EcommerceFrameworkBundle/IndexService/Config/AbstractConfig.php
  doc/Development_Documentation/18_Tools_and_Features/27_Website_Settings.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Analytics/Google/Config/Config.php
  lib/Analytics/Google/Config/ConfigProvider.php
  lib/Analytics/Google/Config/SiteConfigProvider.php
  lib/Analytics/Google/Tracker.php
  lib/Config.php
  lib/Config/ReportConfigWriter.php
  lib/Controller/ArgumentValueResolver/WebsiteConfigValueResolver.php
  lib/Perspective/Config.php
  lib/Web2Print/Config.php
  lib/Web2Print/Processor.php
  lib/Web2Print/Processor/HeadlessChrome.php
  lib/Web2Print/Processor/PdfReactor.php
  lib/Web2Print/Processor/WkHtmlToPdf.php
Labels: Task, BC-BREAK

#12929 [Improvement]: Add exception if no parent id was set
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  tests/Model/Asset/AssetTest.php
  tests/Model/DataObject/ObjectTest.php
  tests/Model/Document/DocumentTest.php
Labels: Improvement, BC-BREAK

#12965 [Data objects] Support exporting empty class
  models/DataObject/ClassDefinition/Service.php
Labels: Bug

#12909 Fix video iframe embed attributes (permissions, data)
  models/Document/Editable/Video.php
Labels: Bug

#12947 [Admin] Fix Asset video open link
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/video.js
Labels: Bug

#12952 [Docs] Link to preview generators
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/55_Preview.md
Labels: Bug

#12987 [TASK]: Remove Pimcore\Config\Config follow up
  bundles/AdminBundle/EventListener/UserPerspectiveListener.php
  bundles/InstallBundle/SystemConfig/ConfigWriter.php
  lib/Perspective/Config.php
  models/Document/Editable/Area/AbstractArea.php
  models/User.php
Labels: Task

#12920 [Static Page Generator] Fix json request to a non document route saves wrong content
  bundles/CoreBundle/EventListener/Frontend/StaticPageGeneratorListener.php
  doc/Development_Documentation/19_Development_Tools_and_Details/20_Static_Page_Generator.md
Labels: Bug

#12950 [Security] Fix loading Authenticator security config through prepend extension
  bundles/CoreBundle/DependencyInjection/Compiler/AuthenticatorSecurityPass.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/PimcoreCoreBundle.php
Labels: Bug

#12963 [Bug]: datahub_context runtime cache value is reset by Pimcore\Model\Version::loadData
  models/Version.php
Labels: Bug

#12985 [BUG][DataObjects]: Renaming DataObjects doesn´t work
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#12980 [BUG][DataObjects]: Pass condition variables types in ClassDefinition listing DAO
  models/DataObject/ClassDefinition/Listing/Dao.php
Labels: Bug

#12990 Fix target group selection in documents
  bundles/AdminBundle/Resources/public/js/pimcore/document/pages/settings.js
Labels: Bug

#12944 [Custom Layouts] Deprecated Class ClassLayoutDefinitionManager and constant PIMCORE_CUSTOMLAYOUT_DIRECTORY
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Model/DataObject/ClassDefinition/ClassLayoutDefinitionManager.php
  stubs/dynamic-constants.php
Labels: Task

#12996 [Thumbnails] Fixes issue with remote thumbnail storage (e.g. S3) and public URLs
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Bug

#12993 Fix: "Save only scheduled tasks" Button doesn't work
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
Labels: Bug

#12935 [BUG] Object: Show error notification for failed asset upload
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
Labels: Bug

#12937 [Doc] Fix: DBAL Deprecations
  doc/Development_Documentation/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  doc/Development_Documentation/26_Best_Practice/10_Advanced_Pricing_System.md
Labels: Bug

#12991 Use fullpath to fix formatter on readonly
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/reverseObjectRelation.js
Labels: Bug

#12933 [Bug]: Adding a new variant of an object which is using ClassificationStore Selects crashes
  models/DataObject/ClassDefinition/Data/Select.php
Labels: Bug

#12964 [Translations] Fix saving user info & no permissions check with admin domain
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
  models/Translation/Dao.php
Labels: Bug

#13005 Set the value to the userModification Property in Admin Translations
  models/Translation/Dao.php
Labels: Bug

#13003 [Bug]: Problem in versions after removing related asset from Pimcore
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
Labels: Bug

#13001 [Installer] Fix creating "system" user
  bundles/CoreBundle/Migrations/Version20220830105212.php
  bundles/InstallBundle/Installer.php
Labels: Bug

#12974 Drop PHP 8.0 Support
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
Labels: BC-BREAK

#13007 Deprecate Mail::setSubject
  bundles/AdminBundle/Controller/Admin/EmailController.php
  lib/Mail.php
  lib/Mail/Plugins/RedirectingPlugin.php
  lib/Maintenance/Tasks/LogMailMaintenanceTask.php
  lib/Tool.php
  lib/Tool/Newsletter.php
  lib/Workflow/Notification/NotificationEmailService.php
Labels: Task

#12997 Update Doctrine DBAL to V3
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  composer.json
  lib/Db/Helper.php
  lib/Model/Listing/AbstractListing.php
Labels: Task, BC-BREAK

#13020 [Task]: Deprecate Workflow classes
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Workflow.php
  models/Workflow/Dao.php
  models/Workflow/Listing.php
  models/Workflow/Listing/Dao.php
Labels: Task

#12867 Removed session configurators
  bundles/AdminBundle/Resources/config/services.yaml
  bundles/AdminBundle/Session/AdminSessionBagConfigurator.php
  bundles/CoreBundle/DependencyInjection/Compiler/SessionConfiguratorPass.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/PimcoreCoreBundle.php
  bundles/CoreBundle/Resources/config/services.yaml
  bundles/CoreBundle/Resources/config/targeting/session.yaml
  bundles/EcommerceFrameworkBundle/Resources/config/services.yaml
  bundles/EcommerceFrameworkBundle/Tools/SessionConfigurator.php
  doc/Development_Documentation/19_Development_Tools_and_Details/35_Working_with_Sessions.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Session/SessionConfigurator.php
  lib/Session/SessionConfiguratorInterface.php
  lib/Targeting/EventListener/TargetingSessionBagListener.php
  lib/Targeting/Session/SessionConfigurator.php
Labels: Task, BC-BREAK

#13023 Update DAO classmap
  bundles/CoreBundle/Command/InternalModelDaoMappingGeneratorCommand.php
  config/dao-classmap.php
Labels: Bug

#13026 [Bug]: The events "preSaveObject" is not working properly.
  bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js
  bundles/AdminBundle/Resources/public/js/pimcore/document/document.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/folder.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
  bundles/AdminBundle/Resources/public/js/pimcore/plugin/broker.js
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Event_Listener_UI.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
Labels: Bug

#12842 [Improvement]: Remove Wkhtmltopdf and Wkhtmltoimage integrations
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/web2print.js
  bundles/AdminBundle/Resources/views/Admin/Document/Document/diff-versions-unsupported.html.twig
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md
  doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Event/DocumentEvents.php
  lib/Image/HtmlToImage.php
  lib/Web2Print/Processor.php
  lib/Web2Print/Processor/WkHtmlToPdf.php
  models/Document/Service.php
Labels: Improvement
