Repository pimcore/pimcore, pull requests merged in 2022-11, with the labels that each got.

#13492 Fix missing semicolon in nginx config
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Labels: Bug

#13475 Remove Session Fallback BC layer
  bundles/AdminBundle/src/Session/Handler/AdminSessionHandler.php
  bundles/EcommerceFrameworkBundle/src/SessionEnvironment.php
  bundles/EcommerceFrameworkBundle/src/Tracking/TrackingManager.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, BC-BREAK

#13491 Remove unused translations
  bundles/CoreBundle/translations/en.json
Labels: Task

#13473 $addTitles is string with "1" and "0" instead of bool
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#13428 [Task][Config]: Fixing a missing case related to the change from yml to yaml
  bundles/CoreBundle/src/Migrations/Version20221025165133.php
  lib/Config.php
Labels: Task

#13434 [Improvement] Pass additionalData to transition events
  doc/Development_Documentation/07_Workflow_Management/09_Working_with_PHP_API.md
  lib/Workflow/Manager.php
Labels: Improvement

#13505 Fix new PhpStan errors with version 1.9
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
  composer.json
  lib/Google/Cse.php
  lib/Routing/Dynamic/DataObjectRouteHandler.php
  lib/Routing/Dynamic/DocumentRouteHandler.php
  lib/Tool/Text.php
  lib/helper-functions.php
Labels: Bug

#13490 [Task]: Add parameter types getGetter/getSetterCode
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/DataObject/ClassBuilder/ObjectBrickContainerClassBuilder.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Table.php
  tests/Model/DataObject/ClassDefinitionTest.php
  tests/Support/Test/DataType/AbstractDataTypeTestCase.php
Labels: Task

#13480 Bump webmozarts/console-parallelization version to v2
  bundles/CoreBundle/src/Command/ThumbnailsImageCommand.php
  bundles/CoreBundle/src/Command/ThumbnailsVideoCommand.php
  bundles/EcommerceFrameworkBundle/src/Command/IndexService/BootstrapCommand.php
  bundles/EcommerceFrameworkBundle/src/Command/IndexService/ProcessPreparationQueueCommand.php
  bundles/EcommerceFrameworkBundle/src/Command/IndexService/ProcessUpdateIndexQueueCommand.php
  composer.json
  lib/Console/Traits/Parallelization.php
Labels: Improvement

#13509 [Bug fix]: handle the case where the ObjectFieldGetter returns a list of objects
  lib/DataObject/GridColumnConfig/Operator/ObjectFieldGetter.php
Labels: Bug

#13513 [Bug]: Classfication Store - Tabpanel - Scrollbar
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
Labels: Bug

#13518 JS Error in properties tab when we try to add property without type
  bundles/AdminBundle/Resources/public/js/pimcore/element/properties.js
Labels: Bug

#13484 Bugfix Migration:
  bundles/CoreBundle/Migrations/Version20210323082921.php
Labels: Bug

#13360 Define MySQL server and port
  doc/Development_Documentation/01_Getting_Started/01_Advanced_Installation_Topics.md
Labels: Bug

#13508 Concrete::getById() must return only Concrete objects
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/AbstractObject.php
Labels: Bug

#13506 [Admin] Improve UI message "Server threw exception"
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Bug

#13407 Bugfix: Add missing open button for readonly image gallery
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/imageGalleryPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/imagegallery.js
Labels: Bug

#13502 Deprecate PreAuthenticatedAdminSessionListener
  bundles/AdminBundle/Security/Firewall/PreAuthenticatedAdminSessionListener.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Bug

#12723 Object Brick layout improvement; Relates #12719
  bundles/AdminBundle/src/Controller/Admin/DataObject/ClassController.php
Labels: Improvement

#13533 change dialog rendering to use default overwrite logic when using inheritance
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/area_abstract.js
Labels: Bug

#13327 [Feature][Dataobject] add direct upload for video
  bundles/AdminBundle/public/js/pimcore/object/classes/data/video.js
  bundles/AdminBundle/public/js/pimcore/object/tags/video.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/Video.php
Labels: Improvement

#13536 [Bug]: DataObject block-element with localizedfields and wysiwyg throws exception
  models/DataObject/ClassDefinition/Data.php
Labels: Bug

#13504 [Bug]: "Publish" in document context menu published wrong version
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#13452 fix: include documents without navigation name as invisible in navigation builder
  lib/Navigation/Builder.php
Labels: Bug

#13529 [Bug]: Visible fields on many-to-many object relations are not shown.
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/booleanSelect.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/calculatedValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
Labels: Bug

#13478 Symfony 6
  .github/ci/scripts/symfony-require-dev.sh
  .github/workflows/codeception.yaml
  .github/workflows/static-analysis.yaml
  bundles/AdminBundle/config/security_abstract_services.yaml
  bundles/AdminBundle/src/Controller/AdminController.php
  bundles/AdminBundle/src/DependencyInjection/PimcoreAdminExtension.php
  bundles/AdminBundle/src/HttpFoundation/JsonResponse.php
  bundles/AdminBundle/src/Security/Authenticator/AdminAbstractAuthenticator.php
  bundles/AdminBundle/src/Security/Authenticator/PreAuthenticatedAdminSessionAuthenticator.php
  bundles/AdminBundle/src/Security/Firewall/PreAuthenticatedAdminSessionListener.php
  bundles/AdminBundle/src/Security/Hasher/AdminPasswordHasher.php
  bundles/AdminBundle/src/Security/User/User.php
  bundles/AdminBundle/src/Security/User/UserProvider.php
  bundles/CoreBundle/Resources/translations/en.json
  bundles/CoreBundle/config/services_workflow.yaml
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  bundles/InstallBundle/src/InstallerKernel.php
  composer.json
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/01_Authenticate_Pimcore_Objects.md
  lib/Console/Application.php
  lib/Controller/Controller.php
  lib/Controller/FrontendController.php
  lib/Kernel.php
  lib/Log/ApplicationLogger.php
  lib/Mail.php
  lib/Routing/DynamicRouteProvider.php
  lib/Routing/Element/Router.php
  lib/Security/Hasher/Factory/UserAwarePasswordHasherFactory.php
  lib/Security/User/ObjectUserProvider.php
  lib/Session/Attribute/LockableAttributeBag.php
  lib/Test/KernelTestCase.php
  lib/Test/WebTestCase.php
  lib/Translation/Translator.php
  lib/Workflow/MarkingStore/DataObjectSplittedStateMarkingStore.php
  lib/Workflow/MarkingStore/StateTableMarkingStore.php
  models/User.php
Labels: Task

#13049 Add configuration for new notifications check
  bundles/AdminBundle/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/public/js/pimcore/startup.js
  bundles/AdminBundle/src/Controller/Admin/IndexController.php
  bundles/AdminBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/Development_Documentation/18_Tools_and_Features/41_Notifications.md
Labels: Improvement

#13481 [Docs] Update Symfony links
  doc/Development_Documentation/00_Overview/README.md
  doc/Development_Documentation/01_Getting_Started/02_Directory_Structure.md
  doc/Development_Documentation/01_Getting_Started/03_Configuration.md
  doc/Development_Documentation/01_Getting_Started/06_Create_a_First_Project.md
  doc/Development_Documentation/02_MVC/00_Controller.md
  doc/Development_Documentation/02_MVC/02_Template/01_Layouts.md
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/README.md
  doc/Development_Documentation/02_MVC/02_Template/README.md
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/README.md
  doc/Development_Documentation/02_MVC/README.md
  doc/Development_Documentation/06_Multi_Language_i18n/04_Shared_Translations.md
  doc/Development_Documentation/07_Workflow_Management/09_Working_with_PHP_API.md
  doc/Development_Documentation/07_Workflow_Management/README.md
  doc/Development_Documentation/10_E-Commerce_Framework/04_Configuration/README.md
  doc/Development_Documentation/18_Tools_and_Features/17_Application_Logger.md
  doc/Development_Documentation/18_Tools_and_Features/39_Sitemaps.md
  doc/Development_Documentation/19_Development_Tools_and_Details/07_Logging.md
  doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/01_Authenticate_Pimcore_Objects.md
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/05_Authenticator_Based_Security.md
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/13_Debugging.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/01_Pimcore_Mail.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/01_Application_Testing.md
  doc/Development_Documentation/19_Development_Tools_and_Details/35_Working_with_Sessions.md
  doc/Development_Documentation/20_Extending_Pimcore/01_Add_Your_Own_Dependencies_and_Packages.md
  doc/Development_Documentation/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/01_Loading_Service_Definitions.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/01_Installers.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/README.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Dependency_Injection_Tags.md
  doc/Development_Documentation/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
  doc/Development_Documentation/21_Deployment/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/03_File_Permissions.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/README.md
  doc/Development_Documentation/26_Best_Practice/15_Build_Role_Rights_System_for_Frontends.md
  doc/Development_Documentation/26_Best_Practice/75_Security_Concept.md
  doc/Development_Documentation/26_Best_Practice/README.md
Labels: Task

#13449 [Improvement] Detect focal point when detecting faces
  bundles/AdminBundle/src/Controller/Admin/Asset/AssetController.php
Labels: Improvement

#13544 [Fix] moving "allowToCreateNewObject" option out of class context scope
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
Labels: Bug

#13560 [Task]: Remove superfluous null coalescing in Application Logger Processor
  lib/Log/Processor/ApplicationLoggerProcessor.php
Labels: Bug

#13538 [Bug]: Objectbrick definition update fails when changing field of type text to type textarea
  models/DataObject/ClassDefinition/Helper/Dao.php
  models/DataObject/Objectbrick/Definition/Dao.php
Labels: Bug

#13571 [Task]: Fix references to `indexservice:process-queue update-index` in doc/comments
  bundles/EcommerceFrameworkBundle/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/09_Findologic.md
Labels: Task

#13547 [Task]: Quoting `key` column identifier in `ecommerceframework_cartcheckoutdata`
  bundles/EcommerceFrameworkBundle/src/CartManager/CartCheckoutData/Dao.php
Labels: Task

#13581 Fix POEditor jobs with new translations path
  .github/ci/scripts/poeditor-export.php
  .github/ci/scripts/poeditor-import.php
  .github/workflows/poeditor-export.yaml
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#13460 [Task][TestHelpers] Apply native parameter and return type hints according to php docs
  tests/Model/DataType/DataTypeTest.php
  tests/Support/Helper/AbstractDefinitionHelper.php
  tests/Support/Helper/AbstractTestDataHelper.php
  tests/Support/Helper/ClassManager.php
  tests/Support/Helper/DataType/Calculator.php
  tests/Support/Helper/DataType/TestDataHelper.php
  tests/Support/Helper/Document/TestDataHelper.php
  tests/Support/Helper/Ecommerce.php
  tests/Support/Helper/Model.php
  tests/Support/Helper/Pimcore.php
  tests/Support/Test/DataType/AbstractDataTypeTestCase.php
  tests/Support/Util/TestHelper.php
Labels: Improvement

#13521 Removed unused `index` field from `object_url_slugs` table
  bundles/CoreBundle/src/Migrations/Version20221107084519.php
  bundles/InstallBundle/dump/install.sql
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Data/UrlSlug.php
Labels: Task, BC-BREAK

#13552 [Data objects] Support fulltext search for multiselect fields with tag mode
  bundles/AdminBundle/public/js/pimcore/object/tags/multiselect.js
Labels: Improvement

#13551 Fix counting items in store while filtering
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
Labels: Bug

#13565 [Task]: Remove parameter colon prefix to support DBAL v3
  bundles/EcommerceFrameworkBundle/src/Controller/AdminOrderController.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/Order/Listing/Filter/OrderDateTime.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/Order/Listing/Filter/OrderSearch.php
  models/Element/Tag/Dao.php
Labels: Task, BC-BREAK

#13543 Check for limit reach before uploading via upload dialog
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
Labels: Bug

#13549 remove install and plugin url prefix check
  lib/Http/RequestHelper.php
Labels: Bug

#13532 add loadTemplateFromPath for getting a maintenance page via file path
  bundles/CoreBundle/EventListener/MaintenancePageListener.php
  doc/Development_Documentation/20_Extending_Pimcore/15_Maintenance_Mode.md
Labels: Bug

#13561 Fix: Asset/Document model overriding
  models/Asset.php
  models/Document.php
Labels: Bug

#13227 [Object Relations] Tag mode
  bundles/AdminBundle/public/js/pimcore/object/classes/data/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
  bundles/CoreBundle/translations/en.json
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
Labels: Improvement

#13578 [Bug]: Fix Datetime format
  bundles/AdminBundle/Security/BruteforceProtectionHandler.php
  bundles/CoreBundle/EventListener/Frontend/FullPageCacheListener.php
  bundles/CoreBundle/EventListener/Frontend/StaticPageGeneratorListener.php
Labels: Bug

#13563 Bugfix(ClassificationStore): KeyConfig
  models/DataObject/Classificationstore/KeyConfig.php
Labels: Bug

#13594 Fix error undefined index 'analytics'
  lib/Analytics/Google/Config/Config.php
  lib/Analytics/Google/Config/ConfigProvider.php
Labels: Bug

#13576 [Bug]: Not editable for components doesn't work
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#13498 [Improvement]: Being able to save filters on grid options
  bundles/AdminBundle/public/js/pimcore/element/helpers/gridColumnConfig.js
  bundles/AdminBundle/public/js/pimcore/element/helpers/gridConfigDialog.js
  bundles/AdminBundle/public/js/pimcore/helpers.js
  bundles/AdminBundle/public/js/pimcore/object/folder/search.js
  bundles/AdminBundle/public/js/pimcore/object/helpers/gridConfigDialog.js
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectHelperController.php
  models/GridConfig.php
Labels: Improvement

#13599 [BUG] Object Grid: Filter for Multiselect field with OptionProvider
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug

#13598 Fix PhpDoc of `CommitOrderProcessorEvents::SEND_CONFIRMATION_MAILS`
  lib/Event/Ecommerce/CommitOrderProcessorEvents.php
Labels: Bug

#13597 Remove `cart_readonly_mode` from the docs
  doc/Development_Documentation/10_E-Commerce_Framework/11_Cart_Manager.md
Labels: Task

#13539 [Docs] Fixed typo in 68_Object_Data_Inheritance.md
  doc/Development_Documentation/26_Best_Practice/68_Object_Data_Inheritance.md
Labels: Bug

#13624 Fix the default timeout value in process
  lib/Tool/Console.php
Labels: Bug

#13607 [Logger] Added examples and reference to logging in the docs
  doc/Development_Documentation/19_Development_Tools_and_Details/07_Logging.md
Labels: Task

#13635 fixed broken links
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/11_Adding_Object_Datatypes.md
Labels: Improvement

#13570 [Task]: WebMozarts v2 - fetchItems() missing `$output` parameter
  lib/Console/Traits/ParallelizationBase.php
Labels: Task

#13584 add previous exception to exception chain
  models/DataObject/ClassDefinition/Dao.php
Labels: Bug

#13537 [Bug] DataObject: add validation for asset upload in ManyToManyRelation fields
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
Labels: Bug

#13657 [Asset] Thumbnail <source> tag should have width="" and height="" attributes
  models/Asset/Image/Thumbnail.php
Labels: Bug

#13622 [Bug]: Read only style for Quantity Value
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/quantityValue.js
Labels: Bug

#13628 Bugfix/window offscreen
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridConfigDialog.js
Labels: Bug

#13457 Fix notification filtering
  models/Notification/Service/NotificationServiceFilterParser.php
Labels: Bug

#13659 Fixes the Xliff import issue with the dataobjects
  lib/Translation/ImporterService/Importer/DataObjectImporter.php
Labels: Bug

#13637 [Session] Fix AdminSessionHandler write close in case of no main request
  bundles/AdminBundle/Session/Handler/AdminSessionHandler.php
Labels: Bug

#13534 [Predefined Asset Metadata] Prevent creation of predefined item with same name
  bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js
  models/Metadata/Predefined.php
  models/Metadata/Predefined/Listing.php
Labels: Bug

#13609 [Pimcore admin] Prevent error if saved object does not exist anymore
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#13604 Add XLIFF Events
  lib/Event/Model/TranslationXliffEvent.php
  lib/Event/TranslationEvents.php
  lib/Translation/ExportService/Exporter/Xliff12Exporter.php
  lib/Translation/ImporterService/Importer/AbstractElementImporter.php
Labels: Improvement

#13585 [Task]: Quote `object_brick_store_x` column identifier
  models/DataObject/Objectbrick/Data/Dao.php
Labels: Task

#13317 Bump monolog/monolog to ^3
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/DefaultMysql.php
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/DefaultMysql/Dao.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Worker/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Worker/DefaultMysql.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Worker/OptimizedMysql.php
  composer.json
  doc/Development_Documentation/18_Tools_and_Features/17_Application_Logger.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Db.php
  lib/Log/ApplicationLogger.php
  lib/Log/Handler/ApplicationLoggerDb.php
  lib/Log/Processor/ApplicationLoggerProcessor.php
Labels: Task, BC-BREAK

#13572 Cleanup/modernize BundleCollection
  lib/HttpKernel/BundleCollection/BundleCollection.php
  lib/Kernel.php
Labels: Improvement

#13619 [Task]: Prepare for DBAL v4, replace deprecated methods
  bundles/AdminBundle/src/Controller/Admin/LogController.php
  bundles/CoreBundle/src/Migrations/Version20201008101817.php
  bundles/CoreBundle/src/Migrations/Version20211018104331.php
  bundles/EcommerceFrameworkBundle/src/IndexService/IndexUpdateService.php
  bundles/EcommerceFrameworkBundle/src/Tools/Installer.php
  composer.json
  lib/Targeting/Storage/DbStorage.php
  tests/Support/Helper/Pimcore.php
Labels: Task

#13681 Fix; Application logger priority should be always lowercase PSR-3 name
  bundles/AdminBundle/Controller/Admin/LogController.php
Labels: Bug

#13658 Add info about naming strategy to update guide
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
Labels: Bug

#13653 [Task] Follow up native params and return type hints
  bundles/AdminBundle/src/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/src/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/src/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/src/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/src/Controller/Admin/ElementController.php
  bundles/AdminBundle/src/EventListener/UsageStatisticsListener.php
  bundles/AdminBundle/src/Helper/GridHelperService.php
  bundles/AdminBundle/src/Security/Authenticator/AdminLoginAuthenticator.php
  bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php
  bundles/EcommerceFrameworkBundle/src/CoreExtensions/ObjectData/IndexFieldSelection.php
  bundles/EcommerceFrameworkBundle/src/Environment.php
  bundles/EcommerceFrameworkBundle/src/Model/Currency.php
  bundles/EcommerceFrameworkBundle/src/PriceSystem/Price.php
  bundles/EcommerceFrameworkBundle/src/PriceSystem/PriceInterface.php
  bundles/EcommerceFrameworkBundle/src/PricingManager/Rule.php
  bundles/EcommerceFrameworkBundle/src/Tracking/AbstractProductData.php
  bundles/EcommerceFrameworkBundle/src/Tracking/ProductAction.php
  composer.json
  lib/Event/Traits/ResponseAwareTrait.php
  lib/Navigation/Renderer/AbstractRenderer.php
  lib/Navigation/Renderer/Breadcrumbs.php
  lib/Routing/RedirectHandler.php
  lib/Tool/Glossary/Processor.php
  lib/Twig/Extension/Templating/HeadScript.php
  lib/Web2Print/Processor/PdfReactor.php
  lib/helper-functions.php
  models/Asset/Image/Thumbnail.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Layout.php
  models/DataObject/ClassDefinition/Layout/Text.php
  models/DataObject/Classificationstore/GroupConfig.php
  models/DataObject/Classificationstore/KeyGroupRelation.php
  models/DataObject/Concrete.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/QuantityValue/Unit.php
  models/DataObject/Service.php
  models/Document/Dao.php
  models/Document/Editable/Areablock.php
  models/Document/Editable/Select.php
  models/Document/Service/Dao.php
  models/Element/AbstractElement.php
  models/Element/AdminStyle.php
  models/Element/Editlock.php
  models/User.php
  models/Version.php
Labels: Task

#13418 Allow usage of `twig/extra-bundle`
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/templating_twig.yaml
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Kernel.php
Labels: Improvement, Bug

#13564 FC layer for tests support classes
  tests/_support/CacheTester.php
  tests/_support/EcommerceTester.php
  tests/_support/Helper/AbstractDefinitionHelper.php
  tests/_support/Helper/AbstractTestDataHelper.php
  tests/_support/Helper/ClassManager.php
  tests/_support/Helper/DataType/Calculator.php
  tests/_support/Helper/DataType/TestDataHelper.php
  tests/_support/Helper/Document/TestDataHelper.php
  tests/_support/Helper/Ecommerce.php
  tests/_support/Helper/Element/PropertiesTestHelper.php
  tests/_support/Helper/Model.php
  tests/_support/Helper/Pimcore.php
  tests/_support/Helper/Unit.php
  tests/_support/ModelTester.php
  tests/_support/ServiceTester.php
  tests/_support/Test/AbstractPropertiesTest.php
  tests/_support/Test/DataType/AbstractDataTypeTestCase.php
  tests/_support/Test/EcommerceTestCase.php
  tests/_support/Test/ModelTestCase.php
  tests/_support/Test/TestCase.php
  tests/_support/UnitTester.php
  tests/_support/Util/Autoloader.php
  tests/_support/Util/TestHelper.php
Labels: Task

#13606 [Object bricks] Sort brick names in generated code for container class
  bundles/CoreBundle/Migrations/Version20221129084031.php
  lib/DataObject/ClassBuilder/ObjectBrickContainerClassBuilder.php
Labels: Improvement

#13405 Deprecated methods
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Document/Editable/EditableHandler.php
  lib/Extension/Document/Areabrick/AreabrickManagerInterface.php
Labels: Task

#13524 Deprecated `$index` property and `getIndex` and `setIndex` methods from `UrlSlug`
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Data/UrlSlug.php
Labels: Task

#13698 [Task]: Fix possible errors after applying php native types
  lib/Web2Print/Processor/api/PDFreactor.class.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/Country.php
  models/DataObject/ClassDefinition/Data/DateRange.php
  models/DataObject/ClassDefinition/Data/Geo/AbstractGeo.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/ImageTrait.php
  models/DataObject/ClassDefinition/Data/Input.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/NumericRange.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/QuantityValueRange.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/Slider.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/ClassDefinition/Data/Textarea.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/ClassDefinition/Layout.php
  models/DataObject/ClassDefinition/Layout/Panel.php
  models/DataObject/Traits/DataHeightTrait.php
  models/DataObject/Traits/DataWidthTrait.php
  models/User.php
Labels: Task

#13701 [Task]: Implement method to get the version dependent system column name for data objects
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Service.php
Labels: Task
