Repository pimcore/pimcore, pull requests merged in 2022-03, with the labels that each got.

#11544 Respect manually set request attribute "_pimcore_frontend_request"
  lib/Http/RequestHelper.php
Labels: Bug

#11554 [Asset] Remove SVG sanitizer
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/CoreBundle/EventListener/AssetSanitizationListener.php
  bundles/CoreBundle/Resources/config/event_listeners.yaml
  composer.json
Labels: Bug

#11537 Fix nice command
  lib/Tool/Console.php
Labels: Bug

#11561 [DataObject] Do not serialize owner BlockElement inside an Objectbrick
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/Data/BlockElement.php
Labels: Bug

#11566 Clears created tmp files on image optimization exceptions
  lib/Image/Optimizer.php
Labels: Bug

#11573 [Task]: escaping 'key' custom property field in elements
  bundles/AdminBundle/Resources/public/js/pimcore/element/properties.js
Labels: Task

#11582 Fix OnlineshopVoucherSeries displays empty alert - resolves #11579
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php
Labels: Bug

#11572 [Task]: escaping fields in SERP preview
  bundles/AdminBundle/Resources/public/js/pimcore/document/pages/settings.js
Labels: Task

#11602 Fix typo in JS pimcore.helpers.itemselector()
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#11583 Removed static text from notification.
  bundles/AdminBundle/Resources/public/js/pimcore/object/object.js
Labels: Bug

#11608 [Actions] Minio: switched to new config
  .github/workflows/codeception.yml
Labels: Bug

#11593 Fix mail settings error message - resolves#11588
  lib/Mail/Plugins/RedirectingPlugin.php
Labels: Bug

#11600 Remove legacy/redundant piwik files
  bundles/EcommerceFrameworkBundle/Resources/views/Tracking/piwik/calls.js.twig
  doc/Development_Documentation/img/piwik_api_client_options.png
  doc/Development_Documentation/img/piwik_api_update_buttons.png
  doc/Development_Documentation/img/piwik_dashboard.png
  doc/Development_Documentation/img/piwik_iframe_integration.png
  doc/Development_Documentation/img/piwik_reports.png
  doc/Development_Documentation/img/piwik_site_settings.png
Labels: Bug

#11601 [Application logger] Correct log file object path if PIMCORE_PROJECT_ROOT is /app
  lib/Log/ApplicationLogger.php
Labels: Bug

#11597 small correction of siteId in the resolveSlug query
  models/DataObject/Data/UrlSlug.php
Labels: Task

#11625 Align `webdav_locks` table creation in `install.sql`
  bundles/InstallBundle/Resources/install.sql
Labels: Task

#11616 [Admin] Documents - Fix not possible to open documents in localhost -…
  lib/Tool.php
Labels: Bug

#11570 Add icon to not editable fields #11562
  bundles/AdminBundle/Resources/public/css/icons.css
  bundles/AdminBundle/Resources/public/img/flat-color-icons/lock-gray.svg
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
Labels: Improvement

#11639 [Data Object] Fallback for mandatory inherited data object brick
  models/DataObject/ClassDefinition/Data/Objectbricks.php
Labels: Bug

#11655 Fix new phpstan errors
  composer.json
  lib/DataObject/GridColumnConfig/Operator/Boolean.php
  models/Asset.php
  models/Document.php
  models/Element/Service.php
Labels: Bug

#11653 [Bug]: missing setting for UUID identifier (when using Pimcore\Model\…
  doc/Development_Documentation/19_Development_Tools_and_Details/19_UUID_Support.md
  doc/Development_Documentation/img/uuid-support-config.jpg
Labels: Bug

#11649 [Data Object] Set _locale when slug of localized field matches
  lib/Routing/Dynamic/DataObjectRouteHandler.php
Labels: Bug

#11644 Make Pngout and Advpng image optimizers optional
  bundles/CoreBundle/Resources/config/image_optimizers.yaml
  lib/Image/Optimizer/AdvancedPngOptimizer.php
  lib/Image/Optimizer/PngOutOptimizer.php
  lib/Tool/Requirements.php
Labels: Improvement

#11648 [Messenger] SearchBackendHandler: do not skip batch and ack message i…
  lib/Messenger/Handler/SearchBackendHandler.php
Labels: Bug

#11447 [Admin] Security - Add handler to enable Content Security Policy
  bundles/AdminBundle/DependencyInjection/Compiler/ContentSecurityPolicyUrlsPass.php
  bundles/AdminBundle/DependencyInjection/Configuration.php
  bundles/AdminBundle/EventListener/AdminSecurityListener.php
  bundles/AdminBundle/PimcoreAdminBundle.php
  bundles/AdminBundle/Resources/config/event_listeners.yaml
  bundles/AdminBundle/Resources/config/security_services.yaml
  bundles/AdminBundle/Resources/public/js/pimcore/document/pages/preview.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  bundles/AdminBundle/Security/ContentSecurityPolicyHandler.php
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  bundles/EcommerceFrameworkBundle/Resources/views/back-office.html.twig
  doc/Development_Documentation/26_Best_Practice/75_Security_Concept.md
  lib/Twig/Extension/Templating/HeadScript.php
Labels: Improvement

#11552 [Reports] Support drag & drop when configuring columns of a custom report
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/item.js
Labels: Improvement

#11621 [Tracking] Fix warning undefined array index in GoogleTagManager
  bundles/EcommerceFrameworkBundle/Tracking/Tracker/GoogleTagManager.php
Labels: Bug

#11591 Add DuplicateFullPathException
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/DuplicateFullPathException.php
Labels: Improvement

#11612 [Documents] Fix deleting a brick does not delete its content
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
Labels: Bug

#11586 [DataObject] Input Field - RegEx: replace default unicode flag with Flags option in class definition
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/input.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/input.js
  bundles/CoreBundle/Resources/translations/en.extended.json
  models/DataObject/ClassDefinition/Data/Input.php
Labels: Improvement, Bug

#11595 Fix: Blocking Events recursion
  bundles/AdminBundle/Controller/Admin/TargetingController.php
  lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php
  lib/Model/AbstractModel.php
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/Classificationstore/CollectionConfig.php
  models/DataObject/Classificationstore/GroupConfig.php
  models/DataObject/Classificationstore/KeyConfig.php
  models/DataObject/Classificationstore/StoreConfig.php
  models/DataObject/QuantityValue/Unit.php
  models/Document.php
  models/Element/AbstractElement.php
  models/Element/Tag.php
  models/Notification.php
  models/Redirect.php
  models/Search/Backend/Data.php
  models/Tool/Targeting/TargetGroup.php
  models/Translation.php
  models/User/AbstractUser.php
  models/Version.php
Labels: Bug

#11470 [Improvement] Add attribute level placeholders support in index-service config
  bundles/EcommerceFrameworkBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/README.md
Labels: Improvement

#11641 [Fix] create language inherited child didn't set the controller & template
  models/Document/DocType.php
  models/Document/DocType/Dao.php
Labels: Bug

#11676 Update install.sql
  bundles/InstallBundle/Resources/install.sql
Labels: Bug

#11675 [Bug]: (Grid view) adds "empty" option in select
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/select.js
Labels: Bug

#11557 [Bug]: Added Multi-site 'id' to DataObject Route Key
  lib/Routing/DataObjectRoute.php
  lib/Routing/Dynamic/DataObjectRouteHandler.php
Labels: Bug

#11669 Thumbnails: deferred service controller: improved error handling
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Bug

#11636 Remove javascript alert().
  bundles/AdminBundle/Resources/public/js/pimcore/workflow/transitions.js
Labels: Bug

#11614 Fix: DocumentResolver::getDocument() don't return document in new areabricks
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
Labels: Bug

#11711 Fix Symfony deprecations
  bundles/CoreBundle/PimcoreCoreBundle.php
  lib/Kernel.php
Labels: Bug

#11713 Doc fix about object_(id) View
  doc/Development_Documentation/19_Development_Tools_and_Details/05_Database_Model.md
Labels: Bug

#11346 Add event for "export report" button
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/report.js
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Plugin_Backend_UI.md
Labels: Improvement

#11712 paramater typo
  doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/README.md
Labels: Bug

#11695 Fix regression of QuickSearch change
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
Labels: Bug

#11726 [Calculated value] Prevent entering an undefined calculated value field type
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/calculatedValue.js
Labels: Bug

#11731 [Maintenance] Log job start
  lib/Maintenance/Executor.php
Labels: Improvement

#11703 Fix Admin QR Code Generator for use with Sites
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
Labels: Bug

#11698 [DataObjects] UrlSlug - fix visibility site specific url fields
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/urlSlug.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js
  models/DataObject/ClassDefinition/Data/UrlSlug.php
Labels: Bug

#11707 [Bug]: Inconsistent getter behaviour when getting values from object brick in preSave listener
  bundles/CoreBundle/Migrations/Version20220318101020.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/DataObject/ClassBuilder/ObjectBrickContainerClassBuilder.php
  models/DataObject/Objectbrick.php
Labels: Bug

#11696 Fix - Name and Editable field of the targetGroup data type was not wo…
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/targetGroup.js
Labels: Bug

#11706 [Asset] Low quality image preview optimization if disabled
  models/Asset/Image.php
Labels: Improvement

#11632 Added srcset attribute to img element
  models/Asset/Image/Thumbnail.php
Labels: Improvement

#11702 [Asset] Thumbnails: added status cache for image thumbnails
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/CoreBundle/Controller/PublicServicesController.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Migrations/Version20220317125711.php
  bundles/InstallBundle/Resources/install.sql
  models/Asset.php
  models/Asset/Dao.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
  phpstan-baseline.neon
  tests/Model/Asset/AssetThumbnailCacheTest.php
Labels: Improvement

#11774 Clearify supported branches
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: Task

#11769 Fix non "thumbnail-able" images to be prefixed (eg. SVG's)
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#11758 Fix cache argument to be priority instead of lifetime
  models/Translation/Listing/Dao.php
Labels: Bug

#11777 [Asset] Wrong frontend prefix is used for low quality image placeholders
  models/Asset/Image.php
Labels: Bug

#11605 Fix Link Editable display in editmode
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/link.js
Labels: Bug

#11785 Fix deprecation in wysiwyg
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
Labels: Bug

#11786 Fix deprecation in Dependency
  models/Dependency.php
Labels: Bug

#11792 [User] Fix strlen deprecation in setPassword()
  models/User.php
Labels: Bug

#11788 Fix deprecation in Multiselect
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug

#11787 Fix deprecation in Numeric
  models/DataObject/ClassDefinition/Data/Numeric.php
Labels: Bug

#11722 [Asset folder preview] Respect limit / Prevent error "Maximum supported image dimension is 65500 pixels"
  models/Asset/Folder.php
Labels: Bug

#11789 Fix deprecation in Select
  models/DataObject/ClassDefinition/Data/Select.php
Labels: Bug

#11782 fix: PHP 8.1 deprecation: passing null to strlen()
  models/DataObject/ClassDefinition/Data/Extension/Text.php
Labels: Bug

#11780 fix: PHP 8.1 doesn't allow passing null to explode()
  models/Staticroute.php
Labels: Bug

#11776 PIMCORE_DEV_MODE env variable should handle boolean string values properly
  lib/Pimcore.php
Labels: Bug

#11744 [Bug]: Date & Time "use current date" cannot be checked
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/datetime.js
Labels: Bug

#11793 [Data Object] Multiselect follow up fix
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug

#11806 Ignore not found properties in deep copies
  models/Element/Service.php
Labels: Bug

#11808 Date fields do not fire changed events
  bundles/AdminBundle/Resources/public/js/pimcore/overrides.js
Labels: Bug

#11794 Fix: Version\Listing::loadIdList() returns string[] instead of int[]
  lib/Db/ConnectionInterface.php
  lib/Db/PimcoreExtensionsTrait.php
  models/Version/Listing/Dao.php
Labels: Bug

#11756 Remove codeception/module-symfony
  composer.json
  tests/_bootstrap.php
  tests/_support/Helper/Pimcore.php
Labels: Improvement
