Repository pimcore/pimcore, pull requests merged in 2022-10, with the labels that each got.

#13154 Fix sending image data embedded in CSV
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
Labels: Improvement

#13274 verify path points to file before reading file
  lib/Twig/Extension/AdminExtension.php
Labels: Bug

#13230 Replaced return type in `InstallerInterface::getOutput` method to be `BufferedOutput`
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Extension/Bundle/Installer/AbstractInstaller.php
  lib/Extension/Bundle/Installer/InstallerInterface.php
Labels: Task, BC-BREAK

#13264 Task: Bump league/html-to-markdown to ^5.1
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#13209 Removed method_exists() BC-layer on Editables
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Templating/Renderer/EditableRenderer.php
  models/Document/Editable.php
  models/Document/Editable/Area.php
  models/Document/Editable/Date.php
  models/Document/Editable/EditmodeDataInterface.php
  models/Document/Editable/IdRewriterInterface.php
  models/Document/Editable/Image.php
  models/Document/Editable/Input.php
  models/Document/Editable/LazyLoadingInterface.php
  models/Document/Editable/Link.php
  models/Document/Editable/Multiselect.php
  models/Document/Editable/Pdf.php
  models/Document/Editable/Relation.php
  models/Document/Editable/Relations.php
  models/Document/Editable/Renderlet.php
  models/Document/Editable/Snippet.php
  models/Document/Editable/Textarea.php
  models/Document/Editable/Video.php
  models/Document/Editable/Wysiwyg.php
  models/Document/Service.php
Labels: Task, BC-BREAK

#13259 Override getFilterConditionExt
  models/DataObject/ClassDefinition/Data/Numeric.php
Labels: Bug

#13239 Code cleanup: Follow-up of #13093
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
Labels: Task

#13325 Codeception: Use node.JS LTS version
  .github/workflows/codeception.yml
Labels: Bug

#13326 Fix new PhpStan errors with version 1.8.8
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/ElasticSearch/NumberRange.php
  bundles/EcommerceFrameworkBundle/FilterService/FilterType/NumberRange.php
  composer.json
  lib/DataObject/GridColumnConfig/Operator/Concatenator.php
  lib/DataObject/GridColumnConfig/ResultContainer.php
  models/DataObject/ClassDefinition/Data/Time.php
  models/User.php
Labels: Bug

#13186 [Feature][Dataobject] add confirm dialog to empty button of relations and add possibility to disable clear relations
  bundles/AdminBundle/public/js/pimcore/object/classes/data/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/public/js/pimcore/object/classes/data/advancedManyToManyRelation.js
  bundles/AdminBundle/public/js/pimcore/object/classes/data/manyToManyObjectRelation.js
  bundles/AdminBundle/public/js/pimcore/object/classes/data/manyToManyRelation.js
  bundles/AdminBundle/public/js/pimcore/object/classes/data/manyToOneRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/manyToManyObjectRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/manyToOneRelation.js
  bundles/CoreBundle/translations/en.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/70_Relation_Types.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
Labels: Improvement

#13286 Update Docs: Upgrade Notes for 10.5
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#13226 Remove getTotalCount from AbstractObject/Asset/Document
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
Labels: Task, BC-BREAK

#13263 [Task]: Bump league/flysystem-bundle to ^3.0
  bundles/CoreBundle/config/pimcore/flysystem.yaml
  composer.json
  doc/Development_Documentation/19_Development_Tools_and_Details/20_Static_Page_Generator.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/03_File_Storage_Setup.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Maintenance/Tasks/LogArchiveTask.php
Labels: Task

#13143 Improvement: site event handling
  lib/Event/Model/SiteEvent.php
  lib/Event/SiteEvents.php
  models/Site.php
Labels: Improvement

#13305 [Bug]: RGBA Color doesn't work if user language is german
  bundles/AdminBundle/Resources/public/js/pimcore/colorpicker-overrides.js
Labels: Bug

#13233 [Improvement]: Add variants to DataObjects getChildren(), listing, ..
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/70_Variants.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/AbstractObject.php
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/Listing.php
  models/Document/Editable/Relations.php
  tests/Model/Permissions/ModelDataObjectPermissionsTest.php
Labels: Improvement

#13147 [Feature][DataObject] Add possibility to download asset in relations
  bundles/AdminBundle/public/js/pimcore/object/classes/data/advancedManyToManyRelation.js
  bundles/AdminBundle/public/js/pimcore/object/classes/data/manyToManyRelation.js
  bundles/AdminBundle/public/js/pimcore/object/classes/data/manyToOneRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/manyToManyRelation.js
  bundles/AdminBundle/public/js/pimcore/object/tags/manyToOneRelation.js
  bundles/CoreBundle/translations/en.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/70_Relation_Types.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
Labels: Improvement

#13329 fixes the height of the object preview iframe
  bundles/AdminBundle/Resources/public/js/pimcore/object/preview.js
Labels: Bug

#13290 Added more methods to `Pimcore/Model/Element/ElementInterface`
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Element/ElementInterface.php
Labels: Improvement, BC-BREAK

#13334 Fix twig example code to actually use a comment as intended
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/00_Placeholder.md
Labels: Bug

#13115 Use TEMPLATE_LOCATION_GLOBAL by default
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Document/Editable/EditableHandler.php
  lib/Extension/Document/Areabrick/AbstractTemplateAreabrick.php
  lib/Extension/Document/Areabrick/TemplateAreabrickInterface.php
Labels: Improvement, BC-BREAK

#13338 add `is_string()` before `strlen()` on possible `null` values in `Pimcore\Model\DataObject\ClassDefinition\Data\Time`
  models/DataObject/ClassDefinition/Data/Time.php
Labels: Bug

#13314 [Ecommerce] Token Manager: do no silently ignore errors on generation
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php
  bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php
Labels: Bug

#13206 Notes: Missing delete option
  bundles/AdminBundle/public/js/pimcore/element/notes.js
  bundles/AdminBundle/src/Controller/Admin/ElementController.php
  bundles/CoreBundle/src/Migrations/Version20221005090000.php
  bundles/InstallBundle/dump/install.sql
  models/Element/Note.php
  models/Element/Service.php
Labels: Bug

#13324 [Bug]: DocumentController::docTypesAction fixes
  bundles/AdminBundle/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Bug

#13350 Fixed the translation key entries.
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/glossary.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#13351 [Improvement]: consistently use .yaml not .yml v1
  .github/ISSUE_TEMPLATE/Bug-Report.yaml
  .github/ISSUE_TEMPLATE/Feature-Request.yaml
  .github/ISSUE_TEMPLATE/Improvement.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ci/files/config/config.yaml
  .github/ci/files/config/routes/test/routes.yaml
  .github/ci/files/config/system.yaml
  .github/ci/files/minio-flysystem.yaml
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/workflows/codeception.yaml
  .github/workflows/docs.yaml
  .github/workflows/lts-repo-sync.yaml
  .github/workflows/mirror.yaml
  .github/workflows/php-cs-fixer.yaml
  .github/workflows/poeditor-export.yaml
  .github/workflows/poeditor-import.yaml
  .github/workflows/pull-request-checklist.yaml
  .github/workflows/stale.yaml
  .github/workflows/static-analysis.yaml
  bundles/AdminBundle/src/Controller/Admin/SettingsController.php
  bundles/CoreBundle/config/routing.yaml
  bundles/CoreBundle/config/routing_dev.yaml
  bundles/InstallBundle/src/Command/InstallCommand.php
  bundles/InstallBundle/src/Installer.php
  bundles/InstallBundle/src/SystemConfig/ConfigWriter.php
  doc/Development_Documentation/01_Getting_Started/03_Configuration.md
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
  doc/Development_Documentation/18_Tools_and_Features/25_System_Settings.md
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  doc/Development_Documentation/19_Development_Tools_and_Details/32_Google_Services_Integration.md
  doc/Development_Documentation/19_Development_Tools_and_Details/40_Custom_Admin_Login_Entry_Point.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/03_Auto_Loading_Config_And_Routing_Definitions.md
  doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Config/BundleConfigLocator.php
  lib/Config/LocationAwareConfigRepository.php
  lib/Kernel.php
  tests/bin/docker-compose.yaml
Labels: Improvement, BC-BREAK, Priority

#12788 Metainfo user names
  bundles/AdminBundle/public/js/pimcore/asset/asset.js
  bundles/AdminBundle/public/js/pimcore/asset/folder.js
  bundles/AdminBundle/public/js/pimcore/document/folder.js
  bundles/AdminBundle/public/js/pimcore/document/page_snippet.js
  bundles/AdminBundle/public/js/pimcore/element/metainfo.js
  bundles/AdminBundle/public/js/pimcore/object/folder.js
  bundles/AdminBundle/public/js/pimcore/object/object.js
  bundles/AdminBundle/src/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/src/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/src/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/src/Controller/Admin/Document/EmailController.php
  bundles/AdminBundle/src/Controller/Admin/Document/FolderController.php
  bundles/AdminBundle/src/Controller/Admin/Document/HardlinkController.php
  bundles/AdminBundle/src/Controller/Admin/Document/LinkController.php
  bundles/AdminBundle/src/Controller/Admin/Document/NewsletterController.php
  bundles/AdminBundle/src/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/src/Controller/Admin/Document/SnippetController.php
  bundles/AdminBundle/src/Controller/Admin/UserController.php
  bundles/AdminBundle/src/Controller/Traits/UserNameTrait.php
  models/User.php
Labels: Improvement

#13309 [Bug] Fix search bug in HTTP Errors log
  bundles/AdminBundle/Resources/public/js/pimcore/settings/httpErrorLog.js
Labels: Bug

#13335 [Improvement]: Add return types for CalculatedValue getter
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
Labels: Improvement

#13339 [Bug]: Can't filter classification store booleanSelect type in grid
  bundles/AdminBundle/Helper/GridHelperService.php
  models/DataObject/ClassDefinition/Data.php
Labels: Bug

#13348 [Bug]: GeoPoint JavaScript Exception
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopoint.js
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#13340 PhpDoc: Remove unnecessary union types included in mixed
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Controller/Admin/Document/PrintpageControllerBase.php
  lib/Cache/Core/CoreCacheHandler.php
  lib/Config.php
  lib/Config/LocationAwareConfigRepository.php
  lib/DataObject/GridColumnConfig/Service.php
  lib/Db/ConnectionInterface.php
  lib/Document/Editable/EditableHandler.php
  lib/Event/Admin/Login/LoginFailedEvent.php
  lib/Helper/Dashboard.php
  lib/Loader/ImplementationLoader/PrefixLoader.php
  lib/Model/Dao/AbstractDao.php
  lib/Model/Dao/PimcoreLocationAwareConfigDao.php
  lib/Routing/Redirect/Csv.php
  lib/Security/Encoder/Factory/AbstractEncoderFactory.php
  lib/Security/Hasher/Factory/AbstractHasherFactory.php
  lib/Targeting/Debug/Util/OverrideAttributeResolver.php
  lib/Targeting/Model/VisitorInfo.php
  lib/Tool.php
  lib/Workflow/Service.php
  models/Asset/WebDAV/Service.php
  models/DataObject/AbstractObject.php
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Helper/CalculatorClassResolver.php
  models/DataObject/ClassDefinition/Helper/ClassResolver.php
  models/DataObject/ClassDefinition/Helper/DefaultValueGeneratorResolver.php
  models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php
  models/DataObject/Localizedfield.php
  models/DataObject/Service.php
  models/Document/Editable/Area/Info.php
  models/Element/Service.php
  models/User.php
  models/Workflow.php
Labels: Bug

#13311 [Bug]: Adds Video Thumbnail support in PublicServices when using Flysystem
  bundles/CoreBundle/Controller/PublicServicesController.php
  bundles/CoreBundle/Resources/config/routing.yml
  tests/Model/Asset/AssetThumbnailCacheTest.php
Labels: Bug

#13346 [Bug]: empty values in $context in CalculatorClassInterface
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/Data/CalculatedValue.php
Labels: Bug

#13349 [StaticPageGenerator] Fix generating static content for homepage
  bundles/CoreBundle/EventListener/Frontend/StaticPageGeneratorListener.php
  doc/Development_Documentation/19_Development_Tools_and_Details/20_Static_Page_Generator.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/01_Apache_Configuration.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Document/StaticPageGenerator.php
Labels: Bug

#13238 Fix styling for inherited fields with label top
  bundles/AdminBundle/Resources/public/css/admin.css
Labels: Bug

#13322 [Task]: Remove deprecated services related to cache and tagRenderer
  bundles/CoreBundle/config/cache.yaml
  bundles/CoreBundle/config/templating.yaml
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, BC-BREAK

#13043 Remove ChildsCompatibilityTrait
  bundles/AdminBundle/public/js/pimcore/asset/helpers/metadataTree.js
  bundles/AdminBundle/public/js/pimcore/object/classes/layout/layout.js
  bundles/AdminBundle/public/js/pimcore/object/fieldlookup/helper.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Layout.php
  models/DataObject/Classificationstore/GroupConfig/Dao.php
  models/Element/ChildsCompatibilityTrait.php
  models/User/AbstractUser/Dao.php
  models/User/UserRole/Folder.php
Labels: Task, Priority

#13312 Task: Remove unused `psr/simple-cache` package requirement
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#13197 [Improvement]: Safety measure preventing user from deleting parent instead of elements selected in grid
  bundles/AdminBundle/public/js/pimcore/elementservice.js
  bundles/CoreBundle/translations/en.json
Labels: Improvement

#13277 Upgraded the mjaschen/phpgeo version to 4
  composer.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#13306 [Task]: Presta/Sitemap-bundle support only ^3.3
  composer.json
  doc/Development_Documentation/18_Tools_and_Features/39_Sitemaps.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Kernel.php
Labels: Task, BC-BREAK

#13364 Remove `@internal` tag from `QueryBuilderHelperTrait`
  lib/Model/Listing/Dao/QueryBuilderHelperTrait.php
Labels: Bug

#13396 Remove Preview Url(Deprecated) from DataObjects
  bundles/AdminBundle/public/js/pimcore/object/classes/class.js
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
  bundles/CoreBundle/translations/en.extended.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/55_Preview.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/05_Class_Settings/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Service.php
Labels: Task, BC-BREAK

#13237 Fix deeplink with custom entrypoint
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/folder.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Bug

#13352 Add missing config params in facade docs
  lib/Twig/Extension/Templating/Navigation.php
Labels: Bug, Task

#13345 Clean example code in `17_Custom_Persistent_Models.md` up
  doc/Development_Documentation/20_Extending_Pimcore/17_Custom_Persistent_Models.md
Labels: Bug, Task

#13342 Fix overflowing name and description on document area on hover
  bundles/AdminBundle/Resources/public/css/editmode.css
Labels: Bug

#13214 Return $this should be type hint static instead of self
  bundles/AdminBundle/src/Security/ContentSecurityPolicyHandler.php
  bundles/CoreBundle/src/Command/Bundle/AbstractBundleCommand.php
  bundles/EcommerceFrameworkBundle/src/IndexService/IndexService.php
  bundles/EcommerceFrameworkBundle/src/Tracking/TrackingManager.php
  bundles/EcommerceFrameworkBundle/src/Tracking/TrackingManagerInterface.php
  lib/Extension/Document/Areabrick/EditableDialogBoxConfiguration.php
  lib/HttpKernel/BundleCollection/BundleCollection.php
  lib/Model/Listing/AbstractListing.php
  lib/Routing/DataObjectRoute.php
  lib/Twig/Extension/Templating/Traits/WebLinksTrait.php
  lib/Web2Print/Processor/HeadlessChrome.php
  models/Document/Editable.php
  models/Element/AbstractElement.php
  models/Element/ElementInterface.php
  models/Notification.php
  models/Notification/Listing.php
  models/Schedule/Task.php
  models/Version.php
  models/Version/Listing.php
Labels: Improvement

#13383 [Fix] adding itemid for working reset
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/time.js
Labels: Bug

#13384 [Fix] getting value.value if value is an object
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/country.js
Labels: Bug

#13368 Remove checking of non-existing request attribute
  bundles/CoreBundle/EventListener/EventedControllerListener.php
Labels: Bug

#13369 Fix usage of `KernelResponseEventInterface` without `KernelControllerEventInterface`
  bundles/CoreBundle/EventListener/EventedControllerListener.php
Labels: Bug

#13265 improvement: add cause element to duplicate full path exception
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/DuplicateFullPathException.php
Labels: Improvement

#13385 [Bug]: Warning: "Attempt to read property "containerKey" on null" when i want to save a data object
  lib/DataObject/GridColumnConfig/Value/DefaultValue.php
Labels: Bug

#13356 Bugfix: Fixed imageGallery mandatory check if at least one image is n…
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/Data/ImageGallery.php
Labels: Bug

#13426 [Bug]: Not possible to create DataObject classes in 11.x branch
  models/DataObject/ClassDefinition.php
Labels: Bug

#13367 [Security] Make new authenticator default and remove support for old authentication system
  .github/ci/scripts/symfony-require-dev.sh
  bundles/AdminBundle/config/pimcore/config.yaml
  bundles/AdminBundle/config/pimcore/default.yaml
  bundles/AdminBundle/config/pimcore/two_factor_authentication.yaml
  bundles/AdminBundle/config/security_services.yaml
  bundles/AdminBundle/config/security_services_legacy.yaml
  bundles/AdminBundle/src/Controller/Admin/LoginController.php
  bundles/AdminBundle/src/Controller/BruteforceProtectedControllerInterface.php
  bundles/AdminBundle/src/DependencyInjection/Compiler/LegacyAuthenticationSecurityPass.php
  bundles/AdminBundle/src/EventListener/BruteforceProtectionListener.php
  bundles/AdminBundle/src/EventListener/TwoFactorListener.php
  bundles/AdminBundle/src/PimcoreAdminBundle.php
  bundles/AdminBundle/src/Security/Authentication/Token/LegacyTwoFactorRequiredToken.php
  bundles/AdminBundle/src/Security/Authentication/Token/PreAuthenticatedAdminToken.php
  bundles/AdminBundle/src/Security/BruteforceProtectionHandler.php
  bundles/AdminBundle/src/Security/Encoder/AdminPasswordEncoder.php
  bundles/AdminBundle/src/Security/Exception/BruteforceProtectionException.php
  bundles/AdminBundle/src/Security/Firewall/PreAuthenticatedAdminSessionListener.php
  bundles/AdminBundle/src/Security/Guard/AdminAuthenticator.php
  bundles/AdminBundle/src/Security/LogoutSuccessHandler.php
  bundles/CoreBundle/config/authenticator_security.yaml
  bundles/CoreBundle/config/pimcore/config.yaml
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/config/services.yaml
  bundles/CoreBundle/src/DependencyInjection/Compiler/PasswordFactoryDecoratorPass.php
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/src/PimcoreCoreBundle.php
  composer.json
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/01_Authenticate_Pimcore_Objects.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Security/Encoder/AbstractUserAwarePasswordEncoder.php
  lib/Security/Encoder/EncoderFactory.php
  lib/Security/Encoder/EncoderFactoryAwareInterface.php
  lib/Security/Encoder/EncoderFactoryAwareUserInterface.php
  lib/Security/Encoder/Factory/AbstractEncoderFactory.php
  lib/Security/Encoder/Factory/UserAwareEncoderFactory.php
  lib/Security/Encoder/PasswordFieldEncoder.php
  lib/Security/Encoder/UserAwarePasswordEncoderInterface.php
  lib/Security/Hasher/Factory/UserAwarePasswordHasherFactory.php
  lib/Security/Hasher/PasswordHasherFactory.php
  lib/Security/Hasher/PasswordHasherFactoryAwareUserInterface.php
  phpstan-parameters.neon
Labels: Task, BC-BREAK

#13400 Bumpped 2fa-bundle version to ^6.0
  composer.json
Labels: Task

#13297 [Improvement]: Move configurations to AdminBundle which are UI only
  bundles/AdminBundle/config/event_listeners.yaml
  bundles/AdminBundle/config/pimcore/config.yaml
  bundles/AdminBundle/config/pimcore/default.yaml
  bundles/AdminBundle/config/services.yaml
  bundles/AdminBundle/src/DependencyInjection/Compiler/TranslatorPass.php
  bundles/AdminBundle/src/DependencyInjection/Configuration.php
  bundles/AdminBundle/src/DependencyInjection/PimcoreAdminExtension.php
  bundles/AdminBundle/src/EventListener/AdminSessionBagListener.php
  bundles/AdminBundle/src/PimcoreAdminBundle.php
  bundles/CoreBundle/config/documents.yaml
  bundles/CoreBundle/config/l10n.yaml
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/config/pimcore/flysystem.yaml
  bundles/CoreBundle/config/templating_twig.yaml
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Tool/Admin.php
Labels: Improvement

#13421 Update 35_Fieldcollections.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/35_Fieldcollections.md
Labels: Bug

#13417 [Search] Use transactions for saving and fix fullpath update issue
  models/Search/Backend/Data.php
  models/Search/Backend/Data/Dao.php
  tests/Model/Permissions/ModelAssetPermissionsTest.php
Labels: Bug

#13442 FullPageCacheListener kernel.request handler needs to be executed aft…
  bundles/CoreBundle/config/event_listeners.yaml
Labels: Bug

#13420 Add translation for "no_further_classes_allowed"
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#13438 Added exception handling in migrations
  bundles/CoreBundle/Migrations/Version20201008101817.php
Labels: Bug

#13394 [Docs] Performance: Mention command pimcore:cache:warming
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/09_Performance_Guide.md
Labels: Bug

#13409 Replace `{@internal}` annotations with `@internal`
  lib/Composer.php
  lib/Model/Paginator/EventSubscriber/PaginateListingSubscriber.php
  lib/Web2Print/Processor/HeadlessChrome.php
  lib/Web2Print/Processor/PdfReactor.php
  lib/Web2Print/Processor/WkHtmlToPdf.php
Labels: Bug

#13399 Update definitions
  .github/ci/files/var/classes/DataObject/Customer.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterCategory.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterCategoryMultiselect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterInputfield.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterMultiRelation.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterMultiSelect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterMultiSelectFromMultiSelect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterNumberRange.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterNumberRangeSelection.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterRelation.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterSelect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterSelectFromMultiSelect.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/OrderByFields.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/OrderPriceModifications.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/PaymentInfo.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/PricingRule.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/TaxEntry.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/VoucherTokenTypePattern.php
  .github/ci/files/var/classes/DataObject/Fieldcollection/Data/VoucherTokenTypeSingle.php
  .github/ci/files/var/classes/DataObject/FilterDefinition.php
  .github/ci/files/var/classes/DataObject/OnlineShopOrder.php
  .github/ci/files/var/classes/DataObject/OnlineShopOrderItem.php
  .github/ci/files/var/classes/DataObject/OnlineShopTaxClass.php
  .github/ci/files/var/classes/DataObject/OnlineShopVoucherSeries.php
  .github/ci/files/var/classes/DataObject/OnlineShopVoucherToken.php
  .github/ci/scripts/setup-pimcore-environment.sh
  bundles/EcommerceFrameworkBundle/install/class_sources/class_FilterDefinition_export.json
  bundles/EcommerceFrameworkBundle/install/class_sources/class_OfferToolCustomProduct_export.json
  bundles/EcommerceFrameworkBundle/install/class_sources/class_OfferToolOfferItem_export.json
  bundles/EcommerceFrameworkBundle/install/class_sources/class_OfferToolOffer_export.json
  bundles/EcommerceFrameworkBundle/install/class_sources/class_OnlineShopOrderItem_export.json
  bundles/EcommerceFrameworkBundle/install/class_sources/class_OnlineShopOrder_export.json
  bundles/EcommerceFrameworkBundle/install/class_sources/class_OnlineShopTaxClass_export.json
  bundles/EcommerceFrameworkBundle/install/class_sources/class_OnlineShopVoucherSeries_export.json
  bundles/EcommerceFrameworkBundle/install/class_sources/class_OnlineShopVoucherToken_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterCategoryMultiselect_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterCategory_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterInputfield_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterMultiRelation_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterMultiSelectFromMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterNumberRangeSelection_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterNumberRange_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterRelation_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterSelectClsStoreAttributes_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterSelectFromMultiSelect_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_FilterSelect_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_OrderPriceModifications_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_PaymentInfo_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_PricingRule_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_SimilarityField_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_TaxEntry_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_VoucherTokenTypePattern_export.json
  bundles/EcommerceFrameworkBundle/install/fieldcollection_sources/fieldcollection_VoucherTokenTypeSingle_export.json
  lib/DataObject/ClassBuilder/ClassBuilder.php
Labels: Task

#13393 Removing bundle manager and registering bundles in extensions.php
  bundles/AdminBundle/config/pimcore/routing.yaml
  bundles/AdminBundle/public/js/pimcore/extensionmanager/admin.js
  bundles/AdminBundle/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/src/Controller/ExtensionManager/ExtensionManagerController.php
  bundles/AdminBundle/templates/admin/index/index.html.twig
  bundles/CoreBundle/config/commands.yaml
  bundles/CoreBundle/config/extensions.yaml
  bundles/CoreBundle/src/Command/Bundle/DisableCommand.php
  bundles/CoreBundle/src/Command/Bundle/EnableCommand.php
  bundles/CoreBundle/src/Command/Bundle/ListCommand.php
  bundles/CoreBundle/src/Migrations/Version20221019042134.php
  bundles/CoreBundle/translations/en.extended.json
  bundles/EcommerceFrameworkBundle/src/PimcoreEcommerceFrameworkBundle.php
  bundles/InstallBundle/src/Installer.php
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/README.md
  doc/Development_Documentation/20_Extending_Pimcore/01_Add_Your_Own_Dependencies_and_Packages.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/04_Bundle_Collection.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/01_Installers.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/README.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Document/Editable/EditableHandler.php
  lib/Extension/Bundle/AbstractPimcoreBundle.php
  lib/Extension/Bundle/Config/StateConfig.php
  lib/Extension/Bundle/PimcoreBundleInterface.php
  lib/Extension/Bundle/PimcoreBundleManager.php
  lib/Extension/Bundle/Traits/StateHelperTrait.php
  lib/Extension/Config.php
  lib/Extension/Document/Areabrick/AreabrickManager.php
  lib/Extension/Document/Areabrick/AreabrickManagerInterface.php
  lib/Kernel.php
  models/Document/Editable/Area.php
  models/Document/Editable/Areablock.php
Labels: Task, BC-BREAK

#13447 [Docs] Clearer update instructions V6 -> V10
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
Labels: Improvement

#13432 docker-compose: rename service php-fpm to just `php` and use new tag names
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  tests/bin/docker-compose.yml
  tests/bin/init-tests.sh
Labels: Bug

#13370 fix: mailto not working anymore when editing links
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#13444 [Security] Authenticator based security - Return plain response
  bundles/AdminBundle/Security/Authenticator/AdminAbstractAuthenticator.php
  bundles/AdminBundle/Security/Authenticator/AdminLoginAuthenticator.php
Labels: Bug

#13347 [Mail] Renderer email content twig templates in a sandbox
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  bundles/CoreBundle/Resources/config/templating_twig.yaml
  doc/Development_Documentation/05_Objects/01_Object_Classes/03_Layout_Elements/01_Dynamic_Text_Labels.md
  doc/Development_Documentation/19_Development_Tools_and_Details/25_Email_Framework/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Mail.php
  lib/Templating/TwigDefaultDelegatingEngine.php
  lib/Twig/Sandbox/SecurityPolicy.php
  models/DataObject/ClassDefinition/Layout/Text.php
Labels: Bug

#13328 [Documents] Editable Dialog Box - Add description support
  bundles/AdminBundle/public/js/pimcore/document/editables/area_abstract.js
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
Labels: Improvement, hacktoberfest-accepted

#13373 [Task] Quoting Pricing rule `condition` field
  bundles/EcommerceFrameworkBundle/src/PricingManager/Rule/Dao.php
Labels: Task

#13371 Task: Removed aliases related to deprecated Pimcore\Db\Connection
  bundles/CoreBundle/config/aliases.yaml
Labels: Task

#13382 [Elements] Filter all control/unassigned and invalid characters as well as line breaks and tabs from keys
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Element/Service.php
Labels: BC-BREAK

#13482 [Bug]: Field Collection field definition generated getters missing native return type
  bundles/CoreBundle/Migrations/Version20221028115803.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
Labels: Bug
