Repository pimcore/pimcore, pull requests merged in 2022-12, with the labels that each got.

#13613 Introduced Db\Helper::upsert() which avoids deadlocks
  lib/Db/Helper.php
Labels: Improvement

#13651 [Data objects] Version preview for blocks
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
Labels: Improvement

#13713 [Docs] Mention migrating document editable naming strategy
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
Labels: Bug

#13643 Fix test env session config
  bundles/CoreBundle/Resources/config/pimcore/test.yaml
  composer.json
Labels: Bug

#13725 More type fixes
  lib/CustomView/Config.php
  lib/Perspective/Config.php
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Video/ImageThumbnail.php
  models/Document/Editable/Image.php
Labels: Task

#13709 Fix: Saving an unpublished snippet results in HTTP 500
  bundles/AdminBundle/Controller/Admin/Document/NewsletterController.php
  bundles/AdminBundle/Controller/Admin/Document/SnippetController.php
Labels: Bug

#13738 [Docs] Add a note about Notes title being added to translation
  doc/Development_Documentation/18_Tools_and_Features/05_Notes_and_Events.md
Labels: Improvement

#13727 [Task]: update Documentation links
  .github/ISSUE_TEMPLATE/Bug-Report.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pull-request-checklist.yaml
  CONTRIBUTING.md
  README.md
  bundles/AdminBundle/public/js/pimcore/helpers.js
  bundles/AdminBundle/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/public/js/pimcore/settings/targeting_toolbar.js
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/55_Number_Types.md
  doc/Development_Documentation/18_Tools_and_Features/13_Perspectives.md
  doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/README.md
  doc/Development_Documentation/21_Deployment/01_Version_Control_Systems.md
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
  doc/Development_Documentation/21_Deployment/05_Deployment_Tools.md
  doc/Development_Documentation/23_Installation_and_Upgrade/01_System_Requirements.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/05_DB_Setup.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
  doc/Development_Documentation/26_Best_Practice/70_Open_By-External_Id.md
Labels: Task

#13726 [Fix] adding validation message for wrong upload type
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/image.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js
Labels: Bug

#13748 [Documents] Fix non-reloading areabricks editable to have correct translation
  bundles/AdminBundle/Controller/Admin/Document/PageController.php
Labels: Bug

#13745 Fix translate button doesn't work in DocumentTypes & PredefinedProperties UI
  bundles/AdminBundle/Resources/public/js/pimcore/settings/docTypes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js
Labels: Bug

#13739 [Bug][11]: Xliff import strict types/ SimpleXML issue
  lib/Translation/ImportDataExtractor/Xliff12DataExtractor.php
Labels: Bug

#13747 [Bug] Fixed undefined array key issue when exporting localized objectbricks
  models/DataObject/Service.php
Labels: Bug

#13703 [BUG] Asset Upload of advancedManyToManyRelation and manyToManyRelation
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToManyRelation.js
Labels: Bug

#13714 [Data objects] Advanced relations: Render "number" meta fields with correct decimal separator
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyObjectRelation.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/advancedManyToManyRelation.js
Labels: Bug

#13697 Bug fix: handle the case where the 'containerType' of context is not set
  models/DataObject/Localizedfield/Dao.php
Labels: Bug

#13690 [Bug]: Wrongfully inheritance of object bricks
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/objectbricks.js
Labels: Bug

#13757 [Bug]: strip_tags needs empty string as default value, cannot handle null
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Controller/Admin/TagsController.php
  bundles/AdminBundle/Security/Authenticator/AdminAbstractAuthenticator.php
  bundles/AdminBundle/Security/Authenticator/AdminLoginAuthenticator.php
  bundles/AdminBundle/Security/Guard/AdminAuthenticator.php
  doc/Development_Documentation/10_E-Commerce_Framework/09_Working_with_Prices/07_Vouchers.md
Labels: Bug

#13762 Revert "Remove codeception/module-symfony (#11756)"
  composer.json
  tests/_bootstrap.php
  tests/_support/Helper/Pimcore.php
Labels: Bug

#13696 Bug fix: handle thumbnail path with comma
  models/Asset/Image/Thumbnail.php
Labels: Bug

#13663 fix sql condition being skipped when exporting objects in grid
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js
Labels: Bug

#13642 Added filter for type column in asset grid
  bundles/AdminBundle/public/js/pimcore/asset/helpers/grid.js
Labels: Improvement

#13074 [Improvement] dispatch event before admin login render
  bundles/AdminBundle/src/Controller/Admin/LoginController.php
  bundles/AdminBundle/templates/admin/login/login.html.twig
  lib/Event/AdminEvents.php
Labels: Improvement

#13741 Further type fixes
  bundles/AdminBundle/src/Controller/Admin/ElementController.php
  lib/Targeting/DataProvider/Device.php
  lib/Tool.php
  lib/Tool/Console.php
  models/DataObject/Traits/DataHeightTrait.php
  models/DataObject/Traits/DataWidthTrait.php
  models/Document/DocType.php
  models/Property/Predefined.php
  models/Tool/TmpStore.php
Labels: Task

#13777 Updated grid export prepare http method to POST
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
Labels: Bug

#13770 [Data Objects] Generate FIELD_NAME constants
  lib/DataObject/ClassBuilder/ClassBuilder.php
  lib/DataObject/ClassBuilder/FieldCollectionClassBuilder.php
  lib/DataObject/ClassBuilder/ObjectBrickClassBuilder.php
  models/DataObject/ClassDefinition/Service.php
Labels: Improvement

#13785 Fix new PhpStan errors with version 1.9.3
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectActionsTrait.php
  composer.json
  lib/Image/Adapter/Imagick.php
Labels: Task

#13786 [Task]: Fix possible errors after applying php native types
  bundles/AdminBundle/src/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/src/Controller/Admin/UserController.php
  lib/Tool/Text.php
  models/DataObject/ClassDefinition/CustomLayout.php
Labels: Task

#13763 [Bug]: Fix problem in grid configuration with invisble block
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree.js
Labels: Bug

#13787 Fix typo in the docs
  doc/Development_Documentation/18_Tools_and_Features/29_Custom_Reports.md
Labels: Bug

#13789 Some type fixes
  bundles/EcommerceFrameworkBundle/src/VoucherService/Token/Listing.php
  bundles/EcommerceFrameworkBundle/src/VoucherService/TokenManager/Pattern.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/ClassDefinition/Data/User.php
  models/DataObject/Data/AbstractQuantityValue.php
  models/DataObject/Data/Video.php
  models/DataObject/QuantityValue/Unit.php
Labels: Task

#13778 Avoid unecessary cast to string in Translator::trans()
  lib/Translation/Translator.php
Labels: Bug

#13752 Do not pupulate users in pimcore:build:classes
  models/DataObject/ClassDefinition/Data/User.php
  tests/Unit/Models/DataObject/ClassDefinition/Data/UserTest.php
Labels: Bug

#13797 [Task]: Fixing tests and remove Elasticsearch 7 support
  bundles/EcommerceFrameworkBundle/config/index_service_configs_workers.yaml
  bundles/EcommerceFrameworkBundle/src/DependencyInjection/IndexService/DefaultWorkerConfigMapper.php
  bundles/EcommerceFrameworkBundle/src/FilterService/FilterType/ElasticSearch/Select.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Config/ElasticSearch.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Config/ElasticSearchConfigInterface.php
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/DefaultFindologic.php
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/DefaultMysql.php
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/ElasticSearch/DefaultElasticSearch7.php
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/ElasticSearch/DefaultElasticSearch8.php
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/ProductListInterface.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Worker/ElasticSearch/AbstractElasticSearch.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Worker/ElasticSearch/DefaultElasticSearch7.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Worker/ElasticSearch/DefaultElasticSearch8.php
  bundles/EcommerceFrameworkBundle/src/Tracking/AbstractProductData.php
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/01_Configuration_Details.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/02_Synonyms.md
  doc/Development_Documentation/10_E-Commerce_Framework/05_Index_Service/01_Product_Index_Configuration/07_Elastic_Search/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Console/Traits/ParallelizationBase.php
  lib/Image/Adapter/Imagick.php
  phpstan-baseline.neon
  tests/Support/Helper/Pimcore.php
Labels: Task, BC-BREAK

#13803 Further type fixes
  models/DataObject/ClassDefinition/Data/Block.php
Labels: Task

#13805 Typo
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/65_Others.md
Labels: Bug

#13766 Bump symfony/contracts to 3.2 & knplabs/knp-paginator-bundle to 6.0.0
  bundles/CoreBundle/config/services.yaml
  composer.json
  lib/Kernel.php
Labels: Task

#13810 Fix: User type
  lib/Event/Admin/Login/LoginFailedEvent.php
Labels: Bug

#13623 make custom reports scrollable when needed
  bundles/AdminBundle/Resources/public/js/pimcore/helpers/generic-grid.js
Labels: Bug

#13735 [Bug]: After moving data object the query tables are still filled with inherited data from source location
  models/DataObject/Concrete.php
Labels: Bug

#13816 [Task] Fix db column quoting
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/DefaultMysql.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
Labels: Task

#13828 [PHP] Prevent deprecated error "Passing null to parameter #1 ($string) of type string is deprecated
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/Select.php
Labels: Bug

#13615 [Improvement]: Let user select an uneditable field in grid view
  bundles/AdminBundle/public/js/pimcore/element/helpers/gridCellEditor.js
Labels: Improvement

#13834 Fix: Do not cast resources to string
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Video/ImageThumbnail.php
Labels: Bug

#13821 [Task]: Fix possible errors after applying php native types
  lib/Workflow/SupportStrategy/ExpressionSupportStrategy.php
Labels: Task

#13838 Do not cast resources to string - further changes
  lib/Document/Adapter/Ghostscript.php
  models/User.php
Labels: Bug

#13846 [Task] Substitute `method exists` with interface check in field definitions
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ClassSavedInterface.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  phpstan-baseline.neon
Labels: Task

#13794 fix: twig sandbox error for "default" filter
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
Labels: Bug

#13852 [Translations] Cleaned up abandoned files
  bundles/CoreBundle/Resources/translations/pt-br.json
  bundles/CoreBundle/Resources/translations/pt_BR.json
  bundles/CoreBundle/Resources/translations/sv-fi.json
  bundles/CoreBundle/Resources/translations/sv_FI.json
  bundles/CoreBundle/Resources/translations/zh-CN.json
  bundles/CoreBundle/Resources/translations/zh_Hans.json
Labels: Bug

#13792 replace lrm characters with - for getValidKey
  models/Element/Service.php
Labels: Bug

#13519 [Web2Print] Render twig templates in a sandbox
  doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Web2Print/Processor.php
Labels: Bug

#13855 [Bug]: Multiple naming in Grid Options
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridConfigDialog.js
Labels: Bug

#13729 Fix xliff import
  lib/Translation/ImporterService/Importer/DocumentImporter.php
Labels: Bug

#13825 Logout from custom firewall always deletes complete session
  bundles/AdminBundle/config/security_services.yaml
  bundles/AdminBundle/src/Security/Event/LogoutListener.php
Labels: Bug

#13857 [Task] Enabled $param parameter for classSaved method in `classSavedInterface`
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/ClassSavedInterface.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/Traits/ClassSavedTrait.php
  phpstan-baseline.neon
Labels: Task

#13854 Fix `property_exists(): Passing null to parameter #2 ($property) of type string is deprecated`
  models/DataObject/Traits/ObjectVarTrait.php
Labels: Bug

#13806 HeadlessChrome: modify config via event listener
  lib/Event/DocumentEvents.php
  lib/Web2Print/Processor/HeadlessChrome.php
Labels: Bug

#13779 [Translations]: Fix WYSIWYG translation not editable
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
Labels: Bug

#13866 Fix adding existing translation results in error in Pimcore admin
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
Labels: Bug

#13672 Fix max height of grouped brick menu
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js
Labels: Bug

#13872 [Bug]: TestDataHelper doesn´t respect localizedFields in assertIsEqua…
  tests/_support/Helper/DataType/TestDataHelper.php
Labels: Bug

#13853 [Bug] Fixed string comparison issue to detect changed while saving localized fields
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/Traits/SimpleComparisonTrait.php
  tests/_support/Test/DataType/AbstractDataTypeTestCase.php
Labels: Bug

#13870 PhpStan: Remove ignored error pattern from baseline file
  lib/Tool/Text/Csv.php
  phpstan-baseline.neon
Labels: Task

#13892 [Tests] docker compose should use debug image as stated in the docs
  tests/bin/docker-compose.yml
Labels: Bug

#13879 [Bug][Pimcore 11] [Assets] Grid metadata batch edit all does not work
  bundles/AdminBundle/src/Helper/GridHelperService.php
Labels: Bug

#13884 Fix: Definition::isWritable(): Return value must be of type bool, string returned
  models/DataObject/ClassDefinition.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
Labels: Bug

#13882 Unit::setBaseunit() must allow string and null
  models/DataObject/QuantityValue/Unit.php
Labels: Bug

#13845 Translation::getByKeyLocalized(): Remove unnecessary func_get_args()
  models/Translation.php
Labels: Bug

#13836 [Improvement]: \Pimcore\Bundle\AdminBundle\GDPR\DataProvider\SentMail…
  bundles/AdminBundle/src/GDPR/DataProvider/SentMail.php
Labels: Improvement

#13907 Fix fclose(): supplied resource is not a valid stream resource
  models/Asset/Video/Thumbnail/Processor.php
Labels: Bug

#13850 User::roles should be an array of integers
  bundles/AdminBundle/src/Controller/Admin/Asset/AssetHelperController.php
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/src/Controller/Admin/UserController.php
  models/User.php
Labels: Bug

#13744 Simplify DirtyIndicatorTrait
  models/Element/Traits/DirtyIndicatorTrait.php
Labels: Improvement

#13837 Fix preGetData missing language param for Data\Wysiwyg
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
Labels: Bug

#13847 Site: getBy* methods shouldn't return string
  models/Site.php
Labels: Bug

#13885 Use Required attributes instead of annotations
  bundles/CoreBundle/src/Command/ClassesRebuildCommand.php
  bundles/CoreBundle/src/EventListener/Traits/PimcoreContextAwareTrait.php
  bundles/CoreBundle/src/EventListener/Traits/ResponseInjectionTrait.php
  bundles/CoreBundle/src/EventListener/Traits/StaticPageContextAwareTrait.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Config/AbstractConfig.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Config/ElasticSearch.php
  bundles/EcommerceFrameworkBundle/src/Tracking/Tracker/Analytics/AbstractAnalyticsTracker.php
  lib/DataObject/GridColumnConfig/Operator/WorkflowState.php
  lib/Document/Renderer/DocumentRenderer.php
  lib/Extension/Bundle/Installer/SettingsStoreAwareInstaller.php
Labels: Task

#13822 [Improvement]: Make getVersionDependentDatabaseColumnName case insensitive
  models/DataObject/Service.php
Labels: Improvement

#13877 Type fixes
  bundles/AdminBundle/src/Controller/Admin/Asset/AssetHelperController.php
  models/Asset/Document.php
Labels: Task

#13896 Improve version checks with Version::MAJOR_VERSION constant
  lib/Version.php
  models/DataObject/Service.php
Labels: Task

#13880 [Routing] Do not invoke dynamic routing for non-default context requests
  lib/Routing/DynamicRouteProvider.php
Labels: Bug

#13848 User::twoFactorAuthentication attribute should be null by default
  models/User.php
Labels: Bug

#13924 [Pimcore 11] Improve version checks & Service::getVersionDependentDatabaseColumnName
  lib/Version.php
  models/DataObject/Service.php
Labels: Task

#13886 [Task]: Deprecated BC layer for `getO_` and `setO_` methods in dataobjects
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/AbstractObject.php
Labels: Task

#13844 [Tags] Enhance tag UI
  bundles/AdminBundle/public/js/pimcore/element/selector/abstract.js
  bundles/AdminBundle/public/js/pimcore/element/tag/assignment.js
  bundles/AdminBundle/public/js/pimcore/element/tag/tree.js
Labels: Improvement

#13928 Doc fixes
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/03_HeadScript.md
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/04_HeadStyle.md
  doc/Development_Documentation/02_MVC/02_Template/02_Template_Extensions/06_InlineScript.md
  doc/Development_Documentation/02_MVC/02_Template/04_Thumbnails.md
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/04_Redirects.md
  doc/Development_Documentation/03_Documents/01_Editables/18_Link.md
  doc/Development_Documentation/04_Assets/01_Working_with_PHP_API.md
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/README.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/65_Others.md
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/README.md
  doc/Development_Documentation/07_Workflow_Management/04_Permissions.md
  doc/Development_Documentation/07_Workflow_Management/README.md
  doc/Development_Documentation/18_Tools_and_Features/35_GDPR_Data_Extractor.md
  doc/Development_Documentation/18_Tools_and_Features/37_Targeting_and_Personalization/README.md
  doc/Development_Documentation/19_Development_Tools_and_Details/07_Logging.md
  doc/Development_Documentation/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  doc/Development_Documentation/20_Extending_Pimcore/README.md
  doc/Development_Documentation/26_Best_Practice/68_Object_Data_Inheritance.md
  doc/User_Documentation/05_DataObjects/01_Grid_Configuration_General.md
Labels: Bug

#13833 [Improvement]: Prompt a confirmation message when doing a batch modification
  bundles/AdminBundle/public/js/pimcore/element/helpers/gridColumnConfig.js
  bundles/CoreBundle/translations/en.json
Labels: Improvement

#13929 minor doc fixes
  doc/Development_Documentation/03_Documents/01_Editables/02_Areablock/02_Bricks.md
Labels: Task

#13931 minor doc fixes
  doc/Development_Documentation/18_Tools_and_Features/README.md
Labels: Task
