Repository pimcore/pimcore, pull requests merged in 2023-09, with the labels that each got.

#15430 [Improvement]: Remove default quality for AVIF format
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
Labels: Improvement, Priority

#15884 Fix: User password reset does not work with user id
  bundles/CoreBundle/src/Command/ResetPasswordCommand.php
Labels: Bug

#15882 Rename wrong migration name Version22020614115124
  bundles/CoreBundle/src/Migrations/Version20220614115124.php
  lib/Migrations/DirectoryAwareVersionComparator.php
Labels: Bug

#14357 Implement class definition interface
  bundles/CoreBundle/src/Command/ClassesRebuildCommand.php
  bundles/CoreBundle/src/Command/Definition/Import/AbstractStructureImportCommand.php
  bundles/CoreBundle/src/Command/Definition/Import/ClassCommand.php
  bundles/CoreBundle/src/Command/Definition/Import/CustomLayoutCommand.php
  bundles/CoreBundle/src/Command/Definition/Import/FieldCollectionCommand.php
  bundles/CoreBundle/src/Command/Definition/Import/ObjectBrickCommand.php
  bundles/CoreBundle/src/Migrations/Version20211018104331.php
  bundles/UuidBundle/src/EventListener/UUIDListener.php
  bundles/UuidBundle/src/Model/Tool/UUID.php
  lib/DataObject/ClassBuilder/ClassBuilder.php
  lib/DataObject/ClassBuilder/ClassBuilderInterface.php
  lib/DataObject/ClassBuilder/FieldDefinitionBuilder.php
  lib/DataObject/ClassBuilder/FieldDefinitionBuilderInterface.php
  lib/DataObject/ClassBuilder/FieldDefinitionPropertiesBuilder.php
  lib/DataObject/ClassBuilder/FieldDefinitionPropertiesBuilderInterface.php
  lib/DataObject/ClassBuilder/ListingClassBuilder.php
  lib/DataObject/ClassBuilder/ListingClassBuilderInterface.php
  lib/DataObject/ClassBuilder/ListingClassFieldDefinitionBuilder.php
  lib/DataObject/ClassBuilder/ListingClassFieldDefinitionBuilderInterface.php
  lib/DataObject/ClassBuilder/ObjectBrickContainerClassBuilder.php
  lib/DataObject/ClassBuilder/ObjectBrickContainerClassBuilderInterface.php
  lib/DataObject/ClassBuilder/PHPClassDumper.php
  lib/DataObject/ClassBuilder/PHPClassDumperInterface.php
  lib/Event/Model/DataObject/ClassDefinitionEvent.php
  lib/Model/DataObject/ClassDefinition/ClassDefinitionManager.php
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/ClassSavedInterface.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/ClassDefinition/Helper/Dao.php
  models/DataObject/ClassDefinition/Helper/VarExportInterface.php
  models/DataObject/ClassDefinition/Listing.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Classificationstore.php
  models/DataObject/Concrete.php
  models/DataObject/Data/AbstractMetadata/Dao.php
  models/DataObject/Data/ObjectMetadata/Dao.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Fieldcollection/Definition/Dao.php
  models/DataObject/Listing/Concrete.php
  models/DataObject/Localizedfield.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Definition.php
  models/DataObject/Objectbrick/Definition/Dao.php
  models/DataObject/Service.php
  models/DataObject/Traits/ClassSavedTrait.php
  tests/Support/Helper/ClassManager.php
  tests/Support/Helper/Model.php
Labels: Improvement, Priority

#15899 Fix: Use the `getFieldType()` method instead of the fieldtype attribute
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/ClassDefinition/Data/Select.php
Labels: Bug

#15770 Deprecate Data::$fieldtype
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data.php
Labels: Bug

#15706 Documentation: Fixed example on how to implement PimcoreBundleInterface
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/README.md
Labels: Bug

#15903 [DataObject] Class Definition Interface - revert breaking changes
  bundles/CoreBundle/src/Command/Definition/Import/ClassCommand.php
  lib/DataObject/ClassBuilder/ClassBuilder.php
  lib/DataObject/ClassBuilder/ClassBuilderInterface.php
  lib/DataObject/ClassBuilder/FieldDefinitionBuilder.php
  lib/DataObject/ClassBuilder/FieldDefinitionBuilderInterface.php
  lib/DataObject/ClassBuilder/FieldDefinitionPropertiesBuilder.php
  lib/DataObject/ClassBuilder/FieldDefinitionPropertiesBuilderInterface.php
  lib/DataObject/ClassBuilder/ListingClassBuilder.php
  lib/DataObject/ClassBuilder/ListingClassBuilderInterface.php
  lib/DataObject/ClassBuilder/ListingClassFieldDefinitionBuilder.php
  lib/DataObject/ClassBuilder/ListingClassFieldDefinitionBuilderInterface.php
  lib/DataObject/ClassBuilder/ObjectBrickContainerClassBuilder.php
  lib/DataObject/ClassBuilder/ObjectBrickContainerClassBuilderInterface.php
  lib/DataObject/ClassBuilder/PHPClassDumper.php
  lib/DataObject/ClassBuilder/PHPClassDumperInterface.php
  lib/Event/Model/DataObject/ClassDefinitionEvent.php
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/DataObject/ClassDefinition/Data/ClassSavedInterface.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
  models/DataObject/ClassDefinition/Data/Table.php
  models/DataObject/ClassDefinition/Helper/Dao.php
  models/DataObject/ClassDefinition/Listing.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Classificationstore.php
  models/DataObject/Concrete.php
  models/DataObject/Data/AbstractMetadata/Dao.php
  models/DataObject/Data/ObjectMetadata/Dao.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Fieldcollection/Definition/Dao.php
  models/DataObject/Listing/Concrete.php
  models/DataObject/Localizedfield.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Definition.php
  models/DataObject/Objectbrick/Definition/Dao.php
  models/DataObject/Service.php
  models/DataObject/Traits/ClassSavedTrait.php
Labels: Task

#15905 [Docs] Workflow Support strategy - remove reference to deprecated class
  doc/07_Workflow_Management/03_Support_Strategies.md
Labels: Task

#15907 [DOC] Fix links to admin bundle
  doc/18_Tools_and_Features/35_GDPR_Data_Extractor.md
  doc/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/07_Adding_Asset_Types.md
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/11_Adding_Object_Datatypes.md
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/12_Adding_Object_ Layout_types.md
  doc/20_Extending_Pimcore/25_Implement_Your_Own_Search.md
Labels: Task

#15909 [Docs] Add upgrade notes about removal of executeMigrationsUp
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15048 [XLIFF] Process field collection blocks
  bundles/XliffBundle/src/AttributeSet/Attribute.php
  bundles/XliffBundle/src/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
  bundles/XliffBundle/src/ImporterService/Importer/DataObjectImporter.php
Labels: Improvement

#15919 [Task]: Remove deprecated force param from Clean Data Storage.md
  doc/22_Administration_of_Pimcore/02_Cleanup_Data_Storage.md
Labels: Task

#15917 [AdminStyle] Allow element text modification on tree
  doc/18_Tools_and_Features/02_Custom_Icons.md
  models/Element/AdminStyle.php
Labels: Improvement

#15922 Fix Return type regression
  models/Asset.php
Labels: Bug

#15868 [Bug]: Fix localizedField in Blocks not having the object
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/Objectbrick.php
Labels: Bug

#15921 [Docs] Pimcore 11 - Add upgrade notes for TinyMCE
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15462 Respect sort order in getSiblings() like in getChildren()
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/AbstractObject.php
Labels: Improvement

#15850 Fix: Version error when using a Calculated Value in Objects Bricks
  models/DataObject/Objectbrick/Data/AbstractData.php
Labels: Bug

#15915 Allow userOwner to be null in search-backend-reindex command
  bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data.php
Labels: Bug

#15870 Editable Image: Thumbnail config should be allow array
  doc/03_Documents/01_Editables/14_Image.md
  models/Document/Editable/Image.php
Labels: Bug

#15830 Fallback to url if text is disabled
  models/Document/Editable/Link.php
Labels: Bug

#15941 [Documents] Prevent error/deprecation due to passing null to Asset::getById in video editable
  models/Document/Editable/Video.php
Labels: Bug

#15925 Fix error Search\Backend\Data:: must not be accessed before initializ…
  bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data.php
Labels: Bug

#15930 POEditor translations import
  bundles/ApplicationLoggerBundle/translations/admin.pt_br.yaml
  bundles/CustomReportsBundle/translations/admin.de.yaml
  bundles/CustomReportsBundle/translations/admin.hu.yaml
  bundles/CustomReportsBundle/translations/admin_ext.pt_br.yaml
  bundles/GlossaryBundle/translations/admin.pt_br.yaml
  bundles/SeoBundle/translations/admin.pt_br.yaml
  bundles/SimpleBackendSearchBundle/translations/admin.pt_br.yaml
  bundles/StaticRoutesBundle/translations/admin.pt_br.yaml
  bundles/WordExportBundle/translations/admin.pt_br.yaml
  bundles/XliffBundle/translations/admin.pt_br.yaml
Labels: Task

#15940 [TinyMCE]: Align the order of pimcore element html attributes to match regex
  bundles/TinymceBundle/public/js/editor.js
Labels: Bug

#15879 [Doc] Update 95_Working_With_Runtime_Cache.md to use RuntimeCache clear
  doc/26_Best_Practice/95_Working_With_Runtime_Cache.md
Labels: Task

#15956 Fixed saving localized advanced many to many relation
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
Labels: Bug

#15957 Define Commands with #[AsCommand] attribute
  bundles/CoreBundle/src/Command/Asset/GenerateChecksumCommand.php
  bundles/CoreBundle/src/Command/Asset/RemoveCustomSettingCommand.php
  bundles/CoreBundle/src/Command/CacheClearCommand.php
  bundles/CoreBundle/src/Command/CacheWarmingCommand.php
  bundles/CoreBundle/src/Command/ClassesDefinitionsBuildCommand.php
  bundles/CoreBundle/src/Command/ClassesRebuildCommand.php
  bundles/CoreBundle/src/Command/DeleteClassificationStoreCommand.php
  bundles/CoreBundle/src/Command/DeleteUnusedLocaleDataCommand.php
  bundles/CoreBundle/src/Command/Document/CleanupCommand.php
  bundles/CoreBundle/src/Command/Document/GeneratePagePreviews.php
  bundles/CoreBundle/src/Command/Document/MigrateElementsCommand.php
  bundles/CoreBundle/src/Command/EmailLogsCleanupCommand.php
  bundles/CoreBundle/src/Command/GenerateStaticPagesCommand.php
  bundles/CoreBundle/src/Command/InternalMigrationHelpersCommand.php
  bundles/CoreBundle/src/Command/InternalModelDaoMappingGeneratorCommand.php
  bundles/CoreBundle/src/Command/InternalUnicodeCldrLanguageTerritoryGeneratorCommand.php
  bundles/CoreBundle/src/Command/LowQualityImagePreviewCommand.php
  bundles/CoreBundle/src/Command/MaintenanceCommand.php
  bundles/CoreBundle/src/Command/MaintenanceModeCommand.php
  bundles/CoreBundle/src/Command/Migrate/StorageCommand.php
  bundles/CoreBundle/src/Command/Migrate/ThumbnailsFolderStructureCommand.php
  bundles/CoreBundle/src/Command/MysqlToolsCommand.php
  bundles/CoreBundle/src/Command/OptimizeImageThumbnailsCommand.php
  bundles/CoreBundle/src/Command/RecyclebinCleanupCommand.php
  bundles/CoreBundle/src/Command/RequirementsCheckCommand.php
  bundles/CoreBundle/src/Command/ResetPasswordCommand.php
  bundles/CoreBundle/src/Command/RunScriptCommand.php
  bundles/CoreBundle/src/Command/ThumbnailsClearCommand.php
  bundles/CoreBundle/src/Command/ThumbnailsImageCommand.php
  bundles/CoreBundle/src/Command/ThumbnailsVideoCommand.php
  bundles/CoreBundle/src/Command/WorkflowDumpCommand.php
  bundles/InstallBundle/src/Command/InstallCommand.php
  bundles/SimpleBackendSearchBundle/src/Command/SearchBackendReindexCommand.php
  doc/05_Objects/05_External_System_Interaction.md
  doc/19_Development_Tools_and_Details/11_Console_CLI.md
Labels: Improvement

#15942 [Improvement]: Make Password Recovery Token to be one time use only
  bundles/CoreBundle/src/Migrations/Version20230913173812.php
  bundles/InstallBundle/dump/install.sql
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Tool/Authentication.php
  models/User.php
  models/User/AbstractUser/Dao.php
Labels: Improvement

#15948 CoreCacheHandler: Don't set key as tag
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Cache/Core/CoreCacheHandler.php
Labels: Improvement, Task

#15796 Fix Symfony deprecations
  .github/ci/files/config/packages/security.yaml
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/DependencyInjection/Compiler/WorkflowPass.php
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Controller/ArgumentValueResolver/DocumentValueResolver.php
  lib/Controller/ArgumentValueResolver/EditmodeValueResolver.php
  lib/Controller/ArgumentValueResolver/WebsiteConfigValueResolver.php
  lib/Serializer/Normalizer/ReferenceLoopNormalizer.php
Labels: Task

#15966 Update the maria db versions for codeception tests
  .github/workflows/codeception.yaml
Labels: Task

#15841 Replace deprecated strftime() function
  bundles/ApplicationLoggerBundle/src/FileObject.php
Labels: Task

#15891 [Docs]: Add recycle bin clean-up command in Cleanup_Data_Storage.md
  doc/22_Administration_of_Pimcore/02_Cleanup_Data_Storage.md
Labels: Task

#15963 Fix allowed brick types are out-of-date for versions
  models/DataObject/Objectbrick.php
Labels: Bug

#15954 Implement Maintenance Mode Helper
  bundles/CoreBundle/config/extensions.yaml
  bundles/CoreBundle/src/Command/MaintenanceModeCommand.php
  bundles/CoreBundle/src/EventListener/MaintenancePageListener.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Bootstrap.php
  lib/Console/Application.php
  lib/Tool/Admin.php
  lib/Tool/MaintenanceModeHelper.php
  lib/Tool/MaintenanceModeHelperInterface.php
Labels: Improvement

#15985 Update documentation for OBJECT_GET_PRE_SEND_DATA
  doc/26_Best_Practice/60_Modifying_Permissions_based_on_Object_Data.md
Labels: Task

#15959 [Improvement] Add Enable\Disable methods for RuntimeCache
  doc/05_Objects/05_External_System_Interaction.md
  lib/Cache/RuntimeCache.php
Labels: Improvement

#15949 [DataObject] Link - Do not mark non-nullable properties as null
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Data/Link.php
Labels: Bug

#14671 Add filter for path column in the dependencies view
  models/Dependency.php
  models/Dependency/Dao.php
  models/Element/Service.php
Labels: Improvement

#15991 Trigger deprecation for maintenance mode schedule on login
  lib/Tool/Admin.php
Labels: Task

#15297 [Sitemap generation] Add option handleCurrentSite
  bundles/SeoBundle/src/Sitemap/Document/DocumentTreeGenerator.php
  doc/18_Tools_and_Features/39_Sitemaps.md
Labels: Improvement

#15869 Deprecate legacy method Image::getThumbnailConfig()
  models/Asset/Image.php
  models/DataObject/Data/Hotspotimage.php
  models/Document/Editable/Image.php
Labels: Improvement

#15992 Improve: add types for filter in the dependencies
  models/Dependency.php
  models/Dependency/Dao.php
  models/Element/Service.php
Labels: Task

#16000 [Bug]: WYSIWYG "Editor Configuration" field ignored
  bundles/TinymceBundle/public/js/editor.js
Labels: Bug

#15960 [Bug]: Fix sanitized text being encoded before persisting to db
  .github/ci/files/config/packages/html_sanitizer.yaml
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/Document/Editable/Wysiwyg.php
  models/Translation/Dao.php
  tests/Model/DataObject/ObjectTest.php
  tests/Unit/Translation/TranslatorTest.php
Labels: Bug

#15798 feat: support using editables in dialog box
  doc/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  models/Document/Editable.php
  models/Document/Editable/Area.php
  models/Document/Editable/Areablock.php
Labels: Improvement

#15861 [Properties] Set cpath when using AbstractElement::setProperty()
  models/DataObject/AbstractObject/Dao.php
  models/Element/AbstractElement.php
  models/Property/Dao.php
Labels: Bug

#15572 Fix: Passing an array for the first argument to QueryBuilder::select() is deprecated
  bundles/ApplicationLoggerBundle/src/Controller/LogController.php
  doc/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  models/Asset/Listing/Dao.php
  models/Document/Listing/Dao.php
  models/Element/Service.php
  models/Element/Tag/Dao.php
  models/Translation/Listing/Dao.php
  models/Version/Dao.php
Labels: Task

#15722 Install required bundles if '--install-bundles' list is empty
  bundles/InstallBundle/src/Command/InstallCommand.php
  doc/01_Getting_Started/02_Advanced_Installation_Topics/README.md
Labels: Improvement

#16013 Reverts #15960 partially to fix anchor tag closing regression
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/Document/Editable/Wysiwyg.php
  models/Translation/Dao.php
  tests/Model/DataObject/ObjectTest.php
  tests/Unit/Translation/TranslatorTest.php
Labels: Bug

#15908 Fix: Can't send email documents in maintenance tasks
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/EventListener/Frontend/GlobalTemplateVariablesListener.php
  lib/Twig/Extension/DocumentEditableExtension.php
Labels: Bug

#16010 [Properties] Update properties only with dirty state
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
  models/Asset/Dao.php
  models/DataObject/AbstractObject.php
  models/DataObject/AbstractObject/Dao.php
  models/Document.php
  models/Document/Dao.php
  models/Element/AbstractElement.php
Labels: Improvement

#16002 Deprecate CsvFormulaFormatter
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Helper/CsvFormulaFormatter.php
  models/Element/Service.php
  models/Translation.php
  tests/Unit/Helper/CsvFormulaTest.php
Labels: Task

#14136 #13401: Add Import/Export Quantity value unit definitions support
  bundles/CoreBundle/config/services.yaml
  bundles/CoreBundle/src/Command/Definition/Import/QuantityValueCommand.php
  models/DataObject/QuantityValue/Service.php
Labels: New Feature

#16016 [Assets] Documents - Add possibility to disable background processing: thumbnails, counting pages, text extraction
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/SimpleBackendSearchBundle/src/Command/SearchBackendReindexCommand.php
  doc/04_Assets/03_Working_with_Thumbnails/05_Document_Thumbnails.md
  doc/04_Assets/README.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
  models/Asset/Document.php
Labels: Improvement

#16026 [Bug]: Remove o_ prefix for the filter of the dependencies
  models/Dependency/Dao.php
Labels: Bug

#16023 [Assets] Calculate Spherical MetaData in AssetUpdateTasksHandler
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
  models/Asset/Video.php
Labels: Improvement
