Repository pimcore/pimcore, pull requests merged in 2023-05, with the labels that each got.

#15012 force process timeout to type integer in Composer Class
  lib/Composer.php
Labels: Bug

#15067 Fix the tag name
  lib/Twig/Extension/Templating/HeadScript.php
Labels: Bug

#15087 [Task]: Psalm action to use latest version
  .github/workflows/psalm.yml
Labels: Task

#15083 [Task] Update doc with migration hint
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15079 [Task]: Deprecated `Import from URL`
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15084 [Security] Improved sanatizing of `pimcore_log` parameter
  lib/Pimcore.php
Labels: Security

#15093 Add upgrade notes
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15077 [Bug] Check if marketing menu is available
  bundles/CustomReportsBundle/public/js/startup.js
Labels: Bug

#15080 [Task]: Fix docs about removal of import from server and url
  doc/05_Objects/01_Object_Classes/05_Class_Settings/20_Custom_Views.md
  doc/18_Tools_and_Features/13_Perspectives.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15095 [Task] Improved application logger panel
  bundles/ApplicationLoggerBundle/public/js/log/admin.js
  bundles/ApplicationLoggerBundle/public/js/log/detailwindow.js
Labels: Task

#15094 [Bug]: Upload folder not working
  models/Asset.php
Labels: Bug

#15097 Move css files of Word Export Bundle
  bundles/WordExportBundle/public/css/word-export.css
  bundles/WordExportBundle/src/Controller/TranslationController.php
Labels: Bug

#15098 Check $data is not null
  models/DataObject/ClassDefinition/Data/Textarea.php
Labels: Improvement

#15109 [Bug] Fix Redirect CSV Import with null values
  bundles/SeoBundle/src/Model/Redirect.php
Labels: Bug

#15119 Make `EncoreHelper` non-internal
  lib/Helper/EncoreHelper.php
Labels: Improvement

#15117 [Bug]: Make `Alt` not nullable in `Document\Editable\Image`
  models/Document/Editable/Image.php
Labels: Bug

#15082 Fix type errors
  bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data/Dao.php
  models/Asset.php
  models/Asset/MetaData/ClassDefinition/Data/Asset.php
  models/Asset/MetaData/ClassDefinition/Data/DataObject.php
  models/Asset/MetaData/ClassDefinition/Data/Document.php
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Dao.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/Classificationstore/KeyConfig/Dao.php
  models/DataObject/Classificationstore/KeyConfig/Listing/Dao.php
  models/DataObject/Classificationstore/KeyGroupRelation/Dao.php
  models/DataObject/Classificationstore/KeyGroupRelation/Listing/Dao.php
  models/DataObject/Concrete/Dao.php
  models/Document/Dao.php
  models/Document/Email/Dao.php
  models/Document/Hardlink/Dao.php
  models/Document/Link/Dao.php
  models/Document/Page/Dao.php
  models/Document/Snippet/Dao.php
  models/Element/Note/Dao.php
  models/Tool/TmpStore/Dao.php
  models/User/AbstractUser/Dao.php
  models/User/UserRole/Dao.php
  models/Version/Dao.php
  tests/Unit/Models/DataObject/ClassDefinition/Data/UserTest.php
Labels: Task

#15131 [Task]: Remove Button control for DataObjects
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Layout/Button.php
Labels: Task

#15141 [Bug][Pimcore 10.6] Config Location for Datahub should not be configured in pimcore config tree
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
Labels: Bug

#15139 [Task] Add migration for data object definitions
  bundles/CoreBundle/Migrations/Version20230508121105.php
Labels: Task

#15143 [Bug][Pimcore 10.6] Pimcore\Bundle\CoreBundle\DependencyInjection\ConfigurationHelper should not be internal
  bundles/CoreBundle/DependencyInjection/ConfigurationHelper.php
Labels: Bug

#15135 Do not use deprecated `Symfony\Component\HttpFoundation\RequestMatcher`
  bundles/CoreBundle/src/EventListener/WebDebugToolbarListener.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Http/Context/PimcoreContextGuesser.php
  lib/Http/RequestMatcherFactory.php
Labels: Improvement

#15136 [Bug] Make setAction accept null values
  models/Schedule/Task.php
Labels: Bug

#15138 Get rid of `Reflection(Method|Property)::setAccessible()`
  models/Element/DeepCopy/PimcoreClassDefinitionReplaceFilter.php
  models/Element/Service.php
  tests/Cache/Core/AbstractCoreHandlerTest.php
  tests/Model/DataObject/DefinitionModifierTest.php
  tests/Support/Util/TestHelper.php
  tests/Unit/HttpKernel/Response/CodeInjectorTest.php
Labels: Improvement

#15132 [Task]: Deprecate Button control for DataObjects
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/button.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Layout/Button.php
Labels: Task

#13974 [Data objects] Relations get truncated when using multiple object bricks
  bundles/CoreBundle/Migrations/Version20230320131322.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Traits/ContextPersistenceTrait.php
Labels: Bug

#15021 fix AreabrickPass to work on Windows
  bundles/CoreBundle/DependencyInjection/Compiler/AreabrickPass.php
Labels: Bug

#15069 Filtering paginated website setting bugfix
  bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js
Labels: Bug

#15102 [Docs] Groups upgrade notes by tag
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#15105 SecurityHelper: there could be numeric values as well, which shouldn't be casted to string
  lib/Security/SecurityHelper.php
Labels: Bug

#15126 Cache translations
  models/Translation/Listing/Dao.php
  tests/Unit/Translation/TranslatorTest.php
Labels: Improvement

#15147 [Bug] Classification Store - Call to undefined function
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
Labels: Bug

#14800 Cleanup in 03_Navigation.md: Whitespace/indentation, consistent parameter keys, …
  doc/Development_Documentation/03_Documents/03_Navigation.md
Labels: Task

#14767 Add missing `cache.end()` call in the performance docs
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/09_Performance_Guide.md
Labels: Bug

#15157 [Bug][SeoBundle] Redirect logging should log into channel redirect
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/SeoBundle/config/redirect_services.yaml
  bundles/SeoBundle/src/Redirect/RedirectHandler.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Bug

#15111 [Bug] Removed serverside html sanitizer
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Alias.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Anonymizer.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/AnyGetter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Arithmetic.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/AssetMetadataGetter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Base64.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Boolean.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/BooleanFormatter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/CaseConverter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/CharCounter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Concatenator.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/DateFormatter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/ElementCounter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/FieldCollectionGetter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/GeopointRenderer.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/HotspotimageRenderer.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/ImageRenderer.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/IsEqual.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Iterator.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/JSON.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/LFExpander.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/LocaleSwitcher.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Merge.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/ObjectFieldGetter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/PHP.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/PHPCode.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/PropertyGetter.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/RequiredBy.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/StringContains.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/StringReplace.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Substring.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Text.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/TranslateValue.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/Trimmer.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/gridcolumn/operator/WorkflowState.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js
  bundles/EcommerceFrameworkBundle/PricingManager/Rule.php
  bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/item.js
  lib/DataObject/GridColumnConfig/Operator/AbstractOperator.php
  lib/DataObject/GridColumnConfig/Operator/AnyGetter.php
  models/DataObject/QuantityValue/Unit.php
  models/Property/Predefined.php
  models/Staticroute.php
  models/WebsiteSetting.php
Labels: Bug

#15171 [Bug]: Pimcore 11 date field column type DATE can not be selected
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/DateRange.php
  models/DataObject/ClassDefinition/Data/Datetime.php
Labels: Bug

#15167 [Class Definition]: remove classSaved BC layer
  models/DataObject/ClassDefinition.php
Labels: Improvement

#15173 Fix redirects without regex are not working
  bundles/SeoBundle/src/Model/Redirect/Dao.php
Labels: Bug

#15175 [Task][Application Logger] Remove PIMCORE_LOG_FILEOBJECT_DIRECTORY
  bundles/ApplicationLoggerBundle/config/pimcore/config.yaml
  bundles/ApplicationLoggerBundle/src/Controller/LogController.php
  bundles/ApplicationLoggerBundle/src/Maintenance/LogArchiveTask.php
  bundles/CoreBundle/config/pimcore/flysystem.yaml
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Bootstrap.php
  stubs/dynamic-constants.php
Labels: Task

#15168 [Docs] Update symfony messenger queue config
  doc/01_Getting_Started/00_Installation/00_Docker_Based_Installation.md
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
Labels: Task

#15177 [Bug] Logger properties can´t be null
  bundles/SeoBundle/src/Redirect/RedirectHandler.php
Labels: Bug

#15174 [Task] Removed `sanitizeHtmlAttributes` method from link editable
  models/Document/Editable/Link.php
Labels: Task

#15154 [Bug][Pimcore 10.6] Loading not existing settings.js
  bundles/AdminBundle/Resources/public/js/pimcore/report/webadmintools/settings.js
Labels: Bug

#15176 [Bug]: Migration from 10.6 to 11.x does not work (with demo-enterprise)
  bundles/CoreBundle/src/Migrations/Version20220908113752.php
  bundles/CoreBundle/src/Migrations/Version20221003115124.php
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
Labels: Bug

#15185 Add missing type hints
  lib/Controller/Traits/JsonHelperTrait.php
  lib/Security/User/ObjectUserProvider.php
  tests/Unit/Translation/TranslatorTest.php
Labels: Improvement

#15133 [Task] Removed `pimcore_log` get parameter
  doc/19_Development_Tools_and_Details/15_Magic_Parameters.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Kernel.php
  lib/Pimcore.php
Labels: Task

#14999 Operator alias throws warning if it is null
  lib/DataObject/GridColumnConfig/Operator/Alias.php
Labels: Bug

#15160 [Task] Adding Bundle Config Event in Installer
  bundles/InstallBundle/src/BundleConfig/BundleWriter.php
  bundles/InstallBundle/src/Command/InstallCommand.php
  bundles/InstallBundle/src/Event/BundleSetupEvent.php
  bundles/InstallBundle/src/Event/InstallEvents.php
  bundles/InstallBundle/src/Installer.php
  doc/01_Getting_Started/02_Advanced_Installation_Topics.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#14789 Fix: in grid in calculatedValue replace on integer
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/calculatedValue.js
Labels: Bug

#15034 Variant Sort By Index Fix
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#14925 [Bug] Fixed `priority` filter in application logger
  bundles/AdminBundle/Controller/Admin/LogController.php
Labels: Bug

#15037 Grid Batch Edit Change To POST
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
Labels: Bug

#14936 allow special characters in group name of custom reports
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/item.js
Labels: Task

#15159 Fix objects tree sort method check
  bundles/AdminBundle/Resources/public/js/pimcore/object/tree.js
Labels: Bug

#15076 [Grid] Support batch update for localized object brick fields
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#15096 Fix default mockup get param
  bundles/EcommerceFrameworkBundle/Model/DefaultMockup.php
Labels: Bug

#15078 Bug fix: layout issue for not_editable structuredTable
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/structuredTable.js
Labels: Bug

#14948 [Bug] Fix Classification Store inheritance
  models/DataObject/Classificationstore.php
Labels: Bug

#15192 [Task]: Add notes about ignore-existing-config removal
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15198 Fix generation of thumbnails with inline thumbnail config
  models/Asset/Image/Thumbnail/Processor.php
Labels: Bug

#15191 [Documents] force inject metadata tags for static page renderer
  lib/Document/StaticPageGenerator.php
Labels: Bug

#15203 Fix cache warming command
  bundles/CoreBundle/src/Command/CacheWarmingCommand.php
Labels: Bug

#15194 [Admin][Documents] Fix (un)publishing documents from tree
  bundles/AdminBundle/Resources/public/js/pimcore/document/tree.js
Labels: Bug

#14832 fix: fixed checking variable if is array and array key exists
  bundles/EcommerceFrameworkBundle/IndexService/ProductList/ElasticSearch/AbstractElasticSearch.php
Labels: Bug

#15201 Fix loading empty data object class -
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#14634 [Image thumbnails] Return correct thumbnail dimensions when using high-res configuration
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#15195 [Bug]: JS error after saving object with field collection item
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/fieldcollections.js
Labels: Bug

#15205 [Task]: Improve non-admin update user
  bundles/AdminBundle/Controller/Admin/UserController.php
Labels: Task, Security

#15204 [Task]: Rename Report\WebAdminTools to SearchConsole
  bundles/AdminBundle/Resources/public/js/pimcore/report/googleSearchConsole/settings.js
  bundles/AdminBundle/Resources/views/Admin/Index/index.html.twig
  bundles/CoreBundle/EventListener/Frontend/GoogleSearchConsoleVerificationListener.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15200 [Flysystem] change default visibility for public storages
  bundles/CoreBundle/src/DependencyInjection/Compiler/FlysystemVisibilityPass.php
  bundles/CoreBundle/src/PimcoreCoreBundle.php
Labels: Bug

#15207 [Task][Docs]: Chromium ports do not need to be exposed
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
Labels: Task

#15208 [Task]: Check PHPDoc annotations again
  models/DataObject/ClassDefinition/Data/EncryptedField.php
Labels: Task

#15210 Type fixes for thumbnail trait
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#15209 Pimcore 11 pre-release TODOs
  .github/workflows/codeception.yaml
  .github/workflows/pull-request-checklist.yaml
  .github/workflows/static-analysis.yaml
  CONTRIBUTING.md
Labels: Task

#15213 [Bug]: make two separate error log items a single item
  bundles/WordExportBundle/src/Controller/TranslationController.php
Labels: Bug

#15219 Return Pimcore JsonResponse from AdminController::adminjson
  bundles/AdminBundle/Controller/AdminController.php
Labels: Bug

#15226 [Bug]: Permission problems with objectbricks in the enterprise demo for superuser
  bundles/CoreBundle/src/Migrations/Version20230517115427.php
  bundles/InstallBundle/src/Installer.php
Labels: Bug

#14637 [Bug] Remove unclickable area of WYSIWYG
  bundles/AdminBundle/Resources/public/css/admin.css
Labels: Bug

#15223 Fix link in upgrade guide
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
Labels: Bug

#15230 Fix Custom documents with fixed namespace
  models/Document.php
Labels: Bug

#15241 [Bug]: Links in Blocks will not be cleaned up when Target Document is deleted
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Link.php
  models/DataObject/Concrete.php
  tests/Model/DataType/LinkTest.php
Labels: Bug

#14990 [Data objects] For input fields checkValidity should check column length
  models/DataObject/ClassDefinition/Data/Input.php
  tests/Model/DataObject/ObjectTest.php
  tests/Service/Element/VersionTest.php
Labels: Improvement

#15232 fix: try to fetch metadata without checking if file exists
  models/Asset/Image/Thumbnail/Processor.php
Labels: Bug

#15235 [Bug]: Fix `The "processes" option does not exist.` when running ` pimcore:thumbnails:image` without the optional WebMozart
  lib/Console/Traits/Parallelization.php
Labels: Bug

#15240 Update trigger_deprecation in User.php
  bundles/AdminBundle/Security/User/User.php
Labels: Bug

#15270 Update priority for CoreBundle & AdminBundle to load after defaults
  lib/Kernel.php
Labels: Bug

#15145 [Task] Improved validation of url slug
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/urlSlug.js
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/65_Others.md
  lib/Routing/DynamicRouteProvider.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
Labels: Bug

#15227 fix: check is stream not local in createXlsxExportFile
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Bug

#15269 [Docs]: Add a hint in web to print about the maintenance cronjob
  doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md
Labels: Task

#15281 [Docs] Fixed typo in 09_Upgrade_Notes for Pimcore 11
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Bug

#15265 Fix set title and description for video when values are null
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/Data/Video.php
Labels: Bug

#15291 [Bug]: Config paths change after upgrade
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/Migrations/Version20230525131748.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Kernel.php
Labels: Bug

#14822 explicitly set flysystem permissions as octal
  bundles/CoreBundle/Resources/config/pimcore/flysystem.yaml
Labels: Improvement

#15272 Update Service.php to remove Windows EOL in generated classes (Pimcore 10)
  models/DataObject/ClassDefinition/Service.php
Labels: Improvement

#14391 chore: Use short list syntax everywhere
  .php-cs-fixer.dist.php
  bundles/CoreBundle/src/Command/ThumbnailsImageCommand.php
  bundles/CoreBundle/src/Command/ThumbnailsVideoCommand.php
  bundles/XliffBundle/src/ImportDataExtractor/Xliff12DataExtractor.php
  bundles/XliffBundle/src/ImporterService/Importer/DataObjectImporter.php
  lib/DataObject/FielddefinitionMarshaller/Traits/RgbaColorTrait.php
  lib/Image/Adapter/GD.php
  lib/Model/Dao/PimcoreLocationAwareConfigDao.php
  lib/Tool/Authentication.php
  lib/Tool/Text/Csv.php
  lib/Video/Adapter/Ffmpeg.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  models/DataObject/Data/RgbaColor.php
  models/Notification/Service/NotificationServiceFilterParser.php
  tests/Model/DataType/ObjectAwareFieldsTest.php
Labels: Task

#15298 [Bug]: 10.6.0 migration fails on mariadb < 10.5.2
  bundles/CoreBundle/Migrations/Version20230322114936.php
Labels: Bug

#15120 Bug fix: OptionProvider issue for Select in combination with ManyToManyObjectRelation
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
Labels: Bug

#14390 chore: Remove unnecessary casts
  bundles/SeoBundle/src/Model/Redirect.php
  lib/Navigation/Renderer/AbstractRenderer.php
  lib/Translation/Translator.php
  lib/Twig/Extension/Templating/Placeholder/ContainerService.php
  lib/Video/Adapter/Ffmpeg.php
  models/Asset/Listing.php
  models/DataObject/Data/GeoCoordinates.php
  models/Document/PageSnippet.php
  tests/Support/Helper/DataType/TestDataHelper.php
Labels: Task

#14850 Fix decimalPrecision for min and maxValue in class
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/numeric.js
Labels: Bug

#14478 chore: Remove useless proxy methods
  lib/Http/Request/Resolver/DocumentResolver.php
  lib/Http/Request/Resolver/OutputTimestampResolver.php
  models/Asset/Listing.php
  models/DataObject/Listing.php
  models/Document/Folder/Dao.php
  models/Document/Listing.php
  models/Notification/Listing.php
Labels: Task

#15277 [Docs]: Improve documentation about the installation of Gotenberg and LibreOffice
  doc/01_Getting_Started/02_Advanced_Installation_Topics.md
  doc/04_Assets/03_Working_with_Thumbnails/05_Document_Thumbnails.md
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
Labels: Task
