Repository pimcore/pimcore, pull requests merged in 2023-08, with the labels that each got.

#15577 [DataObject] Link: Attributes can be null
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Data/Link.php
Labels: Bug, BC-BREAK

#15501 Fix FD_SETSIZE too many open files bug (#15500)
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
  models/User.php
Labels: Bug

#15670 [Bug]: Invalid Custom Reports configuration on config_location symfony-config
  bundles/CustomReportsBundle/src/Tool/Config/Dao.php
Labels: Bug

#15658 Fix: create WebsiteSetting without a name and a language
  models/WebsiteSetting.php
Labels: Bug

#15668 [Sites] Do not throw exception on missing documents permission when loading sites on startup
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
Labels: Bug

#15607 Add check for classification store groups
  models/DataObject/Classificationstore.php
Labels: Bug

#15625 [Cache] Fixed Redis configuration & documentation
  bundles/CoreBundle/config/cache.yaml
  doc/19_Development_Tools_and_Details/09_Cache/README.md
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/09_Performance_Guide.md
Labels: Bug

#15664 Fix import server files dir traversal
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
Labels: Bug

#15609 [Bug]: Remove user from runtime cache on user deletion
  models/User/AbstractUser.php
Labels: Bug

#15578 [Staticroute] Fix: str_replace(): Argument #3 ($subject) must be of type array|string, int given
  bundles/StaticRoutesBundle/src/Model/Staticroute.php
Labels: Bug

#15680 ImageThumbnailTrait: Return value must be of type int, null returned
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#15679 Asset::isAnimatedPng() - Fix: substr(): Argument #3 ($length) must be…
  models/Asset/Image.php
Labels: Bug

#15406 [Feature] Add `AsAreabrick` attribute
  bundles/CoreBundle/src/DependencyInjection/Compiler/AreabrickPass.php
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  doc/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  lib/Extension/Document/Areabrick/Attribute/AsAreabrick.php
Labels: Improvement

#15186 Add missing type hints
  bundles/ApplicationLoggerBundle/src/ApplicationLogger.php
  lib/Serializer/Normalizer/ReferenceLoopNormalizer.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Classificationstore.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/Data/ImageGallery.php
  models/DataObject/Localizedfield.php
  models/DataObject/Objectbrick/Data/AbstractData.php
  models/DataObject/Objectbrick/Definition.php
  models/Document/Editable/Relations.php
Labels: Improvement

#15315 Add support for an in filter operator
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AbstractQuantityValue.php
  models/DataObject/ClassDefinition/Data/Numeric.php
Labels: Improvement

#15696 [Task]: Avoid collation change when renaming o_type
  bundles/CoreBundle/src/Migrations/Version20221003115124.php
Labels: Bug

#15695 Fix: sync configuration helper
  bundles/CoreBundle/DependencyInjection/ConfigurationHelper.php
Labels: Improvement

#15683 [Docs] add caution info box for PHP templates migration to Twig
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
Labels: Improvement, Task

#15712 [Docs] update section title
  doc/23_Installation_and_Upgrade/01_System_Requirements.md
Labels: Task

#15612 [Bug]: Fix locales-utf8 check on macOS under requirements check
  lib/Console/Application.php
  lib/Tool/Requirements.php
Labels: Bug

#15669 Cypress pimcore fix
  bundles/AdminBundle/Resources/public/js/pimcore/functions.js
Labels: Bug

#14337 Implement thumbnail interfaces
  lib/Twig/Extension/ImageThumbnailExtension.php
  models/Asset/Document.php
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Document/ImageThumbnailInterface.php
  models/Asset/Image.php
  models/Asset/Image/Thumbnail.php
  models/Asset/Image/ThumbnailInterface.php
  models/Asset/Service.php
  models/Asset/Thumbnail/ImageThumbnailInterface.php
  models/Asset/Thumbnail/ThumbnailInterface.php
  models/Asset/Thumbnail/ThumbnailMediaInterface.php
  models/Asset/Thumbnail/ThumbnailPathInterface.php
  models/Asset/Video.php
  models/Asset/Video/ImageThumbnail.php
  models/Asset/Video/ImageThumbnailInterface.php
  models/DataObject/Data/Hotspotimage.php
  models/Document/Editable/Image.php
  models/Document/Editable/Video.php
Labels: Improvement, Priority

#15653 Fix: cast document/asset/object id to int
  lib/Tool/Text.php
Labels: Bug

#15720 [Bug]: Fix text selection support on disabled field text
  bundles/AdminBundle/Resources/public/css/ext-modifications.css
Labels: Bug

#15718 fix: disable login throttling on AdminSessionAuthenticator #15671
  bundles/AdminBundle/RateLimiter/AdminRequestRateLimiter.php
  bundles/AdminBundle/Resources/config/security_services.yaml
  bundles/AdminBundle/Security/Authenticator/AdminSessionAuthenticator.php
Labels: Bug

#15732 Set correct types for Data::getDataFromGridEditor()
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/ClassDefinition/Data/Slider.php
Labels: Bug

#15689 [Bug]: Error OpenStreetMap Cors Headers
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geo/abstract.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/geopoint.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/targeting/conditions.js
Labels: Bug

#15677 Update README.md: correct type in "Event API and Event Manger"
  doc/20_Extending_Pimcore/README.md
Labels: Bug

#15702 Fix: Cannot assign null to property Areablock::$currentIndex of type array
  models/Document/Editable/Areablock.php
Labels: Bug

#15713 Allow realName to be null in Editable
  models/Document/Editable.php
Labels: Bug

#15691 Fix Logging in RedirectHandler
  bundles/SeoBundle/src/Redirect/RedirectHandler.php
Labels: Bug

#15540 Imagick adapter: Remove unused initalOptions attribute
  lib/Image/Adapter/Imagick.php
Labels: Task

#15736 Make the title and label translated in workflows
  bundles/AdminBundle/Controller/Admin/WorkflowController.php
  bundles/CoreBundle/Resources/views/Workflow/statusinfo/allPlacesStatusInfo.html.twig
  bundles/CoreBundle/Resources/views/Workflow/statusinfo/toolbarStatusInfo.html.twig
Labels: Bug

#15744 Fix Codeception and PHP Stan errors
  models/Asset/Thumbnail/ImageThumbnailInterface.php
Labels: Bug

#15724 [Bug]: Fix multisite internal link when using document preview
  doc/Development_Documentation/02_MVC/04_Routing_and_URLs/08_Working_with_Sites.md
  models/Document.php
Labels: Bug

#15726 [Bug]: Fix `pimcore:build:classes` requiring DB and Cache
  bundles/CoreBundle/Command/ClassesDefinitionsBuildCommand.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/ClassDefinition/Data/TargetGroup.php
  models/DataObject/ClassDefinition/Data/TargetGroupMultiselect.php
Labels: Bug

#15754 [Bug]: Asset Helper Controller: get-batch-jobs action - Method not allowed
  bundles/AdminBundle/Controller/Admin/Asset/AssetHelperController.php
Labels: Bug

#15752 [Security]: XSS in choose time value Classes Data Objects
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/datetime.js
  bundles/CoreBundle/Resources/translations/en.extended.json
Labels: Security

#15570 Definitions: Set correct types for Pimcore 11
  bundles/CoreBundle/Migrations/Version20230720161000.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/ClassDefinition/Data.php
  models/Document/Editable/Areablock.php
  tests/_support/Helper/AbstractDefinitionHelper.php
Labels: Bug

#15760 Fix migration warning messages
  bundles/CoreBundle/Migrations/Version20210107103923.php
  bundles/CoreBundle/Migrations/Version20210706090823.php
  bundles/CoreBundle/Migrations/Version20211117173000.php
  bundles/CoreBundle/Migrations/Version20230508121105.php
  bundles/CoreBundle/Migrations/Version20230516161000.php
  bundles/CoreBundle/Migrations/Version20230720161000.php
Labels: Bug

#15638 Fix: index attribute of Data must be a boolean
  models/DataObject/ClassDefinition/Data.php
  tests/Support/Helper/AbstractDefinitionHelper.php
  tests/Unit/Models/DataObject/ClassDefinition/Data/UserTest.php
Labels: Bug

#15757 [DataObjects] Fix classification store data loss on adding new group
  models/DataObject/ClassDefinition/Data/Classificationstore.php
Labels: Bug

#15762 QuantityValue: NumberFormatter::format(): Argument #1 ($num) must be …
  models/DataObject/Data/QuantityValue.php
Labels: Bug

#15672 Relations: Wrong return php docs
  models/DataObject/ClassDefinition/Data/Extension/Relation.php
Labels: Bug

#15763 Fix: RgbaColor::getDataForEditmode(): Argument #2 ($object) must be of type ?Concrete, Localizedfield given
  models/DataObject/ClassDefinition/Data/RgbaColor.php
Labels: Bug

#15746 15150 bug deadlock found when trying to get lock on dataobject import 1
  bundles/CoreBundle/Migrations/Version20230616085142.php
  models/DataObject/Data/ObjectMetadata/Dao.php
Labels: Bug

#15714 [Docs] Add notice for deadlock issue on doctrine messenger transport
  doc/Development_Documentation/01_Getting_Started/00_Installation.md
  doc/Development_Documentation/01_Getting_Started/08_Maintenance_Tasks.md
Labels: Task

#15774 Data: Allow null for setIndex() for BC reasons
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data.php
Labels: Bug

#15772 [Bug]: Stop foreign key check when migrating editables link
  bundles/CoreBundle/src/Migrations/Version20230424084415.php
Labels: Bug

#15771 [Version20230616085142] Recreate Foreign key checks for object_metadata_ table
  bundles/CoreBundle/Migrations/Version20230616085142.php
Labels: Bug

#15777 [Task]: Fix useless self-assignment reported by SonarCloud
  lib/Twig/Extension/Templating/Placeholder/ContainerService.php
  models/Document/PageSnippet.php
Labels: Task

#15773 Fix: Editing the Classification values in grid view throws an error
  models/DataObject/Service.php
Labels: Bug

#15496 Fix deprecation: ReferenceLoopNormalizer should implement getSupportedTypes()
  lib/Serializer/Normalizer/ReferenceLoopNormalizer.php
Labels: Task

#15785 PhpStan: Bump version and fix new error
  composer.json
  models/Asset.php
Labels: Task

#15764 Fix: class method naming in document data extractor
  bundles/XliffBundle/src/ExportDataExtractorService/DataExtractor/DocumentDataExtractor.php
Labels: Task

#15792 [CoreBundle] Fix down migrations by removing IF EXISTS, not a valid MySQL 8 statements
  bundles/CoreBundle/Migrations/Version20220119082511.php
  bundles/CoreBundle/Migrations/Version20220120121803.php
  bundles/CoreBundle/Migrations/Version20220120162621.php
Labels: Bug

#15206 [Mail]: Add a new event to modify data before persisting
  lib/Event/MailEvents.php
  lib/Mail.php
Labels: Improvement

#15431 [Config] Harmonize accessing Pimcore config settings via Config::getSystemConfiguration()
  lib/Bootstrap.php
  lib/Image/Adapter/Imagick.php
  lib/Maintenance/Tasks/LowQualityImagePreviewTask.php
  lib/Tool/Authentication.php
  models/Asset.php
  models/Asset/Image.php
  models/Asset/Image/Thumbnail/Config.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
  models/Asset/Video.php
  models/Asset/Video/Thumbnail/Config/Dao.php
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/Document/DocType/Dao.php
  models/Metadata/Predefined/Dao.php
  models/Property/Predefined/Dao.php
  models/Version/Adapter/FileSystemVersionStorageAdapter.php
Labels: Improvement

#15579 Fix deprecation in WebsiteSetting
  models/WebsiteSetting.php
Labels: Bug

#15811 Fix the issue with the '<' in the wysiwg editor
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/Document/Editable/Wysiwyg.php
Labels: Bug

#15807 Allow more elements to fit CKEditor Content
  bundles/CoreBundle/config/pimcore/default.yaml
Labels: Bug

#15804 [Bug]: Can't open Custom Report with data source
  bundles/CustomReportsBundle/public/js/pimcore/report/custom/definitions/sql.js
  bundles/CustomReportsBundle/public/js/pimcore/report/custom/item.js
  bundles/CustomReportsBundle/translations/admin.en.yaml
Labels: Bug

#15823 Make sure unserialized is array
  bundles/CoreBundle/src/Migrations/Version20230424084415.php
Labels: Bug

#15820 Fix deprecation in TestDataHelper
  tests/Support/Helper/DataType/TestDataHelper.php
  tests/Support/Test/DataType/AbstractDataTypeTestCase.php
Labels: Task

#15783 JsonHelperTrait: Use Required attribute
  lib/Controller/Traits/JsonHelperTrait.php
Labels: Task

#15640 Fix: toNumeric returns a string, when integer and decimalSize is set
  models/DataObject/ClassDefinition/Data/Numeric.php
Labels: Bug

#15836 [Task][Docs]: Improve asset document thumbs messenger queue instructions
  doc/04_Assets/03_Working_with_Thumbnails/05_Document_Thumbnails.md
Labels: Task

#15838 fix: add null coalescing check for getTranslations
  models/Translation.php
Labels: Bug

#15822 Fix issue with setting the read target to settings-store after pimcore 11 install
  lib/SystemSettingsConfig.php
Labels: Bug

#15812 [Bug]: Omit Mandatory Check on field with Default Value when creating a new DataObject
  models/DataObject/Concrete.php
  tests/Model/DataObject/ObjectTest.php
  tests/Support/Helper/Model.php
Labels: Bug

#15842 SitemapGeneratorListener: Fix deprecation
  bundles/SeoBundle/src/EventListener/SitemapGeneratorListener.php
  doc/18_Tools_and_Features/39_Sitemaps.md
Labels: Improvement

#15851 [Bug]: Fix Element/Service::getSafeCopyName for Assets
  models/Element/Service.php
Labels: Bug

#15853 Fix ObjectMetadata::save(): Argument #4 ($position) must be of type string
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
Labels: Bug

#15845 [Bug]: Fixes relation clean up not looping through the right array of values
  models/DataObject/ClassDefinition/Dao.php
Labels: Bug

#15859 [Task]: Followp WebDav Nginx upgrade notes
  doc/04_Assets/05_Accessing_Assets_via_WebDAV.md
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15860 fix hardlink child resolver
  lib/Navigation/Builder.php
  models/Document/Hardlink.php
Labels: Bug

#15872 [Task]: Make `sanitycheck` table dropping migration idempotent
  bundles/CoreBundle/src/Migrations/Version20210928135248.php
Labels: Task
