Repository pimcore/pimcore, pull requests merged in 2023-06, with the labels that each got.

#15299 [Bug]: Date::getDataForQueryResource(): Return value must be of type ?int, string returned
  models/DataObject/ClassDefinition/Data/Date.php
Labels: Bug

#15309 [Versions] Set default values for number of versions to be kept
  bundles/InstallBundle/SystemConfig/ConfigWriter.php
Labels: Bug

#15318 Fix: php stan mkdir
  bundles/CoreBundle/src/Migrations/Version20230525131748.php
Labels: Bug

#15323 [Thumbnails] Fix generating image-thumbnail dimensions with fallback to image adapter
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#15322 [Docs] Typo fix
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
Labels: Bug

#15294 Fix missing dependencies to DataObjects in document link editables
  models/DataObject/ClassDefinition/Data/Link.php
  models/Document/Editable/Link.php
Labels: Bug

#15317 [Bug] Fix Objectbrick container class dumping
  lib/DataObject/ClassBuilder/PHPObjectBrickContainerClassDumper.php
Labels: Bug

#15320 [Bug]: Limit for Classificationstore doesn't work with inheritance
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/classificationstore.js
Labels: Bug

#15303 [Task]: Improve Admin translation and application logger sorting
  bundles/AdminBundle/Controller/Admin/LogController.php
  bundles/AdminBundle/Controller/Admin/TranslationController.php
  bundles/AdminBundle/Helper/QueryParams.php
  models/Search/Backend/Data/Listing.php
  models/Translation/Listing.php
Labels: Task

#15352 GridHelperService::prepareListingForGrid should make sure ClassDefinition::getById gets a string
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Task

#15371 Updated EOL information
  README.md
Labels: Task

#15360 Add missing column to install.sql to correct missing column from migration
  bundles/InstallBundle/Resources/install.sql
Labels: Bug

#15280 [Bug]: Fix Dependencies not resolved correctly
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Bug

#15339 Fix preview links for DataObjects when using generators
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#15314 Update ObjectBrickContainerClassBuilder.php
  bundles/CoreBundle/src/Migrations/Version20230606112233.php
  lib/DataObject/ClassBuilder/ObjectBrickContainerClassBuilder.php
Labels: Bug

#15374 [Bug]: Missing use statement in codeception link test
  tests/Model/DataType/LinkTest.php
Labels: Bug

#15253 [Bug]: Fix picture source tag intrisic size
  models/Asset/Image/Thumbnail.php
Labels: Bug

#15310 [Bug] Unescape already escaped csv character
  lib/Helper/CsvFormulaFormatter.php
  models/Element/Service.php
  models/Translation.php
  tests/Unit/Helper/CsvFormulaTest.php
Labels: Bug

#15325 [Bug] Don't cast to int before rounding data
  models/DataObject/ClassDefinition/Data/Numeric.php
Labels: Bug

#15332 Delete old application_logs_archive tables, even if there are gaps in table names
  bundles/ApplicationLoggerBundle/src/Maintenance/LogArchiveTask.php
Labels: Bug

#15351 [Thumbnails] Fix accessing the deferred thumbnail URL doesn't add it to cache
  models/Asset.php
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#15356 Fix: Image editable should only return Image Assets or null
  models/Document/Editable/Image.php
Labels: Bug

#15404 Follow up to #15280
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
Labels: Task

#15058 Fix maintenance task for ObjectBricks and FieldCollections on DB with lower_case_table_names
  lib/Maintenance/Tasks/CleanupBrickTablesTask.php
  lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php
Labels: Improvement

#15408 [Image Thumbnails] Fix auto format enabled check
  models/Asset/Image/Thumbnail/Config.php
Labels: Bug

#15396 Bug BundleEventSetup - Initialize null arrays as empty
  bundles/InstallBundle/src/Event/BundleSetupEvent.php
Labels: Bug

#15385 Add key to unknown option and make gender field not mandatory
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/data/gender.js
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/Gender.php
Labels: Bug

#15409 10.5 End of Life
  README.md
Labels: Task

#15412 [Tests] Use docker compose v2 and latest PHP version
  doc/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  tests/bin/docker-compose.yaml
  tests/bin/init-tests.sh
Labels: Task

#15403 [Documents] Fix: Image editable typehints
  models/Document/Editable/Image.php
Labels: Task

#15333 [Multiselect] getDiffVersionPreview -> prevent error when $options is null
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug

#15425 Revert "Update priority for CoreBundle & AdminBundle to load after defaults"
  lib/Kernel.php
Labels: Bug

#15427 Revert "[Bug]: Fix Dependencies not resolved correctly (#15280)"
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Task

#15375 Fix: Editable relations throw error
  models/Document/Editable/Relations.php
Labels: Bug

#15435 [Improvement] Added `ClassDefinitionInterface`
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Helper/VarExportInterface.php
  models/DataObject/ClassDefinitionInterface.php
Labels: Improvement

#15402 Remove reference to `pimcore:deployment:custom-layouts-rebuild` in the docs
  doc/21_Deployment/05_Deployment_Tools.md
Labels: Bug

#15440 Service::copyAsChild() - $language param should be a string or null
  models/Document/Service.php
Labels: Bug

#15386 Update Hardlink.php
  models/Document/Hardlink.php
Labels: Bug
