Repository pimcore/pimcore, pull requests merged in 2023-07, with the labels that each got.

#15238 Just return extension instance in `PimcoreCoreBundle::getContainerExtension()`
  bundles/CoreBundle/src/PimcoreCoreBundle.php
Labels: Improvement

#15456 [Bug]: TinyMCE removes <br>
  bundles/CoreBundle/config/pimcore/default.yaml
Labels: Bug

#15442 Make phpdoc consistent with higher version
  models/Document/Hardlink.php
  models/Document/Service.php
Labels: Task

#15376 Fix: Breadcrumbs navigation doesn't show any pages
  lib/Navigation/Renderer/AbstractRenderer.php
Labels: Bug

#15358 Fix: CustomLayout attribute default should be a bool
  models/DataObject/ClassDefinition/Service.php
Labels: Bug

#15467 do not mark JsonHelperTrait as internal
  doc/Development_Documentation/20_Extending_Pimcore/24_Add_Your_Own_Permissions.md
  lib/Controller/Traits/JsonHelperTrait.php
Labels: Bug

#15486 Fix the type error in saving a document link
  models/Document/Link.php
Labels: Bug

#15349 [Docs] update users and roles section
  doc/22_Administration_of_Pimcore/07_Users_and_Roles.md
  doc/img/usersAndRoles_Access.png
  doc/img/usersAndRoles_addUser.png
Labels: Task

#15391 [Bug] - Deadlock found when trying to get lock on DataObject import
  bundles/CoreBundle/Migrations/Version20230616085142.php
  models/DataObject/Data/ObjectMetadata/Dao.php
Labels: Bug

#15483 [Bug][FieldCollection]: Fixes potential relation data loss
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php
  tests/Model/Relations/FieldcollectionTest.php
  tests/_support/Helper/Model.php
Labels: Bug

#15525 [Docs] Don't register session bag on stateless request
  doc/19_Development_Tools_and_Details/35_Working_with_Sessions.md
Labels: Task

#15515 Fix error on - Trying to access array offset
  models/DataObject/ClassDefinition/Data/Geobounds.php
Labels: Bug

#15519 [Doc] Nginx does not allow to deliver .webp files
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
Labels: Bug

#15365 [Composer] Improve readability
  .github/ci/scripts/symfony-require-dev.sh
  composer.json
Labels: Task

#15523 [Bug]: Quote sorting key
  bundles/AdminBundle/Helper/GridHelperService.php
Labels: Bug

#15506 [Bug]: Fix object preview not displaying main site
  bundles/AdminBundle/Service/PreviewGenerator.php
Labels: Bug

#15528 [Bug] Typed static property Pimcore\Image\Adapter\Imagick::$CMYKColorProfile must not be accessed before initialization
  lib/Image/Adapter/Imagick.php
Labels: Bug

#15024 WYSIWYG Menu Floating Fix
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/wysiwyg.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/wysiwyg.js
Labels: Bug

#15538 Fix Xss in the Search Documents
  bundles/AdminBundle/Resources/public/js/pimcore/element/selector/document.js
Labels: Security

#15531 Fix PhpDocs in Imagick adapter
  lib/Image/Adapter.php
  lib/Image/Adapter/Imagick.php
Labels: Bug

#15395 Update Video.php
  models/Asset/Video.php
  models/Document/Editable/Video.php
Labels: Bug

#15387 Updated docs generation action
  .github/ci/scripts/docs.sh
  .github/workflows/docs.yaml
  doc/19_Development_Tools_and_Details/09_Cache/03_Full_Page_Cache.md
Labels: Task

#15415 [Docs] update overview chart
  doc/01_Getting_Started/05_Architecture_Overview.md
  doc/img/architectural-chart.png
  doc/img/architectural-chart.pptx
Labels: Task

#15514 [Mail] Inlining styles does not work when CSS file is embedded via pimcore_head_link()
  lib/Helper/Mail.php
Labels: Bug

#15541 Fix Xss in the link Editable
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/link.js
Labels: Security

#15546 Update Video.php
  models/Asset/Video.php
  models/Document/Editable/Video.php
Labels: Task

#15447 Let globalaction determine if the subject is to be saved or not - 11.x
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/07_Workflow_Management/01_Configuration_Details/README.md
  lib/Workflow/GlobalAction.php
Labels: Improvement

#15239 Optimize and harden `EncoreHelper` a bit
  lib/Helper/EncoreHelper.php
Labels: Improvement

#15321 [Improvement] Adapt bug report template
  .github/ISSUE_TEMPLATE/Bug-Report.yaml
Labels: Improvement

#15115 PhpStan: Add strict mode check
  composer.json
  phpstan-baseline.neon
  phpstan-parameters.neon
  phpstan.neon
Labels: Improvement

#15563 Fix: preg_match(): Argument #2 ($subject) must be of type string, bool given
  models/DataObject/ClassDefinition/Data.php
Labels: Bug

#15530 Confidential information provided to user with no permissions
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Controller/Admin/IndexController.php
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/AdminBundle/Resources/public/js/pimcore/startup.js
Labels: Security

#15480 fix: high res PDF thumbnails always display page 1
  bundles/CoreBundle/Controller/PublicServicesController.php
Labels: Bug

#15551 Fix: No encoder has been configured for account "Pimcore\Security\User\User".
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
Labels: Bug

#15543 Fix: o_id and id
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php
  models/DataObject/Data/AbstractMetadata/Dao.php
  models/DataObject/Data/ElementMetadata/Dao.php
  models/DataObject/Data/ObjectMetadata/Dao.php
Labels: Bug

#15518 Allow configuring Argon2 password hashes only if the algorithm exists
  bundles/CoreBundle/DependencyInjection/Configuration.php
Labels: Bug

#15476 Fixed wrong trait filename for ClassicUiBundle; Fixed wrong link to Analytics Adapter
  doc/18_Tools_and_Features/29_Custom_Reports.md
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/13_Loading_Admin_UI_Assets.md
Labels: Bug

#15503 Support StatusCodes other than redirects in RedirectHandler
  lib/Routing/RedirectHandler.php
Labels: Bug

#15548 [DataObjects] Fix adding multiple objectbricks on update
  models/DataObject/Objectbrick.php
  models/DataObject/Objectbrick/Data/Dao.php
Labels: Bug

#15569 Fix TinyMCE config for pimcore specific attributes and drag and drop feature
  bundles/CoreBundle/config/pimcore/default.yaml
  lib/Tool/Text.php
  models/Document.php
Labels: Bug

#15565 Fix default error page response
  bundles/CoreBundle/src/EventListener/ResponseExceptionListener.php
Labels: Bug

#15445 Show display blocks in WYSIWYG
  bundles/TinymceBundle/public/js/editor.js
Labels: Bug

#15574 Unmark BundleManagerEvents as Final
  lib/Event/BundleManagerEvents.php
Labels: Task

#15343 fix: check if asset id exists before creating a hotspot image
  models/DataObject/ClassDefinition/Data/Hotspotimage.php
Labels: Bug

#15576 [Bug]: Fix Base Units in QuantityValue Unit GridView not displaying all units
  bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js
Labels: Bug

#14392 chore: Use more descriptive `str_contains()`/`str_starts_with()`/`str_ends_with()` where possible
  bundles/CoreBundle/src/DependencyInjection/Compiler/LongRunningHelperPass.php
  bundles/CoreBundle/src/DependencyInjection/Compiler/MonologPublicLoggerPass.php
  bundles/CoreBundle/src/EventListener/Frontend/EditmodeListener.php
  bundles/InstallBundle/src/Installer.php
  bundles/SimpleBackendSearchBundle/src/Controller/SearchController.php
  bundles/StaticRoutesBundle/src/Model/Staticroute.php
  bundles/XliffBundle/src/Escaper/Xliff12Escaper.php
  lib/Helper/Mail.php
  lib/Http/ResponseHelper.php
  lib/HttpKernel/BundleLocator/BundleLocator.php
  lib/Image/Adapter/Imagick.php
  lib/Maintenance/Tasks/CleanupBrickTablesTask.php
  lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php
  lib/Maintenance/Tasks/DbCleanupBrokenViewsTask.php
  lib/Migrations/FilteredMigrationsRepository.php
  lib/Migrations/FilteredTableMetadataStorage.php
  lib/Navigation/Page/Url.php
  lib/Navigation/Renderer/AbstractRenderer.php
  lib/Routing/Dynamic/DocumentRouteHandler.php
  lib/Routing/Element/Router.php
  lib/Tool/Console.php
  lib/Tool/Frontend.php
  lib/Tool/Text.php
  lib/Translation/Translator.php
  lib/Twig/Extension/Templating/HeadStyle.php
  models/Asset/Image.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/Concrete.php
  models/DataObject/Data/ObjectMetadata.php
  models/DataObject/Data/StructuredTable.php
  models/DataObject/Data/UrlSlug.php
  models/DataObject/Listing.php
  models/DataObject/Service.php
  models/Document.php
  models/Document/Editable/Link.php
  models/Document/Editable/Video.php
  models/Document/Hardlink/Wrapper.php
  models/Site/Dao.php
  tests/Model/LazyLoading/AbstractLazyLoadingTest.php
  tests/Service/Element/VersionTest.php
Labels: Task

#15524 Fix Document link marshalling
  models/Document/Link.php
Labels: Bug

#15468 removed deprecation warning
  lib/Event/BundleManagerEvents.php
Labels: Bug

#15581 fix: high res PDF thumbnails always display page 1
  models/Asset/Service.php
Labels: Bug

#15592 Revert "Fix: o_id and id (#15543)" partially
  models/DataObject/Data/AbstractMetadata/Dao.php
  models/DataObject/Data/ElementMetadata/Dao.php
  models/DataObject/Data/ObjectMetadata/Dao.php
Labels: Bug, Task

#15580 [SeoBundle] Fix deprecation in Seo Bundle
  bundles/SeoBundle/src/Controller/Document/DocumentController.php
Labels: Bug

#15585 Allow images and relative media in HTMLSanitizer
  bundles/CoreBundle/config/pimcore/default.yaml
Labels: Bug

#15613 [Bug]: WYSIWYG editor crashing due `component.up` error
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/wysiwyg.js
Labels: Bug

#15624 [Translations] Consider only registered in available domains
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/README.md
  models/Translation/Dao.php
  models/Translation/Listing.php
Labels: Bug

#15594 [Bug]: regex for image thumbnails media queries high resolution
  models/Asset/Service.php
Labels: Bug

#14402 Improvement: Adds PRE_COPY event to the copy-contents-action
  models/Asset/Service.php
  models/DataObject/Service.php
  models/Document/Service.php
Labels: Improvement, Priority

#15633 [Docs]: Improve explanation about recycle bin
  doc/Development_Documentation/22_Administration_of_Pimcore/02_Cleanup_Data_Storage.md
  doc/Development_Documentation/22_Administration_of_Pimcore/07_Users_and_Roles.md
Labels: Task

#15630 Fix: readDimensionsFromFile() doesn't return dimensions
  models/Asset/Folder.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#15606 [Docs] Details behavior for workspace permissions
  doc/22_Administration_of_Pimcore/07_Users_and_Roles.md
Labels: Improvement

#15637 [Docs] Moves symfony messenger section
  doc/01_Getting_Started/00_Installation/00_Docker_Based_Installation.md
  doc/01_Getting_Started/00_Installation/01_Webserver_Installation.md
  doc/01_Getting_Started/02_Advanced_Installation_Topics/01_Symfony_Messenger.md
  doc/01_Getting_Started/02_Advanced_Installation_Topics/README.md
  doc/01_Getting_Started/README.md
Labels: Task

#15593 [Task]: PhpStan bump July
  bundles/CoreBundle/src/Command/Bundle/ListCommand.php
  composer.json
  phpstan-baseline.neon
Labels: Task

#15621 Fix: Ceil():Argument #1 ($num) must be of type int|float, null given when uploading video
  models/Asset/Video.php
  models/Document/Editable/Video.php
Labels: Bug
