Repository pimcore/pimcore, pull requests merged in 2023-03, with the labels that each got.

#14443 Remove unused DocumentController::getSeoNodeConfig() method
  bundles/AdminBundle/src/Controller/Admin/Document/DocumentController.php
Labels: Task

#14451 Initialized HeadStyle _captureLock to false
  lib/Twig/Extension/Templating/HeadStyle.php
Labels: Bug

#14498 [Bug] createCSV in CustomReportsController
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
Labels: Bug

#14493 Add check if bundle is installed
  bundles/UuidBundle/src/EventListener/UUIDListener.php
Labels: Bug

#14431 [Bug]: Date editable frontend format fallback
  doc/Development_Documentation/03_Documents/01_Editables/10_Date.md
  models/Document/Editable/Date.php
Labels: Bug

#14500 [Task] Optimizing dialog
  models/Document/Editable/Link.php
Labels: Task

#14504 Task: Follow up for #14431 Carbon
  models/Document/Editable/Date.php
Labels: Task

#14480 [Bug]: load setting from SettingsStore by id returns null
  doc/Development_Documentation/19_Development_Tools_and_Details/42_Settings_Store.md
Labels: Bug

#14420 [Bug]: DatabaseVersionStorageAdapter duplicate ID on autosave
  models/Version/Adapter/DatabaseVersionStorageAdapter.php
Labels: Bug

#14395 Remove wrong/redundant php docs
  bundles/AdminBundle/src/Controller/Admin/EmailController.php
  bundles/CoreBundle/src/Migrations/Version20201007000000.php
  bundles/EcommerceFrameworkBundle/src/IndexService/Getter/DefaultClassificationAttributeGetter.php
  bundles/EcommerceFrameworkBundle/src/IndexService/ProductList/ProductListInterface.php
  lib/Helper/Mail.php
  lib/Mail.php
  lib/Navigation/Renderer/AbstractRenderer.php
  models/Asset/Image.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Image.php
  models/DataObject/ClassDefinition/Data/ImageGallery.php
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Password.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/Document/Editable/Areablock.php
  models/Document/Editable/Image.php
  models/Tool/Email/Log.php
  models/Tool/TmpStore.php
  tests/Model/DataType/ObjectAwareFieldsTest.php
Labels: Task

#14503 [Bug][Migrations] Double check migrations for o_* columns
  bundles/CoreBundle/src/Migrations/Version20221222181745.php
Labels: Bug

#14389 Cleanup `Pimcore\Tool\Authentication::refreshUser()`
  lib/Tool/Authentication.php
Labels: Task

#14476 Type fixes for ReverseObjectRelation
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
Labels: Bug

#14447 [DataObject] Support convertTo on InputQuantityValue
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/AbstractQuantityValue.php
  models/DataObject/ClassDefinition/Data/InputQuantityValue.php
  models/DataObject/ClassDefinition/Data/QuantityValue.php
  models/DataObject/Data/AbstractQuantityValue.php
  models/DataObject/Data/InputQuantityValue.php
  models/DataObject/Data/QuantityValue.php
  models/DataObject/QuantityValue/DefaultConverter.php
  models/DataObject/QuantityValue/QuantityValueConverterInterface.php
  models/DataObject/QuantityValue/UnitConversionService.php
Labels: Improvement, BC-BREAK

#14517 Fix test after merging 10.6 branch
  bundles/CoreBundle/Resources/translations/en.json
  bundles/PersonalizationBundle/tests/Support/Util/TestHelper.php
  bundles/PersonalizationBundle/tests/Unit/Targeting/Document/TargetGroupEditableTest.php
  lib/Google/Cse.php
  lib/Google/Cse/Item.php
Labels: Bug

#14250 Remove deprecated DocumentRouteHandler::addDirectRouteDocumentType() method
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Routing/Dynamic/DocumentRouteHandler.php
Labels: Task

#14514 Reimplement #12736
  bundles/AdminBundle/src/Helper/GridHelperService.php
Labels: Bug

#14438 Remove @internal from PackageVersionTrait
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/README.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Extension/Bundle/Traits/PackageVersionTrait.php
Labels: Task

#14246 [Improvement]: Add Psalm actions
  .github/workflows/psalm.yml
  bundles/FileExplorerBundle/src/Controller/SettingsController.php
  lib/File.php
  lib/Tool/DeviceDetector.php
Labels: Improvement

#14376 [Admin] Trigger Login Redirect Event & Remove redundant events
  bundles/AdminBundle/src/Controller/Admin/LoginController.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Event/AdminEvents.php
Labels: Task

#14519 [10.6] Marked AbstractUser and UserRole class abstract
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/User/AbstractUser.php
  models/User/UserRole.php
Labels: Task

#14411 [Task] Removed the functionality to input metadata html tags in SEO and settings
  bundles/AdminBundle/public/js/pimcore/document/pages/settings.js
  bundles/AdminBundle/src/Controller/Admin/Document/PageController.php
  bundles/CoreBundle/config/event_listeners.yaml
  bundles/CoreBundle/src/EventListener/Frontend/DocumentMetaDataListener.php
  bundles/CoreBundle/src/Migrations/Version20230222174636.php
  bundles/InstallBundle/dump/install.sql
  bundles/PersonalizationBundle/src/Model/Document/Page/Dao.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Document/Page.php
  models/Document/Page/Dao.php
Labels: Task

#14453 [Improvement]: removing block element with default set should clear editable values
  bundles/AdminBundle/public/js/pimcore/document/editables/block.js
Labels: Improvement

#14441 Make AbstractUser and UserRole class abstract
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/User/AbstractUser.php
  models/User/UserRole.php
Labels: BC-BREAK

#14434 [Thumbnails] Remove callback support in transformations
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset/Image/Thumbnail/Processor.php
Labels: Task, BC-BREAK

#14331 [Feature]: fully integrate Symfony's ErrorHandler
  bundles/WebToPrintBundle/src/Processor/PdfReactor.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Bootstrap.php
  lib/Kernel.php
Labels: New Feature

#14491 Fix sizing of custom admin tab icons
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Bug

#14501 [Improvement]: Add getDirtyFields method to DirtyIndicatorTrait
  models/Element/Traits/DirtyIndicatorTrait.php
Labels: Task

#14522 [Task]: Check inheritance in DataObject\Service
  doc/Development_Documentation/05_Objects/01_Object_Classes/01_Data_Types/35_Fieldcollections.md
  models/DataObject/Service.php
Labels: Task

#14526 [Task] Optimized custom reports filter
  models/Tool/CustomReport/Adapter/Sql.php
Labels: Task

#14518 [Improvement]: ScheduledTasks MaintenanceTask blocked by other MaintenanceTasks
  bundles/CoreBundle/config/maintenance.yaml
  bundles/CoreBundle/config/message_handler.yaml
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/DependencyInjection/Compiler/RegisterMaintenanceTaskPass.php
  doc/Development_Documentation/20_Extending_Pimcore/16_Maintenance_Tasks.md
  lib/Maintenance/Executor.php
  lib/Maintenance/ExecutorInterface.php
  lib/Messenger/Handler/ScheduledTaskHandler.php
  lib/Messenger/ScheduledTaskMessage.php
Labels: Improvement

#14521 [Bug]: Relations inside localized fields not loaded in preview mode
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php
  models/Element/Service.php
Labels: Bug

#14427 [Improvement]: Being able to filter on "null" values in the dataobject folder grids
  bundles/AdminBundle/public/js/pimcore/element/helpers/gridColumnConfig.js
  bundles/AdminBundle/src/Helper/GridHelperService.php
Labels: Improvement

#14426 [Flysystem] Fixed visibility for asset and thumbnail storage
  bundles/CoreBundle/config/pimcore/flysystem.yaml
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Bug

#14469 Fix wrong type hints
  bundles/EcommerceFrameworkBundle/src/CartManager/CartInterface.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/AbstractOrderList.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/Order/Listing.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/Order/Listing/Filter/CustomerObject.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/Order/Listing/Filter/OrderDateTime.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/Order/Listing/Filter/OrderSearch.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/Order/Listing/Filter/Payment.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/Order/Listing/Filter/Product.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/Order/Listing/Filter/ProductType.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/OrderListFilterInterface.php
  bundles/EcommerceFrameworkBundle/src/OrderManager/OrderListInterface.php
  bundles/EcommerceFrameworkBundle/src/PriceSystem/ModificatedPrice.php
  bundles/EcommerceFrameworkBundle/src/PriceSystem/PriceInfoInterface.php
  bundles/EcommerceFrameworkBundle/src/PricingManager/Environment.php
  bundles/EcommerceFrameworkBundle/src/PricingManager/EnvironmentInterface.php
  bundles/EcommerceFrameworkBundle/src/PricingManager/PriceInfoInterface.php
  bundles/SeoBundle/src/EventListener/DocumentListener.php
  bundles/SeoBundle/src/EventListener/UrlSlugUpdateListener.php
  lib/Image/Adapter.php
  lib/Image/Adapter/GD.php
  lib/Image/Adapter/Imagick.php
  models/Element/AbstractElement.php
  models/Element/ElementInterface.php
  models/Property.php
  models/Property/Predefined.php
  models/Schedule/Task.php
  models/Tool/Email/Log.php
  models/User/Permission/Definition.php
  models/User/Workspace/DataObject.php
Labels: Task

#14534 Fix, cleanup & refactor some inherited values setter related code (followup of #14428)
  bundles/SimpleBackendSearchBundle/src/Controller/DataObjectController.php
  bundles/XliffBundle/src/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
  doc/05_Objects/01_Object_Classes/01_Data_Types/35_Fieldcollections.md
  doc/05_Objects/01_Object_Classes/05_Class_Settings/25_Inheritance.md
  lib/Workflow/Notification/NotificationEmailService.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/Objectbrick.php
  models/DataObject/Service.php
  models/DataObject/Traits/DefaultValueTrait.php
Labels: Improvement

#14529 Add deprecated in documentation
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
Labels: Task

#14466 [Improvement] Global Language switcher
  bundles/AdminBundle/public/js/pimcore/element/abstract.js
  bundles/AdminBundle/public/js/pimcore/events.js
  bundles/AdminBundle/public/js/pimcore/object/edit.js
  bundles/AdminBundle/public/js/pimcore/object/helpers/edit.js
  bundles/AdminBundle/public/js/pimcore/object/object.js
  bundles/AdminBundle/public/js/pimcore/object/tags/abstract.js
  bundles/AdminBundle/public/js/pimcore/object/tags/fieldcollections.js
  bundles/AdminBundle/public/js/pimcore/object/tags/localizedfields.js
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#14393 Delete unused class `Pimcore\Tool\Cast`
  lib/Tool/Cast.php
Labels: Improvement

#14506 Adds type constants to SettingsStore and use them across the system
  bundles/CoreBundle/src/Migrations/Version20210323110055.php
  bundles/CoreBundle/src/Migrations/Version20210630062445.php
  bundles/CoreBundle/src/Migrations/Version20220829132224.php
  bundles/CoreBundle/src/Migrations/Version20221215071650.php
  bundles/CoreBundle/src/Migrations/Version20221216140012.php
  bundles/CoreBundle/src/Migrations/Version20221220152444.php
  bundles/CoreBundle/src/Migrations/Version20221222134837.php
  bundles/CoreBundle/src/Migrations/Version20221228101109.php
  bundles/CoreBundle/src/Migrations/Version20230107224432.php
  bundles/CoreBundle/src/Migrations/Version20230110130748.php
  bundles/CoreBundle/src/Migrations/Version20230111074323.php
  bundles/CoreBundle/src/Migrations/Version20230113165612.php
  bundles/CoreBundle/src/Migrations/Version20230120111111.php
  bundles/CoreBundle/src/Migrations/Version20230125164101.php
  bundles/CoreBundle/src/Migrations/Version20230202152342.php
  bundles/CoreBundle/src/Migrations/Version20230222075502.php
  bundles/SeoBundle/src/Controller/SettingsController.php
  doc/19_Development_Tools_and_Details/42_Settings_Store.md
  lib/Config/LocationAwareConfigRepository.php
  lib/Config/ReportConfigWriter.php
  lib/Extension/Bundle/Installer/SettingsStoreAwareInstaller.php
  models/Tool/SettingsStore.php
  models/Tool/SettingsStore/Dao.php
  tests/Model/Tool/SettingsStoreTest.php
Labels: Task

#14435 [Task]: Fixes Full page cache documentation and adds an example with DependencyInjection
  doc/Development_Documentation/19_Development_Tools_and_Details/09_Cache/03_Full_Page_Cache.md
Labels: Improvement

#14541 Replace single backslashes with double so copy paste is possible
  bundles/InstallBundle/src/Installer.php
Labels: Task

#14561 Deprecations in 10.6 for removed methods are missing
  bundles/EcommerceFrameworkBundle/CoreExtensions/ClassDefinition/IndexFieldSelection.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/Extension/ColumnType.php
  models/DataObject/ClassDefinition/Data/Extension/QueryColumnType.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
Labels: Task

#14559 [Task]: Deprecate Pimcore\Db\Helper::insertOrUpdate
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Db/Helper.php
  lib/Db/PimcoreExtensionsTrait.php
Labels: Task

#14594 Add the properties count and success in the response of getAvailableControllerReferencesAction() method
  bundles/AdminBundle/Controller/Admin/MiscController.php
Labels: Improvement

#14560 [Task] Improve webtoprint pdf
  bundles/AdminBundle/Resources/public/js/pimcore/document/printpages/pdf_preview.js
Labels: Task

#14499 [System Settings] Change valid_languages format
  .github/ci/files/config/system.yaml
  bundles/AdminBundle/public/js/pimcore/settings/system.js
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/src/Controller/Admin/SettingsController.php
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/config/system.yaml
  bundles/GoogleMarketingBundle/.github/ci/files/config/system.yml
  bundles/PersonalizationBundle/.github/ci/files/config/system.yaml
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Tool.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
Labels: Task, BC-BREAK

#14155 Extracted method to get thumbnail in service
  bundles/CoreBundle/src/Controller/PublicServicesController.php
  doc/04_Assets/07_Restricting_Public_Asset_Access.md
  models/Asset/Service.php
  tests/Model/Asset/AssetThumbnailCacheTest.php
Labels: Improvement

#14509 [Task] Replacing typeloader with class resolver
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/CoreBundle/Resources/config/class_resolvers.yaml
  bundles/CoreBundle/Resources/config/implementation_factories.yaml
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/08_Adding_Document_Types.md
  lib/Model/AbstractModel.php
  lib/Model/Document/TypeDefinition/Loader/TypeLoaderInterface.php
  lib/Resolver/ClassResolver.php
  lib/Resolver/ResolverInterface.php
  models/Document.php
Labels: Task

#14555 [Bug] Shared Translations wrong route prefix.
  bundles/XliffBundle/src/Controller/XliffTranslationController.php
Labels: Bug

#14536 [Bug]: Translation CSV Import type error
  models/Translation.php
Labels: Bug

#14619 Adapt webtoprint to classresolver
  bundles/WebToPrintBundle/src/Controller/Document/PrintpageControllerBase.php
Labels: Bug

#14401 Improvement mark modified fields as dirty
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
  models/DataObject/ClassDefinition/Data.php
  tests/Model/DataObject/ClassDefinitionTest.php
Labels: Improvement

#14606 [ApplicationLogger] Improve Date & Time fields error tooltips
  bundles/AdminBundle/Resources/public/js/pimcore/log/admin.js
Labels: Bug

#14486 Configuration storage location follow-up
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
  lib/Config/LocationAwareConfigRepository.php
  lib/CustomView/Config.php
  lib/Kernel.php
  lib/Model/Dao/PimcoreLocationAwareConfigDao.php
  lib/Perspective/Config.php
  lib/Web2Print/Config.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Video/Thumbnail/Config/Dao.php
  models/Document/DocType/Dao.php
  models/Metadata/Predefined/Dao.php
  models/Property/Predefined/Dao.php
  models/Staticroute/Dao.php
  models/Tool/CustomReport/Config/Dao.php
Labels: Task

#14492 Use SYMFONY_ASSETS_INSTALL env variable when calling assets:install
  lib/Composer.php
  lib/Tool/AssetsInstaller.php
Labels: Task

#14578 Relations usort improvement
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
Labels: Improvement

#14579 [Bug] If config cannot be loaded from cache, make sure it is an array
  lib/Config.php
Labels: Bug

#14558 [Task]: Remove unrelated changes about document class definitions
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
Labels: Bug

#14554 [Task][Web2PrintBundle]: Fix `Add PrintPage` position in right-click menu
  bundles/WebToPrintBundle/public/js/startup.js
Labels: Task

#14612 [Bug]: XLIFF Export type error.
  bundles/XliffBundle/src/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php
Labels: Bug

#14572 [Task]: Deprecate HeadlessChrome processor
  bundles/AdminBundle/Resources/public/js/pimcore/settings/web2print.js
  doc/Development_Documentation/03_Documents/02_Document_Types/15_Print_Documents.md
  doc/Development_Documentation/18_Tools_and_Features/30_Rendering_PDFs.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Web2Print/Processor/HeadlessChrome.php
Labels: Task

#14592 [Improvement]: Improve error message for duplicate names in Predefined Asset Metadata
  bundles/AdminBundle/src/Controller/Admin/SettingsController.php
  bundles/AdminBundle/translations/admin_ext.en.yaml
Labels: Improvement

#14574 [Task]: Improve Tooltip.
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/edit.js
Labels: Task

#14562 [Task]: Improve redirects.
  bundles/AdminBundle/Resources/public/js/pimcore/settings/redirects.js
Labels: Task

#14413 [Bug] Passing object to `DataObjectParamResolver` doesn´t work
  bundles/CoreBundle/Request/ParamConverter/DataObjectParamResolver.php
Labels: Bug

#14477 [Classification Store] Inheritance not working for PHP API
  models/DataObject/Classificationstore.php
Labels: Bug

#14538 [Task] Optimized `SearchController::findAction`
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
Labels: Task

#14540 [Task] added new `PimcoreBundleAdminSupportInterface`
  bundles/AdminBundle/Support/PimcoreBundleAdminSupportInterface.php
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/README.md
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/13_Loading_Admin_UI_Assets.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Event/BundleManagerEvents.php
  lib/Extension/Bundle/PimcoreBundleInterface.php
  lib/Extension/Bundle/PimcoreBundleManager.php
Labels: Task

#14568 [Bug]: Fix password reset output message and throttling
  bundles/AdminBundle/Controller/Admin/LoginController.php
  bundles/AdminBundle/Resources/public/css/login.css
  bundles/AdminBundle/Resources/views/Admin/Login/lostpassword.html.twig
  bundles/AdminBundle/Security/Authenticator/AdminAbstractAuthenticator.php
  bundles/CoreBundle/Resources/config/pimcore/default.yaml
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#14622 [Docoument] Fix null-safe statement in ContentTemplatelistener
  bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php
Labels: Bug

#14630 [Bug] Fixed `LibreOffice::getText` method
  lib/Document/Adapter/Ghostscript.php
  lib/Document/Adapter/LibreOffice.php
Labels: Bug

#14625 Add provider to user model
  bundles/CoreBundle/Migrations/Version20230223101848.php
  bundles/InstallBundle/Resources/install.sql
  models/User.php
Labels: Bug, Task

#14631 [Task] Update scheduling
  bundles/AdminBundle/Resources/public/js/pimcore/element/scheduler.js
Labels: Task

#14629 [Thumbnail] Added possibility to add custom criteria to hash
  models/Asset/Image/Thumbnail/Config.php
Labels: Task

#14569 [Bug]: Weekday translation key conflicting with short country code (Language)
  bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js
Labels: Bug

#14669 [Task] Optimized urlslug input
  bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/Resources/public/js/pimcore/document/pages/settings.js
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
Labels: Task

#14655 [Task]: Add `getPrimaryKey` method in `AbstractDao`
  lib/Model/Dao/AbstractDao.php
Labels: Task

#14633 [Task] Optimized get by UUID
  models/Tool/UUID/Dao.php
Labels: Task

#14652 [Task] Moved `FullTextIndexOptimizeTask` to `SimpleBackendSearchBundle`
  bundles/CoreBundle/config/maintenance.yaml
  bundles/SimpleBackendSearchBundle/config/services.yaml
  bundles/SimpleBackendSearchBundle/src/Task/Maintenance/FullTextIndexOptimizeTask.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, BC-BREAK

#14570 [Task]: Remove weekday translation keys (Language)
  bundles/AdminBundle/translations/admin.en.yaml
  bundles/CoreBundle/translations/admin.cs.yaml
  bundles/CoreBundle/translations/admin.de.yaml
  bundles/CoreBundle/translations/admin.es.yaml
  bundles/CoreBundle/translations/admin.fr.yaml
  bundles/CoreBundle/translations/admin.hu.yaml
  bundles/CoreBundle/translations/admin.it.yaml
  bundles/CoreBundle/translations/admin.ja.yaml
  bundles/CoreBundle/translations/admin.nl.yaml
  bundles/CoreBundle/translations/admin.pl.yaml
  bundles/CoreBundle/translations/admin.pt.yaml
  bundles/CoreBundle/translations/admin.pt_br.yaml
  bundles/CoreBundle/translations/admin.ru.yaml
  bundles/CoreBundle/translations/admin.sk.yaml
  bundles/CoreBundle/translations/admin.sv.yaml
  bundles/CoreBundle/translations/admin.sv_fi.yaml
  bundles/CoreBundle/translations/admin.th.yaml
  bundles/CoreBundle/translations/admin.tr.yaml
  bundles/CoreBundle/translations/admin.uk.yaml
  bundles/CoreBundle/translations/admin.zh_Hans.yaml
Labels: Task

#14678 [Task]: Docs - Remove deprecated Pimcore\Db\Helper::insertOrUpdate method
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#14670 [Task]: Remove deprecated PhpArrayFileTable
  bundles/CoreBundle/src/Migrations/Version20210323082921.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Db/PhpArrayFileTable.php
Labels: Task

#14563 Relation performance fix
  bundles/CoreBundle/Migrations/Version20230307135459.php
  models/DataObject/ClassDefinition/Dao.php
Labels: Task

#14616 [Improvement]: Allow passing array to $thumbinail->getPath() and decide wheter to get the frontend path or not
  bundles/CoreBundle/Command/ThumbnailsImageCommand.php
  doc/Development_Documentation/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Image/Thumbnail.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
  models/Asset/Video/ImageThumbnail.php
  tests/Model/Asset/AssetThumbnailCacheTest.php
Labels: Improvement

#14694 Fix image gallery element 0 problems
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/imageGalleryDropZone.js
Labels: Bug

#14692 Add custom layout rebuild command to documentation.
  doc/21_Deployment/05_Deployment_Tools.md
Labels: Improvement

#14651 [Bug]: PHP API does not validate the objectbrick definition key (or not as in the javascript)
  bundles/AdminBundle/Resources/public/js/pimcore/object/fieldcollection.js
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
Labels: Bug

#14676 [Bug] Fixed overflow of manyToOneRelation field
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/manyToOneRelation.js
Labels: Bug

#14696 Fix Gotenberg adapter
  lib/Document/Adapter/Gotenberg.php
Labels: Bug

#14675 [Improvement] Enabled CSP by default
  bundles/AdminBundle/src/DependencyInjection/Configuration.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  doc/26_Best_Practice/75_Security_Concept.md
Labels: Improvement

#14576 [Task][Web2print]: Remove support for HeadlessChrome
  bundles/AdminBundle/translations/admin_ext.en.yaml
  bundles/WebToPrintBundle/public/js/settings.js
  bundles/WebToPrintBundle/src/Controller/SettingsController.php
  bundles/WebToPrintBundle/src/DependencyInjection/Configuration.php
  bundles/WebToPrintBundle/src/Event/DocumentEvents.php
  bundles/WebToPrintBundle/src/Processor.php
  bundles/WebToPrintBundle/src/Processor/HeadlessChrome.php
  bundles/WebToPrintBundle/translations/admin.en.yaml
  composer.json
  doc/03_Documents/02_Document_Types/15_Print_Documents.md
  doc/18_Tools_and_Features/30_Rendering_PDFs.md
  doc/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#14688 Cleanup Temp files after Processing Assets
  bundles/CoreBundle/Resources/config/message_handler.yaml
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
Labels: Bug

#14636 [Task] Optimized composite index key
  bundles/AdminBundle/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js
Labels: Task

#14717 [Cache] Remove unused dynamic property ____pimcore_cache_item__
  lib/Cache/Core/CoreCacheHandler.php
Labels: Task

#14731 [Task]: Followup Ecommerce PimcoreUrl #14641
  lib/Twig/Extension/Templating/PimcoreUrl.php
Labels: Task

#14310 [Feature]: Custom Asset Types
  bundles/AdminBundle/public/js/pimcore/startup.js
  bundles/AdminBundle/src/Controller/Admin/IndexController.php
  bundles/CoreBundle/config/class_resolvers.yaml
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/07_Adding_Asset_Types.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
Labels: Improvement

#14571 [Task] Bump phpstan version
  bundles/AdminBundle/Controller/Admin/SettingsController.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/PimcoreCoreExtension.php
  bundles/EcommerceFrameworkBundle/PriceSystem/CachingPriceSystem.php
  composer.json
  lib/Config/Config.php
  lib/DataObject/ClassBuilder/ClassBuilder.php
  lib/DataObject/ClassBuilder/FieldCollectionClassBuilder.php
  lib/DataObject/ClassBuilder/ObjectBrickClassBuilder.php
  lib/Log/ApplicationLogger.php
  lib/Maintenance/Tasks/VersionsCleanupTask.php
  lib/Routing/RedirectHandler.php
  lib/Workflow/SupportStrategy/ExpressionSupportStrategy.php
  models/DataObject/ClassDefinition/Data/Block.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/Document/Service.php
  models/Staticroute.php
  models/Version/Dao.php
  phpstan-baseline.neon
Labels: Task

#14728 [Bug] Fixed log detail window
  bundles/ApplicationLoggerBundle/public/js/log/admin.js
Labels: Bug

#14729 [Task] Cherry-Picked `PimcoreBundleAdminSupportInterface` changes
  bundles/AdminBundle/src/Support/BundleAdminSupportTrait.php
  bundles/AdminBundle/src/Support/PimcoreBundleAdminSupportInterface.php
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/13_Loading_Admin_UI_Assets.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Extension/Bundle/AbstractPimcoreBundle.php
Labels: Task

#14715 [Bug]: Unable to save custom report
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/item.js
Labels: Bug

#14581 [Improvement]: Honor "Cache-Control: no-store" response header in ful…
  bundles/CoreBundle/src/EventListener/Frontend/FullPageCacheListener.php
  doc/19_Development_Tools_and_Details/09_Cache/03_Full_Page_Cache.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#14711 [Bug] Fixed regex validation issue
  models/DataObject/ClassDefinition/Data/Input.php
Labels: Bug

#14662 Move stopwatch trait to Personalization Bundle
  bundles/PersonalizationBundle/src/Debug/Traits/StopwatchTrait.php
  bundles/PersonalizationBundle/src/Targeting/DataLoader.php
  bundles/PersonalizationBundle/src/Targeting/Debug/TargetingDataCollector.php
  bundles/PersonalizationBundle/src/Targeting/EventListener/TargetingListener.php
  bundles/PersonalizationBundle/src/Targeting/VisitorInfoResolver.php
Labels: Improvement

#14354 Support language-specific transliteration
  lib/Tool/Transliteration.php
Labels: Bug

#14617 Return 404 if disabled format is requested
  models/Asset/Service.php
Labels: Bug

#14725 Use spaceship operator in PositionSortTrait
  models/DataObject/ClassDefinition/Data/Extension/PositionSortTrait.php
Labels: Improvement

#14407 [Improvement]: Check hardcoded namespaces in models/DataObject/ClassDefinition/Data/Extension/Relation.php
  models/DataObject/ClassDefinition/Data/Extension/Relation.php
Labels: Improvement

#13173 Make link edit panel configurable
  bundles/AdminBundle/public/js/pimcore/document/editables/link.js
  bundles/AdminBundle/public/js/pimcore/helpers.js
  bundles/AdminBundle/public/js/pimcore/object/classes/data/link.js
  bundles/AdminBundle/public/js/pimcore/object/tags/link.js
  bundles/AdminBundle/translations/admin_ext.en.yaml
  doc/03_Documents/01_Editables/18_Link.md
  models/DataObject/ClassDefinition/Data/Link.php
  models/Document/Editable/Link.php
Labels: Improvement

#14753 [Bug]: Class layout label position & inheritance issue
  bundles/AdminBundle/Resources/public/js/pimcore/object/tags/localizedfields.js
Labels: Bug

#14752 removeUnusedColumns should execute only one sql query
  models/DataObject/ClassDefinition/Helper/Dao.php
Labels: Bug

#14763 Revert assets install
  lib/Composer.php
  lib/Tool/AssetsInstaller.php
Labels: Task

#14672 AssignTargetGroup: Remove param $conditionMatcher from constructor
  bundles/PersonalizationBundle/src/Targeting/ActionHandler/AssignTargetGroup.php
Labels: Task

#14768 chore: update docs
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#14770 Moved ext translations from CoreBundle to AdminBundle
  .github/workflows/poeditor-export.yaml
  bundles/CoreBundle/translations/admin_ext.de.yaml
  bundles/CoreBundle/translations/admin_ext.fr.yaml
  bundles/CoreBundle/translations/admin_ext.hu.yaml
  bundles/CoreBundle/translations/admin_ext.it.yaml
  bundles/CoreBundle/translations/admin_ext.nl.yaml
  bundles/CoreBundle/translations/admin_ext.th.yaml
Labels: Bug

#14772 Ecommerce refactoring followup
  .github/workflows/static-analysis.yaml
  bundles/EcommerceFrameworkBundle/.editorconfig
  bundles/EcommerceFrameworkBundle/.gitattributes
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Customer.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterCategory.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterCategoryMultiselect.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterInputfield.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterMultiRelation.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterMultiSelect.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterMultiSelectFromMultiSelect.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterNumberRange.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterNumberRangeSelection.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterRelation.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterSelect.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/FilterSelectFromMultiSelect.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/OrderByFields.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/OrderPriceModifications.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/PaymentInfo.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/TaxEntry.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/VoucherTokenTypePattern.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/Fieldcollection/Data/VoucherTokenTypeSingle.php
  bundles/EcommerceFrameworkBundle/.github/ci/files/var/classes/DataObject/FilterDefinition.php
  bundles/EcommerceFrameworkBundle/.gitignore
  bundles/EcommerceFrameworkBundle/.php_cs.dist
  bundles/EcommerceFrameworkBundle/LICENSE.md
  bundles/EcommerceFrameworkBundle/README.md
  bundles/EcommerceFrameworkBundle/SECURITY.md
  bundles/EcommerceFrameworkBundle/doc/03_Installation.md
  bundles/EcommerceFrameworkBundle/gpl-3.0.txt
  doc/19_Development_Tools_and_Details/29_Testing/02_Core_Tests.md
Labels: Task

#14722 Add check for pimcore_targeting_disabled cookie
  lib/Targeting/EventListener/TargetingListener.php
Labels: Bug

#14775 Removed FileExplorerBundle -> moved to pimcore/file-explorer-bundle
  .github/ci/files/config/bundles.php
  bundles/FileExplorerBundle/.editorconfig
  bundles/FileExplorerBundle/.gitattributes
  bundles/FileExplorerBundle/.gitignore
  bundles/FileExplorerBundle/.php_cs.dist
  bundles/FileExplorerBundle/LICENSE.md
  bundles/FileExplorerBundle/README.md
  bundles/FileExplorerBundle/SECURITY.md
  bundles/FileExplorerBundle/composer.json
  bundles/FileExplorerBundle/config/pimcore/routing.yaml
  bundles/FileExplorerBundle/config/services.yaml
  bundles/FileExplorerBundle/gpl-3.0.txt
  bundles/FileExplorerBundle/public/css/file-explorer.css
  bundles/FileExplorerBundle/public/js/explorer.js
  bundles/FileExplorerBundle/public/js/file.js
  bundles/FileExplorerBundle/public/js/startup.js
  bundles/FileExplorerBundle/src/Controller/SettingsController.php
  bundles/FileExplorerBundle/src/DependencyInjection/PimcoreFileExplorerExtension.php
  bundles/FileExplorerBundle/src/Installer.php
  bundles/FileExplorerBundle/src/PimcoreFileExplorerBundle.php
  bundles/FileExplorerBundle/translations/admin.en.yaml
  composer.json
Labels: Task

#14700 Improve Custom Reports SQL input/output in admin UI
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/definitions/sql.js
Labels: Improvement

#14735 allow Back Office order to display actual currency
  bundles/EcommerceFrameworkBundle/OrderManager/Order/Listing.php
  bundles/EcommerceFrameworkBundle/OrderManager/V7/OrderAgent.php
  bundles/EcommerceFrameworkBundle/Resources/views/admin_order/list.html.twig
Labels: Bug

#14462 Make Targeting Opt-in
  bundles/AdminBundle/public/js/pimcore/document/page.js
  bundles/AdminBundle/public/js/pimcore/document/page_snippet.js
  bundles/AdminBundle/public/js/pimcore/document/snippet.js
  bundles/PersonalizationBundle/config/services.yaml
  bundles/PersonalizationBundle/config/targeting.yaml
  bundles/PersonalizationBundle/config/targeting/listeners.yaml
  bundles/PersonalizationBundle/config/targeting/services.yaml
  bundles/PersonalizationBundle/doc/Development_Documentation/README.md
  bundles/PersonalizationBundle/public/js/document/areatoolbar.js
  bundles/PersonalizationBundle/src/DependencyInjection/Configuration.php
  bundles/PersonalizationBundle/src/DependencyInjection/PimcorePersonalizationExtension.php
  bundles/PersonalizationBundle/src/Targeting/EventListener/DocumentTargetGroupListener.php
  bundles/PersonalizationBundle/src/Targeting/EventListener/Frontend/FullPageCacheCookieCleanupListener.php
  bundles/PersonalizationBundle/src/Targeting/EventListener/RenderletListener.php
  bundles/PersonalizationBundle/src/Targeting/EventListener/TargetingListener.php
  bundles/PersonalizationBundle/src/Targeting/EventListener/TargetingSessionBagListener.php
  bundles/PersonalizationBundle/src/Targeting/EventListener/ToolbarListener.php
  bundles/PersonalizationBundle/src/Targeting/Service/TargetingEnableService.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement, BC-BREAK

#14784 Remove EnabledTrait
  bundles/CoreBundle/src/EventListener/Traits/EnabledTrait.php
Labels: Task

#14126 Remove SystemInfoBundle from the Core
  bundles/SystemInfoBundle/.editorconfig
  bundles/SystemInfoBundle/.gitattributes
  bundles/SystemInfoBundle/.gitignore
  bundles/SystemInfoBundle/.php_cs.dist
  bundles/SystemInfoBundle/LICENSE.md
  bundles/SystemInfoBundle/README.md
  bundles/SystemInfoBundle/SECURITY.md
  bundles/SystemInfoBundle/composer.json
  bundles/SystemInfoBundle/config/pimcore/routing.yaml
  bundles/SystemInfoBundle/config/services.yaml
  bundles/SystemInfoBundle/gpl-3.0.txt
  bundles/SystemInfoBundle/public/css/icons.css
  bundles/SystemInfoBundle/public/js/startup.js
  bundles/SystemInfoBundle/src/Controller/OpcacheController.php
  bundles/SystemInfoBundle/src/Controller/SettingsController.php
  bundles/SystemInfoBundle/src/DependencyInjection/PimcoreSystemInfoExtension.php
  bundles/SystemInfoBundle/src/PimcoreSystemInfoBundle.php
  bundles/SystemInfoBundle/translations/admin.en.yaml
  composer.json
Labels: Task

#14782 [ClassDefinition/CustomLayout] Disallow remove if definitions are not writeable
  bundles/AdminBundle/Resources/public/js/pimcore/object/class.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/CustomLayout.php
Labels: Bug

#14679 [Feature]: migrate all logs to Monolog
  bundles/AdminBundle/config/event_listeners.yaml
  bundles/AdminBundle/config/pimcore/default.yaml
  bundles/AdminBundle/config/services.yaml
  bundles/AdminBundle/src/EventListener/UsageStatisticsListener.php
  bundles/AdminBundle/src/GDPR/DataProvider/PimcoreUsers.php
  bundles/CoreBundle/config/event_listeners.yaml
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/EventListener/Frontend/RoutingListener.php
  bundles/EcommerceFrameworkBundle/src/Resources/config/order_agent.yaml
  bundles/SeoBundle/src/Redirect/RedirectHandler.php
  doc/18_Tools_and_Features/01_Versioning.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Log/Simple.php
Labels: Improvement

#14778 [Task] Moved events from `adminBundle` to `simpleBackendSearchBundle`
  bundles/AdminBundle/Event/AdminEvents.php
  bundles/SimpleBackendSearchBundle/src/Controller/SearchController.php
  bundles/SimpleBackendSearchBundle/src/Event/AdminSearchEvents.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#14709 [VideoThumbnail] fclose only if actually resource
  models/Asset/Video/Thumbnail/Processor.php
Labels: Bug

#14779 [Task] Deprecated search related admin events
  bundles/AdminBundle/Event/AdminEvents.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#14765 [Improvement]: Enhance document configs for more flexibility
  bundles/AdminBundle/public/js/pimcore/document/document.js
  bundles/AdminBundle/public/js/pimcore/document/tree.js
  bundles/AdminBundle/public/js/pimcore/helpers.js
  bundles/AdminBundle/src/Controller/Admin/IndexController.php
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  bundles/PersonalizationBundle/config/pimcore/default.yaml
  bundles/WebToPrintBundle/config/pimcore/default.yaml
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/08_Adding_Document_Types.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Routing/Dynamic/DocumentRouteHandler.php
  models/Document.php
  models/Document/Dao.php
Labels: Improvement

#14761 Deprecate StateHelperTrait
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Extension/Bundle/Traits/StateHelperTrait.php
Labels: Task

#14749 [Feature]: make configuration storage locations configurable via Pimcore's Symfony config tree
  .github/ci/files/config/system.yaml
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/ConfigurationHelper.php
  bundles/CoreBundle/src/Migrations/Version20230320110429.php
  bundles/CustomReportsBundle/src/DependencyInjection/Configuration.php
  bundles/CustomReportsBundle/src/DependencyInjection/PimcoreCustomReportsExtension.php
  bundles/CustomReportsBundle/src/Tool/Config/Dao.php
  bundles/StaticRoutesBundle/src/DependencyInjection/Configuration.php
  bundles/StaticRoutesBundle/src/DependencyInjection/PimcoreStaticRoutesExtension.php
  bundles/StaticRoutesBundle/src/Model/Staticroute/Dao.php
  bundles/WebToPrintBundle/src/Config.php
  bundles/WebToPrintBundle/src/DependencyInjection/Configuration.php
  bundles/WebToPrintBundle/src/DependencyInjection/PimcoreWebToPrintExtension.php
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Config/LocationAwareConfigRepository.php
  lib/CustomView/Config.php
  lib/Kernel.php
  lib/Model/Dao/PimcoreLocationAwareConfigDao.php
  lib/Perspective/Config.php
  models/Asset/Image/Thumbnail/Config/Dao.php
  models/Asset/Video/Thumbnail/Config/Dao.php
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
  models/Document/DocType/Dao.php
  models/Metadata/Predefined/Dao.php
  models/Property/Predefined/Dao.php
  tests/_bootstrap.php
Labels: Improvement

#14737 If low_quality_image_preview is not enabled, prevent further executio…
  lib/Maintenance/Tasks/LowQualityImagePreviewTask.php
Labels: Bug

#14740 [Messenger] Support handling failed maintenance jobs
  bundles/CoreBundle/Command/SearchBackendReindexCommand.php
  doc/Development_Documentation/01_Getting_Started/00_Installation.md
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
  models/Asset/Document.php
Labels: Bug

#14791 [Bug] Remove px in video editable progress image
  models/Document/Editable/Video.php
Labels: Bug

#14798 [CustomLayout] Use object-custom-layout-writeable setting for delete button
  bundles/AdminBundle/public/js/pimcore/object/helpers/customLayoutEditor.js
  bundles/SimpleBackendSearchBundle/src/Command/SearchBackendReindexCommand.php
  models/DataObject/ClassDefinition/CustomLayout.php
Labels: Bug

#14774 [Task] Added password length check to `checkValidity`
  models/DataObject/ClassDefinition/Data/Password.php
Labels: Task

#14793 Remove ConsoleCommandPluginTrait
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Console/ConsoleCommandPluginTrait.php
Labels: Task

#14805 Adds note about ESI & Static Page Generator in 09_Performance_Guide.md
  doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/09_Performance_Guide.md
Labels: Bug
