Repository pimcore/pimcore, pull requests merged in 2023-10, with the labels that each got.

#16009 [Documents] Image Editable - Fix version preview with non-nullable properties assigned null
  models/Document/Editable/Image.php
Labels: Bug

#15950 Adding PruningCacheItemsTask
  bundles/CoreBundle/config/maintenance.yaml
  lib/Maintenance/Tasks/PruningCacheItemsTask.php
Labels: Bug

#16043 Update screenshot with the new option for Options Source
  doc/img/dynamic_select_class.png
  doc/img/dynamic_select_service.png
Labels: Improvement

#16041 [Bug]: saving class with multiple object brick
  models/DataObject/Objectbrick.php
Labels: Bug

#16030 feat: Static page cache folder
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/19_Development_Tools_and_Details/20_Static_Page_Generator.md
  lib/Document/StaticPageGenerator.php
Labels: Improvement

#16048 Docs: add docs for import and export quantity value units
  doc/05_Objects/01_Object_Classes/01_Data_Types/55_Number_Types.md
  doc/21_Deployment/05_Deployment_Tools.md
  doc/img/classes-datatypes-number4.png
Labels: Improvement

#16012 feat: add SSI includes for maintenance job static page generation
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/19_Development_Tools_and_Details/20_Static_Page_Generator.md
  lib/Document/Renderer/DocumentRenderer.php
  lib/Http/RequestHelper.php
Labels: Improvement

#16053 Implement Asset Sanitizer Queue & Preview Check
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/04_Assets/README.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
  models/Asset/Document.php
  models/Asset/Enum/PdfScanStatus.php
  models/Element/Service.php
Labels: Improvement

#16066 [Static Page Generator] Move use_main_domain config under correct node
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/19_Development_Tools_and_Details/20_Static_Page_Generator.md
  lib/Document/StaticPageGenerator.php
Labels: Task

#16054 Add prepare guide for migrating o_ prefix data before upgrading to v11
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
Labels: Bug

#13569 [Reverse relation] Support configuration of visible fields
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
Labels: Improvement

#16072 [Elements]: Add '$params' parameter to ElementInterface::getById
  models/Element/ElementInterface.php
Labels: Improvement, Task

#16089 fix(page-factory): bug with not initalized defaultPageType
  lib/Navigation/Page.php
Labels: Bug

#16025 [Documents]: Removed the 'allowedAttributes' list from link editable
  doc/03_Documents/01_Editables/18_Link.md
  models/Document/Editable/Link.php
Labels: Improvement

#16099 Fix: add h2 - h6 in sanitizer
  .github/ci/files/config/packages/html_sanitizer.yaml
Labels: Bug

#16091 Deprecate the property Pimcore\Navigation\Page::defaultPageType
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Navigation/Page.php
Labels: Task

#16102 [Asset::create()] Prevent warning "unlink(...): No such file or directory" for importing local file as stream
  models/Asset.php
Labels: Bug

#16096 fix(models): Select - updated getDataForGrid $data parameter type
  models/DataObject/ClassDefinition/Data/Select.php
Labels: Bug

#16101 [Docs] Refactor v11.1 upgrade notes
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#16086 [HtmlSanitizer] Sanitize data only on save
  doc/03_Documents/01_Editables/40_WYSIWYG.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/Document/Editable/Wysiwyg.php
  models/Translation/Dao.php
  tests/Model/DataObject/ObjectTest.php
  tests/Unit/Translation/TranslatorTest.php
Labels: Bug

#16115 [11.1-RC1] Fix install error with maintenance mode helper when no db connection
  .github/ci/files/config/packages/test/config.yaml
  lib/Tool/MaintenanceModeHelper.php
Labels: Bug

#16122 Update PHP Stan version
  composer.json
Labels: Task

#16129 [Documents] Add type check for data before passing to sanitizer in wysiwg
  models/Document/Editable/Wysiwyg.php
Labels: Bug

#16131 [Bug]: users.lastLogin is not updated
  lib/Tool/Authentication.php
Labels: Bug

#16136 Add Missing translations for Key bindings
  bundles/ApplicationLoggerBundle/translations/admin.en.yaml
  bundles/GlossaryBundle/translations/admin.en.yaml
  bundles/SeoBundle/translations/admin.en.yaml
Labels: Bug

#16139 Test: add conflict
  composer.json
Labels: Task

#16108 Added worfklow for cloning PRs
  .github/workflows/clone-branch.yml
Labels: New Feature, Task

#16138 [Task]: Fix Sitemap doc referencing a wrong node instead of `pimcore_seo`
  doc/18_Tools_and_Features/39_Sitemaps.md
Labels: Bug

#16152 Fix typo in the docs
  doc/18_Tools_and_Features/07_Properties.md
Labels: Task

#16153 Update PR checklist after `11.1` release
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pull-request-checklist.yaml
Labels: Task

#16171 Fix: Response can't be cached
  bundles/CoreBundle/src/EventListener/Frontend/FullPageCacheListener.php
  doc/19_Development_Tools_and_Details/09_Cache/03_Full_Page_Cache.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Bug
