Repository pimcore/pimcore, pull requests merged in 2023-04, with the labels that each got.

#14829 Remove ecommerce config from core
  bundles/EcommerceFrameworkBundle/src/Resources/config/order_agent.yaml
Labels: Task

#14831 [Task]: Moved `BundleAdminSupportTrait` & `PimcoreBundleAdminSupportInterface` to `support` folder
  bundles/AdminBundle/Support/BundleAdminSupportTrait.php
  bundles/AdminBundle/Support/PimcoreBundleAdminSupportInterface.php
Labels: Task

#14792 [Improvement] Making Composer and AssetInstaller consistent when installing assets
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Composer.php
  lib/Tool/AssetsInstaller.php
Labels: Improvement

#14801 Fix wrong type hints
  lib/Navigation/Renderer/Menu.php
  lib/Navigation/Renderer/RendererInterface.php
  lib/helper-functions.php
  models/DataObject/Service.php
Labels: Bug

#14833 Removed leftover file in Personalization bundle
  bundles/PersonalizationBundle/tests/Unit.suite.yml~
Labels: Bug

#14807 [Task] Deprecated several services
  bundles/AdminBundle/Resources/config/aliases.yaml
  bundles/AdminBundle/Resources/config/event_listeners.yaml
  bundles/AdminBundle/Resources/config/serializer.yaml
  bundles/CoreBundle/Resources/config/aliases.yaml
  bundles/CoreBundle/Resources/config/documents.yaml
  bundles/CoreBundle/Resources/config/templating_twig.yaml
Labels: Task

#14766 [Task]: Check and remove class_aliases in 11.x
  bundles/ApplicationLoggerBundle/src/ApplicationLogger.php
  bundles/ApplicationLoggerBundle/src/Controller/LogController.php
  bundles/ApplicationLoggerBundle/src/FileObject.php
  bundles/ApplicationLoggerBundle/src/Handler/ApplicationLoggerDb.php
  bundles/ApplicationLoggerBundle/src/Maintenance/LogArchiveTask.php
  bundles/ApplicationLoggerBundle/src/Maintenance/LogMailMaintenanceTask.php
  bundles/ApplicationLoggerBundle/src/Processor/ApplicationLoggerProcessor.php
  bundles/CoreBundle/src/Migrations/Version20211209131141.php
  bundles/CoreBundle/src/Migrations/Version20220908113752.php
  models/Version.php
  phpstan-bootstrap.php
Labels: Task

#14844 [Improvement]: Make store values configurable docTypes.js
  bundles/AdminBundle/public/js/pimcore/settings/docTypes.js
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/WebToPrintBundle/config/pimcore/default.yaml
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#14836 [Assets] Generate checksum on asset save
  bundles/CoreBundle/src/Command/Asset/GenerateChecksumCommand.php
  composer.json
  models/Asset.php
  models/Asset/Image/Thumbnail/Processor.php
  tests/Model/Asset/AssetThumbnailCacheTest.php
Labels: Improvement

#14854 [Task] Reverted service deprecation
  bundles/AdminBundle/Resources/config/event_listeners.yaml
Labels: Task

#14661 [Improvement]: Rename "Master" to "Main" or similar in all translations and in code
  bundles/AdminBundle/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/public/js/pimcore/settings/email/blocklist.js
  bundles/AdminBundle/src/Controller/Admin/DataObject/ClassController.php
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectController.php
  bundles/AdminBundle/src/Controller/Admin/Document/DocumentController.php
  bundles/AdminBundle/src/Controller/Admin/Document/DocumentControllerBase.php
  bundles/AdminBundle/src/Controller/Admin/Document/PageController.php
  bundles/AdminBundle/src/Controller/Admin/Document/SnippetController.php
  bundles/AdminBundle/src/Controller/Admin/EmailController.php
  bundles/AdminBundle/translations/admin.en.yaml
  bundles/AdminBundle/webpack.config.js
  bundles/CoreBundle/src/Migrations/Version20230202152342.php
  bundles/WebToPrintBundle/src/Controller/Document/PrintpageControllerBase.php
  bundles/WebToPrintBundle/src/Resources/install/install.sql
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/02_Nginx_Configuration.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/Service.php
  models/Document/PageSnippet.php
  models/Tool/Email/Blocklist/Dao.php
Labels: Improvement

#14845 WYSIWYG 11.x follow up
  bundles/AdminBundle/public/js/pimcore/document/editables/wysiwyg.js
  bundles/AdminBundle/public/js/pimcore/object/tags/wysiwyg.js
  bundles/AdminBundle/public/js/pimcore/settings/translationEditor.js
  bundles/AdminBundle/public/js/pimcore/startup.js
  bundles/TinymceBundle/public/js/editor.js
  doc/03_Documents/01_Editables/40_WYSIWYG.md
  doc/03_Documents/01_Editables/README.md
Labels: Task

#14855 Remove unnecessary save in GenerateChecksumCommand
  bundles/CoreBundle/src/Command/Asset/GenerateChecksumCommand.php
Labels: Task

#14839 [Task]: Prepare WebToPrint Bundle for extraction
  bundles/WebToPrintBundle/.editorconfig
  bundles/WebToPrintBundle/.gitattributes
  bundles/WebToPrintBundle/.gitignore
  bundles/WebToPrintBundle/CONTRIBUTING.md
  bundles/WebToPrintBundle/LICENSE.md
  bundles/WebToPrintBundle/README.md
  bundles/WebToPrintBundle/SECURITY.md
  bundles/WebToPrintBundle/composer.json
  bundles/WebToPrintBundle/doc/01_Print_Documents.md
  bundles/WebToPrintBundle/doc/90_Web2Print_Extending_Config_for_PDFX_conformance.md
  bundles/WebToPrintBundle/doc/img/configs.jpg
  bundles/WebToPrintBundle/doc/img/printdocuments_editmode_preview.png
  bundles/WebToPrintBundle/doc/img/printdocuments_flow.png
  bundles/WebToPrintBundle/doc/img/printdocuments_printcontainers_tree.png
  bundles/WebToPrintBundle/doc/img/printdocuments_printpages_menu.png
  bundles/WebToPrintBundle/gpl-3.0.txt
  doc/03_Documents/README.md
  doc/18_Tools_and_Features/30_Rendering_PDFs.md
  doc/img/printdocuments_settings.png
Labels: Task

#14856 composer.json: Remove unnecessary dependencies
  composer.json
Labels: Task

#14830 Task: Remove `symfony/form` requirement from Core
  .github/ci/scripts/symfony-require-dev.sh
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#14797 [Task] Cleanup yaml files
  .github/ci/files/config/services.yaml
  bundles/AdminBundle/config/aliases.yaml
  bundles/AdminBundle/config/event_listeners.yaml
  bundles/AdminBundle/config/export.yaml
  bundles/AdminBundle/config/pimcore/default.yaml
  bundles/AdminBundle/config/pimcore/two_factor_authentication.yaml
  bundles/AdminBundle/config/security_services.yaml
  bundles/AdminBundle/config/serializer.yaml
  bundles/AdminBundle/config/services.yaml
  bundles/AdminBundle/src/DependencyInjection/PimcoreAdminExtension.php
  bundles/ApplicationLoggerBundle/config/services.yaml
  bundles/CoreBundle/config/aliases.yaml
  bundles/CoreBundle/config/argument_resolvers.yaml
  bundles/CoreBundle/config/class_builder.yaml
  bundles/CoreBundle/config/class_resolvers.yaml
  bundles/CoreBundle/config/documents.yaml
  bundles/CoreBundle/config/event_listeners.yaml
  bundles/CoreBundle/config/extensions.yaml
  bundles/CoreBundle/config/implementation_factories.yaml
  bundles/CoreBundle/config/marshaller.yaml
  bundles/CoreBundle/config/migrations.yaml
  bundles/CoreBundle/config/profiler.yaml
  bundles/CoreBundle/config/services.yaml
  bundles/CoreBundle/config/services_routing.yaml
  bundles/CoreBundle/config/services_symfony_workflow.yaml
  bundles/CoreBundle/config/services_workflow.yaml
  bundles/CoreBundle/config/templating.yaml
  bundles/CoreBundle/config/templating_twig.yaml
  bundles/CustomReportsBundle/config/services.yaml
  bundles/GlossaryBundle/config/services.yaml
  bundles/InstallBundle/config/services.yaml
  bundles/SeoBundle/config/event_listeners.yaml
  bundles/SeoBundle/config/maintenance.yaml
  bundles/SeoBundle/config/redirect_services.yaml
  bundles/SeoBundle/config/services.yaml
  bundles/SeoBundle/config/sitemap_services.yaml
  bundles/SimpleBackendSearchBundle/config/services.yaml
  bundles/StaticRoutesBundle/config/services.yaml
  bundles/TinymceBundle/config/services.yaml
  bundles/UuidBundle/config/services.yaml
  bundles/WebToPrintBundle/config/services.yaml
  bundles/WordExportBundle/config/services.yaml
  bundles/XliffBundle/config/services.yaml
  doc/26_Best_Practice/60_Modifying_Permissions_based_on_Object_Data.md
Labels: Task

#14747 [Task] Cleanup `Pimcore\File`
  bundles/AdminBundle/src/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/src/Controller/Admin/MiscController.php
  bundles/AdminBundle/src/Controller/Admin/SettingsController.php
  bundles/AdminBundle/src/Controller/Admin/TranslationController.php
  bundles/AdminBundle/src/Helper/Dashboard.php
  bundles/CoreBundle/src/Controller/PublicServicesController.php
  bundles/InstallBundle/src/SystemConfig/ConfigWriter.php
  bundles/WordExportBundle/src/Controller/TranslationController.php
  bundles/XliffBundle/src/ExportService/Exporter/Xliff12Exporter.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Config.php
  lib/Config/LocationAwareConfigRepository.php
  lib/DataObject/ClassBuilder/PHPClassDumper.php
  lib/DataObject/ClassBuilder/PHPFieldCollectionClassDumper.php
  lib/DataObject/ClassBuilder/PHPObjectBrickClassDumper.php
  lib/DataObject/ClassBuilder/PHPObjectBrickContainerClassDumper.php
  lib/Document/Adapter/Ghostscript.php
  lib/Document/Adapter/LibreOffice.php
  lib/File.php
  lib/Helper/TemporaryFileHelperTrait.php
  lib/Image/Adapter/GD.php
  lib/Image/Adapter/Imagick.php
  lib/Image/Optimizer.php
  lib/Pimcore.php
  lib/Tool/Requirements.php
  lib/Twig/Extension/HelpersExtension.php
  lib/helper-functions.php
  models/Asset.php
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Service.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
  models/Asset/Video.php
  models/Asset/Video/Thumbnail/Processor.php
  models/Asset/WebDAV/Service.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
  models/Document/Service.php
  models/Element/AdminStyle.php
  models/Element/Service.php
  models/Translation.php
Labels: Task

#14852 Readd the document types to context menu for web2print
  bundles/WebToPrintBundle/public/js/startup.js
  bundles/WebToPrintBundle/src/Controller/Document/PrintpageControllerBase.php
  bundles/WebToPrintBundle/src/Installer.php
Labels: Task

#14866 [Task]: Fix Web2Print Doc Type regression
  bundles/WebToPrintBundle/src/Controller/Document/PrintpageControllerBase.php
Labels: Task

#14851 Ensure leading slashes
  models/DataObject/ClassDefinition/Data/Extension/Relation.php
Labels: Bug

#14864 [Task] Add bc layer for contentMasterDocumentId/contentMainDocumentId property
  models/Document/PageSnippet.php
Labels: Task

#14875 Improve Configuration Storage Locations
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/ConfigurationHelper.php
  doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
  lib/Config/LocationAwareConfigRepository.php
  lib/Kernel.php
Labels: Improvement

#14865 Refactor Console::getPhpCli to find executable
  lib/Tool/Console.php
Labels: Bug

#14885 Fix Routing issue - re-add doctrine/annotations required for fosjsrouting
  composer.json
Labels: Bug

#14877 Removed facedetect support
  bundles/AdminBundle/public/css/admin.css
  bundles/AdminBundle/public/css/icons.css
  bundles/AdminBundle/public/js/pimcore/asset/image.js
  bundles/AdminBundle/src/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/translations/admin.en.yaml
  bundles/CoreBundle/src/Command/Asset/RemoveCustomSettingCommand.php
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/23_Installation_and_Upgrade/01_System_Requirements.md
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
  lib/Tool/Requirements.php
  models/Asset/Image.php
Labels: Task, BC-BREAK

#14890 System requirements check: removed mysqli check
  lib/Tool/Requirements.php
Labels: Task

#14896 [Bug] Fixed loading class during classes rebuild command
  models/DataObject/ClassDefinition/Data/Extension/Relation.php
Labels: Bug

#14899 [Task] Moved `BundleManagerEvents` to AdminBundle
  bundles/AdminBundle/src/Event/BundleManagerEvents.php
  bundles/TinymceBundle/README.md
  doc/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/13_Loading_Admin_UI_Assets.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  doc/26_Best_Practice/71_Style_Backend_Depending_On_App-Env.md
  lib/Extension/Bundle/PimcoreBundleManager.php
Labels: Task

#14889 [Improvement]: Add read target to config location
  bundles/CoreBundle/src/DependencyInjection/ConfigurationHelper.php
  bundles/CustomReportsBundle/src/DependencyInjection/PimcoreCustomReportsExtension.php
  bundles/StaticRoutesBundle/src/DependencyInjection/PimcoreStaticRoutesExtension.php
  doc/21_Deployment/03_Configuration_Environments.md
  lib/Config/LocationAwareConfigRepository.php
  lib/Kernel.php
Labels: Improvement

#14903 [Task] Added migration to resave `classes`, `fieldCollections`, `objectBricks` and `customLayouts`
  bundles/CoreBundle/src/Migrations/Version20230412105530.php
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
Labels: Task

#14872 [Task] Add preparation for changes regarding system settings
  bundles/AdminBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/Configuration.php
  bundles/CoreBundle/DependencyInjection/ConfigurationHelper.php
  doc/Development_Documentation/23_Installation_and_Upgrade/07_Updating_Pimcore/11_Preparing_for_V11.md
Labels: Task

#14906 [Task] Removed wrongly merged deprecations
  bundles/AdminBundle/config/serializer.yaml
Labels: Task

#14867 [System Settings] Use LocationAwareConfigRepository
  .github/ci/files/config/config.yaml
  .github/ci/files/config/system.yaml
  bundles/AdminBundle/config/services.yaml
  bundles/AdminBundle/public/css/icons.css
  bundles/AdminBundle/public/js/pimcore/layout/toolbar.js
  bundles/AdminBundle/public/js/pimcore/settings/system.js
  bundles/AdminBundle/public/js/pimcore/settings/systemAppearance.js
  bundles/AdminBundle/src/Controller/Admin/SettingsController.php
  bundles/AdminBundle/src/DependencyInjection/PimcoreAdminExtension.php
  bundles/AdminBundle/src/Helper/SystemConfig.php
  bundles/AdminBundle/src/Perspective/Config.php
  bundles/AdminBundle/src/System/AdminConfig.php
  bundles/AdminBundle/src/System/Config.php
  bundles/AdminBundle/templates/admin/index/index.html.twig
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/ConfigurationHelper.php
  bundles/CoreBundle/src/Migrations/Version20230405162853.php
  bundles/InstallBundle/src/Command/InstallCommand.php
  bundles/InstallBundle/src/Installer.php
  bundles/InstallBundle/src/SystemConfig/ConfigWriter.php
  doc/21_Deployment/03_Configuration_Environments.md
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/12_V10_to_V11.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Kernel.php
  lib/Mail.php
  lib/Mail/Plugins/RedirectingPlugin.php
  lib/Tool.php
  models/Asset.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/Concrete.php
  models/Document.php
  models/Document/PageSnippet.php
  models/Translation.php
  tests/Model/DataType/LocalizedFieldTest.php
  tests/Model/Inheritance/LocalizedFieldTest.php
  tests/Support/Helper/AbstractDefinitionHelper.php
  tests/Unit/Mail/MailTest.php
Labels: Improvement, BC-BREAK

#14910 Unmark AdminBundle internal
  bundles/AdminBundle/src/PimcoreAdminBundle.php
Labels: Task

#14921 [Bug]: Color branding for login page not working
  .github/ci/files/config/config.yaml
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/InstallBundle/src/Installer.php
  bundles/InstallBundle/src/SystemConfig/ConfigWriter.php
  lib/Cache/Symfony/CacheClearer.php
  lib/Mail.php
  tests/Support/Helper/AbstractDefinitionHelper.php
  tests/Support/Resources/system_settings.json
  tests/Unit/Mail/MailTest.php
Labels: Bug

#14923 [Task]: Clean up PDFReactor path exclusion from Phpstan Neon
  phpstan-parameters.neon
Labels: Task

#14938 Remove en.json
  bundles/CoreBundle/Resources/translations/en.json
Labels: Bug

#14937 [Security] Fixed xss in `quantity values` panel
  bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js
  models/DataObject/QuantityValue/Unit.php
Labels: Security

#14940 [Task]: Deprecate system settings config
  bundles/CoreBundle/DependencyInjection/Configuration.php
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#14825 Security fix in Properties Parameter
  bundles/AdminBundle/Resources/public/js/pimcore/document/editables/link.js
Labels: Security

#14933 [Security] XSS in Classification Store of Data Objects module
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/collectionsPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/groupsPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/propertiesPanel.js
  lib/Security/SecurityHelper.php
Labels: Security

#14942 [Docs] Add Installation Process to Core Bundles #172
  doc/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
  doc/02_MVC/04_Routing_and_URLs/04_Redirects.md
  doc/18_Tools_and_Features/17_Application_Logger.md
  doc/18_Tools_and_Features/21_Glossary.md
  doc/18_Tools_and_Features/29_Custom_Reports.md
  doc/18_Tools_and_Features/38_Robots.txt.md
  doc/18_Tools_and_Features/39_Sitemaps.md
Labels: Task

#14941 [Security] Fixed sql injection in `AssetController`
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
Labels: Security

#14959 [Security] Admin Authenticated Arbitrary File Read
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
Labels: Security

#14947 [Security] Fix xss in static routes panel
  bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js
  lib/Security/SecurityHelper.php
  models/Staticroute.php
Labels: Security

#14958 [Security] Admin Authenticated Arbitrary JavaScript-CSS File Read
  bundles/AdminBundle/Controller/Admin/MiscController.php
Labels: Security

#14928 Refactor: read and write_target
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/ConfigurationHelper.php
  lib/Config/LocationAwareConfigRepository.php
  lib/Kernel.php
Labels: Improvement

#14943 [Security] Fix xss in predefined properties panel
  bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js
  models/Property/Predefined.php
Labels: Security

#14969 Fix XSS in name parameter of Pricing Rules
  bundles/EcommerceFrameworkBundle/PricingManager/Rule.php
  bundles/EcommerceFrameworkBundle/Resources/public/js/pricing/config/panel.js
Labels: Security

#14968 [Security] Fix Admin Translation Export SQL Injection
  bundles/AdminBundle/Controller/Admin/TranslationController.php
Labels: Security

#14952 [Security] Fix sql injection in translation api
  bundles/AdminBundle/Controller/Admin/TranslationController.php
Labels: Security

#14960 [Task]: Follow-up Gotenberg as LibreOffice Adapter
  lib/Document/Adapter/Gotenberg.php
Labels: Task

#14964 Fix: remove getStringWithoutControlChars
  bundles/AdminBundle/Resources/public/js/pimcore/helpers.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/collectionsPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/groupsPanel.js
  bundles/AdminBundle/Resources/public/js/pimcore/object/classificationstore/propertiesPanel.js
Labels: Security

#14953 [Task]: Move SystemSettingsConfig from Admin Bundle back to the Core
  bundles/CoreBundle/config/services.yaml
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/EventListener/Frontend/RoutingListener.php
  doc/18_Tools_and_Features/25_System_Settings.md
  doc/18_Tools_and_Features/26_Appearance_and_Branding.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Event/SystemEvents.php
  lib/Helper/SystemConfig.php
  lib/Mail/Plugins/RedirectingPlugin.php
  lib/SystemSettingsConfig.php
  lib/Tool.php
  models/Asset.php
  models/DataObject/Concrete.php
  models/Document.php
  models/Document/PageSnippet.php
  models/Translation.php
  tests/Model/DataType/LocalizedFieldTest.php
  tests/Model/Inheritance/LocalizedFieldTest.php
  tests/Support/Resources/system_settings.json
Labels: Task

#14975 [Security] Fixed xss on login page
  bundles/AdminBundle/Controller/Admin/LoginController.php
Labels: Security

#14970 Fix: Use PIMCORE_WEB_ROOT
  bundles/AdminBundle/Controller/Admin/MiscController.php
Labels: Security

#14974 [Security] Admin Authenticated Arbitrary File Read
  bundles/AdminBundle/Controller/Admin/Asset/AssetController.php
  bundles/AdminBundle/Resources/public/js/pimcore/asset/tree.js
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Security

#14996 [Task] Merged `10.6` upgrade notes
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#14991 Follow up to #14918
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Extension/Bundle/BundleAdminClassicTrait.php
Labels: Task

#15002 [Task]: Remove system/admin settings remnants
  bundles/InstallBundle/src/Command/InstallCommand.php
  lib/Config.php
  lib/Config/LocationAwareConfigRepository.php
  models/User.php
Labels: Task

#14955 [Security] Stored cross site scripting vulnerability in Save grid option in pimcore dashboard
  bundles/AdminBundle/Controller/Admin/DataObject/DataObjectHelperController.php
  bundles/AdminBundle/Resources/public/js/pimcore/element/helpers/gridColumnConfig.js
  lib/Security/SecurityHelper.php
Labels: Security

#15010 Move BundleAdminClassicTrait to correct path
  lib/Extension/Bundle/Traits/BundleAdminClassicTrait.php
Labels: Task

#14909 Bugfix/null classification store groups
  models/DataObject/Classificationstore.php
Labels: Task

#15013 [Task]: Deprecate import server files
  bundles/CoreBundle/Resources/translations/en.json
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15014 [Bug]: Admin throws SessionBagInterface "pimcore_admin" is not registered
  lib/Config.php
  lib/Event/SystemEvents.php
Labels: Bug

#14986 [Security] Fix xss in link editable
  doc/Development_Documentation/03_Documents/01_Editables/18_Link.md
  doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Security/SecurityHelper.php
  models/Document/Editable/Link.php
Labels: Security

#15007 Fix Xss in name field of custom reports
  bundles/AdminBundle/Controller/Reports/CustomReportController.php
  bundles/AdminBundle/Resources/public/js/pimcore/report/custom/panel.js
Labels: Security

#14972 [Security] Fix Admin Search Find API SQL Injection
  bundles/AdminBundle/Controller/Searchadmin/SearchController.php
Labels: Security

#15036 Follow up of pimcore/pimcore#14953
  lib/Helper/SystemConfig.php
  lib/SystemSettingsConfig.php
Labels: Task

#15001 [Task] Removed deprecated `attributes` data from link editable
  bundles/CoreBundle/src/Migrations/Version20230424084415.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Document/Editable/Link.php
Labels: Task

#15041 [Task] Move ImageChart to GoogleMarketingBundle
  lib/Helper/ImageChart.php
Labels: Task

#15042 [Docs] Fix typo for adding layout type
  doc/Development_Documentation/20_Extending_Pimcore/13_Bundle_Developers_Guide/12_Adding_Object_ Layout_types.md
Labels: Bug

#15038 [Task] Added html sanitizer to translations
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/DependencyInjection/Compiler/TranslationSanitizerPass.php
  bundles/CoreBundle/src/PimcoreCoreBundle.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Tool/Text.php
  models/Translation.php
  models/Translation/Dao.php
Labels: Task

#14945 Remove deprecated code
  bundles/CustomReportsBundle/src/Tool/Config.php
  bundles/StaticRoutesBundle/src/Model/Staticroute/Dao.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Tool/Console.php
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
Labels: Task, BC-BREAK

#15047 Revert migration 20230223101848 to content of 10.6
  bundles/CoreBundle/src/Migrations/Version20230223101848.php
Labels: Bug

#15018 Fix migration error without report settings in db
  bundles/CoreBundle/src/Migrations/Version20230202152342.php
Labels: Bug

#15050 [Task] Adding missing translation key
  bundles/ApplicationLoggerBundle/src/Installer.php
  bundles/XliffBundle/translations/admin.en.yaml
Labels: Task

#15054 [Task] Remove system_appreance_settings from core
  bundles/InstallBundle/src/Installer.php
Labels: Task
