Repository pimcore/pimcore, pull requests merged in 2024-05, with the labels that each got.

#16971 Fix database error when filtering in localized field in the object search
  bundles/SimpleBackendSearchBundle/src/Controller/SearchController.php
Labels: Pimcore:ToDo

#17006 [Bug]: Fix problem when switching language in grid view with localizedfields
  models/DataObject/Service.php
Labels: Bug, Pimcore:ToDo

#16975 [Bug]: Fix wysiwyg max character, soften the warning and add visual helper
  bundles/TinymceBundle/public/js/editor.js
  bundles/TinymceBundle/translations/admin.en.yaml
Labels: Bug, Pimcore:ToDo

#16871 [Improvement] Prevent db errors on index updates on classes rebuild
  models/DataObject/ClassDefinition/Helper/Dao.php
Labels: Improvement, Pimcore:ToDo

#17010 Fix scaling factor can be null
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#17018 [Bug] Fix image preview error if format is source for video and document
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Video/ImageThumbnail.php
Labels: Bug

#16970 [SimpleBackendSearchBundle] Fix Data setters (nullable params)
  bundles/SimpleBackendSearchBundle/src/Model/Search/Backend/Data.php
Labels: Bug, Pimcore:ToDo

#17035 Make allowed thumbnail formats case-insensitive
  models/Asset/Image/Thumbnail/Config.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#17039 [Bug] Fix thumbnail generation if asset or config is null
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Image/Thumbnail.php
  models/Asset/Thumbnail/ImageThumbnailTrait.php
  models/Asset/Video/ImageThumbnail.php
Labels: Bug

#17040 Add tinyMce default config docs
  bundles/TinymceBundle/README.md
Labels: Task

#17005 [Assets] Use symfony/mime to retrieve asset MIME type
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
Labels: Pimcore:ToDo

#16596 Exclude __rawRelationData from being serialized + getBlockedVars() timizations
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/DataObject/Concrete.php
  models/Document.php
  models/Element/AbstractElement.php
Labels: Bug, Pimcore:ToDo

#16644 DocumentRenderer: setCurrentSite to generate correct path of document in static page generator
  lib/Document/Renderer/DocumentRenderer.php
Labels: Pimcore:ToDo

#17054 [Bug]: Fix `pimcore_relations` editable displaying folders as variants
  models/Document/Editable/Relations.php
Labels: Bug, Pimcore:ToDo

#17059 Fix getLatestVersion() method php docs
  models/Asset.php
  models/DataObject/Concrete.php
  models/Document/PageSnippet.php
  models/Element/Traits/VersionDaoTrait.php
Labels: Bug, Pimcore:ToDo

#17023 [Improvement] Add Gotenberg support to define screenshot size
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Image/HtmlToImage.php
Labels: Improvement, Pimcore:ToDo

#17027 Asset: hasMetaData must be convert to bool in Dao
  models/Asset/Dao.php
Labels: Pimcore:ToDo

#17067 [Bug]: Fix Application logger filter datetime locale in US format
  bundles/ApplicationLoggerBundle/public/js/log/admin.js
Labels: Bug, Pimcore:ToDo

#17074 [Improvement]: Prepare for Doctrine v4
  bundles/CoreBundle/src/Migrations/Version20201008101817.php
  bundles/CoreBundle/src/Migrations/Version20210412112812.php
  bundles/CoreBundle/src/Migrations/Version20211018104331.php
  bundles/CoreBundle/src/Migrations/Version20220120162621.php
  bundles/CoreBundle/src/Migrations/Version20230616085142.php
  bundles/SeoBundle/src/Model/Redirect/Dao.php
  bundles/UuidBundle/src/Model/Tool/UUID/Dao.php
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Model/Listing/AbstractListing.php
  lib/Model/Listing/Dao/QueryBuilderHelperTrait.php
  models/DataObject/Classificationstore/Dao.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Listing/Dao.php
  models/DataObject/QuantityValue/Unit/Dao.php
  models/Element/Traits/ScheduledTasksDaoTrait.php
  models/Translation/Listing/Dao.php
  tests/Support/Helper/Pimcore.php
Labels: Improvement, Pimcore:ToDo

#16972 Fix: Video data type field getter throws exception on poster image wi…
  models/DataObject/Data/Video.php
Labels: Bug, Pimcore:ToDo

#17044 [Task]: PhpStan Version Upgrade May
  composer.json
  lib/Helper/Mail.php
Labels: Task, Pimcore:ToDo

#17094 [Docs] Fix typo in 01_Versioning.md
  doc/18_Tools_and_Features/01_Versioning.md
Labels: Task

#17091 [Improvement]: Remove unused `phpoffice/phpspreadsheet`
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#16482 calculate delta for relations in every relational field-type to prevent deadlock
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/Concrete.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/Fieldcollection/Dao.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
  models/DataObject/Traits/ContextPersistenceTrait.php
  tests/Model/Relations/ObjectbrickTest.php
Labels: Pimcore:ToDo, Pimcore:Priority

#17107 NotesAwareTrait: Add missing return type for getLabel()
  lib/Workflow/Notes/NotesAwareTrait.php
Labels: Task
