Repository pimcore/pimcore, pull requests merged in 2024-11, with the labels that each got.

#17727 Update 01_Image_Thumbnails.md
  doc/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
Labels: Improvement

#17794 [Bug]: Fix classification store group table type with no width issue
  models/DataObject/ClassDefinition/Data/Table.php
Labels: Bug, Pimcore:ToDo

#17789 [Improvement]: Add common search interface
  lib/SearchClient/Exception/ClientException.php
  lib/SearchClient/SearchClientInterface.php
Labels: Improvement, Pimcore:ToDo

#17792 Introduce new block syntax
  doc/03_Documents/01_Editables/06_Block.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Twig/Extension/DocumentEditableExtension.php
  lib/Twig/Node/BlockNode.php
  lib/Twig/Node/ManualBlockNode.php
  lib/Twig/Options/BlockOptions.php
  lib/Twig/Options/HasBlockOptionsTrait.php
  lib/Twig/TokenParser/BlockParser.php
  lib/Twig/TokenParser/ManualBlockParser.php
  tests/Unit/Twig/Options/BlockOptionsTest.php
Labels: Improvement, Pimcore:ToDo

#17806 [Docs]: Fix link about Cron Job to right paragraph
  doc/20_Extending_Pimcore/16_Maintenance_Tasks.md
Labels: Task, Pimcore:ToDo

#17793 Optimize Asset Document ImageThumbnail generation
  models/Asset/Document/ImageThumbnail.php
Labels: Pimcore:ToDo

#17804 [Bug]: Error from Migrations - call on null $this->container
  bundles/CoreBundle/src/Migrations/Version20231127124738.php
Labels: Bug, Pimcore:ToDo

#17807 Image processing: possibility to configure the image adapter
  bundles/CoreBundle/src/DependencyInjection/Compiler/ImageAdapterAliasPass.php
  bundles/CoreBundle/src/PimcoreCoreBundle.php
  doc/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  lib/Image.php
  lib/Image/Adapter.php
  lib/Image/AdapterInterface.php
Labels: Improvement, Pimcore:ToDo

#17815 Add brickprefix to avoid ambiguity
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
Labels: Bug, Pimcore:ToDo

#17832 [docs] fix block syntax
  doc/02_MVC/02_Template/README.md
Labels: Task

#17805 Fix: Documents are not copied completely
  models/DataObject/AbstractObject.php
  models/Element/AbstractElement.php
  models/Element/Service.php
  tests/Model/Asset/AssetTest.php
  tests/Model/DataObject/ObjectTest.php
  tests/Model/Document/DocumentTest.php
  tests/Service/Element/ServiceTest.php
Labels: Pimcore:ToDo

#17839 Add fix for phpredis BC break by using a newer symfony cache version
  composer.json
Labels: Bug

#17802 PhpStan Version Upgrade November
  composer.json
  phpstan-baseline.neon
Labels: Task, Pimcore:ToDo

#17834 Index for workspaces permission list
  bundles/CoreBundle/src/Migrations/Version20241114142759.php
  bundles/InstallBundle/dump/install.sql
Labels: Improvement

#17714 [Bug] Get values must be static
  models/DataObject/SelectOptions/Traits/EnumGetValuesTrait.php
  models/DataObject/SelectOptionsInterface.php
Labels: Bug, Pimcore:ToDo

#17829 [Bug] Missing dependencies for Generic execution engine bundle
  composer.json
  doc/19_Development_Tools_and_Details/08_Generic_Execution_Engine/README.md
Labels: Bug, Pimcore:ToDo

#17848 Fix getDefaultValue example
  doc/05_Objects/01_Object_Classes/01_Data_Types/30_Dynamic_Select_Types.md
Labels: Pimcore:ToDo

#17856 [Task]: Followup #17344, replace index name with columns
  models/DataObject/Data/AbstractMetadata/Dao.php
  models/DataObject/Data/ElementMetadata/Dao.php
  models/DataObject/Data/ObjectMetadata/Dao.php
Labels: Task, Pimcore:ToDo

#17847 Improvement index for workspaces permission list
  bundles/CoreBundle/src/Migrations/Version20241114142759.php
  bundles/InstallBundle/dump/install.sql
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement, Pimcore:ToDo

#17799 Impovement #17696 Upgrade dependencies where possible without BC break
  composer.json
  tests/Model/DataType/ClassificationStore/AbstractClassificationStoreTest.php
  tests/Support/Helper/DataType/TestDataHelper.php
  tests/Support/Helper/Model.php
  tests/Support/Test/DataType/AbstractDataTypeTestCase.php
  tests/Twig/PimcoreDateTest.php
Labels: Pimcore:ToDo

#17762 Fix return type on getDataForQueryResource for CalculatedValue
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
Labels: Pimcore:ToDo

#17817 fix: add `id` attribute to valid elements
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/TinymceBundle/public/js/editor.js
Labels: Bug, Pimcore:ToDo

#17851 Fix: Elements deleted by Scheduled Tasks don't appear in Recyclebin
  lib/Maintenance/Tasks/ScheduledTasksTask.php
Labels: Bug, Pimcore:ToDo

#17835 [Improvement]: Added possibility to configure which metadata to be used as `alt`,`copyright`,`title`
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset/Image/Thumbnail.php
Labels: Improvement, Pimcore:ToDo

#17859 [Doc]: Improve docs about config location button being grayed out
  doc/21_Deployment/03_Configuration_Environments.md
Labels: Task, Pimcore:ToDo

#17860 [Improvement]: Add checks for setting QuantityValue values and units
  models/DataObject/Data/AbstractQuantityValue.php
  tests/Model/DataObject/ObjectTest.php
Labels: Improvement, Pimcore:ToDo

#17876 [Docs]: Add upgrade note about `QuantityValue` invalid unit
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, Pimcore:ToDo

#17864 [Improvement]: Upgrade dependencies
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement, Pimcore:ToDo
