Repository pimcore/pimcore, pull requests merged in 2024-04, with the labels that each got.

#16887 PhpStan Version Upgrade March
  composer.json
Labels: Task

#16881 Fix Multiselect: Version Preview and Version Difference display fix
  models/DataObject/ClassDefinition/Data/Multiselect.php
Labels: Bug

#16886 [Bug]: Fix file format icon by lowercasing it
  models/Element/AdminStyle.php
Labels: Bug

#16895 Add bin/console to upgrade hint
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#15383 [Feature] Add definitionModificationDate to classes table to optimize rebuild command performance
  bundles/CoreBundle/src/Command/ClassesRebuildCommand.php
  bundles/CoreBundle/src/Migrations/Version20230615103905.php
  bundles/InstallBundle/dump/install.sql
  lib/Model/DataObject/ClassDefinition/ClassDefinitionManager.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Dao.php
Labels: Pimcore:ToDo

#16884 Fix property changes are not a recognised
  models/Property.php
Labels: Bug

#16844 Added dirty state for the published property of Concretes and Documents
  models/DataObject/Concrete.php
  models/Document.php
Labels: Improvement, Pimcore:ToDo

#16931 [Docs] Update Quantity Value Conversion Docs
  doc/05_Objects/01_Object_Classes/01_Data_Types/55_Number_Types.md
Labels: Bug

#16933 Removed sync releases workflow
  .github/workflows/sync-releases.yml
Labels: Pimcore:ToDo

#16952 Fix: TinyMCE doesn't work
  bundles/TinymceBundle/public/assets/tinymce.js
  bundles/TinymceBundle/public/build/tinymce/271.js
  bundles/TinymceBundle/public/build/tinymce/328.js
  bundles/TinymceBundle/public/build/tinymce/999.js
  bundles/TinymceBundle/public/build/tinymce/entrypoints.json
  bundles/TinymceBundle/public/build/tinymce/manifest.json
  bundles/TinymceBundle/public/build/tinymce/tinymce.js
  bundles/TinymceBundle/public/js/editor.js
Labels: Bug

#16798 Allow compressed database dumps in the installer
  bundles/InstallBundle/src/Installer.php
Labels: Improvement, Pimcore:ToDo

#16950 [Command "pimcore:locale:delete-unused-tables"] Do not delete localized query tables and views with lower_case_table_names = 1
  bundles/CoreBundle/src/Command/DeleteUnusedLocaleDataCommand.php
Labels: Bug

#16949 fix #16948 / Additional Type Support External Image for Deep-Copy (creating memory issues)
  models/DataObject/Data/BlockElement.php
Labels: Bug

#16677 [Docs]: Add instructions about TinyMCE bundle
  bundles/TinymceBundle/README.md
  doc/03_Documents/01_Editables/40_WYSIWYG.md
Labels: Task, Pimcore:ToDo

#16914 [Recyclebin] Fix typo in Item:getStorageFile() method name
  models/Element/Recyclebin/Item.php
  tests/Model/Element/RecyclebinTest.php
Labels: Pimcore:ToDo

#16967 Fix: CalculatedField Expression in Objects should support int as well
  models/DataObject/Service.php
Labels: Bug

#16885 Add RabbitMQ as recommended system-requirement
  doc/01_Getting_Started/02_Advanced_Installation_Topics/01_Symfony_Messenger.md
  doc/23_Installation_and_Upgrade/01_System_Requirements.md
Labels: Pimcore:ToDo

#16958 Conflict with Twig >= 3.9.0
  composer.json
Labels: Bug, Pimcore:ToDo

#16976 Conflict with Twig >= 3.9.0
  composer.json
Labels: Bug, Pimcore:ToDo

#16937 PhpStan Version Upgrade April
  composer.json
Labels: Task

#16769 [Bug, EC]: Fix Sorter of classification store group collection
  lib/DataObject/FielddefinitionMarshaller/Traits/RgbaColorTrait.php
  models/DataObject/Classificationstore/Dao.php
Labels: Bug, Pimcore:ToDo

#16911 [Bug]: Fix DontEnv installer variables
  bin/pimcore-install
  lib/Bootstrap.php
Labels: Bug, Pimcore:ToDo

#16951 [Bug]: Fix dotenv test issues
  .github/ci/files/public/index_test.php
  tests/_bootstrap.php
Labels: Pimcore:ToDo

#16985 [Docs] added PaaS as installation option
  doc/01_Getting_Started/README.md
Labels: Task

#16809 Avoid letting video thumbnail processor fail catastrophically
  bundles/CoreBundle/src/Command/ThumbnailsVideoCommand.php
Labels: Pimcore:ToDo

#16988 FIX : ApplicationLogger -> Stop TaskManager on tab destroy
  bundles/ApplicationLoggerBundle/public/js/log/admin.js
Labels: Bug, Pimcore:ToDo

#16835 Make it possible to have not all languages required
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/05_Objects/01_Object_Classes/01_Data_Types/50_Localized_Fields.md
  doc/img/Objects_LocalizedFields_add_language.png
  lib/SystemSettingsConfig.php
  lib/Tool.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
Labels: Improvement, Pimcore:ToDo

#16968 Fix: Problem with Notification grid column filter
  models/Notification/Listing.php
  models/Notification/Service/NotificationService.php
  models/Notification/Service/NotificationServiceFilterParser.php
Labels: Bug, Pimcore:ToDo

#16969 DOC - Improve editable documentation and make twig syntax more consistent
  doc/03_Documents/01_Editables/02_Areablock/02_Bricks.md
  doc/03_Documents/01_Editables/04_Area.md
  doc/03_Documents/01_Editables/06_Block.md
  doc/03_Documents/01_Editables/08_Checkbox.md
  doc/03_Documents/01_Editables/10_Date.md
  doc/03_Documents/01_Editables/12_Relation_Many-To-One.md
  doc/03_Documents/01_Editables/14_Image.md
  doc/03_Documents/01_Editables/16_Input.md
  doc/03_Documents/01_Editables/18_Link.md
  doc/03_Documents/01_Editables/22_Multiselect.md
  doc/03_Documents/01_Editables/24_Numeric.md
  doc/03_Documents/01_Editables/25_Embed.md
  doc/03_Documents/01_Editables/28_Renderlet.md
  doc/03_Documents/01_Editables/30_Select.md
  doc/03_Documents/01_Editables/36_Textarea.md
  doc/03_Documents/01_Editables/38_Video.md
  doc/03_Documents/01_Editables/40_WYSIWYG.md
  doc/03_Documents/01_Editables/42_Scheduled_Block.md
Labels: Task, Pimcore:ToDo

#16996 Set convert_unsafe_embeds in TinyMce
  bundles/TinymceBundle/public/js/editor.js
Labels: Security
