Repository pimcore/pimcore, pull requests merged in 2024-03, with the labels that each got.

#16715 [Docs]: Fix outdated debug mode setting in docs
  doc/19_Development_Tools_and_Details/09_Cache/README.md
Labels: Task

#16720 Image Adapter: Allow null for cover orientation
  lib/Image/Adapter.php
Labels: Bug

#16719 Fix invalid authenticate token
  lib/Tool/Authentication.php
Labels: Pimcore:ToDo

#16727 [Bug]: DataObject Blocks dataloss when hidden by custom layout
  models/DataObject/ClassDefinition/Data/Block.php
Labels: Bug

#16730 Installer: make database setup independent from kernel and boot kernel only when required
  bundles/InstallBundle/src/Installer.php
  lib/Tool/Authentication.php
  tests/Support/Helper/Pimcore.php
Labels: Improvement

#16725 Add self validating Value Objects
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/ValueObject/Collection/ArrayOfBoolean.php
  lib/ValueObject/Collection/ArrayOfIntegers.php
  lib/ValueObject/Collection/ArrayOfPositiveIntegers.php
  lib/ValueObject/Collection/ArrayOfStrings.php
  lib/ValueObject/Integer/PositiveInteger.php
  lib/ValueObject/String/Path.php
  tests/Unit/ValueObject/Collection/ArrayOfBooleanTest.php
  tests/Unit/ValueObject/Collection/ArrayOfIntegersTest.php
  tests/Unit/ValueObject/Collection/ArrayOfPositiveIntegersTest.php
  tests/Unit/ValueObject/Collection/ArrayOfStringsTest.php
  tests/Unit/ValueObject/Integer/PositiveIntegerTest.php
  tests/Unit/ValueObject/String/PathTest.php
Labels: Improvement

#16731 Positive Integer should not be zero.
  lib/ValueObject/Collection/ArrayOfPositiveIntegers.php
  lib/ValueObject/Integer/PositiveInteger.php
Labels: Improvement

#16733 Installer: use a fixed build dir, do not use the one from `MicroKernelTrait`
  bundles/InstallBundle/src/InstallerKernel.php
Labels: Improvement, Bug

#16735 [Bug]: Fix Localized calculated value has wrong index within field collection
  models/DataObject/ClassDefinition/Data/Fieldcollections.php
Labels: Bug

#16737 Installer: fixing error You have requested a non-existent service "doctrine.dbal.default_connection"
  bundles/InstallBundle/src/Installer.php
Labels: Improvement, Bug

#16738 Installer: consistent log directory in /var/installer/log
  bundles/InstallBundle/src/Command/InstallCommand.php
  bundles/InstallBundle/src/InstallerKernel.php
Labels: Improvement, Bug

#16729 [Task]: Swap order between install bundles and install classes
  bundles/InstallBundle/src/Installer.php
Labels: Task

#15871 Define default value on Multiselect Object Type
  doc/05_Objects/01_Object_Classes/01_Data_Types/30_Dynamic_Select_Types.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/DynamicOptionsProvider/MultiSelectOptionsProviderInterface.php
  models/DataObject/ClassDefinition/DynamicOptionsProvider/SelectOptionsProviderInterface.php
  models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php
  models/DataObject/Service.php
Labels: Improvement, Pimcore:Priority

#16762 Bootstrapping: make sure, $_SERVER contains all values of $_ENV
  lib/Bootstrap.php
Labels: Bug

#16763 Docs: fix preview_url_prefix config example: values needs to include the protocol
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
Labels: Bug

#16608 Added Gotenberg support for creating page and version previews
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  composer.json
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Document/Adapter/Gotenberg.php
  lib/Helper/GotenbergHelper.php
  lib/Image/Chromium.php
  lib/Image/HtmlToImage.php
  lib/Tool/Requirements.php
  models/Document/Service.php
  phpstan-baseline.neon
Labels: Improvement, Pimcore:ToDo

#16736 [Data Objects] Password : Deprecate support for algorithms other than password_hash
  doc/05_Objects/01_Object_Classes/01_Data_Types/95_Text_Types.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/Password.php
Labels: Improvement

#16770 [Task]: Fix hardcoded references of Pimcore 11.1 to 11.2
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pull-request-checklist.yaml
  .github/workflows/sync-changes-scheduled.yml
  CONTRIBUTING.md
Labels: Task

#16772 Use spaces consistently in the installer
  bundles/InstallBundle/src/Installer.php
Labels: Bug

#16779 [Bug]: Fix BC-Break: Default value on multiselect object type introduced by #15871
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/DynamicOptionsProvider/SelectOptionsProviderInterface.php
  models/DataObject/ClassDefinition/DynamicOptionsProvider/SelectionProviderTrait.php
Labels: Bug, Pimcore:ToDo

#16796 DotEnv support BC layer - regression fix for #16652
  lib/Bootstrap.php
Labels: Bug

#16803 DotEnv support BC layer - regression fix for #16652, follow up #16796
  lib/Bootstrap.php
Labels: Bug

#16671 Docs: System Configuration Getter
  doc/18_Tools_and_Features/25_System_Settings.md
Labels: Pimcore:ToDo

#16789 fix(AbstractObject): ModificationDate could be null at this point
  models/DataObject/AbstractObject.php
Labels: Bug, Pimcore:ToDo

#16688 Fix height and width in localized fields
  models/DataObject/ClassDefinition/Data/Localizedfields.php
Labels: Bug, Pimcore:ToDo

#16823 [BUG] Asset Creation: add null check to possible null $tmpFile
  models/Asset.php
Labels: Bug

#16806 recreate behaviour that relations grab attributes in logged-in users …
  models/DataObject/Service.php
Labels: Bug

#16699 Version: Don't throw exception to generate StackTrace
  doc/18_Tools_and_Features/01_Versioning.md
  models/Version.php
Labels: Pimcore:ToDo

#16774 Fix: Thumbnails generation with frame=true throw exception, if GD image adapter in use
  lib/Image/Adapter/GD.php
Labels: Bug, Pimcore:ToDo

#16632 Fixed bug that prevented versions from be cleaned up
  models/Version/Dao.php
Labels: Bug, Pimcore:ToDo

#16833 [Bug]: Revert changes that forces to require symfony runtime
  bin/pimcore-install
Labels: Bug

#16676 (feat) add basic events for fieldcollection definitions
  lib/Event/FieldcollectionDefinitionEvents.php
  lib/Event/Model/DataObject/FieldcollectionDefinitionEvent.php
  models/DataObject/Fieldcollection/Definition.php
Labels: Improvement, Pimcore:ToDo

#16828 Implemented pre-publish and pre-unpublish events
  lib/Event/DataObjectEvents.php
  models/DataObject/Concrete.php
Labels: Pimcore:ToDo

#16840 Revert "Implemented pre-publish and pre-unpublish events (#16828)"
  lib/Event/DataObjectEvents.php
  models/DataObject/Concrete.php
Labels: Bug

#16808 Fix: when table data is not saved as string.
  models/DataObject/ClassDefinition/Data/Table.php
Labels: Pimcore:ToDo

#16846 [docs] Mention PHP 8.3 as supported in system requirements
  doc/23_Installation_and_Upgrade/01_System_Requirements.md
Labels: Task

#16832 [Bug, EC]: ClassificationStore inheritance is not working
  models/DataObject/Classificationstore.php
Labels: Bug

#16862 Fix WebsiteSetting::getById()
  models/WebsiteSetting/Dao.php
Labels: Pimcore:ToDo

#16861 Feature/Improvement: Make wysiwyg dnd image get custom metadata
  lib/Tool/Text.php
Labels: Improvement, Pimcore:ToDo

#16872 Fix: InputQuantityValue toString method now always returns a string instead of null
  models/DataObject/Data/InputQuantityValue.php
Labels: Bug

#16864 Fix: EmbeddedMetaDataTrait::readEmbeddedMetaData()
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
  models/Asset/MetaData/EmbeddedMetaDataTrait.php
Labels: Pimcore:ToDo

#16742 Do not silently ignore invalid setOrder/setOrderKey parameters
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Model/Listing/AbstractListing.php
Labels: Improvement, Pimcore:ToDo

#16873 Optimization of the Dao::getById() methods
  bundles/StaticRoutesBundle/src/Model/Staticroute/Dao.php
  doc/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  lib/Model/Dao/DaoTrait.php
  models/Asset/Dao.php
  models/DataObject/AbstractObject/Dao.php
  models/DataObject/ClassDefinition/CustomLayout/Dao.php
  models/DataObject/Classificationstore/CollectionConfig/Dao.php
  models/DataObject/Classificationstore/CollectionGroupRelation/Dao.php
  models/DataObject/Classificationstore/GroupConfig/Dao.php
  models/DataObject/Classificationstore/KeyConfig/Dao.php
  models/DataObject/Classificationstore/KeyGroupRelation/Dao.php
  models/DataObject/Classificationstore/StoreConfig/Dao.php
  models/DataObject/Concrete/Dao.php
  models/DataObject/QuantityValue/Unit/Dao.php
  models/DataObject/SelectOptions/Config/Dao.php
  models/Document/Dao.php
  models/Document/DocType/Dao.php
  models/Document/Email/Dao.php
  models/Document/Hardlink/Dao.php
  models/Document/Link/Dao.php
  models/Document/Page/Dao.php
  models/Document/Snippet/Dao.php
  models/Element/WorkflowState/Dao.php
  models/Site/Dao.php
  models/Tool/Email/Blocklist/Dao.php
  models/Tool/Email/Log.php
  models/Tool/Email/Log/Dao.php
  models/Tool/SettingsStore.php
  models/Tool/SettingsStore/Dao.php
  models/Tool/TmpStore/Dao.php
Labels: Task
