Repository pimcore/pimcore, pull requests merged in 2024-01, with the labels that each got.

#16412 [bugfix] Table calls htmlspecialchars with null value
  models/DataObject/ClassDefinition/Data/Table.php
Labels: Bug

#16413 [bugfix] Areablock empty data causes Exception
  models/Document/Editable/Areablock.php
Labels: Bug

#16268 Deprecate LocaleServiceInterface aliases
  bundles/CoreBundle/config/aliases.yaml
  bundles/CoreBundle/src/Migrations/Version20231127124738.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
  models/Translation.php
Labels: Improvement

#16432 Adding pimcore_scheduled_tasks to messenger-consume
  doc/01_Getting_Started/00_Installation/01_Webserver_Installation.md
Labels: Task

#16445 Run tests (PhpStan & Codeception) with latest Symfony dev-version (currently 6.4-dev)
  .github/workflows/codeception.yaml
  .github/workflows/static-analysis.yaml
Labels: Bug

#16450 Pimcore\Model\Element\Service:getElementFromSession() - Use lowercase self
  models/Element/Service.php
Labels: Bug, Backlog

#16449 Recreate TODO comment, removed by php-cs-fixer
  models/Document/Editable/Video.php
Labels: Task

#16451 Added information about max length
  doc/03_Documents/01_Editables/40_WYSIWYG.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#16303 Fix Service::copyRecursive()
  models/Asset/Service.php
  models/DataObject/Service.php
  models/Document/Service.php
Labels: Bug

#16311 [Asset] Custom settings shouldn't go to cache when exceeding a certain size
  models/Asset.php
  models/Asset/Dao.php
Labels: Bug

#16456 provide controller results to template
  bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php
Labels: Bug

#16463 Fix open reports from dashboard
  bundles/CustomReportsBundle/public/js/pimcore/layout/portlets/customreports.js
Labels: Bug

#16458 Fix AbstractRelations::buildUniqueKeyForAppending()
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
Labels: Bug

#16441 [Docs] Fix Custom Persistent Models section DAO
  doc/20_Extending_Pimcore/17_Custom_Persistent_Models.md
Labels: Task

#16418 Bugfix renderlet type confusion
  models/Document/Editable/Renderlet.php
Labels: Bug

#16469 [BUG]: Pimcore Datahub File Exporter bundle not exporting data with configured languages
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/Service.php
Labels: Bug

#16478 Added package types to contributing guidelines
  CONTRIBUTING.md
Labels: Task

#16479 [Bug]: Fix static page generated via CLI having invalid hostname
  lib/Document/Renderer/DocumentRenderer.php
Labels: Bug

#16467 Refix generation of thumbnails with inline thumbnail config
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Service.php
Labels: Bug

#16419 fix: determine object aware fields at wakeup time
  models/DataObject/Concrete.php
  models/Element/Service.php
Labels: Bug

#16493 [Docs] Fix broken external links
  doc/00_Overview/README.md
  doc/01_Getting_Started/04_Configuration.md
  doc/02_MVC/02_Template/README.md
  doc/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  doc/05_Objects/03_Working_with_PHP_API.md
  doc/06_Multi_Language_i18n/04_Shared_Translations.md
  doc/18_Tools_and_Features/29_Custom_Reports.md
  doc/18_Tools_and_Features/39_Sitemaps.md
  doc/19_Development_Tools_and_Details/29_Testing/03_Testing_Services.md
  doc/19_Development_Tools_and_Details/35_Working_with_Sessions.md
  doc/20_Extending_Pimcore/11_Event_API_and_Event_Manager.md
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/05_Pimcore_Bundles/01_Installers.md
  doc/20_Extending_Pimcore/15_Maintenance_Mode.md
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/10_V6_to_V10.md
Labels: Task, Pimcore:ToDo

#16499 [Docs] Fix namespaces in Sitemaps
  doc/18_Tools_and_Features/39_Sitemaps.md
Labels: Task

#16495 Symfony Upgrade to Version 6.4
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, Pimcore:ToDo

#16466 [Task]: PhpStan Version Upgrade January
  composer.json
Labels: Task, Pimcore:ToDo

#16229 Update h* elements to allow in html_sanitizer default config
  bundles/CoreBundle/config/pimcore/default.yaml
Labels: Bug, Pimcore:ToDo

#16381 [Bug]: Fix missing QueryBuilder parameter support in Listing Dao
  doc/20_Extending_Pimcore/17_Custom_Persistent_Models.md
  models/Asset/Listing/Dao.php
  models/DataObject/Listing/Dao.php
  models/Document/Listing/Dao.php
  models/Translation/Listing/Dao.php
Labels: Bug, Pimcore:ToDo

#16515 StopMessenger trait should work in maintenance mode
  lib/Helper/StopMessengerWorkersTrait.php
Labels: Bug, Pimcore:ToDo

#16462 Added check to see if children are excluded from navigation
  lib/Navigation/Renderer/Menu.php
Labels: Bug, Pimcore:ToDo

#16509 Fix: fieldcollection abstractData initialize index value
  models/DataObject/Fieldcollection/Data/AbstractData.php
Labels: Bug, Pimcore:ToDo

#16524 Default init function parameter lifetime to 0 and always set it
  lib/Twig/Extension/CacheExtension.php
Labels: Bug

#16436 Support QuantityValueRange on Classification Store
  bundles/CoreBundle/config/marshaller.yaml
  composer.json
  lib/DataObject/ClassificationstoreDataMarshaller/QuantityValueRange.php
Labels: Improvement, Pimcore:ToDo

#15913 add ability to get Image Tag with FrontendPath
  doc/04_Assets/03_Working_with_Thumbnails/01_Image_Thumbnails.md
  models/Asset/Image/Thumbnail.php
Labels: Improvement, Pimcore:ToDo
