Repository pimcore/pimcore, pull requests merged in 2024-08, with the labels that each got.

#17412 [Doc] Fix Path Formatter example
  doc/05_Objects/01_Object_Classes/05_Class_Settings/50_Path_Formatter.md
  lib/Tool.php
Labels: Pimcore:ToDo

#17404 Update typo in twig function instanceof 45_Image_Types.md
  doc/05_Objects/01_Object_Classes/01_Data_Types/45_Image_Types.md
Labels: Pimcore:ToDo

#17365 Data Object: HTML in version preview should be rendered properly for wysiwyg data type
  models/DataObject/ClassDefinition/Data/Extension/Text.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
Labels: Bug, Pimcore:ToDo

#17349 Add static to the getValues function
  models/DataObject/SelectOptions/Traits/EnumGetValuesTrait.php
Labels: Bug, Pimcore:ToDo

#17448 Update 03_Configuration_Environments.md
  doc/21_Deployment/03_Configuration_Environments.md
Labels: Task

#16989 Navigation Container with OPCache creates infinite loop
  lib/Navigation/Container.php
  lib/Navigation/Iterator/PrefixRecursiveFilterIterator.php
Labels: Pimcore:ToDo

#17434 Fix add overlay image over a gif image
  lib/Image/Adapter/Imagick.php
Labels: Pimcore:ToDo

#17480 docs: change code language to php
  doc/18_Tools_and_Features/01_Versioning.md
Labels: Bug

#17460 [Improvement] Get configuration values from environment data
  bundles/GenericExecutionEngineBundle/src/Messenger/Handler/AbstractAutomationActionHandler.php
  doc/19_Development_Tools_and_Details/08_Generic_Execution_Engine/01_Jobs_and_Jobruns/04_Step_Configuration.md
Labels: Improvement

#17470 [Task]: Fix typos in 05_Database_Model.md
  doc/19_Development_Tools_and_Details/05_Database_Model.md
Labels: Bug

#17488 null-safe nullable value of path as third argument of preg_replace
  models/Document.php
Labels: Bug

#17483 [Docs] Run "composer dump autoload -o" after "pimcore:deployment:classes-rebuild --create-classes"
  doc/21_Deployment/05_Deployment_Tools.md
Labels: Bug

#17428 Detect psd files as images
  bundles/CoreBundle/config/pimcore/default.yaml
Labels: Bug, Pimcore:ToDo

#16904 [Bug]: Workflow notification are sent to inactive users
  lib/Workflow/Notification/AbstractNotificationService.php
Labels: Bug, Pimcore:ToDo

#17501 [Bug]: Fix multisite link
  lib/Tool/Text.php
Labels: Bug, Pimcore:Priority

#17508 [Docs] Documentation missing for 'Mandatory language' setting
  doc/06_Multi_Language_i18n/README.md
  doc/img/localization-settings.png
Labels: Task

#17409 HTML sanitizer: Allow img class attribute and hr element
  bundles/CoreBundle/config/pimcore/default.yaml
Labels: Bug, Pimcore:ToDo

#17518 [Task]: Avoid superfluous thumbnail directory delete calls
  models/Asset.php
Labels: Task, Pimcore:ToDo

#17485 [Improvement] Extend notification and notification service
  bundles/CoreBundle/src/Migrations/Version20240813085200.php
  bundles/InstallBundle/dump/install.sql
  doc/18_Tools_and_Features/41_Notifications.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Notification.php
  models/Notification/Dao.php
  models/Notification/Service/NotificationService.php
Labels: Improvement, Pimcore:ToDo

#17519 Gracefully handle cases in which the storage adapter fails to calculate a file's checksum.
  models/Asset.php
Labels: Bug, Pimcore:ToDo

#17538 PhpStan Version Upgrade August
  composer.json
  lib/Tool/Text/Csv.php
Labels: Task

#17456 Data Object: consider unpublished state for reverse object relation
  models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/ManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
Labels: Bug, Pimcore:ToDo

#17390 [Task]: Optimize `tags` queries via runtime cache
  models/Element/Tag.php
  models/Element/Tag/Dao.php
Labels: Task, Pimcore:ToDo

#17433 Remove unnecessary static php docs
  bundles/StaticRoutesBundle/src/Model/Staticroute.php
  lib/Cache/RuntimeCache.php
  lib/Cache/Tool/Warming.php
  lib/Helper/Mail.php
  lib/Pimcore.php
  lib/Tool.php
  lib/Tool/Admin.php
  lib/Tool/Transliteration.php
  models/Asset/Service.php
  models/DataObject/AbstractObject.php
  models/DataObject/Objectbrick/Definition.php
  models/DataObject/Service.php
  models/Document/Hardlink/Service.php
  models/Document/Service.php
  models/Element/Note.php
  models/Element/Recyclebin/Item.php
  models/Element/Service.php
  models/Element/Tag.php
  models/Tool/Email/Log.php
  models/User/Service.php
  models/Version.php
Labels: Task, Pimcore:ToDo

#17420 Added check if data changed on editor before dispatching pimcore.even…
  bundles/TinymceBundle/public/js/editor.js
Labels: Bug, Pimcore:ToDo

#17441 Check the character count on WYSIWYG fields based on the initial content in the field
  bundles/TinymceBundle/public/js/editor.js
Labels: Bug, Pimcore:ToDo, Pimcore:Priority

#17525 Update table docs
  doc/05_Objects/01_Object_Classes/01_Data_Types/85_Structured_Table.md
  doc/05_Objects/01_Object_Classes/01_Data_Types/90_Table.md
  doc/img/Objects_Table_copyandpaste.png
  doc/img/Objects_Table_copyandpasteresult.png
  doc/img/Objects_Table_excel.png
Labels: Pimcore:ToDo

#17444 Prepare for twig >=3.9.0
  bundles/CoreBundle/config/templating_twig.yaml
  doc/02_MVC/02_Template/02_Template_Extensions/00_Placeholder.md
  doc/02_MVC/02_Template/02_Template_Extensions/03_HeadScript.md
  doc/02_MVC/02_Template/02_Template_Extensions/04_HeadStyle.md
  doc/02_MVC/02_Template/02_Template_Extensions/README.md
  doc/02_MVC/02_Template/README.md
  lib/Twig/Extension/CacheExtension.php
  lib/Twig/Extension/CacheTagExtension.php
  lib/Twig/Extension/Templating/HeadScript.php
  lib/Twig/Extension/Templating/HeadStyle.php
  lib/Twig/Extension/Templating/Placeholder/Container.php
  lib/Twig/Node/CacheNode.php
  lib/Twig/TokenParser/CacheParser.php
Labels: Improvement, Pimcore:ToDo

#16800 Don't remove version dependent comments in database dumps
  bundles/InstallBundle/src/Installer.php
Labels: Bug, Pimcore:ToDo
