Repository pimcore/pimcore, pull requests merged in 2024-10, with the labels that each got.

#17628 Update license to make a list out of the last three links
  LICENSE.md
Labels: Task, Pimcore:ToDo

#17671 [Task]: Fix the minor branch usages
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/composer-checks-outdated-monthly.yaml
  .github/workflows/composer-checks-outdated.yaml
  .github/workflows/composer-checks-vulnerabilities.yaml
  .github/workflows/pull-request-checklist.yaml
  .github/workflows/sync-changes-scheduled.yml
Labels: Task, Pimcore:ToDo

#17637 Update composer-checks-vulnerabilities.yaml
  .github/workflows/composer-checks-vulnerabilities.yaml
Labels: Pimcore:ToDo

#17674 [Task]: Change external links from http to https
  bundles/SimpleBackendSearchBundle/public/js/pimcore/element/selector/asset.js
  bundles/SimpleBackendSearchBundle/public/js/pimcore/element/selector/document.js
  bundles/SimpleBackendSearchBundle/public/js/pimcore/element/selector/object.js
  doc/06_Multi_Language_i18n/09_Formatting_Service.md
  doc/18_Tools_and_Features/21_Glossary.md
  doc/23_Installation_and_Upgrade/01_System_Requirements.md
  lib/Tool/Requirements.php
Labels: Task, Pimcore:ToDo

#17632 [Docs]: Add mention of `getCount()` method in Document PHP API Documentation
  doc/03_Documents/09_Working_with_PHP_API.md
Labels: Task, Pimcore:ToDo

#17678 [Docs] improve classification store example
  doc/05_Objects/01_Object_Classes/01_Data_Types/15_Classification_Store.md
Labels: Task

#17057 Fix fallback mechanism for ICU translations
  lib/Translation/Translator.php
Labels: Bug, Pimcore:ToDo

#17660 Fix Task setCid and setCtype methods
  models/Schedule/Task.php
Labels: Bug, Pimcore:ToDo

#17680 [Bug, EC]: Visual mandatory flag on Classification Store group when attribute is not mandatory
  models/DataObject/Classificationstore/KeyGroupRelation/Listing/Dao.php
Labels: Bug, Pimcore:Priority

#17685 [Bug]: Fix domain name validation
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  models/Site.php
Labels: Bug, Pimcore:Priority

#17698 [Bug]: Fix Site Additional domain validation issues
  models/Site.php
Labels: Bug, Pimcore:ToDo

#17708 [Bugfix] Fix typo in @param phpdoc
  models/DataObject/Traits/FieldDefinitionEnrichmentDataTrait.php
Labels: Task

#17699 [Readme] Add instructions for multiple applications on same domain
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/08_Multi_Application_Setup.md
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/README.md
Labels: Pimcore:ToDo

#17738 [Bug]: Fix type error in NumericRange constructor when using decimals
  models/DataObject/ClassDefinition/Data/NumericRange.php
Labels: Bug

#17408 Fix duplicate relations on event listeners save
  models/DataObject/AbstractObject.php
  models/DataObject/Concrete.php
Labels: Pimcore:ToDo

#17739 docs: remove version constraint of league/flysystem-aws-s3-v3
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/03_File_Storage_Setup.md
Labels: Pimcore:ToDo

#17740 [Events] Add Deprecation to remove context from ResolveUploadTargetEvent
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Event/Model/Asset/ResolveUploadTargetEvent.php
Labels: Task

#17743 [Bug]: Fix QuantityRangeValue validation failed on empty field
  models/DataObject/ClassDefinition/Data/QuantityValueRange.php
Labels: Bug, Pimcore:Priority

#17745 QuantityValueRange: Call to a member function getMinimum() on null
  models/DataObject/ClassDefinition/Data/QuantityValueRange.php
Labels: Bug

#17744 [Improvement]: Add `versionCount` index to element and versions table
  bundles/CoreBundle/src/Migrations/Version20241021111028.php
  bundles/InstallBundle/dump/install.sql
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement, Pimcore:Priority

#17758 [Bug]: copyRecursive fails on copying a folder with emails
  models/Element/Service.php
Labels: Bug

#17344 [Bug]: Fix unique constraint issue when updating advanced many-to-many
  bundles/CoreBundle/src/Migrations/Version20241025101923.php
  models/DataObject/Data/AbstractMetadata/Dao.php
  models/DataObject/Data/ElementMetadata/Dao.php
  models/DataObject/Data/ObjectMetadata/Dao.php
Labels: Bug, Pimcore:ToDo

#17709 [Docs] Improve TinyMCE bundle documentation
  bundles/TinymceBundle/README.md
Labels: Task, Pimcore:ToDo

#17774 [Bug]: Merge conflict mistake in Installer mark_migrations_as_done
  bundles/InstallBundle/src/Installer.php
Labels: Bug, Pimcore:ToDo

#17780 [Bug] Panel layout getLayout can return null
  models/DataObject/ClassDefinition/Layout/Panel.php
Labels: Bug

#17787 [Bug,EC] Video Editable HTML Output ampersand
  models/Document/Editable/Video.php
Labels: Bug, Pimcore:Priority

#17767 [Bug]: Fix `php: ../../magick/exception.c:1121: ThrowMagickExceptionList: Assertion` error on install
  lib/Image/Adapter/Imagick.php
  phpstan-baseline.neon
Labels: Bug, Pimcore:ToDo

#17048 Revert native type changes in navigation container
  lib/Navigation/Container.php
Labels: Pimcore:ToDo, Pimcore:Priority
