Repository pimcore/pimcore, pull requests merged in 2024-12, with the labels that each got.

#17873 [Improvement]: Replace Request::get with explicit input sources
  bundles/ApplicationLoggerBundle/src/Controller/LogController.php
  bundles/CoreBundle/src/Controller/PublicServicesController.php
  bundles/CoreBundle/src/EventListener/Frontend/BlockStateListener.php
  bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php
  bundles/CoreBundle/src/EventListener/Traits/PreviewRequestTrait.php
  bundles/CustomReportsBundle/src/Controller/Reports/CustomReportController.php
  bundles/GlossaryBundle/src/Controller/SettingsController.php
  bundles/SeoBundle/src/Controller/MiscController.php
  bundles/SeoBundle/src/Controller/RedirectsController.php
  bundles/SeoBundle/src/Controller/SettingsController.php
  bundles/SimpleBackendSearchBundle/src/Controller/DataObjectController.php
  bundles/SimpleBackendSearchBundle/src/Controller/SearchController.php
  bundles/StaticRoutesBundle/src/Controller/SettingsController.php
  bundles/WordExportBundle/src/Controller/TranslationController.php
  bundles/XliffBundle/src/Controller/XliffTranslationController.php
  doc/02_MVC/02_Template/02_Template_Extensions/README.md
  doc/02_MVC/04_Routing_and_URLs/02_Custom_Routes.md
  doc/03_Documents/01_Editables/28_Renderlet.md
  doc/05_Objects/01_Object_Classes/03_Layout_Elements/02_Preview_Iframe.md
  doc/05_Objects/03_Working_with_PHP_API.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  doc/26_Best_Practice/70_Open_By-External_Id.md
  doc/26_Best_Practice/85_Using_Tags_for_Filtering.md
  lib/Http/Request/Resolver/DocumentResolver.php
  lib/Http/Request/Resolver/EditmodeResolver.php
  lib/Http/Request/Resolver/TemplateResolver.php
  tests/Model/Asset/AssetThumbnailCacheTest.php
Labels: Improvement, Pimcore:ToDo

#17133 Fix error on update in upsert with missing primaryKey "auto_id"
  models/DataObject/Data/AbstractMetadata/Dao.php
  models/DataObject/Data/ElementMetadata/Dao.php
  models/DataObject/Data/ObjectMetadata/Dao.php
Labels: Pimcore:ToDo

#17849 Improvement: Add elements to html_sanitizer
  .github/ci/files/config/packages/html_sanitizer.yaml
  bundles/CoreBundle/config/pimcore/default.yaml
  doc/03_Documents/01_Editables/40_WYSIWYG.md
Labels: Improvement

#17884 [Task]: Deprecate TinyMCE
  bundles/TinymceBundle/public/js/editor.js
  bundles/TinymceBundle/src/PimcoreTinymceBundle.php
  doc/01_Getting_Started/02_Advanced_Installation_Topics/README.md
  doc/03_Documents/01_Editables/40_WYSIWYG.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task

#17892 Fixing regression caused by #17873 in TemplateResolver
  lib/Http/Request/Resolver/TemplateResolver.php
Labels: Bug

#17907 ElementListener: Fix variable variable "$$versionId"
  bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php
Labels: Pimcore:ToDo

#17778 Fix: EncryptedField getDataForGrid return typehint is defined as array while it could returns string
  models/DataObject/ClassDefinition/Data/EncryptedField.php
  models/DataObject/ClassDefinition/Data/RgbaColor.php
  tests/Support/Helper/DataType/TestDataHelper.php
Labels: Pimcore:ToDo

#17895 TinyMCE Bundle shouldn't be a recommended bundle anymore
  bundles/InstallBundle/src/Installer.php
Labels: Improvement

#17911 [Doc] Fix: Multiple Pimcore 11.5 Upgrade Notes
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, Pimcore:ToDo

#17903 Remove excess `*` from PHPDoc
  models/DataObject/Localizedfield.php
Labels: Task, Pimcore:ToDo

#17891 Fix cleanup bricks and fieldcollections tables task
  lib/Maintenance/Tasks/DataObject/CleanupBrickTablesTaskHelper.php
  lib/Maintenance/Tasks/DataObject/CleanupFieldcollectionTablesTaskHelper.php
  lib/Maintenance/Tasks/DataObject/DataObjectTaskHelper.php
Labels: Pimcore:ToDo

#17748 Fix: change sorting column from `path` to `key` to ensure correct order
  lib/Tool/Frontend.php
  tests/Model/Tool/TextTest.php
Labels: Bug, Pimcore:ToDo

#17872 [Bug]: Frontend::getSiteIdForDocument returns wrong id / wrong document public url (#17871)
  lib/Tool/Frontend.php
Labels: Bug, Pimcore:ToDo

#17941 add mimetype to list of system types.
  models/Asset/Service.php
Labels: New Feature
