Repository pimcore/pimcore, pull requests merged in 2024-02, with the labels that each got.

#16385 fix psd files with alpha channels
  lib/Image/Adapter/Imagick.php
Labels: Bug, Pimcore:ToDo

#16186 Also check Pimcore context in `GlobalTemplateVariablesListener::onKernelResponse()`
  bundles/CoreBundle/src/EventListener/Frontend/GlobalTemplateVariablesListener.php
Labels: Bug, Pimcore:ToDo

#16378 Fix: Error when $_SERVER['REQUEST_URI'] is not set
  bundles/SeoBundle/src/Redirect/RedirectHandler.php
Labels: Bug, Pimcore:ToDo

#16529 [Asset] Image thumbnails deferred url should always return file from …
  bundles/CoreBundle/src/Controller/PublicServicesController.php
  models/Asset/Image/Thumbnail/Processor.php
  models/Asset/Service.php
  tests/Model/Asset/AssetThumbnailCacheTest.php
Labels: Bug, Pimcore:ToDo

#16558 Fix Malformed UTF8 message when saving DataObject
  models/Element/Service.php
Labels: Pimcore:ToDo

#16531 Remove duplicate array element in Imagick.php
  lib/Image/Adapter/Imagick.php
Labels: Bug, Pimcore:ToDo

#16569 [Task]: Specify `gotenberg/gotenberg-php` supported version
  composer.json
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
Labels: Task, Pimcore:ToDo

#16546 [Bug] Fix bundle priority issue
  lib/HttpKernel/BundleCollection/BundleCollection.php
  tests/Unit/HttpKernel/BundleCollection/BundleCollectionTest.php
Labels: Bug, Pimcore:ToDo

#16585 Fix typo on 35_Fieldcollections.md
  doc/05_Objects/01_Object_Classes/01_Data_Types/35_Fieldcollections.md
Labels: Pimcore:ToDo

#16589 PHP 8.3 Support
  .github/workflows/codeception.yaml
  .github/workflows/static-analysis.yaml
  composer.json
Labels: Improvement

#16590 Deprecated \Pimcore\Extension\Bundle\AbstractPimcoreBundle::$bundleManager
  lib/Extension/Bundle/AbstractPimcoreBundle.php
Labels: Improvement

#16567 Fix Permission wipe after "login as this user in a different browser" / user token
  lib/Tool/Authentication.php
Labels: Bug, Pimcore:ToDo

#16533 [BUG FIX] passwortRecoveryToken column length to small
  bundles/CoreBundle/src/Migrations/Version20240131080600.php
  bundles/InstallBundle/dump/install.sql
Labels: Bug, Pimcore:ToDo

#16525 fix copy paste error for migration output
  bundles/CoreBundle/src/Migrations/Version20221220152444.php
  bundles/CoreBundle/src/Migrations/Version20230406113010.php
Labels: Task, Pimcore:ToDo

#16080 Consistently use "utf8mb4_general_ci" as database collation
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/05_DB_Setup.md
  tests/bin/docker-compose.yaml
Labels: Improvement, Pimcore:ToDo

#15864 [Images] Allow disabling assets.image.max_pixels config
  models/Asset.php
Labels: Improvement, Pimcore:ToDo

#16233 Add last-modified-since option to ThumbnailsImageCommand
  bundles/CoreBundle/src/Command/ThumbnailsImageCommand.php
Labels: Improvement, Pimcore:ToDo

#16532 Update migration to prevent duplicate key error in Pimcore 10->11 upgrades
  bundles/CoreBundle/src/Migrations/Version20230111074323.php
Labels: Bug

#16267 Fix: Use DocumentRendererInterface instead DocumentRenderer
  bundles/CoreBundle/config/aliases.yaml
  bundles/CoreBundle/config/documents.yaml
  bundles/CoreBundle/src/EventListener/ResponseExceptionListener.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Document/Editable/EditableUsageResolver.php
  lib/Document/StaticPageGenerator.php
  models/Document/Service.php
Labels: Improvement, Pimcore:ToDo

#16539 Include tests into dist zip again
  .gitattributes
Labels: Task, Pimcore:ToDo

#16195 Remove unused parameter and command option from low-quality image preview generation
  bundles/CoreBundle/src/Command/LowQualityImagePreviewCommand.php
  models/Asset/Image.php
Labels: Improvement, Pimcore:Priority

#16633 Readme updates
  README.md
Labels: Task

#16657 Fix o_ prefix on foreign keys by Migration
  bundles/CoreBundle/src/Migrations/Version20240222143211.php
Labels: Bug, Pimcore:ToDo

#16621 Drop foreign key constraint with o_ prefix if it exists and re-create it
  bundles/CoreBundle/src/Migrations/Version20230616085142.php
Labels: Pimcore:ToDo

#16669 Fix: Method hasProperty() throws an error if object is new and not saved yet
  models/Asset/Dao.php
  models/DataObject/AbstractObject/Dao.php
  models/Document/Dao.php
Labels: Bug

#16653 PhpStan Version Upgrade February
  composer.json
Labels: Task, Pimcore:ToDo

#16329 [Bug]: Decrease Queries in Tags
  models/Element/Tag.php
Labels: Task, Pimcore:ToDo

#16652 [Improvement] Make booting consistent with CLI
  .github/ci/files/bin/console
  .github/ci/files/public/index_test.php
  bin/pimcore-install
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Bootstrap.php
  lib/Tool.php
  tests/_bootstrap.php
Labels: Improvement, Pimcore:ToDo, Pimcore:Priority

#16673 ElementInterface::save(): Add missing DuplicateFullPathException php doc
  models/Element/ElementInterface.php
Labels: Pimcore:ToDo

#16680 Installer: add the possibility to specify a list of tasks that should be executed
  bundles/InstallBundle/src/Command/InstallCommand.php
  bundles/InstallBundle/src/Installer.php
Labels: Improvement

#16685 adds class to a tag tinymce
  bundles/TinymceBundle/public/js/editor.js
Labels: Bug

#16692 [Bug]: getByKey for DataObjects results in invalid SQL query
  models/DataObject/AbstractObject.php
Labels: Bug

#16678 Fix: ApplicationLogger Bundle logs not stored in UTC
  bundles/ApplicationLoggerBundle/src/Handler/ApplicationLoggerDb.php
Labels: Bug

#16698 [Docs]: Adapt settings store 11 changes and fix indentation
  doc/21_Deployment/03_Configuration_Environments.md
Labels: Task, Pimcore:ToDo
