Repository pimcore/pimcore, pull requests merged in 2024-07, with the labels that each got.

#17242 [Task] Switch to reusable cs fixer workflow
  .github/workflows/php-cs-fixer.yaml
Labels: Task

#17195 PhpStan Version Upgrade June
  composer.json
Labels: Task, Pimcore:ToDo

#17254 [Improvement]: Adapt docu for Generic Execution Engine
  doc/08_Generic_Execution_Engine/02_Configuration.md
  doc/19_Development_Tools_and_Details/08_Generic_Execution_Engine/01_Usage.md
  doc/19_Development_Tools_and_Details/08_Generic_Execution_Engine/02_Configuration.md
  doc/19_Development_Tools_and_Details/08_Generic_Execution_Engine/03_Extending_Generic_Execution_Engine.md
  doc/19_Development_Tools_and_Details/08_Generic_Execution_Engine/README.md
Labels: Improvement

#17255 [Task]: Fix broken tests
  composer.json
  tests/Support/Resources/system_settings.json
Labels: Task

#17069 [BUG] type error on multiselect unmarshal
  lib/DataObject/ClassificationstoreDataMarshaller/Multiselect.php
Labels: Pimcore:Priority

#17174 escape columns in inheritance helper
  models/DataObject/Concrete/Dao/InheritanceHelper.php
Labels: Bug, Pimcore:ToDo

#17214 Composer: Add conflict pimcore/admin-ui-classic-bundle <1.5
  composer.json
Labels: Pimcore:ToDo

#17258 Composer: Add symfony/string
  .github/ci/scripts/symfony-require-dev.sh
  composer.json
Labels: Task

#17260 [Gee] Job Run context default error handling mode
  bundles/GenericExecutionEngineBundle/src/DependencyInjection/Configuration.php
Labels: Bug

#17209 Remove duplicate error log
  bundles/CoreBundle/config/pimcore/dev.yaml
  bundles/CoreBundle/config/pimcore/prod.yaml
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement, Task, Pimcore:ToDo

#17221 Validate domain names
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  lib/SystemSettingsConfig.php
  models/Site.php
Labels: Pimcore:ToDo

#17275 Update php-cs-fixer.yaml
  .github/workflows/php-cs-fixer.yaml
Labels: Task

#17190 Fix: Inconsistent sorting of quantity value units
  models/DataObject/ClassDefinition/Data/AbstractQuantityValue.php
  models/DataObject/ClassDefinition/Data/QuantityValueRange.php
  models/DataObject/QuantityValue/Service.php
  models/DataObject/QuantityValue/Unit.php
  models/DataObject/QuantityValue/Unit/Dao.php
Labels: Pimcore:ToDo

#17205 [Bug]: Fix Undefined constant "GLOB_BRACE" on Alpine
  bundles/InstallBundle/src/Installer.php
Labels: Pimcore:ToDo

#17290 Fix sitemaps doc
  doc/18_Tools_and_Features/39_Sitemaps.md
Labels: Task

#17308 [Console] fix typehint in execInBackgroundWindows
  lib/Tool/Console.php
Labels: Bug

#17210 Fix deprecations in Dao helper
  models/DataObject/ClassDefinition/Helper/Dao.php
Labels: Pimcore:ToDo

#17267 Update 13_Loading_Admin_UI_Assets.md
  bundles/TinymceBundle/README.md
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/13_Loading_Admin_UI_Assets.md
Labels: Pimcore:ToDo

#17301 [Task]: Tweak explanation of `search_paths` and `handleComposer` config
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
Labels: Task, Pimcore:ToDo

#17272 [Bug]: Column key sensitivity issue in Advanced Many-To-Many
  models/DataObject/Data/ElementMetadata/Dao.php
  models/DataObject/Data/ObjectMetadata/Dao.php
Labels: Bug, Pimcore:ToDo

#17064 [Documentation] [Bug] Tinymce documentation fix
  bundles/TinymceBundle/README.md
Labels: Pimcore:ToDo

#17075 CLA: make it suitable for all Pimcore projects
  CLA.md
Labels: Pimcore:ToDo

#17281 UrlSlug: Fix return/param types
  bundles/CoreBundle/src/Migrations/Version20210706090823.php
  bundles/CoreBundle/src/Migrations/Version20211117173000.php
  bundles/CoreBundle/src/Migrations/Version20230412105530.php
  bundles/CoreBundle/src/Migrations/Version20230508121105.php
  bundles/CoreBundle/src/Migrations/Version20230516161000.php
  bundles/CoreBundle/src/Migrations/Version20230606112233.php
  bundles/CoreBundle/src/Migrations/Version20240708083500.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
Labels: Pimcore:ToDo, Pimcore:Priority

#17207 FrontendController: Fix PhpDoc
  lib/Controller/FrontendController.php
Labels: Pimcore:ToDo

#17245 Reverts changes from #15200 (FlysystemVisibilityPass not needed anymore)
  bundles/CoreBundle/src/DependencyInjection/Compiler/FlysystemVisibilityPass.php
  bundles/CoreBundle/src/PimcoreCoreBundle.php
  composer.json
Labels: Pimcore:ToDo

#17345 [Bug] Processed elements should be incremented only when there are selected elements
  bundles/GenericExecutionEngineBundle/src/Agent/JobExecutionAgent.php
Labels: Bug

#16966 [Composer] Remove unused `rybakit/twig-deferred-extension` dependency
  bundles/CoreBundle/config/templating_twig.yaml
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Pimcore:ToDo

#17252 [Bug, EC]: Fix translations in workflows
  bundles/CoreBundle/templates/Workflow/statusinfo/allPlacesStatusInfo.html.twig
  bundles/CoreBundle/templates/Workflow/statusinfo/toolbarStatusInfo.html.twig
  lib/Workflow/Place/StatusInfo.php
Labels: Bug, Pimcore:ToDo

#17270 [Bug]: Fix lazy loaded Block element in objectbrick
  models/DataObject/ClassDefinition/Data/Block.php
Labels: Bug, Pimcore:ToDo

#17296 [Bug]: Delete Versions that have ever been in used in scheduler
  models/Version/Dao.php
Labels: Bug, Pimcore:ToDo

#17362 [BUG] Imagick: extend clipping path check for images
  lib/Image/Adapter/Imagick.php
Labels: Bug

#17072 Fixing getClasses() in ReverseObjectRelation
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
Labels: Bug, Pimcore:ToDo

#17246 Fix code example for how to create a brick in documentation
  doc/03_Documents/01_Editables/02_Areablock/02_Bricks.md
Labels: Task, Pimcore:ToDo

#17298 Update KeyConfig.php to prevent access before initialization TypeError
  models/DataObject/Classificationstore/KeyConfig.php
Labels: Pimcore:ToDo

#17334 Fix error when deleting unique field in FieldCollection
  models/DataObject/Fieldcollection/Definition/Dao.php
Labels: Bug, Pimcore:ToDo

#17280 Fix Docs: Access and modify internal object list query
  doc/05_Objects/03_Working_with_PHP_API.md
Labels: Pimcore:ToDo

#17025 Add missing return $this php docs
  models/Asset.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php
  models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php
  models/DataObject/ClassDefinition/Data/Checkbox.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
  models/DataObject/ClassDefinition/Data/Geo/AbstractGeo.php
  models/DataObject/ClassDefinition/Data/ImageTrait.php
  models/DataObject/ClassDefinition/Data/Input.php
  models/DataObject/ClassDefinition/Data/Language.php
  models/DataObject/ClassDefinition/Data/Languagemultiselect.php
  models/DataObject/ClassDefinition/Data/Localizedfields.php
  models/DataObject/ClassDefinition/Data/ManyToOneRelation.php
  models/DataObject/ClassDefinition/Data/Multiselect.php
  models/DataObject/ClassDefinition/Data/Numeric.php
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php
  models/DataObject/ClassDefinition/Data/Select.php
  models/DataObject/ClassDefinition/Data/StructuredTable.php
  models/DataObject/ClassDefinition/Data/Textarea.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/ClassDefinition/Data/VarExporterInterface.php
  models/DataObject/ClassDefinition/Data/Video.php
  models/DataObject/ClassDefinition/Data/Wysiwyg.php
  models/DataObject/ClassDefinition/Helper/VarExport.php
  models/DataObject/ClassDefinition/Helper/VarExportInterface.php
  models/DataObject/ClassDefinition/Layout.php
  models/DataObject/ClassDefinition/Layout/Fieldcontainer.php
  models/DataObject/ClassDefinition/Layout/Panel.php
  models/DataObject/ClassDefinition/Layout/Text.php
  models/DataObject/ClassDefinition/Layout/Traits/LabelTrait.php
  models/DataObject/Concrete.php
  models/Document.php
  models/Element/AbstractElement.php
  models/Element/ElementInterface.php
  models/User/Workspace/DataObject.php
  models/User/Workspace/Document.php
Labels: Pimcore:ToDo

#17373 Respect denied workflow permissions in permission checks
  lib/Workflow/Manager.php
  models/Element/AbstractElement.php
Labels: Bug

#17269 [FIX] Allow strings to have escaped quotes
  lib/Model/Listing/AbstractListing.php
Labels: Bug, Pimcore:ToDo

#17289 [Recyclebin] Pass isRecycleBinRestore parameter on recursive restore
  models/Element/Recyclebin/Item.php
Labels: Pimcore:ToDo

#17374 Fix MySql Error 'Syntax error or access violation: 1061 Duplicate key name' when unique key consists of at least 2 columns
  models/DataObject/ClassDefinition/Helper/Dao.php
Labels: Bug

#17360 [Improvement] Execution modes for Generic Execution Engine
  bundles/GenericExecutionEngineBundle/src/Agent/JobExecutionAgent.php
  bundles/GenericExecutionEngineBundle/src/Entity/JobRun.php
  bundles/GenericExecutionEngineBundle/src/Extractor/JobRunExtractor.php
  bundles/GenericExecutionEngineBundle/src/Extractor/JobRunExtractorInterface.php
  bundles/GenericExecutionEngineBundle/src/Messenger/Handler/AbstractAutomationActionHandler.php
  bundles/GenericExecutionEngineBundle/src/Messenger/Messages/AbstractExecutionEngineMessage.php
  bundles/GenericExecutionEngineBundle/src/Model/JobStep.php
  bundles/GenericExecutionEngineBundle/src/Model/JobStepInterface.php
  bundles/GenericExecutionEngineBundle/src/Utils/Enums/SelectionProcessingMode.php
  doc/19_Development_Tools_and_Details/08_Generic_Execution_Engine/01_Usage.md
  doc/19_Development_Tools_and_Details/08_Generic_Execution_Engine/04_Step_Configuration.md
Labels: Improvement, Pimcore:ToDo

#17389 PhpStan Version Upgrade July
  composer.json
Labels: Task

#17012 AbstractModel::__call() - Don't throw and log exceptions
  lib/Model/AbstractModel.php
Labels: Pimcore:ToDo

#17391 [Docs] Removed info about HTML sanitizer max length
  doc/03_Documents/01_Editables/40_WYSIWYG.md
Labels: Bug, Pimcore:ToDo

#17401 fix overwritten loop variable in a nested loop in brick class dumper
  lib/DataObject/ClassBuilder/PHPObjectBrickContainerClassDumper.php
Labels: Pimcore:ToDo

#17384 [Data Objects] Fixed removing a field with an index
  models/DataObject/ClassDefinition/Helper/Dao.php
Labels: Bug, Pimcore:ToDo

#17411 [Doc] 06_Event_Listener_UI.md - Use addPaths methods
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/06_Event_Listener_UI.md
  doc/20_Extending_Pimcore/13_Bundle_Developers_Guide/09_Adding_Document_Editables.md
  doc/26_Best_Practice/71_Style_Backend_Depending_On_App-Env.md
Labels: Task, Pimcore:ToDo

#17414 [Improvement]: Allow JobStep of Generic Execution Engine to change selected elements for the next JobStep
  bundles/GenericExecutionEngineBundle/src/Exception/JobNotFoundException.php
  bundles/GenericExecutionEngineBundle/src/Messenger/Handler/AbstractAutomationActionHandler.php
  bundles/GenericExecutionEngineBundle/src/Model/Job.php
  bundles/GenericExecutionEngineBundle/src/Repository/JobRunRepository.php
  bundles/GenericExecutionEngineBundle/src/Repository/JobRunRepositoryInterface.php
  bundles/GenericExecutionEngineBundle/translations/admin.en.yaml
Labels: Improvement
