Repository pimcore/pimcore, pull requests merged in 2024-06, with the labels that each got.

#17105 Decouple simple backend search from admin UI classic bundle
  bundles/SimpleBackendSearchBundle/src/EventListener/SearchBackendListener.php
Labels: Improvement

#17129 [Bug] Fix thumbnail generation
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/04_Assets/03_Working_with_Thumbnails/README.md
  models/Asset/Thumbnail/ImageThumbnailTrait.php
Labels: Bug

#17135 Fix date attribute storage when client timezone differs from server timezone
  models/DataObject/ClassDefinition/Data/Date.php
Labels: Bug

#17117 Add a mechanism to define the user's timezone for the version preview and CSV exports
  lib/Tool/UserTimezone.php
  models/Asset/MetaData/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/DateRange.php
  models/DataObject/ClassDefinition/Data/Datetime.php
Labels: Bug, Pimcore:ToDo

#17132 [Improvement] Add abort action method to GEE
  bundles/GenericExecutionEngineBundle/src/Agent/JobExecutionAgent.php
  bundles/GenericExecutionEngineBundle/src/Messenger/Handler/AbstractAutomationActionHandler.php
  bundles/GenericExecutionEngineBundle/src/Migrations/.empty
  bundles/GenericExecutionEngineBundle/src/Repository/JobRunErrorLogRepository.php
  bundles/GenericExecutionEngineBundle/src/Repository/JobRunErrorLogRepositoryInterface.php
Labels: Improvement

#17144 [Task] Add throws tag for `abortAction`
  bundles/GenericExecutionEngineBundle/src/Messenger/Handler/AbstractAutomationActionHandler.php
Labels: Task

#17060 Storage migration command should log errors
  bundles/CoreBundle/src/Command/Migrate/StorageCommand.php
Labels: Bug, Pimcore:ToDo

#17084 Fix issue with cropping gif images with focal points
  lib/Image/Adapter/Imagick.php
Labels: Bug, Pimcore:ToDo

#16476 [Video thumbnails] Support creating mpg video thumbnails
  lib/Video/Adapter/Ffmpeg.php
Labels: Pimcore:ToDo

#17147 Fix edit in grid for date fields with date column type
  models/DataObject/ClassDefinition/Data/Date.php
Labels: Bug

#17154 Check in version history if timezone support is enabled
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
Labels: Bug

#17166 Fix date attributes without timezone support when server timezone is configured
  models/DataObject/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/Datetime.php
Labels: Bug

#17097 [Improvement] Follow up #16482 Delta relations field
  models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php
  tests/Model/Relations/DeltaCalculationTest.php
Labels: Improvement, Pimcore:ToDo

#17138 Fix: ClassDefinitionManager->cleanUpDeletedClassDefinitions()
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Dao.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
Labels: Bug, Pimcore:ToDo

#17008 [BUG] fix glossary preg_replace greediness
  bundles/GlossaryBundle/src/Tool/Processor.php
Labels: Pimcore:ToDo

#17109 FieldDefinition: Add missing forbidden names
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Objectbrick/Definition.php
Labels: Bug, Pimcore:ToDo

#17148 Layout: Fix return types of getter methods
  models/Asset.php
  models/DataObject/ClassDefinition/Layout.php
Labels: Bug, Pimcore:ToDo

#17179 Consider & showing Platform Version when installed
  bundles/CoreBundle/src/DataCollector/PimcoreDataCollector.php
  bundles/CoreBundle/templates/Profiler/data_collector.html.twig
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/README.md
  lib/Version.php
Labels: Improvement

#17187 [Improvement]: Various improvements for generic execution engine
  bundles/GenericExecutionEngineBundle/src/Agent/JobExecutionAgent.php
  bundles/GenericExecutionEngineBundle/src/Messenger/Handler/AbstractAutomationActionHandler.php
  bundles/GenericExecutionEngineBundle/src/Repository/JobRunRepository.php
  bundles/GenericExecutionEngineBundle/src/Repository/JobRunRepositoryInterface.php
  bundles/GenericExecutionEngineBundle/translations/admin.en.yaml
Labels: Improvement

#17191 [Improvement]: Move CollectGarbageMiddleware to pimcore repository
  bundles/GenericExecutionEngineBundle/config/pimcore/config.yaml
  bundles/GenericExecutionEngineBundle/config/services.yaml
  bundles/GenericExecutionEngineBundle/src/Messenger/Middleware/StepConditionMiddleware.php
  lib/Messenger/Middleware/CollectGarbageMiddleware.php
Labels: Improvement

#17137 [Improvement]: Add possibility to define date time locale on user basis
  bundles/ApplicationLoggerBundle/public/js/log/admin.js
  bundles/CoreBundle/src/Migrations/Version20240606165618.php
  bundles/InstallBundle/dump/install.sql
  lib/Tool.php
  models/User.php
Labels: Pimcore:ToDo

#16745 [Improvement]: Move grid data related functions to admin-ui-classic-bundle
  bundles/SimpleBackendSearchBundle/src/Controller/SearchController.php
  bundles/SimpleBackendSearchBundle/src/DataProvider/GDPR/Assets.php
  bundles/SimpleBackendSearchBundle/src/DataProvider/GDPR/DataObjects.php
  composer.json
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset/Service.php
  models/DataObject/Service.php
  models/Element/Service.php
  tests/Model/Permissions/ModelAssetPermissionsTest.php
  tests/Model/Permissions/ModelDocumentPermissionsTest.php
Labels: Improvement, Pimcore:ToDo, Pimcore:Priority

#17121 [Improvement]: Resolve Dependencies via Messenger
  bundles/CoreBundle/config/message_handler.yaml
  bundles/CoreBundle/config/pimcore/default.yaml
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Messenger/ElementDependenciesMessage.php
  lib/Messenger/Handler/ElementDependenciesHandler.php
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/DataObject/Concrete.php
  models/Document.php
  models/Document/Hardlink.php
  models/Document/Link.php
  models/Document/PageSnippet.php
  models/Element/AbstractElement.php
Labels: Pimcore:ToDo

#17078 Supress warning if getimagesize() is failing becaus it throws an Exception
  models/Asset/Image.php
Labels: Pimcore:ToDo

#17063 Datatype input regex validates always instead of save and publish
  models/DataObject/ClassDefinition/Data/Input.php
Labels: Bug, Pimcore:ToDo

#17197 Fix: getLastLogin() must not be accessed before initialization on User model
  models/User.php
  models/UserInterface.php
Labels: Pimcore:ToDo

#16999 Update Site.php
  models/Site.php
Labels: Pimcore:ToDo

#17220 [Docs] Add section about where to store sessions
  doc/26_Best_Practice/25_Where_To_Store_Sessions.md
Labels: Task

#17223 Also include backwards compatible timezones
  lib/Tool/UserTimezone.php
Labels: Bug

#17224 [Bug]: Initial sort to sql definition for report does not work
  bundles/CustomReportsBundle/public/js/pimcore/report/custom/definitions/sql.js
Labels: Bug

#17229 [Bug] GCS: Asset Upload broken - stream is not a valid resource
  models/Asset.php
Labels: Bug

#17232 fixing docs
  doc/03_Documents/01_Editables/38_Video.md
  doc/18_Tools_and_Features/39_Sitemaps.md
Labels: Task

#17211 *.dwg files should be unknown asset type
  bundles/CoreBundle/config/pimcore/default.yaml
Labels: Pimcore:ToDo

#17241 [GEE] Make error handling more dynamic
  bundles/GenericExecutionEngineBundle/config/pimcore/default.yaml
  bundles/GenericExecutionEngineBundle/src/Agent/JobExecutionAgent.php
  bundles/GenericExecutionEngineBundle/src/Configuration/ExecutionContext.php
  bundles/GenericExecutionEngineBundle/src/Configuration/ExecutionContextInterface.php
  bundles/GenericExecutionEngineBundle/src/DependencyInjection/Configuration.php
  bundles/GenericExecutionEngineBundle/src/Repository/JobRunRepository.php
Labels: Improvement

#17030 Prematurely exit pimcore:bundle:install with success code if bundle is already installed
  bundles/CoreBundle/src/Command/Bundle/InstallCommand.php
Labels: Pimcore:ToDo
