Repository pimcore/pimcore, pull requests merged in 2025-04, with the labels that each got.

#18237 [Task] Introducing user parameter to make async work in studio
  models/DataObject/Service.php
Labels: Task, Pimcore:ToDo

#18165 [Improvement]: Eventlistener for customizing tags on full page cache entries
  bundles/CoreBundle/src/EventListener/Frontend/FullPageCacheListener.php
  lib/Event/Cache/FullPage/PrepareTagsEvent.php
  lib/Event/FullPageCacheEvents.php
Labels: Improvement, Pimcore:ToDo

#18219 BugFix: Allow language on localized key value to be nullable
  models/DataObject/Classificationstore.php
Labels: Bug, Pimcore:ToDo

#18257 [Improvement]: Eventlistener for customizing tags on full page cache entries
  bundles/CoreBundle/src/EventListener/Frontend/FullPageCacheListener.php
  lib/Event/Cache/FullPage/PrepareTagsEvent.php
  lib/Event/FullPageCacheEvents.php
Labels: Improvement

#18186 Log if error when saving in Asset.
  models/Asset.php
Labels: Improvement, Pimcore:ToDo

#18259 [Task] Consistently use json as column type
  bundles/InstallBundle/dump/install.sql
Labels: Task

#18054 Fix: getCacheFileStream does not check return of file_get_contents
  lib/Document/Adapter.php
  lib/Document/Adapter/Ghostscript.php
  lib/Video/Adapter.php
  lib/Video/Adapter/Ffmpeg.php
  models/Asset/Document/ImageThumbnail.php
  models/Asset/Folder.php
  models/Asset/Video/ImageThumbnail.php
  phpstan-baseline.neon
Labels: Pimcore:ToDo

#17987 TestDataHelper::createHotspots() - seed can't be null
  tests/Support/Helper/DataType/TestDataHelper.php
Labels: Pimcore:ToDo

#18028 Make $includingUnpublished usage more readable
  models/DataObject/AbstractObject/Dao.php
  models/Document/Dao.php
Labels: Task, Pimcore:ToDo

#18230 PhpStan Version Upgrade April
  composer.json
  lib/Image/Adapter/Imagick.php
  lib/Mail.php
  lib/Twig/Extension/Templating/HeadMeta.php
  lib/Twig/Extension/Templating/HeadScript.php
  models/DataObject/Data/EncryptedField.php
  models/User/UserRole/Dao.php
Labels: Task, Pimcore:ToDo

#18213 Update CustomLayouts after saving changes in a Class
  models/DataObject/ClassDefinition.php
Labels: Pimcore:ToDo

#18202 Fix: Frontend::isDocumentInSite() returns false for site root document
  lib/Tool/Frontend.php
  tests/Model/Tool/FrontendTest.php
Labels: Pimcore:ToDo

#18152 Drag'n'Drop of PDF / Excel / Word etc... to the editor doesn't work
  lib/Tool/Text.php
  phpstan-baseline.neon
Labels: Bug, Pimcore:ToDo

#17955 Improve search performance by otimizing SQL filter conditions, exclud…
  bundles/SimpleBackendSearchBundle/src/Controller/SearchController.php
Labels: Pimcore:ToDo

#18248 BugFix: Calculated Value Bool Type Version View Error
  models/DataObject/ClassDefinition/Data/CalculatedValue.php
Labels: Pimcore:ToDo

#18272 Removed unnecessary return type EncryptedField
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Classificationstore/Service.php
Labels: Improvement

#18281 Translator: fallback catalogues should also contain database translation values
  .github/ci/files/translations/messages.de.yml
  .github/ci/files/translations/messages.de_AT.yml
  .github/ci/files/translations/messages.en.yml
  .github/ci/scripts/setup-pimcore-environment.sh
  lib/Translation/Translator.php
  tests/Support/Resources/system_settings.json
  tests/Unit/Translation/TranslatorTest.php
Labels: Improvement

#18289 [Bug] Empty custom settings can lead to a json exception
  models/Asset.php
Labels: Bug

#17616 Transform base image to RGB colorspace if the watermark is in RGB or sRGB
  lib/Image/Adapter/Imagick.php
Labels: Pimcore:ToDo

#18242 Respect default value when using 'pimcore.workflow.place-options-provider'.
  lib/Workflow/Place/OptionsProvider.php
Labels: Pimcore:ToDo

#18267 Add to ImageGallery a __toString.
  models/DataObject/Data/ImageGallery.php
Labels: Bug, Pimcore:ToDo

#18141 #18100 Add password check to `isEqualTo` method of User class
  lib/Security/User/User.php
Labels: Improvement, Pimcore:ToDo

#18304 Log error message when failing to send workflow email.
  lib/Workflow/Notification/NotificationEmailService.php
Labels: Bug

#18284 [Feature]: Allow using same type of objectbrick more than once on a data object
  models/DataObject/Objectbrick/Data/Dao.php
Labels: New Feature

#17852 [Data Objects] Fix revert to previous global inheritance state in DAO
  models/DataObject/Concrete/Dao.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/Objectbrick/Data/Dao.php
Labels: Pimcore:ToDo

#16704 AbstractPimcoreBundle should extend AbstractBundle
  bundles/ApplicationLoggerBundle/src/PimcoreApplicationLoggerBundle.php
  bundles/CustomReportsBundle/src/PimcoreCustomReportsBundle.php
  bundles/GenericExecutionEngineBundle/src/PimcoreGenericExecutionEngineBundle.php
  bundles/GlossaryBundle/src/PimcoreGlossaryBundle.php
  bundles/InstallBundle/src/PimcoreInstallBundle.php
  bundles/SeoBundle/src/PimcoreSeoBundle.php
  bundles/SimpleBackendSearchBundle/src/PimcoreSimpleBackendSearchBundle.php
  bundles/StaticRoutesBundle/src/PimcoreStaticRoutesBundle.php
  bundles/WordExportBundle/src/PimcoreWordExportBundle.php
  bundles/XliffBundle/src/PimcoreXliffBundle.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Extension/Bundle/AbstractPimcoreBundle.php
Labels: Improvement, BC-BREAK, Pimcore:Priority

#18299 Product Registration
  .github/ci/files/config/packages/test/config.yaml
  .github/workflows/codeception.yaml
  .github/workflows/static-analysis.yaml
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  bundles/InstallBundle/src/Command/InstallCommand.php
  bundles/InstallBundle/src/Installer.php
  bundles/InstallBundle/src/SystemConfig/ConfigWriter.php
  composer.json
  doc/01_Getting_Started/00_Installation/00_Docker_Based_Installation.md
  doc/01_Getting_Started/00_Installation/01_Webserver_Installation.md
  doc/01_Getting_Started/02_Product_Registration.md
  doc/01_Getting_Started/03_Advanced_Installation_Topics/01_Symfony_Messenger.md
  doc/01_Getting_Started/03_Advanced_Installation_Topics/README.md
  doc/01_Getting_Started/04_Directory_Structure.md
  doc/01_Getting_Started/05_Configuration.md
  doc/01_Getting_Started/06_Architecture_Overview.md
  doc/01_Getting_Started/07_Create_a_First_Project.md
  doc/01_Getting_Started/README.md
  doc/03_Documents/README.md
  doc/05_Objects/01_Object_Classes/README.md
  doc/20_Extending_Pimcore/README.md
  doc/23_Installation_and_Upgrade/01_System_Requirements.md
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/13_V11_to_V12.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Pimcore.php
  lib/ProductRegistration/RegistrationValidator.php
  lib/ProductRegistration/pimcore-productregistration-ec_public.pem
  lib/Tool/Requirements.php
Labels: New Feature, Task, BC-BREAK

#18328 [Product Registration] Make sure registration validator is loaded also in non-interactive mode
  bundles/InstallBundle/src/Command/InstallCommand.php
Labels: Improvement

#18329 [Product Registration] Improve error messages in non-interactive mode
  bundles/InstallBundle/src/Command/InstallCommand.php
Labels: Task

#18330 Fix: use array_key_exists instead of isset for QuantityValueRange values
  models/DataObject/ClassDefinition/Data/QuantityValueRange.php
Labels: Bug

#18331 [Product Registration] More robust installation detection
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  bundles/InstallBundle/src/Installer.php
Labels: Task

#18319 [Bug]: Fix HTTP 414 "Request URI too long" error when searching for assets
  bundles/SimpleBackendSearchBundle/public/js/pimcore/element/selector/asset.js
  bundles/SimpleBackendSearchBundle/public/js/pimcore/element/selector/document.js
  bundles/SimpleBackendSearchBundle/public/js/pimcore/element/selector/object.js
Labels: Bug, Pimcore:Priority

#17020 Folder with null value in userModification/creationDate/modificationD…
  bundles/CoreBundle/src/Migrations/Version20240916105500.php
  bundles/InstallBundle/dump/install.sql
  bundles/SeoBundle/src/Model/Redirect.php
  models/DataObject/ClassDefinition/CustomLayout.php
  models/Element/AbstractElement.php
  models/Element/ElementInterface.php
  models/Translation/Dao.php
Labels: Bug, BC-BREAK, Pimcore:ToDo

#18300 [Improvement] QuantityValueRange - Allowing for smaller differences between min and max without throwing
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/ClassDefinition/Data/BooleanSelect.php
  models/DataObject/Data/NumericRange.php
  models/DataObject/Data/QuantityValueRange.php
  models/DataObject/Traits/RangeTrait.php
Labels: Improvement, BC-BREAK, Pimcore:ToDo

#17972 [Data Objects] Select data-types: do not configure dynamic options in __set_state() when not in admin mode
  models/DataObject/ClassDefinition/Data/AbstractQuantityValue.php
  models/DataObject/ClassDefinition/Data/Language.php
  models/DataObject/ClassDefinition/Data/Languagemultiselect.php
  models/DataObject/ClassDefinition/Data/QuantityValueRange.php
Labels: Bug, Pimcore:Backlog, Pimcore:Priority

#17809 [Documents] Support pretty url for document which belong to a site
  models/Document/PageSnippet.php
Labels: Pimcore:ToDo
