Repository pimcore/pimcore, pull requests merged in 2025-09, with the labels that each got.

#18607 Prepare documents for Pimcore Studio
  bundles/CoreBundle/src/EventListener/Frontend/EditmodeListener.php
  bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php
Labels: Task, Pimcore:Priority

#16882 Add twig function to get assigned element tags
  doc/02_MVC/02_Template/README.md
  lib/Twig/Extension/PimcoreObjectExtension.php
Labels: Improvement, Pimcore:ToDo

#18666 [Bug]: Fix error HasBlockOptionsTrait
  lib/Twig/Options/HasBlockOptionsTrait.php
Labels: Bug, Pimcore:ToDo

#18701 Fix Platform tests
  lib/Tool/MaintenanceModeHelper.php
Labels: Bug

#18679 [Asset] Prevent flooding pimcore_asset_update message queue transport with faulty assets triggered by previews in admin ui
  bundles/CoreBundle/config/message_handler.yaml
  bundles/CoreBundle/src/Command/Asset/AddToUpdateTaskQueueCommand.php
  bundles/SimpleBackendSearchBundle/src/Command/SearchBackendReindexCommand.php
  lib/Messenger/Handler/AssetUpdateTasksHandler.php
  models/Asset.php
  models/Asset/Document.php
  models/Asset/MetaData/EmbeddedMetaDataTrait.php
  models/Asset/Video.php
Labels: Bug

#18633 [Bugfix]: pass custom renderlet config as query parameters
  models/Document/Editable/Renderlet.php
Labels: Bug, Pimcore:Priority
