Repository pimcore/pimcore, pull requests merged in 2025-02, with the labels that each got.

#18069 Check if group config exists
  models/DataObject/ClassDefinition/Data/Classificationstore.php
Labels: Pimcore:ToDo

#18033 [Bug]: CSV Export tweaks
  models/DataObject/Service.php
Labels: Pimcore:ToDo

#18074 [Task]: Update protected asset doc to cover cache buster urls
  doc/04_Assets/07_Restricting_Public_Asset_Access.md
Labels: Task, Pimcore:ToDo

#18073 [Bug] Inheritance returns object references for getters
  doc/05_Objects/01_Object_Classes/05_Class_Settings/25_Inheritance.md
  doc/26_Best_Practice/68_Object_Data_Inheritance.md
Labels: Bug

#18082 [Bug] Geopoint/Gebounds access data array directly without check
  models/DataObject/ClassDefinition/Data/Geobounds.php
  models/DataObject/ClassDefinition/Data/Geopoint.php
Labels: Bug

#18086 [Docs] Removed tbd page from docs
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/07_Cluster_Setup.md
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/README.md
  doc/23_Installation_and_Upgrade/README.md
Labels: Bug

#18070 Fixed ExtJS chart warning in console -
  bundles/CustomReportsBundle/public/js/pimcore/layout/portlets/customreports.js
Labels: Bug, Pimcore:Backlog

#18050 add nesbot/carbon to composer, adapt to new version
  composer.json
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/README.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Cache/Core/CoreCacheHandler.php
  models/Asset/MetaData/ClassDefinition/Data/Date.php
  models/DataObject/ClassDefinition/Data/DateRange.php
  models/Document/Editable/Date.php
  models/Element/Service.php
  phpstan-parameters.neon
  tests/Twig/PimcoreDateTest.php
Labels: Pimcore:ToDo

#18083 [Bug] Add object as fallback if no version is available
  bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php
Labels: Bug

#18101 [Task] Remove DataObject\Link - __unserialize
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/DataObject/Data/Link.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18102 [Task] Remove the deprecated method Image::getThumbnailConfig()
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset/Image.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18103 [Task] Remove deprecated 'Helper\CsvFormulaFormatter'
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Helper/CsvFormulaFormatter.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18104 [Task] Remove the deprecated method Tool::getCachedSymfonyEnvironments()
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Tool.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18106 [Task] AbstractPimcoreBundle: remove deprecations and BC layer
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Extension/Bundle/AbstractPimcoreBundle.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18108 [Task] LowQualityImagePreviewCommand: remove generator option
  bundles/CoreBundle/src/Command/LowQualityImagePreviewCommand.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, BC-BREAK, Pimcore:ToDo

#18109 [Mail] Do not set fallback from address
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Mail.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18114 [Task] Remove key_value_table.html.twig
  bundles/CoreBundle/templates/Profiler/key_value_table.html.twig
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, BC-BREAK, Pimcore:ToDo

#18115 [Task][Events] ResolveUploadTargetEvent remove context property.
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Event/Model/Asset/ResolveUploadTargetEvent.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18112 [Task] Add deprecation message for return type ?object
  lib/Workflow/Manager.php
Labels: Task

#18113 [Task] Inconsistent Return Type of Workflow/Manager getWorkflowIfExists vs getWorkflowByName
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Workflow/EventSubscriber/NotificationSubscriber.php
  lib/Workflow/Manager.php
  lib/Workflow/Notification/NotificationEmailService.php
  lib/Workflow/Notification/PimcoreNotificationService.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18045 [Bugfix] Change installer sequence
  bundles/InstallBundle/src/Installer.php
Labels: Bug, Pimcore:ToDo

#18116 [Task] Update major version
  lib/Version.php
Labels: Task

#18111 [Task][Data Objects] UrlSlug data-type: fix return/param types
  models/DataObject/ClassDefinition/Data/UrlSlug.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18097 [Task]ElementInterface implementations should allow only int for $id
  bundles/SeoBundle/src/Model/Redirect.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  models/Asset.php
  models/DataObject/AbstractObject.php
  models/Document.php
  models/Element/ElementInterface.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18117 [Task] Remove Pimcore 10 compatibility layer
  tests/Model/DataType/LocalizedFieldTest.php
  tests/Model/Inheritance/LocalizedFieldTest.php
Labels: Task, BC-BREAK, Pimcore:ToDo

#18123 [Task] Fix event size styling
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Task, Pimcore:ToDo

#17546 [Custom Reports] Option for deactivating column settings
  bundles/CustomReportsBundle/public/js/pimcore/report/custom/item.js
  bundles/CustomReportsBundle/public/js/pimcore/report/custom/report.js
  bundles/CustomReportsBundle/public/js/pimcore/report/panel.js
  bundles/CustomReportsBundle/src/Controller/Reports/CustomReportController.php
  bundles/CustomReportsBundle/src/DependencyInjection/Configuration.php
  bundles/CustomReportsBundle/src/Tool/Adapter/AbstractAdapter.php
  bundles/CustomReportsBundle/src/Tool/Adapter/CustomReportAdapterInterface.php
  bundles/CustomReportsBundle/src/Tool/Adapter/Sql.php
  bundles/CustomReportsBundle/src/Tool/Config.php
  bundles/CustomReportsBundle/src/Tool/Config/ColumnInformation.php
  bundles/CustomReportsBundle/src/Tool/Config/Dao.php
  doc/18_Tools_and_Features/29_Custom_Reports.md
  doc/23_Installation_and_Upgrade/07_Updating_Pimcore/13_V11_to_V12.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: BC-BREAK, Pimcore:ToDo

#18120 [Docs]: Specify the difference between currentIndex and current in pimcoreblock
  doc/03_Documents/01_Editables/06_Block.md
Labels: Task, Pimcore:ToDo

#18130 [Task]: Phpstan upgrade February
  composer.json
Labels: Task, Pimcore:ToDo

#18131 [Bug]: Fix regression, `else` part is unreachable on validlanguages as null
  models/DataObject/Service.php
Labels: Bug

#18134 [Improvement] Add LogLevel enum for easier handling of log priority filtering
  bundles/ApplicationLoggerBundle/src/Enum/LogLevel.php
  bundles/ApplicationLoggerBundle/src/Exception/LogLevelNotFoundException.php
  bundles/ApplicationLoggerBundle/src/Maintenance/LogMailMaintenanceTask.php
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
Labels: Improvement

#18133 [Improvement] Log level configuration for `ApplicationLogger`
  bundles/ApplicationLoggerBundle/config/services.yaml
  bundles/ApplicationLoggerBundle/src/ApplicationLogger.php
  bundles/ApplicationLoggerBundle/src/DependencyInjection/PimcoreApplicationLoggerExtension.php
  bundles/ApplicationLoggerBundle/src/Exception/ContainerNotFoundException.php
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  bundles/CoreBundle/src/DependencyInjection/PimcoreCoreExtension.php
  doc/18_Tools_and_Features/17_Application_Logger.md
Labels: Improvement

#18132 [Bug]: Fix regression with expandGridColumnForExport
  models/DataObject/Service.php
Labels: Bug, Pimcore:ToDo

#18143 [Improvement] Translatable log levels
  bundles/ApplicationLoggerBundle/config/services.yaml
  bundles/ApplicationLoggerBundle/src/Controller/LogController.php
  bundles/ApplicationLoggerBundle/src/Enum/LogLevel.php
  bundles/ApplicationLoggerBundle/src/Handler/ApplicationLoggerDb.php
  bundles/ApplicationLoggerBundle/src/Service/TranslationService.php
  bundles/ApplicationLoggerBundle/src/Service/TranslationServiceInterface.php
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
Labels: Improvement

#18056 Fix: When quantity value is removed data objects disappears
  models/DataObject/ClassDefinition/Data/QuantityValue.php
Labels: Pimcore:ToDo, Regression

#17795 [Task]: Remove Chromium (Headless) Support
  bundles/CoreBundle/src/DependencyInjection/Configuration.php
  composer.json
  doc/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/06_Additional_Tools_Installation.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  lib/Helper/GotenbergHelper.php
  lib/Image/Chromium.php
  lib/Image/HtmlToImage.php
  lib/Tool/Requirements.php
  phpstan-baseline.neon
Labels: Task, BC-BREAK

#18145 [GenericExecutionEngine] Support environment variable replacement for config values to handle nested arrays
  bundles/GenericExecutionEngineBundle/src/Messenger/Handler/AbstractAutomationActionHandler.php
Labels: Bug, Pimcore:ToDo

#18042 Fix PhpDocs
  bundles/CustomReportsBundle/src/Tool/Config/Listing.php
  bundles/GenericExecutionEngineBundle/src/Messenger/Handler/AbstractAutomationActionHandler.php
  bundles/StaticRoutesBundle/src/Routing/Staticroute/Router.php
  bundles/XliffBundle/src/AttributeSet/AttributeSet.php
  lib/Cache/RuntimeCache.php
  lib/HttpKernel/BundleCollection/LazyLoadedItem.php
  lib/Image/Adapter/GD.php
  lib/Image/Adapter/Imagick.php
  lib/Image/HtmlToImage.php
  lib/Messenger/Handler/CleanupThumbnailsHandler.php
  lib/Navigation/Page.php
  lib/Workflow/Manager.php
  models/DataObject/AbstractObject.php
  models/DataObject/ClassDefinition.php
  models/DataObject/ClassDefinition/Data.php
  models/DataObject/ClassDefinition/Data/Consent.php
  models/DataObject/ClassDefinition/Data/Objectbricks.php
  models/DataObject/ClassDefinition/Data/UrlSlug.php
  models/DataObject/ClassDefinition/PreviewGeneratorInterface.php
  models/DataObject/ClassDefinition/Service.php
  models/DataObject/Data/UrlSlug.php
  models/DataObject/Fieldcollection/Definition.php
  models/DataObject/Localizedfield/Dao.php
  models/DataObject/OwnerAwareFieldInterface.php
  models/DataObject/Traits/OwnerAwareFieldTrait.php
  models/Document.php
  models/Element/PermissionChecker.php
Labels: Pimcore:ToDo

#18151 Fix PhpDocs of PreviewGeneratorInterface
  models/DataObject/ClassDefinition/PreviewGeneratorInterface.php
Labels: Task

#18156 [Task] [Data Objects] Password data-type: remove support for algorithms other than password_hash
  doc/05_Objects/01_Object_Classes/01_Data_Types/95_Text_Types.md
  doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md
  doc/img/classes-datatypes-text4.jpg
  models/DataObject/ClassDefinition/Data/Password.php
  tests/Support/Helper/Model.php
Labels: Task

#18154 Bugfix/Add open url handler for custom report portlets
  bundles/CustomReportsBundle/public/js/pimcore/layout/portlets/customreports.js
Labels: Bug, Pimcore:ToDo

#18072 Do not execute Composer Checks on fork repositories
  .github/workflows/composer-checks-outdated-monthly.yaml
  .github/workflows/composer-checks-outdated.yaml
  .github/workflows/composer-checks-vulnerabilities.yaml
Labels: Pimcore:ToDo
